/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type {
  CreateWorkOrderDto,
  EmptyBodyDto,
  PickWorkOrderComponentDto,
  UpdateWorkOrderComponentDto,
  UpdateWorkOrderDto,
  WorkOrderPickingSummaryDto,
  WorkOrderResponseDto,
  WorkOrdersControllerFindAllParams
} from '../../model';

import { customFetch } from '../../mutator';

/**
 * Get all work orders with optional filtering by days.
 * @summary List Work Orders
 */
export type workOrdersControllerFindAllResponse200 = {
  data: WorkOrderResponseDto[]
  status: 200
}
    
export type workOrdersControllerFindAllResponseSuccess = (workOrdersControllerFindAllResponse200) & {
  headers: Headers;
};
;

export type workOrdersControllerFindAllResponse = (workOrdersControllerFindAllResponseSuccess)

export const getWorkOrdersControllerFindAllUrl = (params?: WorkOrdersControllerFindAllParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/manufacturing/work-orders?${stringifiedParams}` : `/manufacturing/work-orders`
}

export const workOrdersControllerFindAll = async (params?: WorkOrdersControllerFindAllParams, options?: RequestInit): Promise<workOrdersControllerFindAllResponse> => {
  
  return customFetch<workOrdersControllerFindAllResponse>(getWorkOrdersControllerFindAllUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * Manually create a new Work Order.
 * @summary Create Work Order
 */
export type workOrdersControllerCreateResponse201 = {
  data: WorkOrderResponseDto
  status: 201
}
    
export type workOrdersControllerCreateResponseSuccess = (workOrdersControllerCreateResponse201) & {
  headers: Headers;
};
;

export type workOrdersControllerCreateResponse = (workOrdersControllerCreateResponseSuccess)

export const getWorkOrdersControllerCreateUrl = () => {


  

  return `/manufacturing/work-orders`
}

export const workOrdersControllerCreate = async (createWorkOrderDto: CreateWorkOrderDto, options?: RequestInit): Promise<workOrdersControllerCreateResponse> => {
  
  return customFetch<workOrdersControllerCreateResponse>(getWorkOrdersControllerCreateUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createWorkOrderDto,)
  }
);}


/**
 * Get work order details including component line items.
 * @summary Get Work Order by ID
 */
export type workOrdersControllerFindOneResponse200 = {
  data: WorkOrderResponseDto
  status: 200
}
    
export type workOrdersControllerFindOneResponseSuccess = (workOrdersControllerFindOneResponse200) & {
  headers: Headers;
};
;

export type workOrdersControllerFindOneResponse = (workOrdersControllerFindOneResponseSuccess)

export const getWorkOrdersControllerFindOneUrl = (id: string,) => {


  

  return `/manufacturing/work-orders/${id}`
}

export const workOrdersControllerFindOne = async (id: string, options?: RequestInit): Promise<workOrdersControllerFindOneResponse> => {
  
  return customFetch<workOrdersControllerFindOneResponse>(getWorkOrdersControllerFindOneUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * Update a draft Work Order.
 * @summary Update Work Order
 */
export type workOrdersControllerUpdateResponse200 = {
  data: WorkOrderResponseDto
  status: 200
}
    
export type workOrdersControllerUpdateResponseSuccess = (workOrdersControllerUpdateResponse200) & {
  headers: Headers;
};
;

export type workOrdersControllerUpdateResponse = (workOrdersControllerUpdateResponseSuccess)

export const getWorkOrdersControllerUpdateUrl = (id: string,) => {


  

  return `/manufacturing/work-orders/${id}`
}

export const workOrdersControllerUpdate = async (id: string,
    updateWorkOrderDto: UpdateWorkOrderDto, options?: RequestInit): Promise<workOrdersControllerUpdateResponse> => {
  
  return customFetch<workOrdersControllerUpdateResponse>(getWorkOrdersControllerUpdateUrl(id),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateWorkOrderDto,)
  }
);}


/**
 * Update a component on a draft Work Order.
 * @summary Update Work Order Component
 */
export type workOrdersControllerUpdateComponentResponse200 = {
  data: WorkOrderResponseDto
  status: 200
}
    
export type workOrdersControllerUpdateComponentResponseSuccess = (workOrdersControllerUpdateComponentResponse200) & {
  headers: Headers;
};
;

export type workOrdersControllerUpdateComponentResponse = (workOrdersControllerUpdateComponentResponseSuccess)

export const getWorkOrdersControllerUpdateComponentUrl = (id: string,
    componentId: string,) => {


  

  return `/manufacturing/work-orders/${id}/components/${componentId}`
}

export const workOrdersControllerUpdateComponent = async (id: string,
    componentId: string,
    updateWorkOrderComponentDto: UpdateWorkOrderComponentDto, options?: RequestInit): Promise<workOrdersControllerUpdateComponentResponse> => {
  
  return customFetch<workOrdersControllerUpdateComponentResponse>(getWorkOrdersControllerUpdateComponentUrl(id,componentId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateWorkOrderComponentDto,)
  }
);}


/**
 * Transition Work Order from DRAFT to IN_PROGRESS and generate component picks.
 * @summary Release Work Order
 */
export type workOrdersControllerReleaseResponse200 = {
  data: WorkOrderResponseDto
  status: 200
}

export type workOrdersControllerReleaseResponse201 = {
  data: WorkOrderResponseDto
  status: 201
}
    
export type workOrdersControllerReleaseResponseSuccess = (workOrdersControllerReleaseResponse200 | workOrdersControllerReleaseResponse201) & {
  headers: Headers;
};
;

export type workOrdersControllerReleaseResponse = (workOrdersControllerReleaseResponseSuccess)

export const getWorkOrdersControllerReleaseUrl = (id: string,) => {


  

  return `/manufacturing/work-orders/${id}/release`
}

export const workOrdersControllerRelease = async (id: string,
    emptyBodyDto: EmptyBodyDto, options?: RequestInit): Promise<workOrdersControllerReleaseResponse> => {
  
  return customFetch<workOrdersControllerReleaseResponse>(getWorkOrdersControllerReleaseUrl(id),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      emptyBodyDto,)
  }
);}


/**
 * Transition Work Order from IN_PROGRESS to COMPLETED and record output stock.
 * @summary Complete Work Order Production
 */
export type workOrdersControllerCompleteBuildResponse200 = {
  data: WorkOrderResponseDto
  status: 200
}

export type workOrdersControllerCompleteBuildResponse201 = {
  data: WorkOrderResponseDto
  status: 201
}
    
export type workOrdersControllerCompleteBuildResponseSuccess = (workOrdersControllerCompleteBuildResponse200 | workOrdersControllerCompleteBuildResponse201) & {
  headers: Headers;
};
;

export type workOrdersControllerCompleteBuildResponse = (workOrdersControllerCompleteBuildResponseSuccess)

export const getWorkOrdersControllerCompleteBuildUrl = (id: string,) => {


  

  return `/manufacturing/work-orders/${id}/complete`
}

export const workOrdersControllerCompleteBuild = async (id: string,
    emptyBodyDto: EmptyBodyDto, options?: RequestInit): Promise<workOrdersControllerCompleteBuildResponse> => {
  
  return customFetch<workOrdersControllerCompleteBuildResponse>(getWorkOrdersControllerCompleteBuildUrl(id),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      emptyBodyDto,)
  }
);}


/**
 * Cancel a Work Order and release component picks.
 * @summary Cancel Work Order
 */
export type workOrdersControllerCancelResponse200 = {
  data: WorkOrderResponseDto
  status: 200
}

export type workOrdersControllerCancelResponse201 = {
  data: WorkOrderResponseDto
  status: 201
}
    
export type workOrdersControllerCancelResponseSuccess = (workOrdersControllerCancelResponse200 | workOrdersControllerCancelResponse201) & {
  headers: Headers;
};
;

export type workOrdersControllerCancelResponse = (workOrdersControllerCancelResponseSuccess)

export const getWorkOrdersControllerCancelUrl = (id: string,) => {


  

  return `/manufacturing/work-orders/${id}/cancel`
}

export const workOrdersControllerCancel = async (id: string,
    emptyBodyDto: EmptyBodyDto, options?: RequestInit): Promise<workOrdersControllerCancelResponse> => {
  
  return customFetch<workOrdersControllerCancelResponse>(getWorkOrdersControllerCancelUrl(id),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      emptyBodyDto,)
  }
);}


/**
 * Retrieve component picking summary for a Work Order.
 * @summary Get Work Order Picking Summary
 */
export type workOrdersControllerGetPickingSummaryResponse200 = {
  data: WorkOrderPickingSummaryDto
  status: 200
}
    
export type workOrdersControllerGetPickingSummaryResponseSuccess = (workOrdersControllerGetPickingSummaryResponse200) & {
  headers: Headers;
};
;

export type workOrdersControllerGetPickingSummaryResponse = (workOrdersControllerGetPickingSummaryResponseSuccess)

export const getWorkOrdersControllerGetPickingSummaryUrl = (id: string,) => {


  

  return `/manufacturing/work-orders/${id}/picking`
}

export const workOrdersControllerGetPickingSummary = async (id: string, options?: RequestInit): Promise<workOrdersControllerGetPickingSummaryResponse> => {
  
  return customFetch<workOrdersControllerGetPickingSummaryResponse>(getWorkOrdersControllerGetPickingSummaryUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * Record picked component quantity into WIP bin.
 * @summary Pick Work Order Component
 */
export type workOrdersControllerPickLineResponse201 = {
  data: WorkOrderPickingSummaryDto
  status: 201
}
    
export type workOrdersControllerPickLineResponseSuccess = (workOrdersControllerPickLineResponse201) & {
  headers: Headers;
};
;

export type workOrdersControllerPickLineResponse = (workOrdersControllerPickLineResponseSuccess)

export const getWorkOrdersControllerPickLineUrl = (id: string,
    lineId: string,) => {


  

  return `/manufacturing/work-orders/${id}/picking/lines/${lineId}`
}

export const workOrdersControllerPickLine = async (id: string,
    lineId: string,
    pickWorkOrderComponentDto: PickWorkOrderComponentDto, options?: RequestInit): Promise<workOrdersControllerPickLineResponse> => {
  
  return customFetch<workOrdersControllerPickLineResponse>(getWorkOrdersControllerPickLineUrl(id,lineId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      pickWorkOrderComponentDto,)
  }
);}


/**
 * Cancel a recorded component pick and reverse stock to storage.
 * @summary Cancel Component Pick
 */
export type workOrdersControllerCancelPickResponse200 = {
  data: WorkOrderPickingSummaryDto
  status: 200
}
    
export type workOrdersControllerCancelPickResponseSuccess = (workOrdersControllerCancelPickResponse200) & {
  headers: Headers;
};
;

export type workOrdersControllerCancelPickResponse = (workOrdersControllerCancelPickResponseSuccess)

export const getWorkOrdersControllerCancelPickUrl = (id: string,
    pickId: string,) => {


  

  return `/manufacturing/work-orders/${id}/picking/picks/${pickId}`
}

export const workOrdersControllerCancelPick = async (id: string,
    pickId: string, options?: RequestInit): Promise<workOrdersControllerCancelPickResponse> => {
  
  return customFetch<workOrdersControllerCancelPickResponse>(getWorkOrdersControllerCancelPickUrl(id,pickId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}


