import {
  CanActivate,
  ExecutionContext,
  Injectable,
  Logger,
  UnauthorizedException,
} from '@nestjs/common';
import * as fs from 'fs';
import * as path from 'path';

/**
 * Guard that protects setup endpoints with a one-time file-based token.
 *
 * Two valid authentication paths:
 * 1. **Setup Token**: `X-Setup-Token` header or `?token=` query param,
 *    compared against the `.setup-token` file generated by Phase A scripts.
 * 2. **Admin JWT**: A valid JWT with role `admin` (set by AuthGuard('jwt')
 *    earlier in the pipeline).
 *
 * The guard does NOT check `isSetupComplete()` — admins can re-run at will.
 */
@Injectable()
export class SetupGuard implements CanActivate {
  private readonly logger = new Logger(SetupGuard.name);

  /**
   * Read the setup token from the `.setup-token` file.
   * Returns null if the file doesn't exist or is unreadable.
   */
  private readTokenFromFile(): string | null {
    // Look up from apps/api → project root
    const projectRoot = path.resolve(process.cwd(), '..', '..');
    const tokenPath = path.join(projectRoot, '.setup-token');

    try {
      if (fs.existsSync(tokenPath)) {
        return fs.readFileSync(tokenPath, 'utf-8').trim();
      }
    } catch {
      this.logger.warn('Failed to read .setup-token file');
    }

    // Also try CWD (monorepo root) directly
    const cwdTokenPath = path.join(process.cwd(), '.setup-token');
    try {
      if (cwdTokenPath !== tokenPath && fs.existsSync(cwdTokenPath)) {
        return fs.readFileSync(cwdTokenPath, 'utf-8').trim();
      }
    } catch {
      // Ignore
    }

    return null;
  }

  canActivate(context: ExecutionContext): boolean {
    const request = context.switchToHttp().getRequest();

    // Path 1: Admin JWT — if the user is already authenticated with admin role
    if (request.user?.role === 'admin') {
      return true;
    }

    // Path 2: Setup token — from header or query param
    const headerToken = request.headers['x-setup-token'] as string | undefined;
    const queryToken = request.query?.token as string | undefined;
    const providedToken = headerToken || queryToken;

    if (!providedToken) {
      throw new UnauthorizedException(
        'Setup requires a valid setup token or admin JWT. ' +
          'Provide X-Setup-Token header or ?token= query parameter.',
      );
    }

    const fileToken = this.readTokenFromFile();

    if (!fileToken) {
      throw new UnauthorizedException(
        'No .setup-token file found. Run the setup script to generate one.',
      );
    }

    if (providedToken !== fileToken) {
      throw new UnauthorizedException('Invalid setup token.');
    }

    return true;
  }
}
