/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type { AccountResponseDtoEventsItem } from './accountResponseDtoEventsItem';
import type { AccountResponseDtoContactsItem } from './accountResponseDtoContactsItem';
import type { AccountResponseDtoDeliveryAddressesItem } from './accountResponseDtoDeliveryAddressesItem';
import type { AccountResponseDtoCreditAssessment } from './accountResponseDtoCreditAssessment';

export interface AccountResponseDto {
  customerId: string;
  actorId: string;
  customerNumber: string;
  name: string;
  billingAddressLine1?: string;
  billingAddressLine2?: string;
  billingAddressCity?: string;
  billingAddressStateOrProvince?: string;
  billingAddressPostalCode?: string;
  billingAddressCountry: string;
  telephone1?: string;
  fax?: string;
  emailAddress1?: string;
  customerGroupId?: string;
  taxPositionId?: string;
  currencyCode: string;
  customerDiscount?: string;
  notes?: string;
  bankAccountName?: string;
  bankBsb?: string;
  bankAccountNumber?: string;
  businessNumber?: string;
  isTaxRegistered?: boolean;
  creditLimit?: string;
  isOnCreditHold?: boolean;
  isSalesBlocked?: boolean;
  salesBlockReasons?: string[];
  overrideCreditHoldUntil?: string;
  tradingTermsId?: string;
  earlyPaymentDiscount?: string;
  earlyPaymentDiscountDays?: number;
  stateCode: string;
  sourceId?: string;
  source: string;
  createdBy?: string;
  createdOn?: string;
  modifiedOn?: string;
  /** @nullable */
  parentCustomerId?: string | null;
  /** @nullable */
  parentCustomerName?: string | null;
  childAccounts?: AccountResponseDto[];
  events?: AccountResponseDtoEventsItem[];
  contacts?: AccountResponseDtoContactsItem[];
  deliveryAddresses?: AccountResponseDtoDeliveryAddressesItem[];
  creditAssessment?: AccountResponseDtoCreditAssessment;
  effectiveCreditLimit?: string;
}
