/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type { AccountResponseDto } from './accountResponseDto';

export type AccountsControllerFindAll200AllOf = {
  data?: AccountResponseDto[];
};
