/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */

export interface AccountGroupResponseDto {
  earlyPaymentDiscount?: string;
  earlyPaymentDiscountDays?: number;
  customerGroupId: string;
  groupCode: string;
  name: string;
  defaultDiscountPercentage?: string;
  defaultArAccountId?: string;
  defaultRevenueAccountId?: string;
  defaultCostCenterId?: string;
  defaultActivityId?: string;
  stateCode?: string;
  isOnCreditHold?: boolean;
  creditLimit?: string;
  tradingTermsId?: string;
  taxPositionId?: string;
  modifiedOn?: string;
}
