/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type { ActorOwnerDto } from './actorOwnerDto';

/**
 * @nullable
 */
export type ActorResponseDtoOwner = ActorOwnerDto | null;
