/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type { ActorResponseDtoOwner } from './actorResponseDtoOwner';
import type { ActorNoteResponseDto } from './actorNoteResponseDto';
import type { ActorResponseDtoActorContactLinksItem } from './actorResponseDtoActorContactLinksItem';
import type { ActorResponseDtoEventsItem } from './actorResponseDtoEventsItem';
import type { ActorResponseDtoCustomersItem } from './actorResponseDtoCustomersItem';
import type { ActorResponseDtoSuppliersItem } from './actorResponseDtoSuppliersItem';

export interface ActorResponseDto {
  /** @nullable */
  ownerId?: string | null;
  /** @nullable */
  owner?: ActorResponseDtoOwner;
  /** @nullable */
  ownerDisplayName?: string | null;
  actorId: string;
  stateCode: string;
  name: string;
  legalStatus?: string;
  headquartersAddressLine1?: string;
  headquartersAddressLine2?: string;
  headquartersCity?: string;
  headquartersStateOrProvince?: string;
  headquartersPostalCode?: string;
  headquartersCountry?: string;
  website?: string;
  industry?: string;
  telephone?: string;
  fax?: string;
  email?: string;
  businessNumber?: string;
  isTaxRegistered: boolean;
  createdOn: string;
  modifiedOn: string;
  tags?: string[];
  notes?: ActorNoteResponseDto[];
  actorContactLinks?: ActorResponseDtoActorContactLinksItem[];
  events?: ActorResponseDtoEventsItem[];
  /** @nullable */
  referralMode?: string | null;
  /** @nullable */
  referredByActorId?: string | null;
  /** @nullable */
  referredByContactId?: string | null;
  /** @nullable */
  referredByActorName?: string | null;
  /** @nullable */
  referredByContactName?: string | null;
  /** @nullable */
  referralNote?: string | null;
  customers?: ActorResponseDtoCustomersItem[];
  suppliers?: ActorResponseDtoSuppliersItem[];
}
