/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type { PaginatedResponse } from './paginatedResponse';
import type { ActorsControllerFindAll200AllOf } from './actorsControllerFindAll200AllOf';

export type ActorsControllerFindAll200 = PaginatedResponse & ActorsControllerFindAll200AllOf;
