/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type { ActorLinkResponseDtoLinkType } from './actorLinkResponseDtoLinkType';
import type { ActorLinkPartnerDto } from './actorLinkPartnerDto';

export interface ActorLinkResponseDto {
  linkId: string;
  sourceActorId: string;
  targetActorId: string;
  linkType: ActorLinkResponseDtoLinkType;
  createdOn: string;
  targetActor?: ActorLinkPartnerDto;
  sourceActor?: ActorLinkPartnerDto;
}
