/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */

export type ActorLinkResponseDtoLinkType = typeof ActorLinkResponseDtoLinkType[keyof typeof ActorLinkResponseDtoLinkType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ActorLinkResponseDtoLinkType = {
  parent_company: 'parent_company',
  subsidiary: 'subsidiary',
  partner: 'partner',
  referrer: 'referrer',
} as const;
