/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type { ActorNoteResponseDto } from './actorNoteResponseDto';
import type { ActorResponseDtoActorContactLinksItem } from './actorResponseDtoActorContactLinksItem';
import type { ActorResponseDtoEventsItem } from './actorResponseDtoEventsItem';

export interface ActorResponseDto {
  actorId: string;
  name: string;
  legalStatus?: string;
  headquartersAddressLine1?: string;
  headquartersAddressLine2?: string;
  headquartersCity?: string;
  headquartersStateOrProvince?: string;
  headquartersPostalCode?: string;
  headquartersCountry?: string;
  website?: string;
  industry?: string;
  telephone?: string;
  fax?: string;
  email?: string;
  businessNumber?: string;
  isTaxRegistered: boolean;
  createdOn: string;
  modifiedOn: string;
  tags?: string[];
  notes?: ActorNoteResponseDto[];
  actorContactLinks?: ActorResponseDtoActorContactLinksItem[];
  events?: ActorResponseDtoEventsItem[];
}
