/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */

export type AddProductComponentDtoFractionalBehavior = typeof AddProductComponentDtoFractionalBehavior[keyof typeof AddProductComponentDtoFractionalBehavior];


// eslint-disable-next-line @typescript-eslint/no-redeclare -- External API integration boundaries where exact types are unknown.
export const AddProductComponentDtoFractionalBehavior = {
  allow_fractional: 'allow_fractional',
  round_up: 'round_up',
  round_down: 'round_down',
  round_nearest: 'round_nearest',
} as const;
