/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type { AddProductComponentDtoFractionalBehavior } from './addProductComponentDtoFractionalBehavior';

export interface AddProductComponentDto {
  childProductId: string;
  parentQuantity: string;
  quantity: string;
  sequenceNumber?: number;
  fractionalBehavior?: AddProductComponentDtoFractionalBehavior;
}
