/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */

export type AddReturnLineDtoResolution = typeof AddReturnLineDtoResolution[keyof typeof AddReturnLineDtoResolution];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AddReturnLineDtoResolution = {
  refund: 'refund',
  replace: 'replace',
} as const;
