/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * ModBM API
 * Core Forgeron API System endpoints
 * OpenAPI spec version: 1.0
 */

export interface AddSupplierDto {
  vendorId: string;
  supplierPartNumber?: string;
  /** @minimum 0 */
  costPrice?: number;
  effectiveFrom?: string;
  effectiveTo?: string;
}
