/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.1
 */

export interface AddServiceMemberDto {
  /** Resource ID of the person to assign to the service product */
  resourceId: string;
}
