/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */

export interface AgedBalanceResponseDto {
  customerId: string;
  customerName: string;
  accountNumber: string;
  current: number;
  days1To30: number;
  days31To60: number;
  days61To90: number;
  days90Plus: number;
  totalOutstanding: number;
  glBalance: number;
  discrepancyAmount: number;
  currencyCode: string;
  isOnCreditHold: boolean;
  /** @nullable */
  creditLimit: string | null;
}
