/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type { AnomalyDetailDtoDetails } from './anomalyDetailDtoDetails';

export interface AnomalyDetailDto {
  type: string;
  invoiceNumber?: string;
  invoiceId?: string;
  journalEntryId?: string;
  entryNumber?: string;
  details?: AnomalyDetailDtoDetails;
}
