/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type { AppConfigResponseDtoCreditLimitBehavior } from './appConfigResponseDtoCreditLimitBehavior';
import type { AppConfigResponseDtoTaxProviderMappings } from './appConfigResponseDtoTaxProviderMappings';
import type { AppConfigResponseDtoEnrichmentProviderMappings } from './appConfigResponseDtoEnrichmentProviderMappings';
import type { OrderedSettingDto } from './orderedSettingDto';

export interface AppConfigResponseDto {
  defaultFulfillmentLocationId: string;
  apiRateLimit: string;
  creditLimitBehavior?: AppConfigResponseDtoCreditLimitBehavior;
  taxProviderMappings?: AppConfigResponseDtoTaxProviderMappings;
  enrichmentProviderMappings?: AppConfigResponseDtoEnrichmentProviderMappings;
  smtpHost?: string;
  smtpPort?: number;
  smtpUser?: string;
  smtpPass?: string;
  smtpFromAddress?: string;
  defaultPurchaseTaxCategoryId?: string;
  defaultSalesTaxCategoryId?: string;
  defaultCustomerTermsId?: string;
  defaultSupplierTermsId?: string;
  defaultCustomerTaxPositionId?: string;
  defaultSupplierTaxPositionId?: string;
  actorTags?: OrderedSettingDto[];
  actorContactRoles?: OrderedSettingDto[];
  projectContactRoles?: OrderedSettingDto[];
  projectActorRoles?: OrderedSettingDto[];
  projectStatuses?: OrderedSettingDto[];
  projectTypes?: OrderedSettingDto[];
  referralModes?: OrderedSettingDto[];
}
