/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type { AppConfigResponseDtoTaxProviderMappings } from './appConfigResponseDtoTaxProviderMappings';
import type { AppConfigResponseDtoEnrichmentProviderMappings } from './appConfigResponseDtoEnrichmentProviderMappings';

export interface AppConfigResponseDto {
  defaultFulfillmentLocationId: string;
  apiRateLimit: string;
  taxProviderMappings?: AppConfigResponseDtoTaxProviderMappings;
  enrichmentProviderMappings?: AppConfigResponseDtoEnrichmentProviderMappings;
  smtpHost?: string;
  smtpPort?: number;
  smtpUser?: string;
  smtpPass?: string;
  smtpFromAddress?: string;
  defaultPurchaseTaxCategoryId?: string;
  defaultSalesTaxCategoryId?: string;
}
