/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.1
 */

export interface AssignProjectResourceDto {
  /** Project Resource ID to assign to the project */
  resourceId: string;
  /** Optional staffing notes or role on project */
  notes?: string;
}
