/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type { AutoMatchSmartMatchDtoConfidence } from './autoMatchSmartMatchDtoConfidence';

export interface AutoMatchSmartMatchDto {
  bankLineIds: string[];
  journalLineIds: string[];
  confidence: AutoMatchSmartMatchDtoConfidence;
  date: string;
  description: string;
  amount: number;
}
