/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type { AutoMatchSmartMatchDto } from './autoMatchSmartMatchDto';
import type { AutoMatchProposedRuleMatchDto } from './autoMatchProposedRuleMatchDto';

export interface AutoMatchResponseDto {
  autoMatchedCount: number;
  smartMatchedCount: number;
  unmatchedCount: number;
  smartMatches: AutoMatchSmartMatchDto[];
  proposedRuleMatches?: AutoMatchProposedRuleMatchDto[];
}
