/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */

export interface AvailablePoLineDto {
  purchaseOrderId: string;
  purchaseOrderLineId: string;
  orderNumber: string;
  stateCode: string;
  quantity: string;
  vendorId: string;
  vendorName: string;
  deliveryLocationId: string;
  locationName: string;
  availableQty: number;
}
