/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.1
 */

export interface BalanceSheetValidationDto {
  totalAssets: number;
  totalLiabilities: number;
  totalEquity: number;
  totalLiabilitiesAndEquity: number;
  drift: number;
  isBalanced: boolean;
  totalAssetsMovementMtd?: number;
  totalLiabilitiesAndEquityMovementMtd?: number;
  totalAssetsMovementYtd?: number;
  totalLiabilitiesAndEquityMovementYtd?: number;
  totalAssetsMovementLastYtd?: number;
  totalLiabilitiesAndEquityMovementLastYtd?: number;
}
