/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */

export interface BinResponseDto {
  id: string;
  zoneId: string;
  binNumber: string;
  binType?: string;
  isConsignment?: boolean;
  isBonded?: boolean;
  isUnavailable?: boolean;
  createdAt: string;
  updatedAt: string;
}
