/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */

export type CashFlowLineItemDtoCategory = typeof CashFlowLineItemDtoCategory[keyof typeof CashFlowLineItemDtoCategory];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CashFlowLineItemDtoCategory = {
  operating: 'operating',
  investing: 'investing',
  financing: 'financing',
} as const;
