/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type { CashFlowLineItemDto } from './cashFlowLineItemDto';

export interface CashFlowSectionDto {
  title: string;
  lines: CashFlowLineItemDto[];
  netCash: number;
}
