/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type { CashFlowPeriodDto } from './cashFlowPeriodDto';
import type { CashFlowSectionDto } from './cashFlowSectionDto';
import type { CashFlowReconciliationDto } from './cashFlowReconciliationDto';
import type { CashFlowStatementResponseDto as PackagesSdk__CashFlowStatementResponseDto } from './cashFlowStatementResponseDto';

export interface CashFlowStatementResponseDto {
  period: CashFlowPeriodDto;
  operatingActivities: CashFlowSectionDto;
  investingActivities: CashFlowSectionDto;
  financingActivities: CashFlowSectionDto;
  reconciliation: CashFlowReconciliationDto;
  comparativePeriod?: PackagesSdk__CashFlowStatementResponseDto;
}
