/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */

export interface CashFlowReconciliationDto {
  beginningCash: number;
  netChangeInCash: number;
  endingCash: number;
  glCashBalance: number;
  drift: number;
  isReconciled: boolean;
}
