/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */

export interface ClientErrorDto {
  /** @maxLength 1000 */
  message: string;
  /** @maxLength 5000 */
  stack?: string;
  /** @maxLength 255 */
  component?: string;
  url?: string;
}
