/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.1
 */
import type { ConsumeExpenseDtoSourceType } from './consumeExpenseDtoSourceType';
import type { ConsumeExpenseDtoMetadata } from './consumeExpenseDtoMetadata';

export interface ConsumeExpenseDto {
  /** Project Task ID to record expense on */
  projectTaskId: string;
  /** Description of the direct project expense */
  description: string;
  /**
   * Quantity (default: 1)
   * @minimum 0.0001
   */
  quantity?: number;
  /**
   * Unit cost rate of the expense
   * @minimum 0
   */
  unitCost: number;
  /**
   * Unit billable price rate (defaults to unitCost)
   * @minimum 0
   */
  unitPrice?: number;
  /**
   * Alias for unitPrice (billable unit price rate)
   * @minimum 0
   */
  unitBillablePrice?: number;
  /** Override discount percentage */
  discountPercentage?: number;
  /** Date of expense posting */
  postingDate?: string;
  /** Date when the expense occurred */
  expenseDate?: string;
  /** Receipt / reference number */
  referenceNumber?: string;
  /** Additional expense notes */
  notes?: string;
  /** Source document ID (e.g., invoice ID, receipt ID) */
  sourceId?: string;
  /** Target Budget Line ID */
  budgetLineId?: string;
  /** Source type (defaults to manual_journal) */
  sourceType?: ConsumeExpenseDtoSourceType;
  /** Custom metadata object */
  metadata?: ConsumeExpenseDtoMetadata;
}
