/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type { Object } from './object';

export type ContactsControllerFindAllParams = {
q?: string;
page?: number;
cursor?: string;
direction?: Object;
limit?: number;
state?: string;
includeArchived?: boolean;
customerId?: string;
vendorId?: string;
days?: Object;
purchaseOrderId?: string;
productId?: string;
sort?: string;
sortDirection?: Object;
/**
 * Comma separated list of fields to include in the response (e.g. "id,name")
 */
fields?: string;
};
