/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */

export interface ContactResponseDto {
  id: string;
  firstName: string;
  lastName: string;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  phone?: string | null;
  /** @nullable */
  mobile?: string | null;
  /** @nullable */
  jobTitle?: string | null;
  isPrimary: boolean;
  /** @nullable */
  createdOn: string | null;
  /** @nullable */
  modifiedOn: string | null;
}
