/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type { PaginatedResponse } from './paginatedResponse';
import type { ContactsControllerFindAll200AllOf } from './contactsControllerFindAll200AllOf';

export type ContactsControllerFindAll200 = PaginatedResponse & ContactsControllerFindAll200AllOf;
