/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */

export interface CopyProductDto {
  /** Optional new unique SKU. If omitted, will be auto-generated with -COPY suffix. */
  productNumber?: string;
  /** Optional new product name. If omitted, defaults to source name with (Copy). */
  name?: string;
}
