/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */

export interface CreateWorkOrderComponentDto {
  /** Product ID of the component item */
  productId: string;
  /** Expected component quantity for this work order */
  expectedQuantity: string;
  /** Optional unit cost */
  unitCost?: string;
}
