/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.1
 */
import type { CreateShipmentLineDto } from './createShipmentLineDto';

export interface CreateShipmentDto {
  notes?: string;
  shippingNotes?: string;
  deliveryCompanyName?: string;
  trackingNumber?: string;
  lines: CreateShipmentLineDto[];
}
