/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * ModBM API
 * Core Forgeron API System endpoints
 * OpenAPI spec version: 1.0
 */
import type { CreatePaymentDtoPaymentType } from './createPaymentDtoPaymentType';
import type { CreatePaymentDtoPartyType } from './createPaymentDtoPartyType';
import type { CreatePaymentDtoModeOfPayment } from './createPaymentDtoModeOfPayment';

export interface CreatePaymentDto {
  paymentId: string;
  paymentType: CreatePaymentDtoPaymentType;
  partyType: CreatePaymentDtoPartyType;
  partyId: string;
  paymentDate: string;
  modeOfPayment: CreatePaymentDtoModeOfPayment;
  /** @minimum 0.01 */
  totalAmount: number;
  glAccountBank: string;
  referenceNumber?: string;
  currencyCode: string;
  submitImmediately?: boolean;
}
