/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * ModBM API
 * Core Forgeron API System endpoints
 * OpenAPI spec version: 1.0
 */

export interface CreateAccountDto {
  customerNumber: string;
  name: string;
  address1Line1?: string;
  address1Line2?: string;
  address1City?: string;
  address1StateOrProvince?: string;
  address1PostalCode?: string;
  address1Country?: string;
  telephone1?: string;
  fax?: string;
  emailAddress1?: string;
  primaryContactName?: string;
  primaryContactEmail?: string;
  primaryContactPhone?: string;
  customerGroupId?: string;
  parentCustomerId?: string;
  taxCategoryId?: string;
  currencyCode?: string;
  customerDiscount?: string;
  notes?: string;
  bankAccountName?: string;
  bankBsb?: string;
  bankAccountNumber?: string;
}
