/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type { CreateCrmActivityDtoType } from './createCrmActivityDtoType';
import type { CreateCrmActivityDtoStatus } from './createCrmActivityDtoStatus';
import type { CreateCrmActivityDtoPriority } from './createCrmActivityDtoPriority';

export interface CreateCrmActivityDto {
  type: CreateCrmActivityDtoType;
  subject: string;
  description?: string;
  status: CreateCrmActivityDtoStatus;
  priority: CreateCrmActivityDtoPriority;
  actorId?: string;
  contactIds?: string[];
  opportunityId?: string;
  dueDate?: string;
  assignedToUserId?: string;
}
