/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */

export type CreateCrmActivityDtoStatus = typeof CreateCrmActivityDtoStatus[keyof typeof CreateCrmActivityDtoStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateCrmActivityDtoStatus = {
  open: 'open',
  completed: 'completed',
  cancelled: 'cancelled',
  scheduled: 'scheduled',
} as const;
