/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type { CreateBusinessReportDtoUiConfig } from './createBusinessReportDtoUiConfig';

export interface CreateBusinessReportDto {
  /** The unique slug of the report configuration */
  slug: string;
  /** The name of the report */
  name: string;
  /** Description of the report */
  description?: string;
  /** The data source hook */
  dataSourceHook: string;
  /** UI configuration as JSON object */
  uiConfig?: CreateBusinessReportDtoUiConfig;
}
