/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * ModBM API
 * Core Forgeron API System endpoints
 * OpenAPI spec version: 1.0
 */

export type CreateSupplierGroupDtoPurchasingBlockReason = typeof CreateSupplierGroupDtoPurchasingBlockReason[keyof typeof CreateSupplierGroupDtoPurchasingBlockReason];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateSupplierGroupDtoPurchasingBlockReason = {
  compliance_breach: 'compliance_breach',
  quality_issues: 'quality_issues',
  dispute: 'dispute',
  financial_risk: 'financial_risk',
  other: 'other',
} as const;
