/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.1
 */
import type { CreateSalesCreditNoteLineDto } from './createSalesCreditNoteLineDto';

export interface CreateSalesCreditNoteDto {
  returnId?: string;
  customerId?: string;
  notes?: string;
  lines?: CreateSalesCreditNoteLineDto[];
}
