/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.1
 */

export interface CreateProjectTaskDto {
  /** Task WBS code (e.g. 1.0, 1.1) */
  taskCode: string;
  /** Task name */
  name: string;
  /** Task description */
  description?: string;
  /** Parent task ID for hierarchical subtasks */
  parentTaskId?: string;
  /** Is milestone trigger */
  isMilestone?: boolean;
  /** Is task billable to customer */
  isBillable?: boolean;
  plannedStartDate?: string;
  plannedEndDate?: string;
}
