/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * ModBM API
 * Core Forgeron API System endpoints
 * OpenAPI spec version: 1.0
 */
import type { CreatePurchaseReturnLineDto } from './createPurchaseReturnLineDto';

export interface CreatePurchaseReturnDto {
  notes?: string;
  lines: CreatePurchaseReturnLineDto[];
}
