/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */

export type CreateCrmActivityDtoType = typeof CreateCrmActivityDtoType[keyof typeof CreateCrmActivityDtoType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateCrmActivityDtoType = {
  call: 'call',
  meeting: 'meeting',
  email: 'email',
  task: 'task',
  note: 'note',
} as const;
