/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type { CreateUserDtoRole } from './createUserDtoRole';

export interface CreateUserDto {
  /**
   * @minLength 2
   * @maxLength 50
   * @pattern /^[a-zA-Z0-9_.-]+$/
   */
  username: string;
  /**
   * @minLength 6
   * @maxLength 72
   */
  password: string;
  role: CreateUserDtoRole;
  /** @maxLength 100 */
  displayName?: string;
  /** @maxLength 255 */
  email?: string;
}
