/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */

export type CreateSupplierExpiryDtoExpiryType = typeof CreateSupplierExpiryDtoExpiryType[keyof typeof CreateSupplierExpiryDtoExpiryType];


// eslint-disable-next-line @typescript-eslint/no-redeclare -- External API integration boundaries where exact types are unknown.
export const CreateSupplierExpiryDtoExpiryType = {
  insurance: 'insurance',
  tax_certificate: 'tax_certificate',
  trial_period: 'trial_period',
  other: 'other',
} as const;
