/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type { CreateProductDtoProductType } from './createProductDtoProductType';
import type { CreateProductDtoStructureType } from './createProductDtoStructureType';

export interface CreateProductDto {
  productNumber: string;
  name: string;
  productType?: CreateProductDtoProductType;
  structureType?: CreateProductDtoStructureType;
  barcode?: string;
  listPrice?: string;
  standardCost?: string;
  tradePrice?: string;
  priceLevel3?: string;
  priceLevel4?: string;
  purchaseTaxCategoryId?: string;
  salesTaxCategoryId?: string;
  externalTaxCode?: string;
  alternateProductNumber?: string;
  imagePath?: string;
  productGroupId?: string;
  notes?: string;
  stateCode?: string;
  baseUom: string;
  weight?: string;
  alternateInvoiceDescription?: string;
  boxQuantity?: string;
  defaultSalesUomId?: string;
  defaultPurchaseUomId?: string;
}
