/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * ModBM API
 * Core Forgeron API System endpoints
 * OpenAPI spec version: 1.0
 */
import type { CreatePurchaseOrderLineDto } from './createPurchaseOrderLineDto';

export interface CreatePurchaseOrderDto {
  purchaseOrderId: string;
  orderNumber: string;
  deliveryLocationId: string;
  name?: string;
  vendorId: string;
  currencyCode?: string;
  notes?: string;
  referenceNumber?: string;
  lines?: CreatePurchaseOrderLineDto[];
}
