/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */

export type CreateContactDtoEntityType = typeof CreateContactDtoEntityType[keyof typeof CreateContactDtoEntityType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateContactDtoEntityType = {
  customer: 'customer',
  actor: 'actor',
  project: 'project',
} as const;
