/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */

export type CreateBinDtoBinType = typeof CreateBinDtoBinType[keyof typeof CreateBinDtoBinType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateBinDtoBinType = {
  storage: 'storage',
  pick: 'pick',
  bulk: 'bulk',
  receiving: 'receiving',
  staging: 'staging',
  quarantine: 'quarantine',
  in_transit: 'in_transit',
} as const;
