/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */

export interface CreateOpportunityDto {
  name: string;
  status?: string;
  type: string;
  ownerId?: string;
  estimatedValue?: string;
  currencyCode?: string;
  targetCloseDate?: string;
  /**
   * @minimum 0
   * @maximum 100
   */
  probability?: number;
  actualValue?: string;
  description?: string;
}
