/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * ModBM API
 * Core Forgeron API System endpoints
 * OpenAPI spec version: 1.0
 */
import type { JournalLineDto } from './journalLineDto';

export interface CreateJournalEntryDto {
  journalEntryId: string;
  lines: JournalLineDto[];
  memo?: string;
  entryDate?: string;
  actor?: string;
}
