/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * ModBM API
 * Core Forgeron API System endpoints
 * OpenAPI spec version: 1.0
 */
import type { CreateTaxCategoryDtoType } from './createTaxCategoryDtoType';

export interface CreateTaxCategoryDto {
  code: string;
  title: string;
  type: CreateTaxCategoryDtoType;
  rate?: string;
  isDefault?: boolean;
}
