/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.1
 */
import type { CreateTransferOrderLineDto } from './createTransferOrderLineDto';

export interface CreateTransferOrderDto {
  sourceLocationId: string;
  destinationLocationId: string;
  notes?: string;
  shippingNotes?: string;
  lines: CreateTransferOrderLineDto[];
}
