/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */

export interface CreateTaxPositionMappingDto {
  /** @maxLength 255 */
  sourceTaxCategoryId: string;
  /** @maxLength 255 */
  destinationTaxCategoryId: string;
}
