/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type { CreateOrderLineDto } from './createOrderLineDto';
import type { OrderCustomFieldsDto } from './orderCustomFieldsDto';

export interface CreateOrderDto {
  salesOrderId: string;
  name?: string;
  customerId: string;
  customerOrderNumber?: string;
  notes?: string;
  fulfillmentLocationId?: string;
  shippingNotes?: string;
  deliveryCompanyName?: string;
  deliveryName?: string;
  deliveryPhone?: string;
  deliveryAddressLine1?: string;
  deliveryAddressLine2?: string;
  deliveryCity?: string;
  deliveryState?: string;
  deliveryPostalCode?: string;
  deliveryCountry?: string;
  lines: CreateOrderLineDto[];
  customFields?: OrderCustomFieldsDto;
}
