/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type { CreateAccountRequestDtoMetadata } from './createAccountRequestDtoMetadata';

export interface CreateAccountRequestDto {
  accountCode: string;
  name: string;
  accountType: string;
  parentAccountId?: string;
  isGroup?: boolean;
  isBankAccount?: boolean;
  currencyCode?: string;
  metadata?: CreateAccountRequestDtoMetadata;
}
