/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */

export type CreateSupplierGroupDtoPaymentBlockReason = typeof CreateSupplierGroupDtoPaymentBlockReason[keyof typeof CreateSupplierGroupDtoPaymentBlockReason];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateSupplierGroupDtoPaymentBlockReason = {
  invoice_dispute: 'invoice_dispute',
  missing_goods: 'missing_goods',
  contractual_breach: 'contractual_breach',
  other: 'other',
} as const;
