/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */

export interface CreateBankStatementLineDto {
  glAccountId: string;
  date: string;
  description: string;
  amount: number;
  /** @nullable */
  reference?: string | null;
  /** @nullable */
  type?: string | null;
  /** @nullable */
  payee?: string | null;
}
