/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.1
 */

export type CreateProjectBudgetLineDtoLineType = typeof CreateProjectBudgetLineDtoLineType[keyof typeof CreateProjectBudgetLineDtoLineType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateProjectBudgetLineDtoLineType = {
  resource: 'resource',
  item: 'item',
  expense: 'expense',
} as const;
