/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * ModBM API
 * Core Forgeron API System endpoints
 * OpenAPI spec version: 1.0
 */
import type { CreateShipmentLineDto } from './createShipmentLineDto';

export interface CreateShipmentDto {
  notes?: string;
  trackingNumber?: string;
  lines: CreateShipmentLineDto[];
}
