/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */

export type CreateUserDtoRole = typeof CreateUserDtoRole[keyof typeof CreateUserDtoRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateUserDtoRole = {
  admin: 'admin',
  viewer: 'viewer',
  sales: 'sales',
  warehouse: 'warehouse',
  procurement: 'procurement',
  finance: 'finance',
} as const;
