/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.1
 */
import type { CreateProjectBudgetLineDtoLineType } from './createProjectBudgetLineDtoLineType';

export interface CreateProjectBudgetLineDto {
  /** Target Project Task ID */
  projectTaskId: string;
  lineType: CreateProjectBudgetLineDtoLineType;
  /** Resource ID (if lineType is resource) */
  resourceId?: string;
  /** Product ID (if lineType is item) */
  productId?: string;
  description?: string;
  /**
   * Planned quantity
   * @minimum 0
   */
  plannedQuantity: number;
  /**
   * Unit cost estimate
   * @minimum 0
   */
  unitCost: number;
  /**
   * Unit price estimate
   * @minimum 0
   */
  unitPrice: number;
  /** Override line discount percentage */
  discountPercentage?: number;
}
