/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.1
 */
import type { CreateProjectResourceDtoResourceType } from './createProjectResourceDtoResourceType';

export interface CreateProjectResourceDto {
  /** Resource name */
  name: string;
  resourceType: CreateProjectResourceDtoResourceType;
  /** Linked system user ID (for employees) */
  userId?: string;
  /** Linked supplier ID (for external contractors) */
  vendorId?: string;
  /** Default service product SKU for billing */
  serviceProductId?: string;
  /** Base unit of measure (e.g. HOUR, DAY) */
  baseUom: string;
  /**
   * Internal unit cost rate
   * @minimum 0
   */
  directUnitCost?: number;
  /**
   * Default billing unit price rate
   * @minimum 0
   */
  unitPrice: number;
  /** Is resource active */
  isActive?: boolean;
}
