/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.1
 */
import type { CreateCrmActivityDtoStatus } from './createCrmActivityDtoStatus';
import type { CreateCrmActivityDtoPriority } from './createCrmActivityDtoPriority';

export interface CreateCrmActivityDto {
  /** Activity type (e.g. call, meeting, email, task, note or custom type) */
  type: string;
  subject: string;
  description?: string;
  status: CreateCrmActivityDtoStatus;
  priority: CreateCrmActivityDtoPriority;
  organizationId?: string;
  contactIds?: string[];
  opportunityId?: string;
  dueDate?: string;
  assignedToUserId?: string;
}
