/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type { CreateDebitNoteLineDto } from './createDebitNoteLineDto';

export interface CreateDebitNoteDto {
  returnId: string;
  supplierReferenceNumber?: string;
  lines: CreateDebitNoteLineDto[];
  taxAmount?: string;
  feeAmount?: string;
  notes?: string;
}
