/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type { CreatePaymentDtoPaymentType } from './createPaymentDtoPaymentType';
import type { CreatePaymentDtoModeOfPayment } from './createPaymentDtoModeOfPayment';
import type { PaymentLineDto } from './paymentLineDto';

export interface CreatePaymentDto {
  paymentId: string;
  paymentType: CreatePaymentDtoPaymentType;
  partyId?: string;
  paymentDate: string;
  modeOfPayment: CreatePaymentDtoModeOfPayment;
  /** @minimum 0.01 */
  totalAmount: number;
  glAccountBank: string;
  referenceNumber?: string;
  currencyCode: string;
  submitImmediately?: boolean;
  lines?: PaymentLineDto[];
}
