/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type { CrmActivitiesControllerFindAllType } from './crmActivitiesControllerFindAllType';
import type { CrmActivitiesControllerFindAllStatus } from './crmActivitiesControllerFindAllStatus';
import type { CrmActivitiesControllerFindAllPriority } from './crmActivitiesControllerFindAllPriority';
import type { Object } from './object';

export type CrmActivitiesControllerFindAllParams = {
actorId?: string;
contactId?: string;
opportunityId?: string;
assignedToUserId?: string;
type?: CrmActivitiesControllerFindAllType;
status?: CrmActivitiesControllerFindAllStatus;
priority?: CrmActivitiesControllerFindAllPriority;
myTasks?: string;
q?: string;
page?: number;
cursor?: string;
direction?: Object;
limit?: number;
state?: string;
includeArchived?: boolean;
customerId?: string;
vendorId?: string;
days?: Object;
purchaseOrderId?: string;
productId?: string;
projectId?: string;
sort?: string;
sortDirection?: Object;
};
