/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.1
 */
import type { Object } from './object';
import type { CrmActivitiesControllerFindAllStatus } from './crmActivitiesControllerFindAllStatus';
import type { CrmActivitiesControllerFindAllPriority } from './crmActivitiesControllerFindAllPriority';

export type CrmActivitiesControllerFindAllParams = {
organizationId?: string;
contactId?: string;
opportunityId?: string;
assignedToUserId?: string;
/**
 * Activity type (e.g. call, meeting, email, task, note or custom type)
 */
type?: Object;
status?: CrmActivitiesControllerFindAllStatus;
priority?: CrmActivitiesControllerFindAllPriority;
myTasks?: string;
/**
 * Filter open tasks that are overdue
 */
isOverdue?: string;
/**
 * Filter activities with due date on or after this ISO date
 */
dueDateFrom?: string;
/**
 * Filter activities with due date on or before this ISO date
 */
dueDateTo?: string;
q?: string;
page?: number;
cursor?: string;
direction?: Object;
limit?: number;
state?: string;
includeArchived?: boolean;
customerId?: string;
vendorId?: string;
days?: Object;
purchaseOrderId?: string;
productId?: string;
projectId?: string;
sort?: string;
sortDirection?: Object;
};
