/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */

export type CrmActivitiesControllerFindAllPriority = typeof CrmActivitiesControllerFindAllPriority[keyof typeof CrmActivitiesControllerFindAllPriority];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CrmActivitiesControllerFindAllPriority = {
  low: 'low',
  medium: 'medium',
  high: 'high',
  urgent: 'urgent',
} as const;
