/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type { CrmMapActorActorLinkDto } from './crmMapActorActorLinkDto';
import type { CrmMapActorContactLinkDto } from './crmMapActorContactLinkDto';
import type { CrmMapProjectActorLinkDto } from './crmMapProjectActorLinkDto';
import type { CrmMapProjectContactLinkDto } from './crmMapProjectContactLinkDto';

export interface CrmMapEdgesDto {
  actorActor: CrmMapActorActorLinkDto[];
  actorContact: CrmMapActorContactLinkDto[];
  projectActor: CrmMapProjectActorLinkDto[];
  projectContact: CrmMapProjectContactLinkDto[];
  referralActorActor?: CrmMapActorActorLinkDto[];
  referralContactActor?: CrmMapActorContactLinkDto[];
}
