/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type { CrmMapActorActorLinkDto } from './crmMapActorActorLinkDto';
import type { CrmMapActorContactLinkDto } from './crmMapActorContactLinkDto';
import type { CrmMapOpportunityActorLinkDto } from './crmMapOpportunityActorLinkDto';
import type { CrmMapOpportunityContactLinkDto } from './crmMapOpportunityContactLinkDto';

export interface CrmMapEdgesDto {
  actorActor: CrmMapActorActorLinkDto[];
  actorContact: CrmMapActorContactLinkDto[];
  opportunityActor: CrmMapOpportunityActorLinkDto[];
  opportunityContact: CrmMapOpportunityContactLinkDto[];
  referralActorActor?: CrmMapActorActorLinkDto[];
  referralContactActor?: CrmMapActorContactLinkDto[];
}
