/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.1
 */
import type { CrmMapOrganizationNodeDto } from './crmMapOrganizationNodeDto';
import type { CrmMapContactNodeDto } from './crmMapContactNodeDto';
import type { CrmMapOpportunityNodeDto } from './crmMapOpportunityNodeDto';

export interface CrmMapNodesDto {
  organizations: CrmMapOrganizationNodeDto[];
  contacts: CrmMapContactNodeDto[];
  opportunities: CrmMapOpportunityNodeDto[];
}
