/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */

export type CrmMapControllerGetMapParams = {
/**
 * ID of the focal node
 */
focalNodeId?: string;
/**
 * Max distance from the focal node
 * @minimum 1
 */
maxDistance?: number;
};
