/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type { CrmMapNodesDto } from './crmMapNodesDto';
import type { CrmMapEdgesDto } from './crmMapEdgesDto';

export interface CrmMapResponseDto {
  nodes: CrmMapNodesDto;
  edges: CrmMapEdgesDto;
}
