/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type { CrmMapActorNodeDto } from './crmMapActorNodeDto';
import type { CrmMapContactNodeDto } from './crmMapContactNodeDto';
import type { CrmMapProjectNodeDto } from './crmMapProjectNodeDto';

export interface CrmMapNodesDto {
  actors: CrmMapActorNodeDto[];
  contacts: CrmMapContactNodeDto[];
  projects: CrmMapProjectNodeDto[];
}
