/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */

export type CustomersControllerGetAgedBalancesAgingBasis = typeof CustomersControllerGetAgedBalancesAgingBasis[keyof typeof CustomersControllerGetAgedBalancesAgingBasis];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CustomersControllerGetAgedBalancesAgingBasis = {
  invoiceDate: 'invoiceDate',
  dueDate: 'dueDate',
} as const;
