/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * ModBM API
 * Core Forgeron API System endpoints
 * OpenAPI spec version: 1.0
 */

export interface DbConfigDto {
  host?: string;
  database?: string;
  username?: string;
  password?: string;
  port?: number;
}
