/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */

export interface DeliveryAddressResponseDto {
  id: string;
  customerId: string;
  /** @nullable */
  addressName?: string | null;
  /** @nullable */
  companyName?: string | null;
  /** @nullable */
  recipientName?: string | null;
  /** @nullable */
  recipientPhone?: string | null;
  /** @nullable */
  addressLine1: string | null;
  /** @nullable */
  addressLine2?: string | null;
  /** @nullable */
  city?: string | null;
  /** @nullable */
  stateOrProvince?: string | null;
  /** @nullable */
  postalCode?: string | null;
  /** @nullable */
  country: string | null;
  isPrimary: boolean;
  /** @nullable */
  sourceId?: string | null;
  source: string;
  /** @nullable */
  createdOn?: string | null;
  /** @nullable */
  modifiedOn?: string | null;
}
