/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.1
 */
import type { DirectFulfilledLineDto } from './directFulfilledLineDto';

export interface DirectFulfillmentResponseDto {
  salesOrderId: string;
  orderNumber: string;
  stateCode: string;
  shipmentId?: string;
  shipmentNumber?: string;
  fulfilledLines: DirectFulfilledLineDto[];
  cogsAmount: string;
  message?: string;
}
