/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */

export type DiscountMatrixControllerListParams = {
customerGroupId: string;
customerId: string;
ownerType: string;
/**
 * Comma separated list of fields to include in the response (e.g. "id,name")
 */
fields?: string;
};
