/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */

export interface DiscountMatrixResponseDto {
  discountMatrixId: string;
  /** @nullable */
  customerGroupId: string | null;
  /** @nullable */
  customerId: string | null;
  /** @nullable */
  productGroupId: string | null;
  discountPercentage: string;
  /** @nullable */
  createdOn: string | null;
  /** @nullable */
  modifiedOn: string | null;
}
