/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */

export interface EmailDocumentDto {
  /** The recipient email address */
  emailAddress: string;
  /** The email subject */
  subject: string;
  /** The text body for the email */
  body: string;
  /** The hook slug for the PDF template to use (e.g. sales-order-quote) */
  hookSlug?: string;
  /** Custom text injected into the generated PDF */
  customPdfText?: string;
}
