/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */

export interface Enable2FaDto {
  /** @maxLength 255 */
  code: string;
  /** @maxLength 1024 */
  secret: string;
}
