/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.1
 */
import type { EnrichmentProviderDtoSchema } from './enrichmentProviderDtoSchema';

export interface EnrichmentProviderDto {
  name: string;
  type: string;
  supportedCountries: string[];
  schema: EnrichmentProviderDtoSchema;
}
