/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type { DbConfigDto } from './dbConfigDto';
import type { ExecuteEltDtoSource } from './executeEltDtoSource';

export interface ExecuteEltDto {
  /** If provided, all legacy invoices (sales and purchase) with a due date before this date will be considered paid. */
  legacyInvoicesPaidBeforeDate?: string;
  dbConfig?: DbConfigDto;
  source?: ExecuteEltDtoSource;
  resumeExtraction?: boolean;
  skipExtraction?: boolean;
  defaultLocationCode?: string;
  baseCurrency?: string;
  defaultTaxCategoryCode?: string;
  importInventoryFromLocations?: boolean;
}
