/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */

export type ExecuteEltDtoSource = typeof ExecuteEltDtoSource[keyof typeof ExecuteEltDtoSource];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ExecuteEltDtoSource = {
  abm: 'abm',
  odoo: 'odoo',
} as const;
