/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type { DbConfigDto } from './dbConfigDto';

export interface ExecuteEltDto {
  dbConfig?: DbConfigDto;
  abmImport?: boolean;
  odooImport?: boolean;
  resumeExtraction?: boolean;
  skipExtraction?: boolean;
  defaultLocationCode?: string;
  baseCurrency?: string;
  defaultTaxCategoryCode?: string;
  enableCustomImports?: boolean;
}
