/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.1
 */

export interface FulfillDirectLineDto {
  /** Sales order line ID to fulfill */
  salesOrderLineId: string;
  /** Quantity to directly fulfill */
  quantityToFulfill: string;
  /** Optional specific bin ID to issue stock from */
  binId?: string;
}
