/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type { FulfillCounterLineDto } from './fulfillCounterLineDto';

export interface FulfillCounterOrderDto {
  /** Specific lines and quantities to fulfill. If omitted, fulfills all unfulfilled lines up to available stock. */
  lines?: FulfillCounterLineDto[];
  /** Allow partial fulfillment if stock on hand is less than requested quantity */
  allowPartialFulfillment?: boolean;
  /** Optional fulfillment or handover notes */
  notes?: string;
}
