/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */

export interface FulfillCounterLineDto {
  /** Sales order line ID to fulfill */
  salesOrderLineId: string;
  /** Quantity to fulfill over the counter */
  quantityToFulfill: string;
  /** Optional specific bin ID to issue stock from */
  binId?: string;
}
