/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */

export interface GenerateFiscalPeriodsDto {
  /** Fiscal year e.g. 2026 */
  fiscalYear: number;
}
