/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */

/**
 * Indicates whether the net amount is payable, refundable, or zero
 */
export type GenericTaxSummaryDtoNetStatus = typeof GenericTaxSummaryDtoNetStatus[keyof typeof GenericTaxSummaryDtoNetStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GenericTaxSummaryDtoNetStatus = {
  payable: 'payable',
  refundable: 'refundable',
  zero: 'zero',
} as const;
