/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type { GenericTaxSummaryDtoNetStatus } from './genericTaxSummaryDtoNetStatus';
import type { TaxCategoryBreakdownDto } from './taxCategoryBreakdownDto';

export interface GenericTaxSummaryDto {
  /** Total output tax collected on sales (Tax Payable) */
  totalOutputTax: number;
  /** Total input tax paid on purchases (Tax Deductible / Reclaimable) */
  totalInputTax: number;
  /** Net tax liability or refund claim (Output Tax - Input Tax) */
  netTaxLiability: number;
  /** Indicates whether the net amount is payable, refundable, or zero */
  netStatus: GenericTaxSummaryDtoNetStatus;
  /** Total gross sales turnover (inclusive of tax) */
  totalGrossSales: number;
  /** Total net revenue / sales (exclusive of tax) */
  totalNetSales: number;
  /** Net taxable sales turnover */
  taxableSales: number;
  /** Net zero-rated or exempt sales turnover */
  exemptSales: number;
  /** Total net purchases / expense base */
  totalNetPurchases: number;
  /** Net taxable purchases */
  taxablePurchases: number;
  /** Base currency code */
  currencyCode: string;
  /** Breakdown of turnover and taxes by configured tax category */
  categories: TaxCategoryBreakdownDto[];
}
