/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */

export type GlControllerGetFiscalPeriodsStatus = typeof GlControllerGetFiscalPeriodsStatus[keyof typeof GlControllerGetFiscalPeriodsStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GlControllerGetFiscalPeriodsStatus = {
  open: 'open',
  soft_locked: 'soft_locked',
  hard_closed: 'hard_closed',
} as const;
