/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */

export type GlControllerGetCashFlowParams = {
startDate: string;
endDate: string;
periodName?: string;
fiscalYear?: number;
periodNumber?: number;
comparativeStartDate?: string;
comparativeEndDate?: string;
};
