/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.1
 */

export type GlControllerGetProfitAndLossParams = {
startDate: string;
endDate: string;
periodName?: string;
fiscalYear?: number;
periodNumber?: number;
};
