/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type { PurchaseReturnLineResponseDto } from './purchaseReturnLineResponseDto';
import type { GlobalPurchaseReturnDtoShipmentsItem } from './globalPurchaseReturnDtoShipmentsItem';
import type { GlobalPurchaseReturnDtoShipmentLinesItem } from './globalPurchaseReturnDtoShipmentLinesItem';

export interface GlobalPurchaseReturnDto {
  orderNumber?: string;
  vendorName?: string;
  vendorId?: string;
  vendorCode?: string;
  currencyCode?: string;
  debitNoteId?: string;
  debitNoteNumber?: string;
  debitNoteState?: string;
  debitNoteTotalAmount?: string;
  returnId: string;
  returnNumber: string;
  purchaseOrderId: string;
  stateCode: string;
  /** @nullable */
  notes?: string | null;
  /** @nullable */
  createdBy?: string | null;
  /** @nullable */
  createdOn?: string | null;
  /** @nullable */
  modifiedOn?: string | null;
  lines?: PurchaseReturnLineResponseDto[];
  shipments?: GlobalPurchaseReturnDtoShipmentsItem[];
  shipmentLines?: GlobalPurchaseReturnDtoShipmentLinesItem[];
}
