/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type { GlobalNoteDto } from './globalNoteDto';

export interface GlobalNotesListResponseDto {
  data: GlobalNoteDto[];
  total: number;
  page: number;
  limit: number;
}
