/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type { PaginatedResponse } from './paginatedResponse';
import type { GoodsReceivedControllerFindAllLines200AllOf } from './goodsReceivedControllerFindAllLines200AllOf';

export type GoodsReceivedControllerFindAllLines200 = PaginatedResponse & GoodsReceivedControllerFindAllLines200AllOf;
