/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */

export interface InventoryResponseDto {
  inventoryLevelId: string;
  productId: string;
  productNumber: string;
  productName: string;
  locationNo: string;
  locationName: string;
  quantityOnHand: string;
  quantityCommitted: string;
  quantityReserved: string;
  quantityOnOrder: string;
  quantityAvailable: string;
  /** @nullable */
  alternateProductNumber?: string | null;
  /** @nullable */
  defaultBinNumber?: string | null;
}
