/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type { PaginatedResponse } from './paginatedResponse';
import type { InventoryControllerFindBins200AllOf } from './inventoryControllerFindBins200AllOf';

export type InventoryControllerFindBins200 = PaginatedResponse & InventoryControllerFindBins200AllOf;
