/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type { PaginatedResponse } from './paginatedResponse';
import type { InvoiceDetailControllerGetPurchaseInvoicesGlobal200AllOf } from './invoiceDetailControllerGetPurchaseInvoicesGlobal200AllOf';

export type InvoiceDetailControllerGetPurchaseInvoicesGlobal200 = PaginatedResponse & InvoiceDetailControllerGetPurchaseInvoicesGlobal200AllOf;
