/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type { PaginatedResponse } from './paginatedResponse';
import type { InvoiceDetailControllerGetSalesInvoicesGlobal200AllOf } from './invoiceDetailControllerGetSalesInvoicesGlobal200AllOf';

export type InvoiceDetailControllerGetSalesInvoicesGlobal200 = PaginatedResponse & InvoiceDetailControllerGetSalesInvoicesGlobal200AllOf;
