/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type { JobProgressDtoProgressItem } from './jobProgressDtoProgressItem';

export interface JobProgressDto {
  status: string;
  progress: JobProgressDtoProgressItem[];
  logs: string[];
}
