/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type { JournalLineDtoPartyType } from './journalLineDtoPartyType';

export interface JournalLineDto {
  accountCode?: string;
  accountId?: string;
  costCenterId?: string;
  activityId?: string;
  partyType?: JournalLineDtoPartyType;
  /** @nullable */
  partyId?: string | null;
  /** @minimum 0 */
  debit: number;
  /** @minimum 0 */
  credit: number;
  /** @minimum 0 */
  foreignDebit?: number;
  /** @minimum 0 */
  foreignCredit?: number;
  foreignCurrencyCode?: string;
  exchangeRate?: number;
  memo?: string;
}
