/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */

export type LicenseStatusDtoType = typeof LicenseStatusDtoType[keyof typeof LicenseStatusDtoType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LicenseStatusDtoType = {
  trial: 'trial',
  perpetual: 'perpetual',
  none: 'none',
} as const;
