/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type { LicenseStatusDtoState } from './licenseStatusDtoState';
import type { LicenseStatusDtoType } from './licenseStatusDtoType';

export interface LicenseStatusDto {
  state: LicenseStatusDtoState;
  type: LicenseStatusDtoType;
  /** @nullable */
  expiresAt: string | null;
  /** @nullable */
  warningMessage: string | null;
  /** @nullable */
  systemId: string | null;
  /** @nullable */
  licenseHash: string | null;
}
