/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.1
 */

export interface LoginResponseDto {
  access_token?: string;
  username: string;
  /** @nullable */
  displayName?: string | null;
  role: string;
  twoFactorRequired?: boolean;
  tempToken?: string;
}
