/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.1
 */

export interface MarkStocktakeBinEmptyDto {
  /** Optional notes for marking bin empty */
  notes?: string;
}
