/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */

export interface MatchedJournalLineDto {
  debit: number;
  credit: number;
  /** @nullable */
  memo?: string | null;
  entryDate: string;
  isReconciled: boolean;
}
