/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type { OpenDemandLocationAvailabilityDto } from './openDemandLocationAvailabilityDto';

export interface OpenDemandDto {
  id: string;
  /** @nullable */
  salesOrderId?: string | null;
  /** @nullable */
  demandWorkOrderId?: string | null;
  /** @nullable */
  workOrderComponentId?: string | null;
  /** @nullable */
  demandType?: string | null;
  orderNumber: string;
  productId: string;
  productName: string;
  /** @nullable */
  productDescription?: string | null;
  quantity: number;
  createdOn: string;
  /** @nullable */
  vendorId?: string | null;
  /** @nullable */
  vendorName?: string | null;
  /** @nullable */
  costPrice?: number | null;
  /** @nullable */
  currencyCode?: string | null;
  /** @nullable */
  locationId?: string | null;
  /** @nullable */
  locationName?: string | null;
  /** @nullable */
  purchaseOrderId?: string | null;
  /** @nullable */
  purchaseOrderNumber?: string | null;
  /** @nullable */
  purchaseOrderState?: string | null;
  /** @nullable */
  transferOrderId?: string | null;
  /** @nullable */
  transferOrderNumber?: string | null;
  /** @nullable */
  transferOrderState?: string | null;
  availableElsewhere: OpenDemandLocationAvailabilityDto[];
}
