/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type { PaginatedResponse } from './paginatedResponse';
import type { OpportunitiesControllerFindAll200AllOf } from './opportunitiesControllerFindAll200AllOf';

export type OpportunitiesControllerFindAll200 = PaginatedResponse & OpportunitiesControllerFindAll200AllOf;
