/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type { OpportunityResponseDtoOwner } from './opportunityResponseDtoOwner';
import type { OpportunityNoteResponseDto } from './opportunityNoteResponseDto';
import type { OpportunityResponseDtoOpportunityActorsItem } from './opportunityResponseDtoOpportunityActorsItem';
import type { OpportunityResponseDtoOpportunityContactsItem } from './opportunityResponseDtoOpportunityContactsItem';
import type { OpportunityResponseDtoEventsItem } from './opportunityResponseDtoEventsItem';

export interface OpportunityResponseDto {
  opportunityId: string;
  stateCode: string;
  name: string;
  status: string;
  type: string;
  /** @nullable */
  estimatedValue?: string | null;
  /** @nullable */
  currencyCode?: string | null;
  /** @nullable */
  targetCloseDate?: string | null;
  /** @nullable */
  probability?: number | null;
  /** @nullable */
  actualValue?: string | null;
  /** @nullable */
  description?: string | null;
  createdOn: string;
  modifiedOn: string;
  /** @nullable */
  ownerId?: string | null;
  owner?: OpportunityResponseDtoOwner;
  notes?: OpportunityNoteResponseDto[];
  opportunityActors?: OpportunityResponseDtoOpportunityActorsItem[];
  opportunityContacts?: OpportunityResponseDtoOpportunityContactsItem[];
  /**
   * Total deal revenue calculated live from linked sales quote line items
   * @nullable
   */
  dealRevenue?: number | null;
  /**
   * Total number of linked sales quotes
   * @nullable
   */
  quoteCount?: number | null;
  events?: OpportunityResponseDtoEventsItem[];
}
