/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core Forgeron API System endpoints
 * OpenAPI spec version: 1.0
 */

export type OrderPickingControllerGetShippingQueue200Item = { [key: string]: unknown };
