/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */

export type OrderPickingControllerGetPickingQueueStatus = typeof OrderPickingControllerGetPickingQueueStatus[keyof typeof OrderPickingControllerGetPickingQueueStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OrderPickingControllerGetPickingQueueStatus = {
  ready: 'ready',
  partial: 'partial',
  blocked: 'blocked',
  all: 'all',
} as const;
