/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.1
 */
import type { OrganizationLinkResponseDtoLinkType } from './organizationLinkResponseDtoLinkType';
import type { OrganizationLinkPartnerDto } from './organizationLinkPartnerDto';

export interface OrganizationLinkResponseDto {
  linkId: string;
  sourceOrganizationId: string;
  targetOrganizationId: string;
  linkType: OrganizationLinkResponseDtoLinkType;
  createdOn: string;
  targetOrganization?: OrganizationLinkPartnerDto;
  sourceOrganization?: OrganizationLinkPartnerDto;
}
