/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type { GoodsReceivedResponseDto } from './goodsReceivedResponseDto';
import type { PaginatedGoodsReceivedDtoMeta } from './paginatedGoodsReceivedDtoMeta';

export interface PaginatedGoodsReceivedDto {
  data: GoodsReceivedResponseDto[];
  meta: PaginatedGoodsReceivedDtoMeta;
}
