/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type { PaymentRunCandidateResponseDtoDueDate } from './paymentRunCandidateResponseDtoDueDate';
import type { PaymentRunCandidateResponseDtoInvoiceDate } from './paymentRunCandidateResponseDtoInvoiceDate';
import type { PaymentRunCandidateResponseDtoTotalAmount } from './paymentRunCandidateResponseDtoTotalAmount';
import type { PaymentRunCandidateResponseDtoOutstandingAmount } from './paymentRunCandidateResponseDtoOutstandingAmount';

export interface PaymentRunCandidateResponseDto {
  invoiceId: string;
  invoiceNumber: string;
  supplierId: string;
  supplierName: string;
  dueDate: PaymentRunCandidateResponseDtoDueDate;
  invoiceDate: PaymentRunCandidateResponseDtoInvoiceDate;
  totalAmount: PaymentRunCandidateResponseDtoTotalAmount;
  outstandingAmount: PaymentRunCandidateResponseDtoOutstandingAmount;
  /** @nullable */
  earlyPaymentDiscount: string | null;
  /** @nullable */
  earlyPaymentDiscountDays: number | null;
  cashAmount: number;
  discountAmount: number;
  hasDiscountOpportunity: boolean;
  isDueSoon: boolean;
}
