/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type { PaymentRunCandidateDtoDueDate } from './paymentRunCandidateDtoDueDate';
import type { PaymentRunCandidateDtoInvoiceDate } from './paymentRunCandidateDtoInvoiceDate';
import type { PaymentRunCandidateDtoTotalAmount } from './paymentRunCandidateDtoTotalAmount';
import type { PaymentRunCandidateDtoOutstandingAmount } from './paymentRunCandidateDtoOutstandingAmount';

export interface PaymentRunCandidateDto {
  invoiceId: string;
  invoiceNumber: string;
  supplierId: string;
  supplierName: string;
  dueDate: PaymentRunCandidateDtoDueDate;
  invoiceDate: PaymentRunCandidateDtoInvoiceDate;
  totalAmount: PaymentRunCandidateDtoTotalAmount;
  outstandingAmount: PaymentRunCandidateDtoOutstandingAmount;
  /** @nullable */
  earlyPaymentDiscount: string | null;
  /** @nullable */
  earlyPaymentDiscountDays: number | null;
  cashAmount: number;
  discountAmount: number;
  hasDiscountOpportunity: boolean;
  isDueSoon: boolean;
}
