/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type { PaginatedResponse } from './paginatedResponse';
import type { PaymentsControllerFindAll200AllOf } from './paymentsControllerFindAll200AllOf';

export type PaymentsControllerFindAll200 = PaginatedResponse & PaymentsControllerFindAll200AllOf;
