/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */

export interface PickingBarcodeDto {
  salesOrderId: string;
  salesOrderLineId: string;
  lineNumber: number;
  productId: string;
  productNumber: string;
  productDescription: string;
  binId: string;
  binName: string;
  quantityToPick: string;
  barcodePayload: string;
}
