/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type { PickingSummaryLineDto } from './pickingSummaryLineDto';
import type { PickingSummaryPickDto } from './pickingSummaryPickDto';

export interface PickingSummaryDto {
  isCreditBlocked?: boolean;
  totalLines: number;
  fullyPickedLines: number;
  isFullyPicked: boolean;
  lines: PickingSummaryLineDto[];
  picks: PickingSummaryPickDto[];
}
