/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */

export interface PickingQueueOrderDto {
  id: string;
  orderNumber: string;
  /** @nullable */
  name?: string | null;
  customerName: string;
  /** @nullable */
  customerOrderNumber?: string | null;
  stateCode: string;
  createdOn: string;
  createdBy: string;
  /** @nullable */
  currencyCode?: string | null;
  type?: string;
  pickabilityStatus: string;
  hasAllocation: boolean;
}
