/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */

export interface PoAllocationDto {
  id: string;
  /** @nullable */
  salesOrderId?: string | null;
  /** @nullable */
  demandWorkOrderId?: string | null;
  /** @nullable */
  workOrderComponentId?: string | null;
  /** @nullable */
  demandType?: string | null;
  orderNumber: string;
  productId: string;
  productName: string;
  quantity: number;
  createdOn: string;
  /** @nullable */
  purchaseOrderLineId?: string | null;
  stateCode: string;
}
