/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */

export interface ProductGroupResponseDto {
  id: string;
  groupCode: string;
  name: string;
  /** @nullable */
  defaultRevenueAccountId: string | null;
  /** @nullable */
  defaultExpenseAccountId: string | null;
  /** @nullable */
  defaultCostCenterId: string | null;
  /** @nullable */
  defaultActivityId: string | null;
  tenantId: string;
  createdAt: string;
  updatedAt: string;
}
