/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.1
 */

export type ProductsControllerUploadImageBody = {
  /** Image file (JPG, PNG, WebP, GIF, SVG up to 5MB) */
  file: Blob;
};
