/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type { PaginatedResponse } from './paginatedResponse';
import type { ProductsControllerFindAll200AllOf } from './productsControllerFindAll200AllOf';

export type ProductsControllerFindAll200 = PaginatedResponse & ProductsControllerFindAll200AllOf;
