/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.1
 */

export interface ProfitAndLossSummaryDto {
  totalRevenue: number;
  totalCogs: number;
  grossProfit: number;
  grossMarginPercentage: number;
  totalOperatingExpenses: number;
  operatingIncome: number;
  totalOtherIncomeExpense: number;
  netIncome: number;
  netMarginPercentage: number;
}
