/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.1
 */
import type { ProfitAndLossPeriodDto } from './profitAndLossPeriodDto';
import type { ProfitAndLossSectionDto } from './profitAndLossSectionDto';
import type { ProfitAndLossSummaryDto } from './profitAndLossSummaryDto';

export interface ProfitAndLossResponseDto {
  period: ProfitAndLossPeriodDto;
  revenue: ProfitAndLossSectionDto;
  costOfGoodsSold: ProfitAndLossSectionDto;
  operatingExpenses: ProfitAndLossSectionDto;
  otherIncomeExpense: ProfitAndLossSectionDto;
  summary: ProfitAndLossSummaryDto;
}
