/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.1
 */
import type { ProjectResourceResponseDtoUser } from './projectResourceResponseDtoUser';
import type { ProjectResourceResponseDtoVendor } from './projectResourceResponseDtoVendor';
import type { ProjectResourceResponseDtoServiceProduct } from './projectResourceResponseDtoServiceProduct';

export interface ProjectResourceResponseDto {
  resourceId: string;
  resourceNumber: string;
  name: string;
  resourceType: string;
  /** @nullable */
  userId?: string | null;
  /** @nullable */
  vendorId?: string | null;
  /** @nullable */
  serviceProductId?: string | null;
  baseUom: string;
  directUnitCost: string;
  unitPrice: string;
  isActive: boolean;
  /** @nullable */
  createdOn?: string | null;
  /** @nullable */
  modifiedOn?: string | null;
  /** @nullable */
  user?: ProjectResourceResponseDtoUser;
  /** @nullable */
  vendor?: ProjectResourceResponseDtoVendor;
  /** @nullable */
  serviceProduct?: ProjectResourceResponseDtoServiceProduct;
}
