/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.1
 */

export type ProjectsControllerGetLedgerEntriesLineType = typeof ProjectsControllerGetLedgerEntriesLineType[keyof typeof ProjectsControllerGetLedgerEntriesLineType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProjectsControllerGetLedgerEntriesLineType = {
  resource: 'resource',
  item: 'item',
  expense: 'expense',
} as const;
