/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type { ProjectNoteResponseDtoCreatedBy } from './projectNoteResponseDtoCreatedBy';

export interface ProjectNoteResponseDto {
  noteId: string;
  content: string;
  createdOn: string;
  createdById?: string;
  createdBy?: ProjectNoteResponseDtoCreatedBy;
}
