/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.1
 */
import type { ProjectResponseProjectManagerDto } from './projectResponseProjectManagerDto';

/**
 * Creator user details
 * @nullable
 */
export type ProjectNoteResponseDtoCreatedBy = ProjectResponseProjectManagerDto | null;
