/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.1
 */

export interface ProjectResponseCustomerDto {
  customerId: string;
  customerNumber: string;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  customerName?: string | null;
  /** @nullable */
  currencyCode?: string | null;
  /** @nullable */
  tradingTermsId?: string | null;
  /** @nullable */
  paymentTerms?: string | null;
}
