/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.1
 */
import type { ProjectNoteResponseDtoCreatedBy } from './projectNoteResponseDtoCreatedBy';

export interface ProjectNoteResponseDto {
  /** Unique note ID */
  noteId: string;
  /** Parent project ID */
  projectId: string;
  /** Content of the note */
  content: string;
  /**
   * User ID of the note creator
   * @nullable
   */
  createdById?: string | null;
  /**
   * Creator user details
   * @nullable
   */
  createdBy?: ProjectNoteResponseDtoCreatedBy;
  /** Timestamp when note was created */
  createdOn: string;
}
