/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.1
 */
import type { PaginatedResponse } from './paginatedResponse';
import type { ProjectsControllerGetLedgerEntries200AllOf } from './projectsControllerGetLedgerEntries200AllOf';

export type ProjectsControllerGetLedgerEntries200 = PaginatedResponse & ProjectsControllerGetLedgerEntries200AllOf;
