/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.1
 */

export interface ProjectProfitabilityResponseDto {
  projectId: string;
  totalBudgetCost: number;
  totalBudgetPrice: number;
  totalActualCost: number;
  totalBillablePrice: number;
  totalBilledPrice: number;
  costVariance: number;
  estimatedMarginPercent: number;
  actualMarginPercent: number;
  laborActualCost: number;
  materialActualCost: number;
  expenseActualCost: number;
}
