/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type { ProjectFeedbackResponseDtoActor } from './projectFeedbackResponseDtoActor';

export interface ProjectFeedbackResponseDto {
  feedbackId: string;
  projectId: string;
  actorId: string;
  dealProposalReason?: string;
  dealRefusalReason?: string;
  snapshotName?: string;
  asOfDate?: string;
  actor?: ProjectFeedbackResponseDtoActor;
}
