/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type { ProjectResponseDtoOwner } from './projectResponseDtoOwner';
import type { ProjectNoteResponseDto } from './projectNoteResponseDto';
import type { ProjectResponseDtoProjectActorsItem } from './projectResponseDtoProjectActorsItem';
import type { ProjectResponseDtoProjectContactsItem } from './projectResponseDtoProjectContactsItem';

export interface ProjectResponseDto {
  projectId: string;
  name: string;
  status: string;
  type: string;
  createdOn: string;
  modifiedOn: string;
  ownerId?: string;
  owner?: ProjectResponseDtoOwner;
  notes?: ProjectNoteResponseDto[];
  projectActors?: ProjectResponseDtoProjectActorsItem[];
  projectContacts?: ProjectResponseDtoProjectContactsItem[];
}
