/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.1
 */

export interface ProjectLedgerEntryResponseDto {
  ledgerId: string;
  projectId: string;
  projectTaskId: string;
  entryType: string;
  lineType: string;
  sourceType: string;
  /** @nullable */
  sourceId?: string | null;
  /** @nullable */
  inventoryEntryId?: string | null;
  /** @nullable */
  resourceId?: string | null;
  /** @nullable */
  productId?: string | null;
  /** @nullable */
  description?: string | null;
  quantity: string;
  unitCostBase: string;
  totalCostBase: string;
  unitPriceBase: string;
  /** @nullable */
  discountPercentage?: string | null;
  totalPriceBase: string;
  isBillable?: boolean;
  isBilled: boolean;
  /** @nullable */
  salesInvoiceLineId?: string | null;
  /** @nullable */
  salesInvoiceNumber?: string | null;
  /** @nullable */
  salesInvoiceId?: string | null;
  /** @nullable */
  budgetLineId?: string | null;
  postingDate: string;
  createdBy: string;
  /** @nullable */
  createdOn?: string | null;
}
