/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.1
 */

export interface ProjectStagingInventoryItemDto {
  productId: string;
  productNumber: string;
  productName: string;
  actualQuantity: number;
  baseUom?: string;
}
