/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.1
 */
import type { ProjectResponseDtoMetadata } from './projectResponseDtoMetadata';
import type { ProjectResponseDtoCustomer } from './projectResponseDtoCustomer';
import type { ProjectResponseDtoOpportunity } from './projectResponseDtoOpportunity';
import type { ProjectResponseDtoProjectManager } from './projectResponseDtoProjectManager';
import type { ProjectResponseDtoStagingLocation } from './projectResponseDtoStagingLocation';
import type { ProjectResponseDtoStagingBin } from './projectResponseDtoStagingBin';
import type { ProjectTaskResponseDto } from './projectTaskResponseDto';
import type { ProjectBudgetLineResponseDto } from './projectBudgetLineResponseDto';
import type { ProjectLedgerEntryResponseDto } from './projectLedgerEntryResponseDto';
import type { ProjectNoteResponseDto } from './projectNoteResponseDto';
import type { ProjectStagingInventoryItemDto } from './projectStagingInventoryItemDto';

export interface ProjectResponseDto {
  projectId: string;
  projectNumber: string;
  name: string;
  /** @nullable */
  description?: string | null;
  customerId: string;
  /** @nullable */
  opportunityId?: string | null;
  stateCode: string;
  /** @nullable */
  stage?: string | null;
  billingType: string;
  /** @nullable */
  projectManagerId?: string | null;
  currencyCode: string;
  /** @nullable */
  stagingLocationId?: string | null;
  /** @nullable */
  stagingBinId?: string | null;
  /** @nullable */
  startDate?: string | null;
  /** @nullable */
  targetEndDate?: string | null;
  /** @nullable */
  actualEndDate?: string | null;
  /** @nullable */
  notes?: string | null;
  /** @nullable */
  metadata?: ProjectResponseDtoMetadata;
  /** @nullable */
  discountPercentage?: string | null;
  /** @nullable */
  tradingTermsId?: string | null;
  /** @nullable */
  paymentTerms?: string | null;
  /** @nullable */
  createdBy?: string | null;
  createdOn: string;
  modifiedOn: string;
  /** @nullable */
  customer?: ProjectResponseDtoCustomer;
  /** @nullable */
  opportunity?: ProjectResponseDtoOpportunity;
  /** @nullable */
  projectManager?: ProjectResponseDtoProjectManager;
  /** @nullable */
  stagingLocation?: ProjectResponseDtoStagingLocation;
  /** @nullable */
  stagingBin?: ProjectResponseDtoStagingBin;
  tasks?: ProjectTaskResponseDto[];
  budgetLines?: ProjectBudgetLineResponseDto[];
  ledgerEntries?: ProjectLedgerEntryResponseDto[];
  projectNotes?: ProjectNoteResponseDto[];
  stagingInventory?: ProjectStagingInventoryItemDto[];
}
