/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.1
 */

/**
 * The payload of the event
 */
export type PublishEventDtoPayload = { [key: string]: unknown };
