/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type { PublishEventDtoPayload } from './publishEventDtoPayload';

export interface PublishEventDto {
  /** The type of event to publish (e.g. order.created) */
  type: string;
  /** The payload of the event */
  payload: PublishEventDtoPayload;
}
