/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */

export interface PurchaseInvoiceResponseDto {
  invoiceId: string;
  invoiceNumber: string;
  vendorId: string;
  /** @nullable */
  purchaseOrderId?: string | null;
  /** @nullable */
  supplierInvoiceNumber?: string | null;
  /** @nullable */
  receiptFilename?: string | null;
  totalAmount: string;
  outstandingAmount: string;
  /** @nullable */
  taxAmount?: string | null;
  currencyCode: string;
  stateCode: string;
  /** @nullable */
  notes?: string | null;
  /** @nullable */
  createdBy?: string | null;
  /** @nullable */
  createdOn?: string | null;
  /** @nullable */
  modifiedOn?: string | null;
}
