/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type { PurchaseOrderLineResponseDto } from './purchaseOrderLineResponseDto';
import type { PurchaseOrderResponseDtoCustomFields } from './purchaseOrderResponseDtoCustomFields';

export interface PurchaseOrderResponseDto {
  lines?: PurchaseOrderLineResponseDto[];
  purchaseOrderId: string;
  orderNumber: string;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  vendorId?: string | null;
  deliveryLocationId: string;
  /** @nullable */
  referenceNumber?: string | null;
  stateCode: string;
  currencyCode: string;
  /** @nullable */
  notes?: string | null;
  /** @nullable */
  customFields?: PurchaseOrderResponseDtoCustomFields;
  /** @nullable */
  createdBy?: string | null;
  /** @nullable */
  createdOn?: string | null;
  /** @nullable */
  modifiedOn?: string | null;
  /** @nullable */
  expectedDate?: string | null;
  vendorName?: string;
}
