/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type { PurchaseReturnLineResponseDto } from './purchaseReturnLineResponseDto';
import type { PurchaseReturnResponseDtoShipmentsItem } from './purchaseReturnResponseDtoShipmentsItem';
import type { PurchaseReturnResponseDtoShipmentLinesItem } from './purchaseReturnResponseDtoShipmentLinesItem';

export interface PurchaseReturnResponseDto {
  returnId: string;
  returnNumber: string;
  purchaseOrderId: string;
  stateCode: string;
  /** @nullable */
  notes?: string | null;
  /** @nullable */
  createdBy?: string | null;
  /** @nullable */
  createdOn?: string | null;
  /** @nullable */
  modifiedOn?: string | null;
  lines?: PurchaseReturnLineResponseDto[];
  shipments?: PurchaseReturnResponseDtoShipmentsItem[];
  shipmentLines?: PurchaseReturnResponseDtoShipmentLinesItem[];
}
