/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type { PaginatedResponse } from './paginatedResponse';
import type { PurchaseOrdersControllerFindAll200AllOf } from './purchaseOrdersControllerFindAll200AllOf';

export type PurchaseOrdersControllerFindAll200 = PaginatedResponse & PurchaseOrdersControllerFindAll200AllOf;
