/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */

export type PutawayLineDtoSourceType = typeof PutawayLineDtoSourceType[keyof typeof PutawayLineDtoSourceType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PutawayLineDtoSourceType = {
  goods_receipt: 'goods_receipt',
  sales_return: 'sales_return',
  transfer_receipt: 'transfer_receipt',
  work_order: 'work_order',
} as const;
