/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type { PutawayLineDtoSourceType } from './putawayLineDtoSourceType';

export interface PutawayLineDto {
  reason?: string;
  lineId: string;
  sourceType: PutawayLineDtoSourceType;
  destinationBinId: string;
  quantity: string;
  newTotalQuantity?: string;
}
