/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */

export type QuarantineMoveDtoSourceType = typeof QuarantineMoveDtoSourceType[keyof typeof QuarantineMoveDtoSourceType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const QuarantineMoveDtoSourceType = {
  goods_receipt: 'goods_receipt',
  sales_return: 'sales_return',
  manual: 'manual',
} as const;
