/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type { QuarantineMoveDtoSourceType } from './quarantineMoveDtoSourceType';

export interface QuarantineMoveDto {
  productId?: string;
  sourceBinId?: string;
  targetBinId?: string;
  quantity?: string;
  sourceType?: QuarantineMoveDtoSourceType;
  lineId?: string;
  reason?: string;
}
