/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */

export interface ReconciliationRuleResponseDto {
  typeCondition?: string;
  payeeConditionType?: string;
  payeeConditionValue?: string;
  ruleId: string;
  glAccountId?: string;
  conditionType: string;
  conditionValue: string;
  amountMin?: number;
  amountMax?: number;
  targetGlAccountId: string;
  costCenterId?: string;
  activityId?: string;
  partyType?: string;
  partyId?: string;
  memo?: string;
  priority?: number;
}
