/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.1
 */
import type { RecordStocktakeCountDtoCountMode } from './recordStocktakeCountDtoCountMode';

export interface RecordStocktakeCountDto {
  productId: string;
  binId: string;
  quantity: string;
  countMode?: RecordStocktakeCountDtoCountMode;
  notes?: string;
}
