/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type { ResolveDiscountRuleDtoOwnerType } from './resolveDiscountRuleDtoOwnerType';

export interface ResolveDiscountRuleDto {
  ownerType: ResolveDiscountRuleDtoOwnerType;
  /** @nullable */
  productGroupId: string | null;
  discountPercentage: string;
}
