/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type { ReturnLineResponseDto } from './returnLineResponseDto';

export interface ReturnResponseDto {
  returnId: string;
  returnNumber: string;
  stateCode: string;
  orderNumber?: string;
  customerId?: string;
  customerNumber?: string;
  customerName?: string;
  locationId?: string;
  locationName?: string;
  notes?: string;
  lines: ReturnLineResponseDto[];
}
