/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.1
 */

export interface ReturnInventoryDto {
  /** Project Task ID materials are returning from */
  projectTaskId: string;
  /** Product ID being returned */
  productId: string;
  /** Destination warehouse location ID */
  locationId: string;
  /** Destination warehouse bin ID */
  binId: string;
  /**
   * Quantity to return
   * @minimum 0.0001
   */
  quantity: number;
  /**
   * Override unit cost
   * @minimum 0
   */
  unitCost?: number;
  /**
   * Override unit price
   * @minimum 0
   */
  unitPrice?: number;
  /** Transaction memo / notes */
  memo?: string;
}
