/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */

export interface RunHookBodyDto {
  /** Optional shipment ID for shipment/picking hooks */
  shipmentId?: string;
  customPdfText?: string;
  /** Deprecated legacy alias for customPdfText */
  quoteIntroText?: string;
}
