/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.1
 */
import type { SalesSettingsResponseDtoSalesOrderMetadataSchema } from './salesSettingsResponseDtoSalesOrderMetadataSchema';
import type { SalesSettingsResponseDtoSalesInvoiceMetadataSchema } from './salesSettingsResponseDtoSalesInvoiceMetadataSchema';
import type { SalesSettingsResponseDtoCreditNoteMetadataSchema } from './salesSettingsResponseDtoCreditNoteMetadataSchema';

export interface SalesSettingsResponseDto {
  salesSettingsId: string;
  /** @nullable */
  salesOrderMetadataSchema?: SalesSettingsResponseDtoSalesOrderMetadataSchema;
  /** @nullable */
  salesInvoiceMetadataSchema?: SalesSettingsResponseDtoSalesInvoiceMetadataSchema;
  /** @nullable */
  creditNoteMetadataSchema?: SalesSettingsResponseDtoCreditNoteMetadataSchema;
  modifiedOn: string;
}
