/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type { InvoiceLineResponseDto } from './invoiceLineResponseDto';
import type { SalesInvoiceResponseDtoAllocationsItem } from './salesInvoiceResponseDtoAllocationsItem';

export interface SalesInvoiceResponseDto {
  invoiceId: string;
  invoiceNumber: string;
  customerId: string;
  customerName: string;
  totalAmount: string;
  outstandingAmount: string;
  taxAmount: string;
  currencyCode: string;
  stateCode: string;
  notes?: string;
  salesOrderId?: string;
  createdBy: string;
  createdOn: string;
  lines: InvoiceLineResponseDto[];
  allocations?: SalesInvoiceResponseDtoAllocationsItem[];
}
