/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.1
 */
import type { InvoiceLineResponseDto } from './invoiceLineResponseDto';
import type { SalesInvoiceResponseDtoAllocationsItem } from './salesInvoiceResponseDtoAllocationsItem';
import type { SalesInvoiceResponseDtoEventsItem } from './salesInvoiceResponseDtoEventsItem';
import type { SalesInvoiceResponseDtoMetadata } from './salesInvoiceResponseDtoMetadata';

export interface SalesInvoiceResponseDto {
  invoiceId: string;
  invoiceNumber: string;
  customerId: string;
  customerName: string;
  customerOrderNumber?: string;
  totalAmount: string;
  outstandingAmount: string;
  taxAmount: string;
  currencyCode: string;
  stateCode: string;
  notes?: string;
  salesOrderId?: string;
  orderNumber?: string;
  projectId?: string;
  projectNumber?: string;
  earlyPaymentDiscount?: string;
  earlyPaymentDiscountDays?: number;
  createdBy: string;
  createdOn: string;
  invoiceDate?: string;
  dueDate?: string;
  lines: InvoiceLineResponseDto[];
  allocations?: SalesInvoiceResponseDtoAllocationsItem[];
  events?: SalesInvoiceResponseDtoEventsItem[];
  metadata?: SalesInvoiceResponseDtoMetadata;
  termsDescription?: string;
}
