/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.1
 */
import type { SampleReportDtoDataItem } from './sampleReportDtoDataItem';

export interface SampleReportDto {
  isMockData: boolean;
  data: SampleReportDtoDataItem[];
}
