/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.1
 */
import type { SampleRecordDtoData } from './sampleRecordDtoData';

export interface SampleRecordDto {
  isMockData: boolean;
  data: SampleRecordDtoData;
}
