/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */

export type SearchResultDtoType = typeof SearchResultDtoType[keyof typeof SearchResultDtoType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SearchResultDtoType = {
  product: 'product',
  customer: 'customer',
  sales_order: 'sales_order',
  supplier: 'supplier',
  purchase_order: 'purchase_order',
  shipment: 'shipment',
  goods_receipt: 'goods_receipt',
  sales_invoice: 'sales_invoice',
  purchase_invoice: 'purchase_invoice',
  sales_return: 'sales_return',
  purchase_return: 'purchase_return',
  sales_credit_note: 'sales_credit_note',
  purchase_debit_note: 'purchase_debit_note',
  transfer_order: 'transfer_order',
  work_order: 'work_order',
  contact: 'contact',
  project: 'project',
  payment: 'payment',
} as const;
