/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.1
 */

export interface ServiceMemberResponseDto {
  memberId: string;
  productId: string;
  resourceId: string;
  resourceNumber?: string;
  name?: string;
  resourceType?: string;
  directUnitCost?: string;
  unitPrice?: string;
  baseUom?: string;
  /** @nullable */
  userId?: string | null;
  /** @nullable */
  username?: string | null;
  /** @nullable */
  displayName?: string | null;
  /** @nullable */
  email?: string | null;
  createdOn?: string;
}
