/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type { SetupValidationDtoMetrics } from './setupValidationDtoMetrics';
import type { SetupValidationDtoDataCounts } from './setupValidationDtoDataCounts';

export interface SetupValidationDto {
  status: string;
  metrics?: SetupValidationDtoMetrics;
  dataCounts?: SetupValidationDtoDataCounts;
}
