/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type { ShipmentLineResponseDto } from './shipmentLineResponseDto';

export interface ShipmentResponseDto {
  lines?: ShipmentLineResponseDto[];
  shipmentId: string;
  shipmentNumber: string;
  orderId: string;
  stateCode: string;
  trackingNumber?: string;
  carrierId?: string;
  notes?: string;
  createdOn?: string;
  deliveryName?: string;
  deliveryPhone?: string;
  deliveryAddressLine1?: string;
  deliveryAddressLine2?: string;
  deliveryCity?: string;
  deliveryState?: string;
  deliveryPostalCode?: string;
  deliveryCountry?: string;
  shippingNotes?: string;
}
