/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */

export interface ShippingContextLineDto {
  salesOrderLineId: string;
  lineNumber: number;
  productId: string;
  productNumber: string;
  productDescription: string;
  quantity: string;
  quantityPicked: string;
  quantityShipped: string;
  isPhysical: boolean;
  availableToShip: string;
}
