/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.1
 */
import type { ShippingContextDtoOrder } from './shippingContextDtoOrder';
import type { ShippingContextLineDto } from './shippingContextLineDto';
import type { ShipmentResponseDto } from './shipmentResponseDto';

export interface ShippingContextDto {
  isCreditBlocked?: boolean;
  order?: ShippingContextDtoOrder;
  lines: ShippingContextLineDto[];
  shipments: ShipmentResponseDto[];
}
