/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.1
 */

/**
 * Target lifecycle state
 */
export type StocktakeStateTransitionDtoStateCode = typeof StocktakeStateTransitionDtoStateCode[keyof typeof StocktakeStateTransitionDtoStateCode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StocktakeStateTransitionDtoStateCode = {
  cancelled: 'cancelled',
  draft: 'draft',
  open: 'open',
  review: 'review',
  submitted: 'submitted',
} as const;
