/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.1
 */
import type { PaginatedResponse } from './paginatedResponse';
import type { StocktakesControllerFindAll200AllOf } from './stocktakesControllerFindAll200AllOf';

export type StocktakesControllerFindAll200 = PaginatedResponse & StocktakesControllerFindAll200AllOf;
