/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.1
 */

export interface StocktakeSuccessResponseDto {
  success: boolean;
  stocktakeId?: string;
  stocktakeNumber?: string;
  stateCode?: string;
  reconciledCount?: number;
  inventoryEntryId?: string;
}
