/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.1
 */

export type StocktakesControllerFindLinesStatus = typeof StocktakesControllerFindLinesStatus[keyof typeof StocktakesControllerFindLinesStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StocktakesControllerFindLinesStatus = {
  uncounted: 'uncounted',
  counted: 'counted',
  discrepancies: 'discrepancies',
  match: 'match',
  surplus: 'surplus',
  shortage: 'shortage',
} as const;
