/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.1
 */
import type { StocktakeLineResponseDtoStatus } from './stocktakeLineResponseDtoStatus';

export interface StocktakeLineResponseDto {
  stocktakeLineId: string;
  stocktakeId: string;
  productId: string;
  productNumber: string;
  productName: string;
  /** @nullable */
  barcode?: string | null;
  /** @nullable */
  alternateProductNumber?: string | null;
  baseUom: string;
  binId: string;
  binNumber: string;
  /** @nullable */
  zoneCode?: string | null;
  /** @nullable */
  expectedQuantity?: string | null;
  /** @nullable */
  countedQuantity?: string | null;
  /** @nullable */
  varianceQuantity?: string | null;
  status: StocktakeLineResponseDtoStatus;
  isUnlisted: boolean;
  /** @nullable */
  notes?: string | null;
  /** @nullable */
  lastCountedBy?: string | null;
  /** @nullable */
  lastCountedAt?: string | null;
}
