/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */

export interface StrategicIntelligenceResponseDto {
  intelligenceId: string;
  actorId: string;
  managerIntent?: string;
  sectorInterests?: string;
  externalGrowthProjects?: string;
  futureSaleIntent?: string;
  timeline?: string;
  strategicRationale?: string;
  snapshotName?: string;
  asOfDate?: string;
}
