/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type { TrialBalanceZeroSumDto } from './trialBalanceZeroSumDto';
import type { SubledgerParityItemDto } from './subledgerParityItemDto';

export interface SubledgerReconciliationResponseDto {
  timestamp: string;
  isOverallBalanced: boolean;
  trialBalanceZeroSum: TrialBalanceZeroSumDto;
  accountsReceivable: SubledgerParityItemDto;
  accountsPayable: SubledgerParityItemDto;
  goodsReceivedNotInvoiced: SubledgerParityItemDto;
  perpetualInventory: SubledgerParityItemDto;
}
