/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */

export interface SubledgerParityItemDto {
  controlAccountCode: string;
  controlAccountName: string;
  subledgerBalance: number;
  glBalance: number;
  drift: number;
  isMatched: boolean;
}
