/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type { PaginatedResponse } from './paginatedResponse';
import type { SuppliersControllerFindAll200AllOf } from './suppliersControllerFindAll200AllOf';

export type SuppliersControllerFindAll200 = PaginatedResponse & SuppliersControllerFindAll200AllOf;
