/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type { PaginatedResponse } from './paginatedResponse';
import type { SuppliersControllerFindSupplierExpiries200AllOf } from './suppliersControllerFindSupplierExpiries200AllOf';

export type SuppliersControllerFindSupplierExpiries200 = PaginatedResponse & SuppliersControllerFindSupplierExpiries200AllOf;
