/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */

export interface SupplierGroupResponseDto {
  /** @nullable */
  earlyPaymentDiscount?: string | null;
  /** @nullable */
  earlyPaymentDiscountDays?: number | null;
  supplierGroupId: string;
  groupCode: string;
  name: string;
  /** @nullable */
  defaultApAccountId: string | null;
  /** @nullable */
  defaultExpenseAccountId: string | null;
  /** @nullable */
  tradingTermsId: string | null;
  /** @nullable */
  creditLimit: string | null;
  isPurchasingBlocked: boolean;
  /** @nullable */
  purchasingBlockReason: string | null;
  isPaymentBlocked: boolean;
  /** @nullable */
  paymentBlockReason: string | null;
  /** @nullable */
  blockNotes: string | null;
  /** @nullable */
  defaultCostCenterId: string | null;
  /** @nullable */
  defaultActivityId: string | null;
  /** @nullable */
  taxPositionId: string | null;
  tenantId: string;
  createdAt: string;
  updatedAt: string;
}
