/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type { SyncSummaryDto } from './syncSummaryDto';
import type { TypeBreakdownDto } from './typeBreakdownDto';
import type { OutboxEventDto } from './outboxEventDto';

export interface SyncStatusResponseDto {
  summary: SyncSummaryDto;
  byType: TypeBreakdownDto[];
  recentEvents: OutboxEventDto[];
}
