/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */

export interface SystemVersionResponseDto {
  /** API version number */
  apiVersion: string;
  /** API build timestamp */
  apiBuildTime: string;
  /** Node.js version */
  nodeVersion: string;
  /** OS platform */
  osPlatform: string;
  /** OS release */
  osRelease: string;
}
