/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */

export interface TaxPositionResponseDto {
  taxPositionId: string;
  code: string;
  title: string;
  isDefault: boolean;
}
