/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */

export type TaxReportsControllerGetTaxReportReportType = typeof TaxReportsControllerGetTaxReportReportType[keyof typeof TaxReportsControllerGetTaxReportReportType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TaxReportsControllerGetTaxReportReportType = {
  generic: 'generic',
  au_bas: 'au_bas',
  uk_vat: 'uk_vat',
  sg_gst: 'sg_gst',
  nz_gst: 'nz_gst',
  de_ustva: 'de_ustva',
  us_sales_tax: 'us_sales_tax',
} as const;
