/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */

export interface TestOdooConnectionDto {
  host: string;
  database: string;
  username: string;
  password: string;
  /**
   * @minimum 1
   * @maximum 65535
   */
  port?: number;
}
