/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */

export type ToggleQuarantineDtoSourceType = typeof ToggleQuarantineDtoSourceType[keyof typeof ToggleQuarantineDtoSourceType];


// eslint-disable-next-line @typescript-eslint/no-redeclare -- External API integration boundaries where exact types are unknown.
export const ToggleQuarantineDtoSourceType = {
  goods_receipt: 'goods_receipt',
  sales_return: 'sales_return',
} as const;
