/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type { TransferLineResponseDto } from './transferLineResponseDto';
import type { TransferEventResponseDto } from './transferEventResponseDto';

export interface TransferResponseDto {
  transferOrderId: string;
  orderNumber: string;
  stateCode: string;
  sourceLocationId: string;
  sourceLocationName?: string;
  destinationLocationId: string;
  destinationLocationName?: string;
  notes?: string;
  shippingNotes?: string;
  createdBy?: string;
  createdOn: string;
  lines?: TransferLineResponseDto[];
  events?: TransferEventResponseDto[];
}
