/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */

export interface TransferLineResponseDto {
  id: string;
  transferOrderLineId: string;
  productId: string;
  productNumber?: string;
  productDescription?: string;
  quantity: string;
  quantityShipped?: string;
  quantityReceived?: string;
}
