/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type { TransferEventResponseDtoPayload } from './transferEventResponseDtoPayload';

export interface TransferEventResponseDto {
  eventId: string;
  eventType: string;
  payload?: TransferEventResponseDtoPayload;
  actor?: string;
  createdOn: string;
}
