/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type { SearchResultDto } from './searchResultDto';

export interface UniversalSearchResponseDto {
  results: SearchResultDto[];
}
