/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.1
 */

export type UomResponseDtoCategory = typeof UomResponseDtoCategory[keyof typeof UomResponseDtoCategory];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UomResponseDtoCategory = {
  goods: 'goods',
  service: 'service',
} as const;
