/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.1
 */

export interface UpdateInvoiceLineDto {
  description?: string;
  productId?: string;
  glAccountId?: string;
  quantityInvoiced?: number;
  pricePerUnit?: number;
}
