/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */

export interface UpdateWorkOrderDto {
  /** Target quantity to produce */
  targetQuantity?: string;
  /** Fulfillment location ID */
  locationId?: string;
  /**
   * WIP Bin ID (optional)
   * @nullable
   */
  wipBinId?: string | null;
}
