/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type { UpdateProductDtoProductType } from './updateProductDtoProductType';
import type { UpdateProductDtoStructureType } from './updateProductDtoStructureType';

export interface UpdateProductDto {
  productNumber?: string;
  name?: string;
  productType?: UpdateProductDtoProductType;
  structureType?: UpdateProductDtoStructureType;
  barcode?: string;
  listPrice?: string;
  standardCost?: string;
  tradePrice?: string;
  priceLevel3?: string;
  priceLevel4?: string;
  purchaseTaxCategoryId?: string;
  salesTaxCategoryId?: string;
  alternateProductNumber?: string;
  productGroupId?: string;
  notes?: string;
  stateCode?: string;
  baseUom?: string;
  /** @nullable */
  defaultSalesUomId?: string | null;
  /** @nullable */
  defaultPurchaseUomId?: string | null;
}
