/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.1
 */
import type { UpdateProjectDtoBillingType } from './updateProjectDtoBillingType';
import type { UpdateProjectDtoMetadata } from './updateProjectDtoMetadata';

export interface UpdateProjectDto {
  /** Custom project code / number */
  projectNumber?: string;
  name?: string;
  description?: string;
  customerId?: string;
  opportunityId?: string;
  /** Delivery stage */
  stage?: string;
  billingType?: UpdateProjectDtoBillingType;
  projectManagerId?: string;
  currencyCode?: string;
  /** Staging warehouse location ID */
  stagingLocationId?: string;
  /** Staging warehouse bin ID */
  stagingBinId?: string;
  startDate?: string;
  targetEndDate?: string;
  notes?: string;
  /** Custom metadata object */
  metadata?: UpdateProjectDtoMetadata;
  /** Default project discount percentage */
  discountPercentage?: number;
  /**
   * Trading / Payment terms ID override for the project
   * @nullable
   */
  tradingTermsId?: string | null;
}
