/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * ModBM API
 * Core Forgeron API System endpoints
 * OpenAPI spec version: 1.0
 */

export interface UpdatePurchaseOrderLineDto {
  quantity?: string;
  pricePerUnit?: string;
  discountPercentage?: string;
  productDescription?: string;
  unitOfMeasure?: string;
  taxCategoryId?: string;
}
