/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type { UpdateOrderLineDtoLineType } from './updateOrderLineDtoLineType';

export interface UpdateOrderLineDto {
  lineType?: UpdateOrderLineDtoLineType;
  quantity?: string;
  pricePerUnit?: string;
  unitCost?: string;
  discountPercentage?: string;
  taxCategoryId?: string;
  tax?: string;
  productDescription?: string;
  unitOfMeasure?: string;
  fulfillmentLocationId?: string;
}
