/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */

export interface UpdateMappingProfileDto {
  name?: string;
  dateColumn?: string;
  amountColumn?: string;
  debitColumn?: string;
  creditColumn?: string;
  descriptionColumn?: string;
  typeColumn?: string;
  payeeColumn?: string;
  referenceColumn?: string;
  headerRows?: number;
}
