/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.1
 */

export type UpdateProjectResourceDtoResourceType = typeof UpdateProjectResourceDtoResourceType[keyof typeof UpdateProjectResourceDtoResourceType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateProjectResourceDtoResourceType = {
  person: 'person',
  contractor: 'contractor',
  equipment: 'equipment',
} as const;
