/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * ModBM API
 * Core Forgeron API System endpoints
 * OpenAPI spec version: 1.0
 */

export interface UpdateExchangeRateDto {
  currencyName?: string;
  buyRate?: string;
  sellRate?: string;
  effectiveDate?: string;
}
