/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */

export type UpdateAppConfigDtoCreditLimitBehavior = typeof UpdateAppConfigDtoCreditLimitBehavior[keyof typeof UpdateAppConfigDtoCreditLimitBehavior];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateAppConfigDtoCreditLimitBehavior = {
  hard: 'hard',
  soft: 'soft',
  notify: 'notify',
} as const;
