/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type { UpdateUserDtoRole } from './updateUserDtoRole';

export interface UpdateUserDto {
  /**
   * @minLength 6
   * @maxLength 72
   */
  password?: string;
  role?: UpdateUserDtoRole;
  /** @maxLength 100 */
  displayName?: string;
  /** @maxLength 255 */
  email?: string;
}
