/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */

export interface UpdateGoodsReceivedDto {
  vendorId?: string;
  locationId?: string;
  packingSlipNumber?: string;
  notes?: string;
}
