/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.1
 */

export type UpdateUomDtoCategory = typeof UpdateUomDtoCategory[keyof typeof UpdateUomDtoCategory];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateUomDtoCategory = {
  goods: 'goods',
  service: 'service',
} as const;
