/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.1
 */
import type { UpdateCrmSettingsDtoOrganizationMetadataSchema } from './updateCrmSettingsDtoOrganizationMetadataSchema';
import type { UpdateCrmSettingsDtoOpportunityMetadataSchema } from './updateCrmSettingsDtoOpportunityMetadataSchema';
import type { UpdateCrmSettingsDtoContactMetadataSchema } from './updateCrmSettingsDtoContactMetadataSchema';
import type { UpdateCrmSettingsDtoCustomerMetadataSchema } from './updateCrmSettingsDtoCustomerMetadataSchema';
import type { UpdateCrmSettingsDtoSupplierMetadataSchema } from './updateCrmSettingsDtoSupplierMetadataSchema';

export interface UpdateCrmSettingsDto {
  /** @nullable */
  organizationMetadataSchema?: UpdateCrmSettingsDtoOrganizationMetadataSchema;
  /** @nullable */
  opportunityMetadataSchema?: UpdateCrmSettingsDtoOpportunityMetadataSchema;
  /** @nullable */
  contactMetadataSchema?: UpdateCrmSettingsDtoContactMetadataSchema;
  /** @nullable */
  customerMetadataSchema?: UpdateCrmSettingsDtoCustomerMetadataSchema;
  /** @nullable */
  supplierMetadataSchema?: UpdateCrmSettingsDtoSupplierMetadataSchema;
}
