/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type { UpdateAppConfigDtoCreditLimitBehavior } from './updateAppConfigDtoCreditLimitBehavior';
import type { UpdateAppConfigDtoTaxProviderMappings } from './updateAppConfigDtoTaxProviderMappings';
import type { UpdateAppConfigDtoEnrichmentProviderMappings } from './updateAppConfigDtoEnrichmentProviderMappings';
import type { OrderedSettingDto } from './orderedSettingDto';

export interface UpdateAppConfigDto {
  defaultFulfillmentLocationId?: string;
  creditLimitBehavior?: UpdateAppConfigDtoCreditLimitBehavior;
  defaultCustomerTermsId?: string;
  defaultSupplierTermsId?: string;
  defaultCustomerTaxPositionId?: string;
  defaultSupplierTaxPositionId?: string;
  defaultPurchaseTaxCategoryId?: string;
  defaultSalesTaxCategoryId?: string;
  apiRateLimit?: string;
  taxProviderMappings?: UpdateAppConfigDtoTaxProviderMappings;
  enrichmentProviderMappings?: UpdateAppConfigDtoEnrichmentProviderMappings;
  smtpHost?: string;
  smtpPort?: number;
  smtpUser?: string;
  smtpPass?: string;
  smtpFromAddress?: string;
  actorTags?: OrderedSettingDto[];
  actorContactRoles?: OrderedSettingDto[];
  projectContactRoles?: OrderedSettingDto[];
  projectActorRoles?: OrderedSettingDto[];
  referralModes?: OrderedSettingDto[];
  projectStatuses?: OrderedSettingDto[];
  projectTypes?: OrderedSettingDto[];
}
