/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * ModBM API
 * Core Forgeron API System endpoints
 * OpenAPI spec version: 1.0
 */
import type { UpdateSupplierGroupDtoPurchasingBlockReason } from './updateSupplierGroupDtoPurchasingBlockReason';
import type { UpdateSupplierGroupDtoPaymentBlockReason } from './updateSupplierGroupDtoPaymentBlockReason';

export interface UpdateSupplierGroupDto {
  groupCode?: string;
  name?: string;
  defaultApAccountId?: string;
  defaultExpenseAccountId?: string;
  tradingTermsId?: string;
  earlyPaymentDiscount?: string;
  creditLimit?: string;
  isPurchasingBlocked?: boolean;
  purchasingBlockReason?: UpdateSupplierGroupDtoPurchasingBlockReason;
  isPaymentBlocked?: boolean;
  paymentBlockReason?: UpdateSupplierGroupDtoPaymentBlockReason;
  blockNotes?: string;
  defaultCostCenterId?: string;
  defaultActivityId?: string;
}
