/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type { UpdateSupplierDtoPurchasingBlockReason } from './updateSupplierDtoPurchasingBlockReason';
import type { UpdateSupplierDtoPaymentBlockReason } from './updateSupplierDtoPaymentBlockReason';

export interface UpdateSupplierDto {
  earlyPaymentDiscount?: string;
  earlyPaymentDiscountDays?: number;
  actorId?: string;
  vendorNumber?: string;
  name?: string;
  address1Line1?: string;
  address1Line2?: string;
  address1City?: string;
  address1StateOrProvince?: string;
  address1PostalCode?: string;
  address1Country?: string;
  telephone1?: string;
  fax?: string;
  emailAddress1?: string;
  tradingTermsId?: string;
  creditLimit?: string;
  isPurchasingBlocked?: boolean;
  purchasingBlockReason?: UpdateSupplierDtoPurchasingBlockReason;
  isPaymentBlocked?: boolean;
  paymentBlockReason?: UpdateSupplierDtoPaymentBlockReason;
  blockNotes?: string;
  supplierGroupId?: string;
  currencyCode?: string;
  notes?: string;
  bankAccountName?: string;
  bankBsb?: string;
  bankAccountNumber?: string;
  businessNumber?: string;
  isTaxRegistered?: boolean;
  taxPositionId?: string;
}
