/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type { UpdateUserSettingsDtoDashboardConfig } from './updateUserSettingsDtoDashboardConfig';
import type { UpdateUserSettingsDtoReportConfigs } from './updateUserSettingsDtoReportConfigs';
import type { UpdateUserSettingsDtoPreferences } from './updateUserSettingsDtoPreferences';

export interface UpdateUserSettingsDto {
  /** Dashboard configuration layout and pinned widgets */
  dashboardConfig?: UpdateUserSettingsDtoDashboardConfig;
  /** Saved report configurations and filters */
  reportConfigs?: UpdateUserSettingsDtoReportConfigs;
  /** Generic UI preferences */
  preferences?: UpdateUserSettingsDtoPreferences;
}
