/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.1
 */

/**
 * JSON Schema definition for user-defined metadata on Sales Invoices
 * @nullable
 */
export type UpdateSalesSettingsDtoSalesInvoiceMetadataSchema = { [key: string]: unknown } | null;
