/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */

export interface UpdateContactDto {
  firstName?: string;
  lastName?: string;
  email?: string;
  /** @pattern /^\+?[0-9\s\-()]+$/ */
  phone?: string;
  /** @pattern /^\+?[0-9\s\-()]+$/ */
  mobile?: string;
  jobTitle?: string;
  isPrimary?: boolean;
  primaryFor?: string[];
  opportunityRole?: string;
  projectRole?: string;
}
