/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.1
 */
import type { UpdateSalesSettingsDtoSalesOrderMetadataSchema } from './updateSalesSettingsDtoSalesOrderMetadataSchema';
import type { UpdateSalesSettingsDtoSalesInvoiceMetadataSchema } from './updateSalesSettingsDtoSalesInvoiceMetadataSchema';
import type { UpdateSalesSettingsDtoCreditNoteMetadataSchema } from './updateSalesSettingsDtoCreditNoteMetadataSchema';

export interface UpdateSalesSettingsDto {
  /**
   * JSON Schema definition for user-defined metadata on Sales Orders
   * @nullable
   */
  salesOrderMetadataSchema?: UpdateSalesSettingsDtoSalesOrderMetadataSchema;
  /**
   * JSON Schema definition for user-defined metadata on Sales Invoices
   * @nullable
   */
  salesInvoiceMetadataSchema?: UpdateSalesSettingsDtoSalesInvoiceMetadataSchema;
  /**
   * JSON Schema definition for user-defined metadata on Credit Notes
   * @nullable
   */
  creditNoteMetadataSchema?: UpdateSalesSettingsDtoCreditNoteMetadataSchema;
}
