/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */

export type UpdateOrderLineDtoLineType = typeof UpdateOrderLineDtoLineType[keyof typeof UpdateOrderLineDtoLineType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateOrderLineDtoLineType = {
  Product: 'Product',
  Comment: 'Comment',
} as const;
