/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.1
 */

export interface UpdateReportDto {
  name?: string;
  slug?: string;
  description?: string;
  template?: string;
  outputNamePattern?: string;
  contexts?: string[];
}
