/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * ModBM API
 * Core Forgeron API System endpoints
 * OpenAPI spec version: 1.0
 */

export interface UpdateProductGroupDto {
  groupCode?: string;
  name?: string;
  defaultRevenueAccountId?: string;
  defaultExpenseAccountId?: string;
  defaultCostCenterId?: string;
  defaultActivityId?: string;
}
