/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.1
 */
import type { PaginatedResponse } from './paginatedResponse';
import type { UsersControllerFindAll200AllOf } from './usersControllerFindAll200AllOf';

export type UsersControllerFindAll200 = PaginatedResponse & UsersControllerFindAll200AllOf;
