/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.1
 */

export interface UserResponseDto {
  userId: string;
  username: string;
  role: string;
  isActive: boolean;
  /** @nullable */
  displayName: string | null;
  /** @nullable */
  email: string | null;
  tenantId: string;
  twoFactorEnabled: boolean;
  createdAt: string;
  updatedAt: string;
}
