/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.1
 */
import type { UserResponseDto } from './userResponseDto';

export type UsersControllerFindAll200AllOf = {
  data: UserResponseDto[];
};
