/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */

export interface WebhookResponseDto {
  webhookId: string;
  targetUrl: string;
  eventTypes: string[];
  secretKey: string;
  isActive: boolean;
  /** @nullable */
  createdOn: string | null;
}
