/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type { WorkOrderAvailableBinDto } from './workOrderAvailableBinDto';

export interface WorkOrderPickingLineDto {
  salesOrderLineId: string;
  lineNumber: number;
  productId: string;
  productNumber: string;
  productType: string;
  productDescription: string;
  locationName: string;
  quantity: string;
  quantityPicked: string;
  quantityShipped: string;
  remaining: string;
  isFullyPicked: boolean;
  isPhysical: boolean;
  onHand: string;
  availableBins: WorkOrderAvailableBinDto[];
}
