/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type { WorkOrderResponseDtoCreatedOn } from './workOrderResponseDtoCreatedOn';
import type { WorkOrderResponseDtoModifiedOn } from './workOrderResponseDtoModifiedOn';
import type { WorkOrderComponentResponseDto } from './workOrderComponentResponseDto';

export interface WorkOrderResponseDto {
  workOrderId: string;
  orderNumber: string;
  productId: string;
  productName: string;
  productNumber: string;
  targetQuantity: string;
  completedQuantity: string;
  locationId: string;
  locationName: string;
  /** @nullable */
  wipBinId?: string | null;
  /** @nullable */
  wipBinName?: string | null;
  stateCode: string;
  /** @nullable */
  totalCost?: string | null;
  /** @nullable */
  createdBy?: string | null;
  createdOn?: WorkOrderResponseDtoCreatedOn;
  modifiedOn?: WorkOrderResponseDtoModifiedOn;
  components?: WorkOrderComponentResponseDto[];
}
