/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type { WorkOrderPickingLineDto } from './workOrderPickingLineDto';
import type { WorkOrderPickDetailDto } from './workOrderPickDetailDto';

export interface WorkOrderPickingSummaryDto {
  totalLines: number;
  fullyPickedLines: number;
  isFullyPicked: boolean;
  lines: WorkOrderPickingLineDto[];
  picks: WorkOrderPickDetailDto[];
}
