/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */

export interface WorkOrderComponentResponseDto {
  workOrderComponentId: string;
  productId: string;
  productName: string;
  productNumber: string;
  expectedQuantity: string;
  /** @nullable */
  unitCost?: string | null;
}
