/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type {
  ChangeOrderStateDto,
  CreateOrderDto,
  CreateOrderLineDto,
  EmailDocumentDto,
  EmptyBodyDto,
  OrderResponseDto,
  OrdersControllerEmailDocument201,
  OrdersControllerFindAll200,
  OrdersControllerFindAllParams,
  OrdersControllerFindOneParams,
  OverrideCreditHoldDto,
  UpdateOrderDto,
  UpdateOrderLineDto
} from '../../model';

import { customFetch } from '../../mutator';

/**
 * Retrieve a paginated list of sales orders globally.
 * @summary Find All Orders
 */
export type ordersControllerFindAllResponse200 = {
  data: OrdersControllerFindAll200
  status: 200
}
    
export type ordersControllerFindAllResponseSuccess = (ordersControllerFindAllResponse200) & {
  headers: Headers;
};
;

export type ordersControllerFindAllResponse = (ordersControllerFindAllResponseSuccess)

export const getOrdersControllerFindAllUrl = (params?: OrdersControllerFindAllParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/sales-orders?${stringifiedParams}` : `/sales-orders`
}

export const ordersControllerFindAll = async (params?: OrdersControllerFindAllParams, options?: RequestInit): Promise<ordersControllerFindAllResponse> => {
  
  return customFetch<ordersControllerFindAllResponse>(getOrdersControllerFindAllUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * Create a new sales order with or without line items.
 * @summary Create Order
 */
export type ordersControllerCreateResponse201 = {
  data: OrderResponseDto
  status: 201
}
    
export type ordersControllerCreateResponseSuccess = (ordersControllerCreateResponse201) & {
  headers: Headers;
};
;

export type ordersControllerCreateResponse = (ordersControllerCreateResponseSuccess)

export const getOrdersControllerCreateUrl = () => {


  

  return `/sales-orders`
}

export const ordersControllerCreate = async (createOrderDto: CreateOrderDto, options?: RequestInit): Promise<ordersControllerCreateResponse> => {
  
  return customFetch<ordersControllerCreateResponse>(getOrdersControllerCreateUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createOrderDto,)
  }
);}


/**
 * Manually trigger an external tax calculation for the order.
 * @summary Calculate Taxes
 */
export type ordersControllerTriggerTaxCalculationResponse201 = {
  data: OrderResponseDto
  status: 201
}
    
export type ordersControllerTriggerTaxCalculationResponseSuccess = (ordersControllerTriggerTaxCalculationResponse201) & {
  headers: Headers;
};
;

export type ordersControllerTriggerTaxCalculationResponse = (ordersControllerTriggerTaxCalculationResponseSuccess)

export const getOrdersControllerTriggerTaxCalculationUrl = (id: string,) => {


  

  return `/sales-orders/${id}/tax`
}

export const ordersControllerTriggerTaxCalculation = async (id: string,
    emptyBodyDto: EmptyBodyDto, options?: RequestInit): Promise<ordersControllerTriggerTaxCalculationResponse> => {
  
  return customFetch<ordersControllerTriggerTaxCalculationResponse>(getOrdersControllerTriggerTaxCalculationUrl(id),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      emptyBodyDto,)
  }
);}


/**
 * Generates a Document PDF and queues it to be emailed to the customer.
 * @summary Email Document
 */
export type ordersControllerEmailDocumentResponse201 = {
  data: OrdersControllerEmailDocument201
  status: 201
}
    
export type ordersControllerEmailDocumentResponseSuccess = (ordersControllerEmailDocumentResponse201) & {
  headers: Headers;
};
;

export type ordersControllerEmailDocumentResponse = (ordersControllerEmailDocumentResponseSuccess)

export const getOrdersControllerEmailDocumentUrl = (id: string,) => {


  

  return `/sales-orders/${id}/email-document`
}

export const ordersControllerEmailDocument = async (id: string,
    emailDocumentDto: EmailDocumentDto, options?: RequestInit): Promise<ordersControllerEmailDocumentResponse> => {
  
  return customFetch<ordersControllerEmailDocumentResponse>(getOrdersControllerEmailDocumentUrl(id),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      emailDocumentDto,)
  }
);}


/**
 * Update the processing state of a sales order.
 * @summary Change Order State
 */
export type ordersControllerChangeStateResponse200 = {
  data: OrderResponseDto
  status: 200
}
    
export type ordersControllerChangeStateResponseSuccess = (ordersControllerChangeStateResponse200) & {
  headers: Headers;
};
;

export type ordersControllerChangeStateResponse = (ordersControllerChangeStateResponseSuccess)

export const getOrdersControllerChangeStateUrl = (id: string,) => {


  

  return `/sales-orders/${id}/state`
}

export const ordersControllerChangeState = async (id: string,
    changeOrderStateDto: ChangeOrderStateDto, options?: RequestInit): Promise<ordersControllerChangeStateResponse> => {
  
  return customFetch<ordersControllerChangeStateResponse>(getOrdersControllerChangeStateUrl(id),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      changeOrderStateDto,)
  }
);}


/**
 * Temporarily overrides a credit hold for this specific order.
 * @summary Override Credit Hold
 */
export type ordersControllerOverrideCreditHoldResponse200 = {
  data: OrderResponseDto
  status: 200
}
    
export type ordersControllerOverrideCreditHoldResponseSuccess = (ordersControllerOverrideCreditHoldResponse200) & {
  headers: Headers;
};
;

export type ordersControllerOverrideCreditHoldResponse = (ordersControllerOverrideCreditHoldResponseSuccess)

export const getOrdersControllerOverrideCreditHoldUrl = (id: string,) => {


  

  return `/sales-orders/${id}/override-credit-hold`
}

export const ordersControllerOverrideCreditHold = async (id: string,
    overrideCreditHoldDto: OverrideCreditHoldDto, options?: RequestInit): Promise<ordersControllerOverrideCreditHoldResponse> => {
  
  return customFetch<ordersControllerOverrideCreditHoldResponse>(getOrdersControllerOverrideCreditHoldUrl(id),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      overrideCreditHoldDto,)
  }
);}


/**
 * Mark a sales order as archived.
 * @summary Archive Order
 */
export type ordersControllerArchiveResponse201 = {
  data: OrderResponseDto
  status: 201
}
    
export type ordersControllerArchiveResponseSuccess = (ordersControllerArchiveResponse201) & {
  headers: Headers;
};
;

export type ordersControllerArchiveResponse = (ordersControllerArchiveResponseSuccess)

export const getOrdersControllerArchiveUrl = (id: string,) => {


  

  return `/sales-orders/${id}/archive`
}

export const ordersControllerArchive = async (id: string,
    emptyBodyDto: EmptyBodyDto, options?: RequestInit): Promise<ordersControllerArchiveResponse> => {
  
  return customFetch<ordersControllerArchiveResponse>(getOrdersControllerArchiveUrl(id),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      emptyBodyDto,)
  }
);}


/**
 * Restore an archived sales order.
 * @summary Unarchive Order
 */
export type ordersControllerUnarchiveResponse201 = {
  data: OrderResponseDto
  status: 201
}
    
export type ordersControllerUnarchiveResponseSuccess = (ordersControllerUnarchiveResponse201) & {
  headers: Headers;
};
;

export type ordersControllerUnarchiveResponse = (ordersControllerUnarchiveResponseSuccess)

export const getOrdersControllerUnarchiveUrl = (id: string,) => {


  

  return `/sales-orders/${id}/unarchive`
}

export const ordersControllerUnarchive = async (id: string,
    emptyBodyDto: EmptyBodyDto, options?: RequestInit): Promise<ordersControllerUnarchiveResponse> => {
  
  return customFetch<ordersControllerUnarchiveResponse>(getOrdersControllerUnarchiveUrl(id),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      emptyBodyDto,)
  }
);}


/**
 * Add a new line item to a draft sales order.
 * @summary Add Order Line
 */
export type ordersControllerAddLineResponse201 = {
  data: OrderResponseDto
  status: 201
}
    
export type ordersControllerAddLineResponseSuccess = (ordersControllerAddLineResponse201) & {
  headers: Headers;
};
;

export type ordersControllerAddLineResponse = (ordersControllerAddLineResponseSuccess)

export const getOrdersControllerAddLineUrl = (id: string,) => {


  

  return `/sales-orders/${id}/lines`
}

export const ordersControllerAddLine = async (id: string,
    createOrderLineDto: CreateOrderLineDto, options?: RequestInit): Promise<ordersControllerAddLineResponse> => {
  
  return customFetch<ordersControllerAddLineResponse>(getOrdersControllerAddLineUrl(id),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createOrderLineDto,)
  }
);}


/**
 * Modify an existing line item on a sales order.
 * @summary Update Order Line
 */
export type ordersControllerUpdateLineResponse200 = {
  data: OrderResponseDto
  status: 200
}
    
export type ordersControllerUpdateLineResponseSuccess = (ordersControllerUpdateLineResponse200) & {
  headers: Headers;
};
;

export type ordersControllerUpdateLineResponse = (ordersControllerUpdateLineResponseSuccess)

export const getOrdersControllerUpdateLineUrl = (id: string,
    lineId: string,) => {


  

  return `/sales-orders/${id}/lines/${lineId}`
}

export const ordersControllerUpdateLine = async (id: string,
    lineId: string,
    updateOrderLineDto: UpdateOrderLineDto, options?: RequestInit): Promise<ordersControllerUpdateLineResponse> => {
  
  return customFetch<ordersControllerUpdateLineResponse>(getOrdersControllerUpdateLineUrl(id,lineId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateOrderLineDto,)
  }
);}


/**
 * Delete a line item from a sales order.
 * @summary Remove Order Line
 */
export type ordersControllerRemoveLineResponse200 = {
  data: OrderResponseDto
  status: 200
}
    
export type ordersControllerRemoveLineResponseSuccess = (ordersControllerRemoveLineResponse200) & {
  headers: Headers;
};
;

export type ordersControllerRemoveLineResponse = (ordersControllerRemoveLineResponseSuccess)

export const getOrdersControllerRemoveLineUrl = (id: string,
    lineId: string,) => {


  

  return `/sales-orders/${id}/lines/${lineId}`
}

export const ordersControllerRemoveLine = async (id: string,
    lineId: string, options?: RequestInit): Promise<ordersControllerRemoveLineResponse> => {
  
  return customFetch<ordersControllerRemoveLineResponse>(getOrdersControllerRemoveLineUrl(id,lineId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}


/**
 * Add a new line item to a confirmed sales order.
 * @summary Add Post-Confirmation Line
 */
export type ordersControllerAddPostConfirmationLineResponse201 = {
  data: OrderResponseDto
  status: 201
}
    
export type ordersControllerAddPostConfirmationLineResponseSuccess = (ordersControllerAddPostConfirmationLineResponse201) & {
  headers: Headers;
};
;

export type ordersControllerAddPostConfirmationLineResponse = (ordersControllerAddPostConfirmationLineResponseSuccess)

export const getOrdersControllerAddPostConfirmationLineUrl = (id: string,) => {


  

  return `/sales-orders/${id}/post-confirmation-lines`
}

export const ordersControllerAddPostConfirmationLine = async (id: string,
    createOrderLineDto: CreateOrderLineDto, options?: RequestInit): Promise<ordersControllerAddPostConfirmationLineResponse> => {
  
  return customFetch<ordersControllerAddPostConfirmationLineResponse>(getOrdersControllerAddPostConfirmationLineUrl(id),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createOrderLineDto,)
  }
);}


/**
 * Retrieve detailed information for a specific sales order.
 * @summary Find Order
 */
export type ordersControllerFindOneResponse200 = {
  data: OrderResponseDto
  status: 200
}
    
export type ordersControllerFindOneResponseSuccess = (ordersControllerFindOneResponse200) & {
  headers: Headers;
};
;

export type ordersControllerFindOneResponse = (ordersControllerFindOneResponseSuccess)

export const getOrdersControllerFindOneUrl = (id: string,
    params?: OrdersControllerFindOneParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/sales-orders/${id}?${stringifiedParams}` : `/sales-orders/${id}`
}

export const ordersControllerFindOne = async (id: string,
    params?: OrdersControllerFindOneParams, options?: RequestInit): Promise<ordersControllerFindOneResponse> => {
  
  return customFetch<ordersControllerFindOneResponse>(getOrdersControllerFindOneUrl(id,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * Modify the details or metadata of an existing sales order.
 * @summary Update Order
 */
export type ordersControllerUpdateResponse200 = {
  data: OrderResponseDto
  status: 200
}
    
export type ordersControllerUpdateResponseSuccess = (ordersControllerUpdateResponse200) & {
  headers: Headers;
};
;

export type ordersControllerUpdateResponse = (ordersControllerUpdateResponseSuccess)

export const getOrdersControllerUpdateUrl = (id: string,) => {


  

  return `/sales-orders/${id}`
}

export const ordersControllerUpdate = async (id: string,
    updateOrderDto: UpdateOrderDto, options?: RequestInit): Promise<ordersControllerUpdateResponse> => {
  
  return customFetch<ordersControllerUpdateResponse>(getOrdersControllerUpdateUrl(id),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateOrderDto,)
  }
);}


