/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.1
 */
import type {
  AddStocktakeUnlistedProductDto,
  BatchRecordStocktakeCountsDto,
  CreateStocktakeDto,
  MarkStocktakeBinEmptyDto,
  RecordStocktakeCountDto,
  StocktakeLineResponseDto,
  StocktakeResponseDto,
  StocktakeStateTransitionDto,
  StocktakeSuccessResponseDto,
  StocktakesControllerFindAll200,
  StocktakesControllerFindAllParams,
  StocktakesControllerFindCounts200,
  StocktakesControllerFindCountsParams,
  StocktakesControllerFindLines200,
  StocktakesControllerFindLinesParams,
  SubmitStocktakeDto,
  UpdateStocktakeDto,
  UpdateStocktakeLineDto
} from '../../model';

import { customFetch } from '../../mutator';

/**
 * Create a new stocktake header with initial scope snapshot lines in draft state.
 * @summary Create Stocktake
 */
export type stocktakesControllerCreateResponse201 = {
  data: StocktakeResponseDto
  status: 201
}
    
export type stocktakesControllerCreateResponseSuccess = (stocktakesControllerCreateResponse201) & {
  headers: Headers;
};
;

export type stocktakesControllerCreateResponse = (stocktakesControllerCreateResponseSuccess)

export const getStocktakesControllerCreateUrl = () => {


  

  return `/inventory/stocktakes`
}

export const stocktakesControllerCreate = async (createStocktakeDto: CreateStocktakeDto, options?: RequestInit): Promise<stocktakesControllerCreateResponse> => {
  
  return customFetch<stocktakesControllerCreateResponse>(getStocktakesControllerCreateUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createStocktakeDto,)
  }
);}


/**
 * Retrieve a paginated list of stocktakes with aggregate progress metrics.
 * @summary List Stocktakes
 */
export type stocktakesControllerFindAllResponse200 = {
  data: StocktakesControllerFindAll200
  status: 200
}
    
export type stocktakesControllerFindAllResponseSuccess = (stocktakesControllerFindAllResponse200) & {
  headers: Headers;
};
;

export type stocktakesControllerFindAllResponse = (stocktakesControllerFindAllResponseSuccess)

export const getStocktakesControllerFindAllUrl = (params?: StocktakesControllerFindAllParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/inventory/stocktakes?${stringifiedParams}` : `/inventory/stocktakes`
}

export const stocktakesControllerFindAll = async (params?: StocktakesControllerFindAllParams, options?: RequestInit): Promise<stocktakesControllerFindAllResponse> => {
  
  return customFetch<stocktakesControllerFindAllResponse>(getStocktakesControllerFindAllUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * Retrieve single stocktake by ID with progress stats.
 * @summary Get Stocktake by ID
 */
export type stocktakesControllerFindOneResponse200 = {
  data: StocktakeResponseDto
  status: 200
}
    
export type stocktakesControllerFindOneResponseSuccess = (stocktakesControllerFindOneResponse200) & {
  headers: Headers;
};
;

export type stocktakesControllerFindOneResponse = (stocktakesControllerFindOneResponseSuccess)

export const getStocktakesControllerFindOneUrl = (id: string,) => {


  

  return `/inventory/stocktakes/${id}`
}

export const stocktakesControllerFindOne = async (id: string, options?: RequestInit): Promise<stocktakesControllerFindOneResponse> => {
  
  return customFetch<stocktakesControllerFindOneResponse>(getStocktakesControllerFindOneUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * Update stocktake name, notes, or blind count flag.
 * @summary Update Stocktake Header
 */
export type stocktakesControllerUpdateResponse200 = {
  data: StocktakeResponseDto
  status: 200
}
    
export type stocktakesControllerUpdateResponseSuccess = (stocktakesControllerUpdateResponse200) & {
  headers: Headers;
};
;

export type stocktakesControllerUpdateResponse = (stocktakesControllerUpdateResponseSuccess)

export const getStocktakesControllerUpdateUrl = (id: string,) => {


  

  return `/inventory/stocktakes/${id}`
}

export const stocktakesControllerUpdate = async (id: string,
    updateStocktakeDto: UpdateStocktakeDto, options?: RequestInit): Promise<stocktakesControllerUpdateResponse> => {
  
  return customFetch<stocktakesControllerUpdateResponse>(getStocktakesControllerUpdateUrl(id),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateStocktakeDto,)
  }
);}


/**
 * Delete a draft or cancelled stocktake.
 * @summary Delete Stocktake
 */
export type stocktakesControllerDeleteResponse200 = {
  data: StocktakeSuccessResponseDto
  status: 200
}
    
export type stocktakesControllerDeleteResponseSuccess = (stocktakesControllerDeleteResponse200) & {
  headers: Headers;
};
;

export type stocktakesControllerDeleteResponse = (stocktakesControllerDeleteResponseSuccess)

export const getStocktakesControllerDeleteUrl = (id: string,) => {


  

  return `/inventory/stocktakes/${id}`
}

export const stocktakesControllerDelete = async (id: string, options?: RequestInit): Promise<stocktakesControllerDeleteResponse> => {
  
  return customFetch<stocktakesControllerDeleteResponse>(getStocktakesControllerDeleteUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}


/**
 * Transition lifecycle state (draft -> open -> review -> submitted / cancelled).
 * @summary Change Stocktake State
 */
export type stocktakesControllerChangeStateResponse200 = {
  data: StocktakeResponseDto
  status: 200
}
    
export type stocktakesControllerChangeStateResponseSuccess = (stocktakesControllerChangeStateResponse200) & {
  headers: Headers;
};
;

export type stocktakesControllerChangeStateResponse = (stocktakesControllerChangeStateResponseSuccess)

export const getStocktakesControllerChangeStateUrl = (id: string,) => {


  

  return `/inventory/stocktakes/${id}/state`
}

export const stocktakesControllerChangeState = async (id: string,
    stocktakeStateTransitionDto: StocktakeStateTransitionDto, options?: RequestInit): Promise<stocktakesControllerChangeStateResponse> => {
  
  return customFetch<stocktakesControllerChangeStateResponse>(getStocktakesControllerChangeStateUrl(id),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      stocktakeStateTransitionDto,)
  }
);}


/**
 * Retrieve paginated lines for a stocktake. Expected quantities are masked during blind count in open state.
 * @summary List Stocktake Lines
 */
export type stocktakesControllerFindLinesResponse200 = {
  data: StocktakesControllerFindLines200
  status: 200
}
    
export type stocktakesControllerFindLinesResponseSuccess = (stocktakesControllerFindLinesResponse200) & {
  headers: Headers;
};
;

export type stocktakesControllerFindLinesResponse = (stocktakesControllerFindLinesResponseSuccess)

export const getStocktakesControllerFindLinesUrl = (id: string,
    params?: StocktakesControllerFindLinesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/inventory/stocktakes/${id}/lines?${stringifiedParams}` : `/inventory/stocktakes/${id}/lines`
}

export const stocktakesControllerFindLines = async (id: string,
    params?: StocktakesControllerFindLinesParams, options?: RequestInit): Promise<stocktakesControllerFindLinesResponse> => {
  
  return customFetch<stocktakesControllerFindLinesResponse>(getStocktakesControllerFindLinesUrl(id,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * Add a product/bin not in the original scope during counting or review.
 * @summary Add Unlisted Product to Stocktake
 */
export type stocktakesControllerAddUnlistedProductResponse201 = {
  data: StocktakeLineResponseDto
  status: 201
}
    
export type stocktakesControllerAddUnlistedProductResponseSuccess = (stocktakesControllerAddUnlistedProductResponse201) & {
  headers: Headers;
};
;

export type stocktakesControllerAddUnlistedProductResponse = (stocktakesControllerAddUnlistedProductResponseSuccess)

export const getStocktakesControllerAddUnlistedProductUrl = (id: string,) => {


  

  return `/inventory/stocktakes/${id}/lines`
}

export const stocktakesControllerAddUnlistedProduct = async (id: string,
    addStocktakeUnlistedProductDto: AddStocktakeUnlistedProductDto, options?: RequestInit): Promise<stocktakesControllerAddUnlistedProductResponse> => {
  
  return customFetch<stocktakesControllerAddUnlistedProductResponse>(getStocktakesControllerAddUnlistedProductUrl(id),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      addStocktakeUnlistedProductDto,)
  }
);}


/**
 * Manually adjust line counted quantity or notes during review.
 * @summary Update Stocktake Line
 */
export type stocktakesControllerUpdateLineResponse200 = {
  data: StocktakeLineResponseDto
  status: 200
}
    
export type stocktakesControllerUpdateLineResponseSuccess = (stocktakesControllerUpdateLineResponse200) & {
  headers: Headers;
};
;

export type stocktakesControllerUpdateLineResponse = (stocktakesControllerUpdateLineResponseSuccess)

export const getStocktakesControllerUpdateLineUrl = (id: string,
    lineId: string,) => {


  

  return `/inventory/stocktakes/${id}/lines/${lineId}`
}

export const stocktakesControllerUpdateLine = async (id: string,
    lineId: string,
    updateStocktakeLineDto: UpdateStocktakeLineDto, options?: RequestInit): Promise<stocktakesControllerUpdateLineResponse> => {
  
  return customFetch<stocktakesControllerUpdateLineResponse>(getStocktakesControllerUpdateLineUrl(id,lineId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateStocktakeLineDto,)
  }
);}


/**
 * Delete an unlisted or uncounted line from a draft/review stocktake.
 * @summary Delete Stocktake Line
 */
export type stocktakesControllerDeleteLineResponse200 = {
  data: StocktakeSuccessResponseDto
  status: 200
}
    
export type stocktakesControllerDeleteLineResponseSuccess = (stocktakesControllerDeleteLineResponse200) & {
  headers: Headers;
};
;

export type stocktakesControllerDeleteLineResponse = (stocktakesControllerDeleteLineResponseSuccess)

export const getStocktakesControllerDeleteLineUrl = (id: string,
    lineId: string,) => {


  

  return `/inventory/stocktakes/${id}/lines/${lineId}`
}

export const stocktakesControllerDeleteLine = async (id: string,
    lineId: string, options?: RequestInit): Promise<stocktakesControllerDeleteLineResponse> => {
  
  return customFetch<stocktakesControllerDeleteLineResponse>(getStocktakesControllerDeleteLineUrl(id,lineId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}


/**
 * Retrieve the append-only scan/count log for audit and concurrency verification.
 * @summary List Stocktake Counts
 */
export type stocktakesControllerFindCountsResponse200 = {
  data: StocktakesControllerFindCounts200
  status: 200
}
    
export type stocktakesControllerFindCountsResponseSuccess = (stocktakesControllerFindCountsResponse200) & {
  headers: Headers;
};
;

export type stocktakesControllerFindCountsResponse = (stocktakesControllerFindCountsResponseSuccess)

export const getStocktakesControllerFindCountsUrl = (id: string,
    params?: StocktakesControllerFindCountsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/inventory/stocktakes/${id}/counts?${stringifiedParams}` : `/inventory/stocktakes/${id}/counts`
}

export const stocktakesControllerFindCounts = async (id: string,
    params?: StocktakesControllerFindCountsParams, options?: RequestInit): Promise<stocktakesControllerFindCountsResponse> => {
  
  return customFetch<stocktakesControllerFindCountsResponse>(getStocktakesControllerFindCountsUrl(id,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * Record a physical count/scan action by counter username.
 * @summary Record Single Stocktake Count
 */
export type stocktakesControllerRecordCountResponse201 = {
  data: StocktakeLineResponseDto
  status: 201
}
    
export type stocktakesControllerRecordCountResponseSuccess = (stocktakesControllerRecordCountResponse201) & {
  headers: Headers;
};
;

export type stocktakesControllerRecordCountResponse = (stocktakesControllerRecordCountResponseSuccess)

export const getStocktakesControllerRecordCountUrl = (id: string,) => {


  

  return `/inventory/stocktakes/${id}/counts`
}

export const stocktakesControllerRecordCount = async (id: string,
    recordStocktakeCountDto: RecordStocktakeCountDto, options?: RequestInit): Promise<stocktakesControllerRecordCountResponse> => {
  
  return customFetch<stocktakesControllerRecordCountResponse>(getStocktakesControllerRecordCountUrl(id),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      recordStocktakeCountDto,)
  }
);}


/**
 * Record multiple physical counts/scans atomically.
 * @summary Record Batch Stocktake Counts
 */
export type stocktakesControllerRecordBatchCountsResponse201 = {
  data: StocktakeLineResponseDto[]
  status: 201
}
    
export type stocktakesControllerRecordBatchCountsResponseSuccess = (stocktakesControllerRecordBatchCountsResponse201) & {
  headers: Headers;
};
;

export type stocktakesControllerRecordBatchCountsResponse = (stocktakesControllerRecordBatchCountsResponseSuccess)

export const getStocktakesControllerRecordBatchCountsUrl = (id: string,) => {


  

  return `/inventory/stocktakes/${id}/counts/batch`
}

export const stocktakesControllerRecordBatchCounts = async (id: string,
    batchRecordStocktakeCountsDto: BatchRecordStocktakeCountsDto, options?: RequestInit): Promise<stocktakesControllerRecordBatchCountsResponse> => {
  
  return customFetch<stocktakesControllerRecordBatchCountsResponse>(getStocktakesControllerRecordBatchCountsUrl(id),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      batchRecordStocktakeCountsDto,)
  }
);}


/**
 * Mark all uncounted items in the specified bin as zero quantity.
 * @summary Mark Bin Empty
 */
export type stocktakesControllerMarkBinEmptyResponse200 = {
  data: StocktakeSuccessResponseDto
  status: 200
}
    
export type stocktakesControllerMarkBinEmptyResponseSuccess = (stocktakesControllerMarkBinEmptyResponse200) & {
  headers: Headers;
};
;

export type stocktakesControllerMarkBinEmptyResponse = (stocktakesControllerMarkBinEmptyResponseSuccess)

export const getStocktakesControllerMarkBinEmptyUrl = (id: string,
    binId: string,) => {


  

  return `/inventory/stocktakes/${id}/bins/${binId}/mark-empty`
}

export const stocktakesControllerMarkBinEmpty = async (id: string,
    binId: string,
    markStocktakeBinEmptyDto: MarkStocktakeBinEmptyDto, options?: RequestInit): Promise<stocktakesControllerMarkBinEmptyResponse> => {
  
  return customFetch<stocktakesControllerMarkBinEmptyResponse>(getStocktakesControllerMarkBinEmptyUrl(id,binId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      markStocktakeBinEmptyDto,)
  }
);}


/**
 * Calculate live inventory deltas, write inventory adjustment movements, post GL shrinkage journals, and close stocktake.
 * @summary Submit Stocktake Reconciliation
 */
export type stocktakesControllerSubmitResponse200 = {
  data: StocktakeSuccessResponseDto
  status: 200
}
    
export type stocktakesControllerSubmitResponseSuccess = (stocktakesControllerSubmitResponse200) & {
  headers: Headers;
};
;

export type stocktakesControllerSubmitResponse = (stocktakesControllerSubmitResponseSuccess)

export const getStocktakesControllerSubmitUrl = (id: string,) => {


  

  return `/inventory/stocktakes/${id}/submit`
}

export const stocktakesControllerSubmit = async (id: string,
    submitStocktakeDto: SubmitStocktakeDto, options?: RequestInit): Promise<stocktakesControllerSubmitResponse> => {
  
  return customFetch<stocktakesControllerSubmitResponse>(getStocktakesControllerSubmitUrl(id),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      submitStocktakeDto,)
  }
);}


