/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type {
  CreateDeliveryAddressDto,
  DeleteDeliveryAddressSuccessDto,
  DeliveryAddressResponseDto,
  UpdateDeliveryAddressDto
} from '../../model';

import { customFetch } from '../../mutator';

/**
 * Create a new delivery address for a customer.
 * @summary Create a new delivery address
 */
export type deliveryAddressesControllerCreateResponse201 = {
  data: DeliveryAddressResponseDto
  status: 201
}
    
export type deliveryAddressesControllerCreateResponseSuccess = (deliveryAddressesControllerCreateResponse201) & {
  headers: Headers;
};
;

export type deliveryAddressesControllerCreateResponse = (deliveryAddressesControllerCreateResponseSuccess)

export const getDeliveryAddressesControllerCreateUrl = () => {


  

  return `/delivery-addresses`
}

export const deliveryAddressesControllerCreate = async (createDeliveryAddressDto: CreateDeliveryAddressDto, options?: RequestInit): Promise<deliveryAddressesControllerCreateResponse> => {
  
  return customFetch<deliveryAddressesControllerCreateResponse>(getDeliveryAddressesControllerCreateUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createDeliveryAddressDto,)
  }
);}


/**
 * Update an existing delivery address.
 * @summary Update an existing delivery address
 */
export type deliveryAddressesControllerUpdateResponse200 = {
  data: DeliveryAddressResponseDto
  status: 200
}
    
export type deliveryAddressesControllerUpdateResponseSuccess = (deliveryAddressesControllerUpdateResponse200) & {
  headers: Headers;
};
;

export type deliveryAddressesControllerUpdateResponse = (deliveryAddressesControllerUpdateResponseSuccess)

export const getDeliveryAddressesControllerUpdateUrl = (id: string,) => {


  

  return `/delivery-addresses/${id}`
}

export const deliveryAddressesControllerUpdate = async (id: string,
    updateDeliveryAddressDto: UpdateDeliveryAddressDto, options?: RequestInit): Promise<deliveryAddressesControllerUpdateResponse> => {
  
  return customFetch<deliveryAddressesControllerUpdateResponse>(getDeliveryAddressesControllerUpdateUrl(id),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateDeliveryAddressDto,)
  }
);}


/**
 * Delete a delivery address.
 * @summary Delete a delivery address
 */
export type deliveryAddressesControllerRemoveResponse200 = {
  data: DeleteDeliveryAddressSuccessDto
  status: 200
}
    
export type deliveryAddressesControllerRemoveResponseSuccess = (deliveryAddressesControllerRemoveResponse200) & {
  headers: Headers;
};
;

export type deliveryAddressesControllerRemoveResponse = (deliveryAddressesControllerRemoveResponseSuccess)

export const getDeliveryAddressesControllerRemoveUrl = (id: string,) => {


  

  return `/delivery-addresses/${id}`
}

export const deliveryAddressesControllerRemove = async (id: string, options?: RequestInit): Promise<deliveryAddressesControllerRemoveResponse> => {
  
  return customFetch<deliveryAddressesControllerRemoveResponse>(getDeliveryAddressesControllerRemoveUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}


