ALTER TABLE "herobm_core"."activities" ALTER COLUMN "is_system" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."activities" ALTER COLUMN "is_active" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."actor_contact_links" ALTER COLUMN "link_type" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."actors" ALTER COLUMN "is_tax_registered" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."actors" ALTER COLUMN "tags" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."api_keys" ALTER COLUMN "is_active" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."app_settings" ALTER COLUMN "inventory_valuation_method" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."app_settings" ALTER COLUMN "inventory_accounting_mode" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."app_settings" ALTER COLUMN "credit_limit_behavior" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."app_settings" ALTER COLUMN "actor_tags" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."app_settings" ALTER COLUMN "actor_contact_roles" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."app_settings" ALTER COLUMN "project_contact_roles" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."app_settings" ALTER COLUMN "project_actor_roles" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."app_settings" ALTER COLUMN "project_statuses" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."app_settings" ALTER COLUMN "project_types" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."app_settings" ALTER COLUMN "api_rate_limit" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."backorders" ALTER COLUMN "state_code" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."bank_statement_lines" ALTER COLUMN "is_reconciled" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."bin_contents" ALTER COLUMN "actual_quantity" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."bins" ALTER COLUMN "is_consignment" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."bins" ALTER COLUMN "is_bonded" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."bins" ALTER COLUMN "is_unavailable" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."bins" ALTER COLUMN "source" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."business_reports" ALTER COLUMN "ui_config" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."business_reports" ALTER COLUMN "is_system" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."cost_centers" ALTER COLUMN "is_system" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."cost_centers" ALTER COLUMN "is_active" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."csv_mapping_profiles" ALTER COLUMN "header_rows" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."customer_delivery_addresses" ALTER COLUMN "is_primary" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."customer_delivery_addresses" ALTER COLUMN "source" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."customer_groups" ALTER COLUMN "state_code" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."customer_groups" ALTER COLUMN "early_payment_discount" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."customer_groups" ALTER COLUMN "credit_limit" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."customer_groups" ALTER COLUMN "is_on_credit_hold" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."customers" ALTER COLUMN "state_code" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."customers" ALTER COLUMN "source" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."discount_matrix" ALTER COLUMN "discount_percentage" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."email_outbox" ALTER COLUMN "attachments" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."email_outbox" ALTER COLUMN "status" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."email_outbox" ALTER COLUMN "retries" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."gl_accounts" ALTER COLUMN "is_group" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."gl_accounts" ALTER COLUMN "is_system" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."gl_accounts" ALTER COLUMN "is_bank_account" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."gl_accounts" ALTER COLUMN "metadata" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."gl_accounts" ALTER COLUMN "is_active" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."gl_journal_entries" ALTER COLUMN "is_reversed" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."gl_journal_lines" ALTER COLUMN "debit" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."gl_journal_lines" ALTER COLUMN "credit" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."gl_journal_lines" ALTER COLUMN "foreign_debit" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."gl_journal_lines" ALTER COLUMN "foreign_credit" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."gl_journal_lines" ALTER COLUMN "exchange_rate" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."gl_journal_lines" ALTER COLUMN "is_reconciled" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."gl_reconciliations" ALTER COLUMN "status" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."gl_settings" ALTER COLUMN "account_metadata_schema" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."gl_settings" ALTER COLUMN "bank_match_date_tolerance_days" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."gl_settings" ALTER COLUMN "supported_batch_payment_formats" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."gl_settings" ALTER COLUMN "revenue_routing_precedence" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."gl_settings" ALTER COLUMN "expense_routing_precedence" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."goods_received" ALTER COLUMN "state_code" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."goods_received_lines" ALTER COLUMN "match_status" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."goods_received_lines" ALTER COLUMN "putaway_status" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."integrations" ALTER COLUMN "config" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."integrations" ALTER COLUMN "is_active" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."inventory_entries" ALTER COLUMN "is_reversed" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."locations" ALTER COLUMN "source" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."payment_allocations" ALTER COLUMN "discount_amount" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."payment_entries" ALTER COLUMN "state_code" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."payment_entries" ALTER COLUMN "base_total_amount" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."payment_entries" ALTER COLUMN "base_unallocated_amount" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."payment_entries" ALTER COLUMN "exchange_rate" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."pdf_templates" ALTER COLUMN "output_name_pattern" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."_pipeline_jobs" ALTER COLUMN "progress_json" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."_pipeline_jobs" ALTER COLUMN "logs_json" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."product_components" ALTER COLUMN "parent_quantity" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."product_components" ALTER COLUMN "sequence_number" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."product_components" ALTER COLUMN "fractional_behavior" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."product_default_bins" ALTER COLUMN "is_primary_per_loc" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."product_default_bins" ALTER COLUMN "min_quantity" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."product_suppliers" ALTER COLUMN "cost_price" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."product_suppliers" ALTER COLUMN "discount_percent" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."product_suppliers" ALTER COLUMN "is_preferred" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."product_suppliers" ALTER COLUMN "state_code" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."product_suppliers" ALTER COLUMN "source" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."product_uoms" ALTER COLUMN "is_sales_default" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."product_uoms" ALTER COLUMN "is_purchase_default" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."products" ALTER COLUMN "structure_type" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."products" ALTER COLUMN "list_price" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."products" ALTER COLUMN "standard_cost" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."products" ALTER COLUMN "trade_price" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."products" ALTER COLUMN "price_level_3" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."products" ALTER COLUMN "price_level_4" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."products" ALTER COLUMN "weighted_average_cost" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."products" ALTER COLUMN "weight" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."products" ALTER COLUMN "box_quantity" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."products" ALTER COLUMN "state_code" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."products" ALTER COLUMN "source" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."projects" ALTER COLUMN "status" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."purchase_debit_note_lines" ALTER COLUMN "tax_amount" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."purchase_debit_notes" ALTER COLUMN "tax_amount" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."purchase_debit_notes" ALTER COLUMN "fee_amount" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."purchase_debit_notes" ALTER COLUMN "outstanding_amount" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."purchase_debit_notes" ALTER COLUMN "base_total_amount" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."purchase_debit_notes" ALTER COLUMN "base_outstanding_amount" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."purchase_debit_notes" ALTER COLUMN "exchange_rate" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."purchase_debit_notes" ALTER COLUMN "state_code" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."purchase_invoice_lines" ALTER COLUMN "match_status" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."purchase_invoices" ALTER COLUMN "outstanding_amount" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."purchase_invoices" ALTER COLUMN "tax_amount" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."purchase_invoices" ALTER COLUMN "base_total_amount" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."purchase_invoices" ALTER COLUMN "base_outstanding_amount" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."purchase_invoices" ALTER COLUMN "exchange_rate" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."purchase_invoices" ALTER COLUMN "state_code" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."purchase_order_lines" ALTER COLUMN "discount_percentage" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."purchase_order_lines" ALTER COLUMN "tax" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."purchase_order_lines" ALTER COLUMN "quantity_received" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."purchase_order_return_lines" ALTER COLUMN "return_fee" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."purchase_order_return_shipments" ALTER COLUMN "state_code" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."purchase_order_returns" ALTER COLUMN "state_code" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."purchase_orders" ALTER COLUMN "state_code" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."purchase_orders" ALTER COLUMN "base_total_amount" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."purchase_orders" ALTER COLUMN "exchange_rate" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."reconciliation_rules" ALTER COLUMN "priority" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."sales_credit_note_lines" ALTER COLUMN "tax_amount" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."sales_credit_notes" ALTER COLUMN "tax_amount" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."sales_credit_notes" ALTER COLUMN "fee_amount" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."sales_credit_notes" ALTER COLUMN "outstanding_amount" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."sales_credit_notes" ALTER COLUMN "base_total_amount" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."sales_credit_notes" ALTER COLUMN "base_outstanding_amount" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."sales_credit_notes" ALTER COLUMN "exchange_rate" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."sales_credit_notes" ALTER COLUMN "state_code" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."sales_invoices" ALTER COLUMN "outstanding_amount" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."sales_invoices" ALTER COLUMN "tax_amount" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."sales_invoices" ALTER COLUMN "base_total_amount" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."sales_invoices" ALTER COLUMN "base_outstanding_amount" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."sales_invoices" ALTER COLUMN "exchange_rate" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."sales_invoices" ALTER COLUMN "state_code" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."sales_order_lines" ALTER COLUMN "discount_percentage" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."sales_order_lines" ALTER COLUMN "tax" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."sales_order_lines" ALTER COLUMN "quantity_picked" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."sales_order_lines" ALTER COLUMN "is_post_confirmation" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."sales_order_picks" ALTER COLUMN "state_code" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."sales_order_return_lines" ALTER COLUMN "quantity_received" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."sales_order_return_lines" ALTER COLUMN "resolution" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."sales_order_return_lines" ALTER COLUMN "return_fee" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."sales_order_return_lines" ALTER COLUMN "putaway_status" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."sales_order_returns" ALTER COLUMN "state_code" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."sales_order_shipments" ALTER COLUMN "state_code" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."sales_orders" ALTER COLUMN "state_code" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."sales_orders" ALTER COLUMN "base_total_amount" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."sales_orders" ALTER COLUMN "exchange_rate" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."sales_orders" ALTER COLUMN "discrepancies_acknowledged" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."sales_orders" ALTER COLUMN "source" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."supplier_groups" ALTER COLUMN "early_payment_discount" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."supplier_groups" ALTER COLUMN "credit_limit" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."supplier_groups" ALTER COLUMN "is_purchasing_blocked" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."supplier_groups" ALTER COLUMN "is_payment_blocked" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."suppliers" ALTER COLUMN "is_purchasing_blocked" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."suppliers" ALTER COLUMN "state_code" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."suppliers" ALTER COLUMN "source" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."tax_categories" ALTER COLUMN "rate" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."trading_terms" ALTER COLUMN "is_active" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."transfer_order_lines" ALTER COLUMN "quantity_shipped" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."transfer_order_lines" ALTER COLUMN "quantity_received" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."transfer_order_picks" ALTER COLUMN "state_code" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."transfer_order_receipt_lines" ALTER COLUMN "putaway_status" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."transfer_order_receipts" ALTER COLUMN "state_code" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."transfer_order_shipments" ALTER COLUMN "state_code" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."transfer_orders" ALTER COLUMN "state_code" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."user_settings" ALTER COLUMN "dashboard_config" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."user_settings" ALTER COLUMN "report_configs" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."user_settings" ALTER COLUMN "preferences" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."users" ALTER COLUMN "is_active" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."webhooks" ALTER COLUMN "is_active" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "herobm_core"."zones" ALTER COLUMN "source" DROP DEFAULT;