ALTER TABLE "herobm_core"."gl_match_groups" ALTER COLUMN "match_group_id" SET DEFAULT gen_random_uuid();--> statement-breakpoint
ALTER TABLE "herobm_core"."actors" ADD CONSTRAINT "actors_referred_by_actor_id_actors_actor_id_fk" FOREIGN KEY ("referred_by_actor_id") REFERENCES "herobm_core"."actors"("actor_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "herobm_core"."actors" ADD CONSTRAINT "actors_referred_by_contact_id_contacts_contact_id_fk" FOREIGN KEY ("referred_by_contact_id") REFERENCES "herobm_core"."contacts"("contact_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "herobm_core"."bank_statement_lines" ADD CONSTRAINT "bank_statement_lines_match_group_id_gl_match_groups_match_group_id_fk" FOREIGN KEY ("match_group_id") REFERENCES "herobm_core"."gl_match_groups"("match_group_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "herobm_core"."contacts" ADD CONSTRAINT "contacts_referred_by_contact_id_contacts_contact_id_fk" FOREIGN KEY ("referred_by_contact_id") REFERENCES "herobm_core"."contacts"("contact_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "herobm_core"."gl_journal_entries" ADD CONSTRAINT "gl_journal_entries_reversed_by_gl_journal_entries_journal_entry_id_fk" FOREIGN KEY ("reversed_by") REFERENCES "herobm_core"."gl_journal_entries"("journal_entry_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "herobm_core"."gl_journal_lines" ADD CONSTRAINT "gl_journal_lines_match_group_id_gl_match_groups_match_group_id_fk" FOREIGN KEY ("match_group_id") REFERENCES "herobm_core"."gl_match_groups"("match_group_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "herobm_core"."products" ADD CONSTRAINT "products_default_sales_uom_id_product_uoms_product_uom_id_fk" FOREIGN KEY ("default_sales_uom_id") REFERENCES "herobm_core"."product_uoms"("product_uom_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "herobm_core"."products" ADD CONSTRAINT "products_default_purchase_uom_id_product_uoms_product_uom_id_fk" FOREIGN KEY ("default_purchase_uom_id") REFERENCES "herobm_core"."product_uoms"("product_uom_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_sales_orders_fulfillment_location_id" ON "herobm_core"."sales_orders" USING btree ("fulfillment_location_id");