-- Backfill / Ensure Casbin policies exist for admin and other standard roles across all system resources
INSERT INTO "herobm_core"."casbin_rule" ("ptype", "v0", "v1", "v2", "v3")
SELECT ptype, v0, v1, v2, v3 FROM (
  VALUES
    -- viewer read access
    ('p', 'viewer', 'customers', 'read', 'allow'),
    ('p', 'viewer', 'products', 'read', 'allow'),
    ('p', 'viewer', 'inventory', 'read', 'allow'),
    ('p', 'viewer', 'sales-orders', 'read', 'allow'),
    ('p', 'viewer', 'sales-returns', 'read', 'allow'),
    ('p', 'viewer', 'sales-credit-notes', 'read', 'allow'),
    ('p', 'viewer', 'purchase-orders', 'read', 'allow'),
    ('p', 'viewer', 'purchase-returns', 'read', 'allow'),
    ('p', 'viewer', 'purchase-debit-notes', 'read', 'allow'),
    ('p', 'viewer', 'suppliers', 'read', 'allow'),
    ('p', 'viewer', 'receptions', 'read', 'allow'),
    ('p', 'viewer', 'goods-received', 'read', 'allow'),
    ('p', 'viewer', 'work-orders', 'read', 'allow'),
    ('p', 'viewer', 'crm', 'read', 'allow'),
    ('p', 'viewer', 'dashboard', 'read', 'allow'),
    ('p', 'viewer', 'tax-categories', 'read', 'allow'),
    ('p', 'viewer', 'settings', 'read', 'allow'),
    ('p', 'viewer', 'report', 'read', 'allow'),
    ('p', 'viewer', 'business_report', 'read', 'allow'),
    ('p', 'viewer', 'payments', 'read', 'allow'),
    ('p', 'viewer', 'credit-control', 'read', 'allow'),
    ('p', 'viewer', 'fiscal-periods', 'read', 'allow'),

    -- admin full access
    ('p', 'admin', 'dashboard', 'read', 'allow'),
    ('p', 'admin', 'dashboard', 'write', 'allow'),
    ('p', 'admin', 'customers', 'read', 'allow'),
    ('p', 'admin', 'customers', 'write', 'allow'),
    ('p', 'admin', 'customers', 'archive', 'allow'),
    ('p', 'admin', 'crm', 'read', 'allow'),
    ('p', 'admin', 'crm', 'write', 'allow'),
    ('p', 'admin', 'crm', 'archive', 'allow'),
    ('p', 'admin', 'crm', 'delete', 'allow'),
    ('p', 'admin', 'products', 'read', 'allow'),
    ('p', 'admin', 'products', 'write', 'allow'),
    ('p', 'admin', 'products', 'archive', 'allow'),
    ('p', 'admin', 'sales-orders', 'read', 'allow'),
    ('p', 'admin', 'sales-orders', 'write', 'allow'),
    ('p', 'admin', 'sales-orders', 'archive', 'allow'),
    ('p', 'admin', 'sales-orders', 'handle', 'allow'),
    ('p', 'admin', 'sales-orders', 'invoice', 'allow'),
    ('p', 'admin', 'sales-returns', 'read', 'allow'),
    ('p', 'admin', 'sales-returns', 'write', 'allow'),
    ('p', 'admin', 'sales-returns', 'archive', 'allow'),
    ('p', 'admin', 'sales-returns', 'handle', 'allow'),
    ('p', 'admin', 'sales-returns', 'invoice', 'allow'),
    ('p', 'admin', 'sales-credit-notes', 'read', 'allow'),
    ('p', 'admin', 'sales-credit-notes', 'write', 'allow'),
    ('p', 'admin', 'sales-credit-notes', 'archive', 'allow'),
    ('p', 'admin', 'sales-credit-notes', 'invoice', 'allow'),
    ('p', 'admin', 'purchase-orders', 'read', 'allow'),
    ('p', 'admin', 'purchase-orders', 'write', 'allow'),
    ('p', 'admin', 'purchase-orders', 'archive', 'allow'),
    ('p', 'admin', 'purchase-orders', 'handle', 'allow'),
    ('p', 'admin', 'purchase-orders', 'invoice', 'allow'),
    ('p', 'admin', 'work-orders', 'read', 'allow'),
    ('p', 'admin', 'work-orders', 'write', 'allow'),
    ('p', 'admin', 'work-orders', 'archive', 'allow'),
    ('p', 'admin', 'work-orders', 'handle', 'allow'),
    ('p', 'admin', 'purchase-returns', 'read', 'allow'),
    ('p', 'admin', 'purchase-returns', 'write', 'allow'),
    ('p', 'admin', 'purchase-returns', 'archive', 'allow'),
    ('p', 'admin', 'purchase-returns', 'handle', 'allow'),
    ('p', 'admin', 'purchase-returns', 'invoice', 'allow'),
    ('p', 'admin', 'purchase-debit-notes', 'read', 'allow'),
    ('p', 'admin', 'purchase-debit-notes', 'write', 'allow'),
    ('p', 'admin', 'purchase-debit-notes', 'archive', 'allow'),
    ('p', 'admin', 'purchase-debit-notes', 'handle', 'allow'),
    ('p', 'admin', 'purchase-debit-notes', 'invoice', 'allow'),
    ('p', 'admin', 'suppliers', 'read', 'allow'),
    ('p', 'admin', 'suppliers', 'write', 'allow'),
    ('p', 'admin', 'suppliers', 'archive', 'allow'),
    ('p', 'admin', 'receptions', 'read', 'allow'),
    ('p', 'admin', 'receptions', 'write', 'allow'),
    ('p', 'admin', 'receptions', 'archive', 'allow'),
    ('p', 'admin', 'goods-received', 'read', 'allow'),
    ('p', 'admin', 'goods-received', 'write', 'allow'),
    ('p', 'admin', 'goods-received', 'archive', 'allow'),
    ('p', 'admin', 'goods-received', 'handle', 'allow'),
    ('p', 'admin', 'inventory', 'read', 'allow'),
    ('p', 'admin', 'inventory', 'write', 'allow'),
    ('p', 'admin', 'inventory', 'archive', 'allow'),
    ('p', 'admin', 'inventory', 'handle', 'allow'),
    ('p', 'admin', 'users', 'read', 'allow'),
    ('p', 'admin', 'users', 'write', 'allow'),
    ('p', 'admin', 'users', 'archive', 'allow'),
    ('p', 'admin', 'roles', 'read', 'allow'),
    ('p', 'admin', 'roles', 'write', 'allow'),
    ('p', 'admin', 'roles', 'archive', 'allow'),
    ('p', 'admin', 'settings', 'read', 'allow'),
    ('p', 'admin', 'settings', 'write', 'allow'),
    ('p', 'admin', 'settings', 'archive', 'allow'),
    ('p', 'admin', 'gl', 'read', 'allow'),
    ('p', 'admin', 'gl', 'write', 'allow'),
    ('p', 'admin', 'fiscal-periods', 'read', 'allow'),
    ('p', 'admin', 'fiscal-periods', 'write', 'allow'),
    ('p', 'admin', 'payments', 'read', 'allow'),
    ('p', 'admin', 'payments', 'write', 'allow'),
    ('p', 'admin', 'payments', 'archive', 'allow'),
    ('p', 'admin', 'credit-control', 'read', 'allow'),
    ('p', 'admin', 'credit-control', 'write', 'allow'),
    ('p', 'admin', 'report', 'read', 'allow'),
    ('p', 'admin', 'report', 'write', 'allow'),
    ('p', 'admin', 'report', 'archive', 'allow'),
    ('p', 'admin', 'business_report', 'read', 'allow'),
    ('p', 'admin', 'business_report', 'write', 'allow'),
    ('p', 'admin', 'business_report', 'archive', 'allow'),
    ('p', 'admin', 'system_logs', 'read', 'allow'),
    ('p', 'admin', 'system_logs', 'write', 'allow'),
    ('p', 'admin', 'system_logs', 'archive', 'allow'),
    ('p', 'admin', 'setup', 'read', 'allow'),
    ('p', 'admin', 'setup', 'execute', 'allow'),
    ('p', 'admin', 'import', 'read', 'allow'),
    ('p', 'admin', 'import', 'write', 'allow'),
    ('p', 'admin', 'import', 'archive', 'allow'),
    ('p', 'admin', 'api_keys', 'read', 'allow'),
    ('p', 'admin', 'api_keys', 'write', 'allow'),
    ('p', 'admin', 'api_keys', 'archive', 'allow'),
    ('p', 'admin', 'webhooks', 'read', 'allow'),
    ('p', 'admin', 'webhooks', 'write', 'allow'),
    ('p', 'admin', 'webhooks', 'archive', 'allow'),
    ('p', 'admin', 'events', 'read', 'allow'),
    ('p', 'admin', 'events', 'write', 'allow'),
    ('p', 'admin', 'events', 'archive', 'allow'),
    ('p', 'admin', 'data-export', 'read', 'allow'),
    ('p', 'admin', 'data-export', 'write', 'allow'),

    -- finance access
    ('p', 'finance', 'credit-control', 'read', 'allow'),
    ('p', 'finance', 'credit-control', 'write', 'allow'),
    ('p', 'finance', 'gl', 'read', 'allow'),
    ('p', 'finance', 'gl', 'write', 'allow'),
    ('p', 'finance', 'fiscal-periods', 'read', 'allow'),
    ('p', 'finance', 'fiscal-periods', 'write', 'allow'),
    ('p', 'finance', 'payments', 'write', 'allow'),
    ('p', 'finance', 'sales-orders', 'invoice', 'allow'),
    ('p', 'finance', 'purchase-orders', 'invoice', 'allow'),
    ('p', 'finance', 'sales-returns', 'invoice', 'allow'),
    ('p', 'finance', 'purchase-returns', 'invoice', 'allow'),
    ('p', 'finance', 'purchase-debit-notes', 'read', 'allow'),
    ('p', 'finance', 'purchase-debit-notes', 'write', 'allow'),
    ('p', 'finance', 'purchase-debit-notes', 'invoice', 'allow'),
    ('p', 'finance', 'sales-credit-notes', 'read', 'allow'),
    ('p', 'finance', 'sales-credit-notes', 'invoice', 'allow')
) AS v(ptype, v0, v1, v2, v3)
WHERE NOT EXISTS (
  SELECT 1 FROM "herobm_core"."casbin_rule" c
  WHERE c.ptype = v.ptype
    AND c.v0 = v.v0
    AND c.v1 = v.v1
    AND c.v2 = v.v2
    AND c.v3 = v.v3
);
