/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type {
  CreateDebitNoteDto,
  EmptyBodyDto,
  PurchaseDebitNoteResponseDto,
  PurchaseDebitNotesControllerFindAllParams,
  PurchaseInvoiceResponseDto
} from '../../model';

import { customFetch } from '../../mutator';

/**
 * Retrieve purchase bills for a purchase order
 * @summary Get Purchase Bills
 */
export type purchaseInvoiceControllerGetPurchaseBillsResponse200 = {
  data: PurchaseInvoiceResponseDto[]
  status: 200
}
    
export type purchaseInvoiceControllerGetPurchaseBillsResponseSuccess = (purchaseInvoiceControllerGetPurchaseBillsResponse200) & {
  headers: Headers;
};
;

export type purchaseInvoiceControllerGetPurchaseBillsResponse = (purchaseInvoiceControllerGetPurchaseBillsResponseSuccess)

export const getPurchaseInvoiceControllerGetPurchaseBillsUrl = (id: string,) => {


  

  return `/purchase-orders/${id}/invoices`
}

export const purchaseInvoiceControllerGetPurchaseBills = async (id: string, options?: RequestInit): Promise<purchaseInvoiceControllerGetPurchaseBillsResponse> => {
  
  return customFetch<purchaseInvoiceControllerGetPurchaseBillsResponse>(getPurchaseInvoiceControllerGetPurchaseBillsUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * Retrieve a list of purchase debit notes.
 * @summary Find Debit Notes
 */
export type purchaseDebitNotesControllerFindAllResponse200 = {
  data: PurchaseDebitNoteResponseDto[]
  status: 200
}
    
export type purchaseDebitNotesControllerFindAllResponseSuccess = (purchaseDebitNotesControllerFindAllResponse200) & {
  headers: Headers;
};
;

export type purchaseDebitNotesControllerFindAllResponse = (purchaseDebitNotesControllerFindAllResponseSuccess)

export const getPurchaseDebitNotesControllerFindAllUrl = (params?: PurchaseDebitNotesControllerFindAllParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/purchase-debit-notes?${stringifiedParams}` : `/purchase-debit-notes`
}

export const purchaseDebitNotesControllerFindAll = async (params?: PurchaseDebitNotesControllerFindAllParams, options?: RequestInit): Promise<purchaseDebitNotesControllerFindAllResponse> => {
  
  return customFetch<purchaseDebitNotesControllerFindAllResponse>(getPurchaseDebitNotesControllerFindAllUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * Create a new purchase debit note.
 * @summary Create Debit Note
 */
export type purchaseDebitNotesControllerCreateDebitNoteResponse201 = {
  data: PurchaseDebitNoteResponseDto
  status: 201
}
    
export type purchaseDebitNotesControllerCreateDebitNoteResponseSuccess = (purchaseDebitNotesControllerCreateDebitNoteResponse201) & {
  headers: Headers;
};
;

export type purchaseDebitNotesControllerCreateDebitNoteResponse = (purchaseDebitNotesControllerCreateDebitNoteResponseSuccess)

export const getPurchaseDebitNotesControllerCreateDebitNoteUrl = () => {


  

  return `/purchase-debit-notes`
}

export const purchaseDebitNotesControllerCreateDebitNote = async (createDebitNoteDto: CreateDebitNoteDto, options?: RequestInit): Promise<purchaseDebitNotesControllerCreateDebitNoteResponse> => {
  
  return customFetch<purchaseDebitNotesControllerCreateDebitNoteResponse>(getPurchaseDebitNotesControllerCreateDebitNoteUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createDebitNoteDto,)
  }
);}


/**
 * Retrieve a purchase debit note by ID.
 * @summary Get Debit Note
 */
export type purchaseDebitNotesControllerFindOneResponse200 = {
  data: PurchaseDebitNoteResponseDto
  status: 200
}
    
export type purchaseDebitNotesControllerFindOneResponseSuccess = (purchaseDebitNotesControllerFindOneResponse200) & {
  headers: Headers;
};
;

export type purchaseDebitNotesControllerFindOneResponse = (purchaseDebitNotesControllerFindOneResponseSuccess)

export const getPurchaseDebitNotesControllerFindOneUrl = (id: string,) => {


  

  return `/purchase-debit-notes/${id}`
}

export const purchaseDebitNotesControllerFindOne = async (id: string, options?: RequestInit): Promise<purchaseDebitNotesControllerFindOneResponse> => {
  
  return customFetch<purchaseDebitNotesControllerFindOneResponse>(getPurchaseDebitNotesControllerFindOneUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * Post an existing debit note.
 * @summary Post Debit Note
 */
export type purchaseDebitNotesControllerPostDebitNoteResponse200 = {
  data: PurchaseDebitNoteResponseDto
  status: 200
}
    
export type purchaseDebitNotesControllerPostDebitNoteResponseSuccess = (purchaseDebitNotesControllerPostDebitNoteResponse200) & {
  headers: Headers;
};
;

export type purchaseDebitNotesControllerPostDebitNoteResponse = (purchaseDebitNotesControllerPostDebitNoteResponseSuccess)

export const getPurchaseDebitNotesControllerPostDebitNoteUrl = (id: string,) => {


  

  return `/purchase-debit-notes/${id}/post`
}

export const purchaseDebitNotesControllerPostDebitNote = async (id: string,
    emptyBodyDto: EmptyBodyDto, options?: RequestInit): Promise<purchaseDebitNotesControllerPostDebitNoteResponse> => {
  
  return customFetch<purchaseDebitNotesControllerPostDebitNoteResponse>(getPurchaseDebitNotesControllerPostDebitNoteUrl(id),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      emptyBodyDto,)
  }
);}


