/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type {
  CreateProjectActorDto,
  CreateProjectContactDto,
  CreateProjectDto,
  CreateProjectNoteDto,
  EmptyBodyDto,
  ProjectNoteResponseDto,
  ProjectResponseDto,
  ProjectsControllerAddActor201,
  ProjectsControllerAddContact201,
  ProjectsControllerFindAll200,
  ProjectsControllerFindAllParams,
  ProjectsControllerRemove200,
  ProjectsControllerRemoveActor200,
  ProjectsControllerRemoveContact200,
  ProjectsControllerRemoveNote200,
  ProjectsControllerUpdateActor200,
  ProjectsControllerUpdateContact200,
  UpdateProjectActorDto,
  UpdateProjectContactDto,
  UpdateProjectDto
} from '../../model';

import { customFetch } from '../../mutator';

/**
 * Create Project
 * @summary Create Project
 */
export type projectsControllerCreateResponse201 = {
  data: ProjectResponseDto
  status: 201
}
    
export type projectsControllerCreateResponseSuccess = (projectsControllerCreateResponse201) & {
  headers: Headers;
};
;

export type projectsControllerCreateResponse = (projectsControllerCreateResponseSuccess)

export const getProjectsControllerCreateUrl = () => {


  

  return `/projects`
}

export const projectsControllerCreate = async (createProjectDto: CreateProjectDto, options?: RequestInit): Promise<projectsControllerCreateResponse> => {
  
  return customFetch<projectsControllerCreateResponse>(getProjectsControllerCreateUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createProjectDto,)
  }
);}


/**
 * Get all Projects
 * @summary Get all Projects
 */
export type projectsControllerFindAllResponse200 = {
  data: ProjectsControllerFindAll200
  status: 200
}
    
export type projectsControllerFindAllResponseSuccess = (projectsControllerFindAllResponse200) & {
  headers: Headers;
};
;

export type projectsControllerFindAllResponse = (projectsControllerFindAllResponseSuccess)

export const getProjectsControllerFindAllUrl = (params?: ProjectsControllerFindAllParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/projects?${stringifiedParams}` : `/projects`
}

export const projectsControllerFindAll = async (params?: ProjectsControllerFindAllParams, options?: RequestInit): Promise<projectsControllerFindAllResponse> => {
  
  return customFetch<projectsControllerFindAllResponse>(getProjectsControllerFindAllUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * Get Project by ID
 * @summary Get Project by ID
 */
export type projectsControllerFindOneResponse200 = {
  data: ProjectResponseDto
  status: 200
}
    
export type projectsControllerFindOneResponseSuccess = (projectsControllerFindOneResponse200) & {
  headers: Headers;
};
;

export type projectsControllerFindOneResponse = (projectsControllerFindOneResponseSuccess)

export const getProjectsControllerFindOneUrl = (id: string,) => {


  

  return `/projects/${id}`
}

export const projectsControllerFindOne = async (id: string, options?: RequestInit): Promise<projectsControllerFindOneResponse> => {
  
  return customFetch<projectsControllerFindOneResponse>(getProjectsControllerFindOneUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * Update Project
 * @summary Update Project
 */
export type projectsControllerUpdateResponse200 = {
  data: ProjectResponseDto
  status: 200
}
    
export type projectsControllerUpdateResponseSuccess = (projectsControllerUpdateResponse200) & {
  headers: Headers;
};
;

export type projectsControllerUpdateResponse = (projectsControllerUpdateResponseSuccess)

export const getProjectsControllerUpdateUrl = (id: string,) => {


  

  return `/projects/${id}`
}

export const projectsControllerUpdate = async (id: string,
    updateProjectDto: UpdateProjectDto, options?: RequestInit): Promise<projectsControllerUpdateResponse> => {
  
  return customFetch<projectsControllerUpdateResponse>(getProjectsControllerUpdateUrl(id),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateProjectDto,)
  }
);}


/**
 * Delete Project
 * @summary Delete Project
 */
export type projectsControllerRemoveResponse200 = {
  data: ProjectsControllerRemove200
  status: 200
}
    
export type projectsControllerRemoveResponseSuccess = (projectsControllerRemoveResponse200) & {
  headers: Headers;
};
;

export type projectsControllerRemoveResponse = (projectsControllerRemoveResponseSuccess)

export const getProjectsControllerRemoveUrl = (id: string,) => {


  

  return `/projects/${id}`
}

export const projectsControllerRemove = async (id: string, options?: RequestInit): Promise<projectsControllerRemoveResponse> => {
  
  return customFetch<projectsControllerRemoveResponse>(getProjectsControllerRemoveUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}


/**
 * Archives a project
 * @summary Archive Project
 */
export type projectsControllerArchiveResponse200 = {
  data: ProjectResponseDto
  status: 200
}

export type projectsControllerArchiveResponse201 = {
  data: ProjectResponseDto
  status: 201
}
    
export type projectsControllerArchiveResponseSuccess = (projectsControllerArchiveResponse200 | projectsControllerArchiveResponse201) & {
  headers: Headers;
};
;

export type projectsControllerArchiveResponse = (projectsControllerArchiveResponseSuccess)

export const getProjectsControllerArchiveUrl = (id: string,) => {


  

  return `/projects/${id}/archive`
}

export const projectsControllerArchive = async (id: string,
    emptyBodyDto: EmptyBodyDto, options?: RequestInit): Promise<projectsControllerArchiveResponse> => {
  
  return customFetch<projectsControllerArchiveResponse>(getProjectsControllerArchiveUrl(id),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      emptyBodyDto,)
  }
);}


/**
 * Unarchives a project
 * @summary Unarchive Project
 */
export type projectsControllerUnarchiveResponse200 = {
  data: ProjectResponseDto
  status: 200
}

export type projectsControllerUnarchiveResponse201 = {
  data: ProjectResponseDto
  status: 201
}
    
export type projectsControllerUnarchiveResponseSuccess = (projectsControllerUnarchiveResponse200 | projectsControllerUnarchiveResponse201) & {
  headers: Headers;
};
;

export type projectsControllerUnarchiveResponse = (projectsControllerUnarchiveResponseSuccess)

export const getProjectsControllerUnarchiveUrl = (id: string,) => {


  

  return `/projects/${id}/unarchive`
}

export const projectsControllerUnarchive = async (id: string,
    emptyBodyDto: EmptyBodyDto, options?: RequestInit): Promise<projectsControllerUnarchiveResponse> => {
  
  return customFetch<projectsControllerUnarchiveResponse>(getProjectsControllerUnarchiveUrl(id),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      emptyBodyDto,)
  }
);}


/**
 * Add Note to Project
 * @summary Add Note to Project
 */
export type projectsControllerAddNoteResponse201 = {
  data: ProjectNoteResponseDto
  status: 201
}
    
export type projectsControllerAddNoteResponseSuccess = (projectsControllerAddNoteResponse201) & {
  headers: Headers;
};
;

export type projectsControllerAddNoteResponse = (projectsControllerAddNoteResponseSuccess)

export const getProjectsControllerAddNoteUrl = (id: string,) => {


  

  return `/projects/${id}/notes`
}

export const projectsControllerAddNote = async (id: string,
    createProjectNoteDto: CreateProjectNoteDto, options?: RequestInit): Promise<projectsControllerAddNoteResponse> => {
  
  return customFetch<projectsControllerAddNoteResponse>(getProjectsControllerAddNoteUrl(id),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createProjectNoteDto,)
  }
);}


/**
 * Delete Note from Project
 * @summary Delete Note from Project
 */
export type projectsControllerRemoveNoteResponse200 = {
  data: ProjectsControllerRemoveNote200
  status: 200
}
    
export type projectsControllerRemoveNoteResponseSuccess = (projectsControllerRemoveNoteResponse200) & {
  headers: Headers;
};
;

export type projectsControllerRemoveNoteResponse = (projectsControllerRemoveNoteResponseSuccess)

export const getProjectsControllerRemoveNoteUrl = (id: string,
    noteId: string,) => {


  

  return `/projects/${id}/notes/${noteId}`
}

export const projectsControllerRemoveNote = async (id: string,
    noteId: string, options?: RequestInit): Promise<projectsControllerRemoveNoteResponse> => {
  
  return customFetch<projectsControllerRemoveNoteResponse>(getProjectsControllerRemoveNoteUrl(id,noteId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}


/**
 * Add Contact to Project
 * @summary Add Contact to Project
 */
export type projectsControllerAddContactResponse201 = {
  data: ProjectsControllerAddContact201
  status: 201
}
    
export type projectsControllerAddContactResponseSuccess = (projectsControllerAddContactResponse201) & {
  headers: Headers;
};
;

export type projectsControllerAddContactResponse = (projectsControllerAddContactResponseSuccess)

export const getProjectsControllerAddContactUrl = (id: string,) => {


  

  return `/projects/${id}/contacts`
}

export const projectsControllerAddContact = async (id: string,
    createProjectContactDto: CreateProjectContactDto, options?: RequestInit): Promise<projectsControllerAddContactResponse> => {
  
  return customFetch<projectsControllerAddContactResponse>(getProjectsControllerAddContactUrl(id),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createProjectContactDto,)
  }
);}


/**
 * Remove Contact from Project
 * @summary Remove Contact from Project
 */
export type projectsControllerRemoveContactResponse200 = {
  data: ProjectsControllerRemoveContact200
  status: 200
}
    
export type projectsControllerRemoveContactResponseSuccess = (projectsControllerRemoveContactResponse200) & {
  headers: Headers;
};
;

export type projectsControllerRemoveContactResponse = (projectsControllerRemoveContactResponseSuccess)

export const getProjectsControllerRemoveContactUrl = (id: string,
    contactId: string,) => {


  

  return `/projects/${id}/contacts/${contactId}`
}

export const projectsControllerRemoveContact = async (id: string,
    contactId: string, options?: RequestInit): Promise<projectsControllerRemoveContactResponse> => {
  
  return customFetch<projectsControllerRemoveContactResponse>(getProjectsControllerRemoveContactUrl(id,contactId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}


/**
 * Update Contact Role on Project
 * @summary Update Contact Role on Project
 */
export type projectsControllerUpdateContactResponse200 = {
  data: ProjectsControllerUpdateContact200
  status: 200
}
    
export type projectsControllerUpdateContactResponseSuccess = (projectsControllerUpdateContactResponse200) & {
  headers: Headers;
};
;

export type projectsControllerUpdateContactResponse = (projectsControllerUpdateContactResponseSuccess)

export const getProjectsControllerUpdateContactUrl = (id: string,
    contactId: string,) => {


  

  return `/projects/${id}/contacts/${contactId}`
}

export const projectsControllerUpdateContact = async (id: string,
    contactId: string,
    updateProjectContactDto: UpdateProjectContactDto, options?: RequestInit): Promise<projectsControllerUpdateContactResponse> => {
  
  return customFetch<projectsControllerUpdateContactResponse>(getProjectsControllerUpdateContactUrl(id,contactId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateProjectContactDto,)
  }
);}


/**
 * Add Actor to Project
 * @summary Add Actor to Project
 */
export type projectsControllerAddActorResponse201 = {
  data: ProjectsControllerAddActor201
  status: 201
}
    
export type projectsControllerAddActorResponseSuccess = (projectsControllerAddActorResponse201) & {
  headers: Headers;
};
;

export type projectsControllerAddActorResponse = (projectsControllerAddActorResponseSuccess)

export const getProjectsControllerAddActorUrl = (id: string,) => {


  

  return `/projects/${id}/actors`
}

export const projectsControllerAddActor = async (id: string,
    createProjectActorDto: CreateProjectActorDto, options?: RequestInit): Promise<projectsControllerAddActorResponse> => {
  
  return customFetch<projectsControllerAddActorResponse>(getProjectsControllerAddActorUrl(id),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createProjectActorDto,)
  }
);}


/**
 * Update Actor Role on Project
 * @summary Update Actor Role on Project
 */
export type projectsControllerUpdateActorResponse200 = {
  data: ProjectsControllerUpdateActor200
  status: 200
}
    
export type projectsControllerUpdateActorResponseSuccess = (projectsControllerUpdateActorResponse200) & {
  headers: Headers;
};
;

export type projectsControllerUpdateActorResponse = (projectsControllerUpdateActorResponseSuccess)

export const getProjectsControllerUpdateActorUrl = (id: string,
    actorId: string,) => {


  

  return `/projects/${id}/actors/${actorId}`
}

export const projectsControllerUpdateActor = async (id: string,
    actorId: string,
    updateProjectActorDto: UpdateProjectActorDto, options?: RequestInit): Promise<projectsControllerUpdateActorResponse> => {
  
  return customFetch<projectsControllerUpdateActorResponse>(getProjectsControllerUpdateActorUrl(id,actorId),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateProjectActorDto,)
  }
);}


/**
 * Remove Actor from Project
 * @summary Remove Actor from Project
 */
export type projectsControllerRemoveActorResponse200 = {
  data: ProjectsControllerRemoveActor200
  status: 200
}
    
export type projectsControllerRemoveActorResponseSuccess = (projectsControllerRemoveActorResponse200) & {
  headers: Headers;
};
;

export type projectsControllerRemoveActorResponse = (projectsControllerRemoveActorResponseSuccess)

export const getProjectsControllerRemoveActorUrl = (id: string,
    actorId: string,) => {


  

  return `/projects/${id}/actors/${actorId}`
}

export const projectsControllerRemoveActor = async (id: string,
    actorId: string, options?: RequestInit): Promise<projectsControllerRemoveActorResponse> => {
  
  return customFetch<projectsControllerRemoveActorResponse>(getProjectsControllerRemoveActorUrl(id,actorId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}


