/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type {
  CreateCrmActivityDto,
  CrmActivitiesControllerFindAll200,
  CrmActivitiesControllerFindAllParams,
  CrmActivitiesControllerRemove200,
  CrmActivityResponseDto,
  EmptyBodyDto,
  UpdateCrmActivityDto
} from '../../model';

import { customFetch } from '../../mutator';

/**
 * Logs a new interaction (Call, Meeting, Email, Task) against an Actor, Contact, or Project.
 * @summary Create CRM Activity
 */
export type crmActivitiesControllerCreateResponse201 = {
  data: CrmActivityResponseDto
  status: 201
}
    
export type crmActivitiesControllerCreateResponseSuccess = (crmActivitiesControllerCreateResponse201) & {
  headers: Headers;
};
;

export type crmActivitiesControllerCreateResponse = (crmActivitiesControllerCreateResponseSuccess)

export const getCrmActivitiesControllerCreateUrl = () => {


  

  return `/crm-activities`
}

export const crmActivitiesControllerCreate = async (createCrmActivityDto: CreateCrmActivityDto, options?: RequestInit): Promise<crmActivitiesControllerCreateResponse> => {
  
  return customFetch<crmActivitiesControllerCreateResponse>(getCrmActivitiesControllerCreateUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createCrmActivityDto,)
  }
);}


/**
 * Retrieves CRM activities and tasks with filtering by entity, assignee, and status.
 * @summary List CRM Activities
 */
export type crmActivitiesControllerFindAllResponse200 = {
  data: CrmActivitiesControllerFindAll200
  status: 200
}
    
export type crmActivitiesControllerFindAllResponseSuccess = (crmActivitiesControllerFindAllResponse200) & {
  headers: Headers;
};
;

export type crmActivitiesControllerFindAllResponse = (crmActivitiesControllerFindAllResponseSuccess)

export const getCrmActivitiesControllerFindAllUrl = (params?: CrmActivitiesControllerFindAllParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/crm-activities?${stringifiedParams}` : `/crm-activities`
}

export const crmActivitiesControllerFindAll = async (params?: CrmActivitiesControllerFindAllParams, options?: RequestInit): Promise<crmActivitiesControllerFindAllResponse> => {
  
  return customFetch<crmActivitiesControllerFindAllResponse>(getCrmActivitiesControllerFindAllUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * Retrieves a single CRM activity by unique identifier.
 * @summary Get CRM Activity
 */
export type crmActivitiesControllerFindOneResponse200 = {
  data: CrmActivityResponseDto
  status: 200
}
    
export type crmActivitiesControllerFindOneResponseSuccess = (crmActivitiesControllerFindOneResponse200) & {
  headers: Headers;
};
;

export type crmActivitiesControllerFindOneResponse = (crmActivitiesControllerFindOneResponseSuccess)

export const getCrmActivitiesControllerFindOneUrl = (id: string,) => {


  

  return `/crm-activities/${id}`
}

export const crmActivitiesControllerFindOne = async (id: string, options?: RequestInit): Promise<crmActivitiesControllerFindOneResponse> => {
  
  return customFetch<crmActivitiesControllerFindOneResponse>(getCrmActivitiesControllerFindOneUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * Modifies an existing interaction or task.
 * @summary Update CRM Activity
 */
export type crmActivitiesControllerUpdateResponse200 = {
  data: CrmActivityResponseDto
  status: 200
}
    
export type crmActivitiesControllerUpdateResponseSuccess = (crmActivitiesControllerUpdateResponse200) & {
  headers: Headers;
};
;

export type crmActivitiesControllerUpdateResponse = (crmActivitiesControllerUpdateResponseSuccess)

export const getCrmActivitiesControllerUpdateUrl = (id: string,) => {


  

  return `/crm-activities/${id}`
}

export const crmActivitiesControllerUpdate = async (id: string,
    updateCrmActivityDto: UpdateCrmActivityDto, options?: RequestInit): Promise<crmActivitiesControllerUpdateResponse> => {
  
  return customFetch<crmActivitiesControllerUpdateResponse>(getCrmActivitiesControllerUpdateUrl(id),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateCrmActivityDto,)
  }
);}


/**
 * Permanently removes a CRM activity or task.
 * @summary Delete CRM Activity
 */
export type crmActivitiesControllerRemoveResponse200 = {
  data: CrmActivitiesControllerRemove200
  status: 200
}
    
export type crmActivitiesControllerRemoveResponseSuccess = (crmActivitiesControllerRemoveResponse200) & {
  headers: Headers;
};
;

export type crmActivitiesControllerRemoveResponse = (crmActivitiesControllerRemoveResponseSuccess)

export const getCrmActivitiesControllerRemoveUrl = (id: string,) => {


  

  return `/crm-activities/${id}`
}

export const crmActivitiesControllerRemove = async (id: string, options?: RequestInit): Promise<crmActivitiesControllerRemoveResponse> => {
  
  return customFetch<crmActivitiesControllerRemoveResponse>(getCrmActivitiesControllerRemoveUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}


/**
 * Quickly marks a CRM task as completed.
 * @summary Complete Task
 */
export type crmActivitiesControllerCompleteResponse200 = {
  data: CrmActivityResponseDto
  status: 200
}
    
export type crmActivitiesControllerCompleteResponseSuccess = (crmActivitiesControllerCompleteResponse200) & {
  headers: Headers;
};
;

export type crmActivitiesControllerCompleteResponse = (crmActivitiesControllerCompleteResponseSuccess)

export const getCrmActivitiesControllerCompleteUrl = (id: string,) => {


  

  return `/crm-activities/${id}/complete`
}

export const crmActivitiesControllerComplete = async (id: string,
    emptyBodyDto: EmptyBodyDto, options?: RequestInit): Promise<crmActivitiesControllerCompleteResponse> => {
  
  return customFetch<crmActivitiesControllerCompleteResponse>(getCrmActivitiesControllerCompleteUrl(id),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      emptyBodyDto,)
  }
);}


