// ---------------------------------------------------------------------------
// Event Type Registry — Single source of truth for all event type strings
// ---------------------------------------------------------------------------

/**
 * Aggregate types map to specific per-entity event tables.
 * 'system' routes to the system_events table for cross-cutting concerns.
 */
export const EntityType = {
  SALES_ORDER: 'sales_order',
  PURCHASE_ORDER: 'purchase_order',
  PRODUCT: 'product',
  CUSTOMER: 'customer',
  SUPPLIER: 'supplier',
  PRODUCT_SUPPLIER: 'product_supplier',
  SHIPMENT: 'shipment',
  PAYMENT: 'payment',
  TRANSFER_ORDER: 'transfer_order',
  SALES_INVOICE: 'sales_invoice',
  SALES_RETURN: 'sales_return',
  PURCHASE_INVOICE: 'purchase_invoice',
  PURCHASE_RETURN: 'purchase_return',
  SYSTEM: 'system', // the entire system (for system-wide events or generic stuff)
  WAREHOUSE: 'warehouse', // warehouse operations
  INVENTORY_LEDGER: 'inventory_ledger',
  GENERAL_LEDGER: 'general_ledger',
  EMAIL: 'email',
  BUSINESS_REPORT: 'business_report',
  INTEGRATION: 'integration',

  // ── Auxiliary / Configuration Entities ─────────────────────────────
  USER: 'user',
  API_KEY: 'api_key', // TEST_CREDENTIAL
  WEBHOOK: 'webhook',
  APP_SETTINGS: 'app_settings',
  GL_SETTINGS: 'gl_settings',
  MACRO: 'macro',

  RECONCILIATION_RULE: 'reconciliation_rule',
  BANK_STATEMENT_LINE: 'bank_statement_line',
  GL_MATCH_GROUP: 'gl_match_group',
  GL_RECONCILIATION: 'gl_reconciliation',
  CSV_MAPPING_PROFILE: 'csv_mapping_profile',

  PRODUCT_GROUP: 'product_group',
  CUSTOMER_GROUP: 'customer_group',
  SUPPLIER_GROUP: 'supplier_group',

  TAX_CATEGORY: 'tax_category',
  TAX_POSITION: 'tax_position',
  TAX_POSITION_MAPPING: 'tax_position_mapping',
  EXCHANGE_RATE: 'exchange_rate',
  COST_CENTER: 'cost_center',
  ACTIVITY: 'activity',
  GL_ACCOUNT: 'gl_account',

  LOCATION: 'location',
  ZONE: 'zone',
  BIN: 'bin',
} as const;

export type EntityTypeValue = (typeof EntityType)[keyof typeof EntityType];

import {
  SALES_ORDER_STATE,
  CUSTOMER_STATE,
  PURCHASE_ORDER_STATE,
} from '@herobm/shared';

/**
 * All known event types across the platform.
 * Grouped by domain for readability.
 */
export const EventType = {
  // ── Lifecycle (shared across entities) ──────────────────────────────
  CREATED: 'created',
  UPDATED: 'updated',
  STATUS_CHANGED: 'status_changed',
  ARCHIVED: SALES_ORDER_STATE.ARCHIVED,
  UNARCHIVED: 'unarchived',
  DELETED: 'deleted',

  // ── Line operations ─────────────────────────────────────────────────
  LINE_ADDED: 'line_added',
  LINE_UPDATED: 'line_updated',
  LINE_REMOVED: 'line_removed',
  POST_CONFIRMATION_LINE_ADDED: 'post_confirmation_line_added',

  // ── Sales domain ────────────────────────────────────────────────────
  SALES_INVOICED: 'sales_invoiced',
  STOCK_DISPATCHED: 'stock_dispatched',
  BACKORDERS_ALLOCATED: 'backorders_allocated',
  CREDIT_NOTE_POSTED: 'credit_note_posted',
  AUTO_STATUS_CHANGED: 'auto_status_changed',
  TAX_CALCULATED: 'tax_calculated',

  // ── Procurement domain ──────────────────────────────────────────────
  PURCHASE_INVOICED: 'purchase_invoiced',
  DEMAND_ALLOCATED: 'demand_allocated',
  DEMAND_UNALLOCATED: 'demand_unallocated',
  DEMAND_REALLOCATED: 'demand_reallocated',
  RECEIPT_MATCHED: 'receipt_matched',
  RECEIPT_UNMATCHED: 'receipt_unmatched',
  INVOICE_MATCHED: 'invoice_matched',
  INVOICE_UNMATCHED: 'invoice_unmatched',
  ORDER_LINKED: 'order_linked',
  ORDER_UNLINKED: 'order_unlinked',
  RETURN_CREATED: 'return_created',
  RETURN_UPDATED: 'return_updated',
  RETURN_PROCESSED: 'return_processed',
  RETURN_LINE_ADDED: 'return_line_added',
  RETURN_LINE_UPDATED: 'return_line_updated',
  RETURN_LINE_REMOVED: 'return_line_removed',
  LOCATION_DISCREPANCY_WARNING: 'location_discrepancy_warning',
  OVER_RECEIVED_WARNING: 'over_received_warning',
  PRICE_DISCREPANCY_WARNING: 'price_discrepancy_warning',

  // ── Warehouse domain ────────────────────────────────────────────────
  PICK_CREATED: 'pick_created',
  PICK_CANCELLED: 'pick_cancelled',
  PUTAWAY_COMPLETED: 'putaway_completed',
  RECEIPT_CREATED: 'receipt_created',
  RECEIPT_STATUS_CHANGED: 'receipt_status_changed',
  ENTRY_POSTED: 'entry_posted',
  STOCK_MOVED: 'stock_moved',

  // ── Product domain ──────────────────────────────────────────────────
  LINKED: 'linked',
  UNLINKED: 'unlinked',
  UOM_ADDED: 'uom_added',
  UOM_REMOVED: 'uom_removed',

  // ── Shipments domain ──────────────────────────────────────────────────
  SHIPMENT_CREATED: 'shipment_created',
  SHIPMENT_UPDATED: 'shipment_updated',
  SHIPMENT_LINE_ADDED: 'shipment_line_added',
  SHIPMENT_LINE_UPDATED: 'shipment_line_updated',
  SHIPMENT_LINE_REMOVED: 'shipment_line_removed',

  // ── Quote domain ──────────────────────────────────────────────────

  // ── Supplier domain ─────────────────────────────────────────────────
  ADDED_EXPIRY: 'added_expiry',
  UPDATED_EXPIRY: 'updated_expiry',
  DELETED_EXPIRY: 'deleted_expiry',

  // ── System domain ───────────────────────────────────────────────────
  GL_POSTED: 'gl_posted',
  STOCK_ADJUSTED: 'stock_adjusted',

  // ── Email domain ────────────────────────────────────────────────────
  QUEUED: 'queued',
  SENT: 'sent',
  FAILED: 'failed',

  // ── Payment domain ──────────────────────────────────────────────────
  PAYMENT_SUBMITTED: 'payment_submitted',
  PAYMENT_ALLOCATED: 'payment_allocated',
  PAYMENT_CANCELLED: 'payment_cancelled',
} as const;

export type EventTypeValue = (typeof EventType)[keyof typeof EventType];

/**
 * Outbox gating: which event types should be enqueued for integration relay.
 * Only events in this set produce an outbox row in addition to the audit row.
 */
export const OUTBOX_EVENT_TYPES: ReadonlySet<string> = new Set([
  'activity.created',
  'activity.deleted',
  'activity.updated',
  'api_key.created',
  'api_key.deleted',
  'app_settings.updated',
  'bank_statement_line.created',
  'bank_statement_line.deleted',
  'bank_statement_line.updated',
  'bin.created',
  'bin.deleted',
  'bin.updated',
  'business_report.created',
  'business_report.deleted',
  'business_report.updated',
  'cost_center.created',
  'cost_center.deleted',
  'cost_center.updated',
  'csv_mapping_profile.created',
  'csv_mapping_profile.deleted',
  'csv_mapping_profile.updated',
  'customer.archived',
  'customer.created',
  'customer.status_changed',
  'customer.unarchived',
  'customer.updated',
  'customer_group.created',
  'customer_group.deleted',
  'customer_group.updated',
  'email.queued',
  'exchange_rate.created',
  'exchange_rate.deleted',
  'exchange_rate.updated',
  'general_ledger.entry_posted',
  'gl_account.created',
  'gl_account.updated',
  'gl_match_group.created',
  'gl_match_group.deleted',
  'gl_reconciliation.created',
  'gl_reconciliation.deleted',
  'gl_reconciliation.updated',
  'gl_settings.updated',
  'integration.updated',
  'inventory_ledger.entry_posted',
  'location.created',
  'location.deleted',
  'location.updated',
  'macro.created',
  'macro.deleted',
  'macro.updated',
  'payment.created',
  'payment.payment_allocated',
  'payment.status_changed',
  'payment.updated',
  'payment.payment_cancelled',
  'product.archived',
  'product.created',
  'product.status_changed',
  'product.unarchived',
  'product.uom_added',
  'product.uom_removed',
  'product.updated',
  'product_group.created',
  'product_group.deleted',
  'product_group.updated',
  'product_supplier.linked',
  'product_supplier.unlinked',
  'purchase_invoice.status_changed',
  'purchase_invoice.updated',
  'purchase_order.archived',
  'purchase_order.created',
  'purchase_order.demand_allocated',
  'purchase_order.demand_unallocated',
  'purchase_order.invoice_matched',
  'purchase_order.invoice_unmatched',
  'purchase_order.return_created',
  'purchase_order.status_changed',
  'purchase_order.unarchived',
  'purchase_order.updated',
  'purchase_return.status_changed',
  'reconciliation_rule.created',
  'reconciliation_rule.deleted',
  'reconciliation_rule.updated',
  'sales_invoice.credit_note_posted',
  'sales_invoice.status_changed',
  'sales_order.archived',
  'sales_order.auto_status_changed',
  'sales_order.backorders_allocated',
  'sales_order.created',
  'sales_order.credit_note_posted',
  'sales_order.demand_allocated',
  'sales_order.demand_reallocated',
  'sales_order.demand_unallocated',
  'sales_order.post_confirmation_line_added',

  'sales_order.return_created',
  'sales_order.return_line_added',
  'sales_order.return_line_removed',
  'sales_order.return_line_updated',
  'sales_order.return_updated',
  'sales_order.sales_invoiced',
  'sales_order.status_changed',
  'sales_order.tax_calculated',
  'sales_order.unarchived',
  'sales_order.updated',
  'sales_return.status_changed',
  'sales_return.updated',
  'shipment.shipment_created',
  'shipment.shipment_line_added',
  'shipment.shipment_line_removed',
  'shipment.shipment_line_updated',
  'shipment.shipment_updated',
  'supplier.added_expiry',
  'supplier.archived',
  'supplier.created',
  'supplier.deleted_expiry',
  'supplier.status_changed',
  'supplier.unarchived',
  'supplier.updated',
  'supplier.updated_expiry',
  'supplier_group.created',
  'supplier_group.deleted',
  'supplier_group.updated',
  'system.receipt_matched',
  'system.receipt_unmatched',
  'system.updated',
  'tax_category.created',
  'tax_category.deleted',
  'tax_category.updated',
  'tax_position.created',
  'tax_position.deleted',
  'tax_position.updated',
  'tax_position_mapping.created',
  'tax_position_mapping.deleted',
  'transfer_order.created',
  'transfer_order.status_changed',
  'transfer_order.stock_dispatched',
  'transfer_order.updated',
  'user.created',
  'user.deleted',
  'user.status_changed',
  'user.updated',
  'warehouse.pick_cancelled',
  'warehouse.pick_created',
  'warehouse.putaway_completed',
  'warehouse.receipt_created',
  'warehouse.receipt_status_changed',
  'warehouse.shipment_dispatched',
  'warehouse.shipment_status_changed',
  'warehouse.stock_moved',
  'webhook.created',
  'webhook.deleted',
  'webhook.updated',
  'zone.created',
  'zone.deleted',
  'zone.updated',
]);
