/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type {
  CreateSupplierDto,
  CreateSupplierExpiryDto,
  CreateSupplierGroupDto,
  EmptyBodyDto,
  SupplierGroupResponseDto,
  SupplierGroupsControllerFindAllParams,
  SupplierGroupsControllerFindOneParams,
  SupplierResponseDto,
  SuppliersControllerFindAll200,
  SuppliersControllerFindAllParams,
  SuppliersControllerFindByProduct200,
  SuppliersControllerFindByProductParams,
  SuppliersControllerFindOneParams,
  SuppliersControllerFindSupplierExpiries200,
  SuppliersControllerFindSupplierExpiriesParams,
  SuppliersControllerFindSupplierProducts200,
  SuppliersControllerFindSupplierProductsParams,
  SuppliersControllerGetAgedBalances200,
  SuppliersControllerGetAgedBalancesParams,
  UpdateSupplierDto,
  UpdateSupplierExpiryDto,
  UpdateSupplierGroupDto
} from '../../model';

import { customFetch } from '../../mutator';

/**
 * Retrieve a paginated list of all suppliers.
 * @summary List Suppliers
 */
export type suppliersControllerFindAllResponse200 = {
  data: SuppliersControllerFindAll200
  status: 200
}
    
export type suppliersControllerFindAllResponseSuccess = (suppliersControllerFindAllResponse200) & {
  headers: Headers;
};
;

export type suppliersControllerFindAllResponse = (suppliersControllerFindAllResponseSuccess)

export const getSuppliersControllerFindAllUrl = (params?: SuppliersControllerFindAllParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/suppliers?${stringifiedParams}` : `/suppliers`
}

export const suppliersControllerFindAll = async (params?: SuppliersControllerFindAllParams, options?: RequestInit): Promise<suppliersControllerFindAllResponse> => {
  
  return customFetch<suppliersControllerFindAllResponse>(getSuppliersControllerFindAllUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * Register a new supplier.
 * @summary Create Supplier
 */
export type suppliersControllerCreateResponse201 = {
  data: SupplierResponseDto
  status: 201
}
    
export type suppliersControllerCreateResponseSuccess = (suppliersControllerCreateResponse201) & {
  headers: Headers;
};
;

export type suppliersControllerCreateResponse = (suppliersControllerCreateResponseSuccess)

export const getSuppliersControllerCreateUrl = () => {


  

  return `/suppliers`
}

export const suppliersControllerCreate = async (createSupplierDto: CreateSupplierDto, options?: RequestInit): Promise<suppliersControllerCreateResponse> => {
  
  return customFetch<suppliersControllerCreateResponse>(getSuppliersControllerCreateUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createSupplierDto,)
  }
);}


/**
 * Retrieve aged balances for all suppliers with outstanding invoices.
 * @summary Get Aged Balances
 */
export type suppliersControllerGetAgedBalancesResponse200 = {
  data: SuppliersControllerGetAgedBalances200
  status: 200
}
    
export type suppliersControllerGetAgedBalancesResponseSuccess = (suppliersControllerGetAgedBalancesResponse200) & {
  headers: Headers;
};
;

export type suppliersControllerGetAgedBalancesResponse = (suppliersControllerGetAgedBalancesResponseSuccess)

export const getSuppliersControllerGetAgedBalancesUrl = (params?: SuppliersControllerGetAgedBalancesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/suppliers/aged-balances?${stringifiedParams}` : `/suppliers/aged-balances`
}

export const suppliersControllerGetAgedBalances = async (params?: SuppliersControllerGetAgedBalancesParams, options?: RequestInit): Promise<suppliersControllerGetAgedBalancesResponse> => {
  
  return customFetch<suppliersControllerGetAgedBalancesResponse>(getSuppliersControllerGetAgedBalancesUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * Retrieve suppliers that supply a specific product.
 * @summary List Product Suppliers
 */
export type suppliersControllerFindByProductResponse200 = {
  data: SuppliersControllerFindByProduct200
  status: 200
}
    
export type suppliersControllerFindByProductResponseSuccess = (suppliersControllerFindByProductResponse200) & {
  headers: Headers;
};
;

export type suppliersControllerFindByProductResponse = (suppliersControllerFindByProductResponseSuccess)

export const getSuppliersControllerFindByProductUrl = (productId: string,
    params?: SuppliersControllerFindByProductParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/suppliers/by-product/${productId}?${stringifiedParams}` : `/suppliers/by-product/${productId}`
}

export const suppliersControllerFindByProduct = async (productId: string,
    params?: SuppliersControllerFindByProductParams, options?: RequestInit): Promise<suppliersControllerFindByProductResponse> => {
  
  return customFetch<suppliersControllerFindByProductResponse>(getSuppliersControllerFindByProductUrl(productId,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * Retrieve detailed information for a specific supplier.
 * @summary Get Supplier
 */
export type suppliersControllerFindOneResponse200 = {
  data: SupplierResponseDto
  status: 200
}
    
export type suppliersControllerFindOneResponseSuccess = (suppliersControllerFindOneResponse200) & {
  headers: Headers;
};
;

export type suppliersControllerFindOneResponse = (suppliersControllerFindOneResponseSuccess)

export const getSuppliersControllerFindOneUrl = (id: string,
    params?: SuppliersControllerFindOneParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/suppliers/${id}?${stringifiedParams}` : `/suppliers/${id}`
}

export const suppliersControllerFindOne = async (id: string,
    params?: SuppliersControllerFindOneParams, options?: RequestInit): Promise<suppliersControllerFindOneResponse> => {
  
  return customFetch<suppliersControllerFindOneResponse>(getSuppliersControllerFindOneUrl(id,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * Modify the details of an existing supplier.
 * @summary Update Supplier
 */
export type suppliersControllerUpdateResponse200 = {
  data: SupplierResponseDto
  status: 200
}
    
export type suppliersControllerUpdateResponseSuccess = (suppliersControllerUpdateResponse200) & {
  headers: Headers;
};
;

export type suppliersControllerUpdateResponse = (suppliersControllerUpdateResponseSuccess)

export const getSuppliersControllerUpdateUrl = (id: string,) => {


  

  return `/suppliers/${id}`
}

export const suppliersControllerUpdate = async (id: string,
    updateSupplierDto: UpdateSupplierDto, options?: RequestInit): Promise<suppliersControllerUpdateResponse> => {
  
  return customFetch<suppliersControllerUpdateResponse>(getSuppliersControllerUpdateUrl(id),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateSupplierDto,)
  }
);}


/**
 * Retrieve a list of products provided by a specific supplier.
 * @summary List Supplier Products
 */
export type suppliersControllerFindSupplierProductsResponse200 = {
  data: SuppliersControllerFindSupplierProducts200
  status: 200
}
    
export type suppliersControllerFindSupplierProductsResponseSuccess = (suppliersControllerFindSupplierProductsResponse200) & {
  headers: Headers;
};
;

export type suppliersControllerFindSupplierProductsResponse = (suppliersControllerFindSupplierProductsResponseSuccess)

export const getSuppliersControllerFindSupplierProductsUrl = (id: string,
    params?: SuppliersControllerFindSupplierProductsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/suppliers/${id}/products?${stringifiedParams}` : `/suppliers/${id}/products`
}

export const suppliersControllerFindSupplierProducts = async (id: string,
    params?: SuppliersControllerFindSupplierProductsParams, options?: RequestInit): Promise<suppliersControllerFindSupplierProductsResponse> => {
  
  return customFetch<suppliersControllerFindSupplierProductsResponse>(getSuppliersControllerFindSupplierProductsUrl(id,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * Mark a supplier as archived.
 * @summary Archive Supplier
 */
export type suppliersControllerArchiveResponse201 = {
  data: SupplierResponseDto
  status: 201
}
    
export type suppliersControllerArchiveResponseSuccess = (suppliersControllerArchiveResponse201) & {
  headers: Headers;
};
;

export type suppliersControllerArchiveResponse = (suppliersControllerArchiveResponseSuccess)

export const getSuppliersControllerArchiveUrl = (id: string,) => {


  

  return `/suppliers/${id}/archive`
}

export const suppliersControllerArchive = async (id: string,
    emptyBodyDto: EmptyBodyDto, options?: RequestInit): Promise<suppliersControllerArchiveResponse> => {
  
  return customFetch<suppliersControllerArchiveResponse>(getSuppliersControllerArchiveUrl(id),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      emptyBodyDto,)
  }
);}


/**
 * Restore an archived supplier to active status.
 * @summary Unarchive Supplier
 */
export type suppliersControllerUnarchiveResponse201 = {
  data: SupplierResponseDto
  status: 201
}
    
export type suppliersControllerUnarchiveResponseSuccess = (suppliersControllerUnarchiveResponse201) & {
  headers: Headers;
};
;

export type suppliersControllerUnarchiveResponse = (suppliersControllerUnarchiveResponseSuccess)

export const getSuppliersControllerUnarchiveUrl = (id: string,) => {


  

  return `/suppliers/${id}/unarchive`
}

export const suppliersControllerUnarchive = async (id: string,
    emptyBodyDto: EmptyBodyDto, options?: RequestInit): Promise<suppliersControllerUnarchiveResponse> => {
  
  return customFetch<suppliersControllerUnarchiveResponse>(getSuppliersControllerUnarchiveUrl(id),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      emptyBodyDto,)
  }
);}


/**
 * Retrieve expiry records for a specific supplier.
 * @summary List Expiries
 */
export type suppliersControllerFindSupplierExpiriesResponse200 = {
  data: SuppliersControllerFindSupplierExpiries200
  status: 200
}
    
export type suppliersControllerFindSupplierExpiriesResponseSuccess = (suppliersControllerFindSupplierExpiriesResponse200) & {
  headers: Headers;
};
;

export type suppliersControllerFindSupplierExpiriesResponse = (suppliersControllerFindSupplierExpiriesResponseSuccess)

export const getSuppliersControllerFindSupplierExpiriesUrl = (id: string,
    params?: SuppliersControllerFindSupplierExpiriesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/suppliers/${id}/expiries?${stringifiedParams}` : `/suppliers/${id}/expiries`
}

export const suppliersControllerFindSupplierExpiries = async (id: string,
    params?: SuppliersControllerFindSupplierExpiriesParams, options?: RequestInit): Promise<suppliersControllerFindSupplierExpiriesResponse> => {
  
  return customFetch<suppliersControllerFindSupplierExpiriesResponse>(getSuppliersControllerFindSupplierExpiriesUrl(id,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * Add an expiry record for a specific supplier.
 * @summary Create Expiry
 */
export type suppliersControllerCreateExpiryResponse201 = {
  data: SupplierResponseDto
  status: 201
}
    
export type suppliersControllerCreateExpiryResponseSuccess = (suppliersControllerCreateExpiryResponse201) & {
  headers: Headers;
};
;

export type suppliersControllerCreateExpiryResponse = (suppliersControllerCreateExpiryResponseSuccess)

export const getSuppliersControllerCreateExpiryUrl = (id: string,) => {


  

  return `/suppliers/${id}/expiries`
}

export const suppliersControllerCreateExpiry = async (id: string,
    createSupplierExpiryDto: CreateSupplierExpiryDto, options?: RequestInit): Promise<suppliersControllerCreateExpiryResponse> => {
  
  return customFetch<suppliersControllerCreateExpiryResponse>(getSuppliersControllerCreateExpiryUrl(id),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createSupplierExpiryDto,)
  }
);}


/**
 * Modify an existing expiry record for a supplier.
 * @summary Update Expiry
 */
export type suppliersControllerUpdateExpiryResponse200 = {
  data: SupplierResponseDto
  status: 200
}
    
export type suppliersControllerUpdateExpiryResponseSuccess = (suppliersControllerUpdateExpiryResponse200) & {
  headers: Headers;
};
;

export type suppliersControllerUpdateExpiryResponse = (suppliersControllerUpdateExpiryResponseSuccess)

export const getSuppliersControllerUpdateExpiryUrl = (id: string,
    expiryId: string,) => {


  

  return `/suppliers/${id}/expiries/${expiryId}`
}

export const suppliersControllerUpdateExpiry = async (id: string,
    expiryId: string,
    updateSupplierExpiryDto: UpdateSupplierExpiryDto, options?: RequestInit): Promise<suppliersControllerUpdateExpiryResponse> => {
  
  return customFetch<suppliersControllerUpdateExpiryResponse>(getSuppliersControllerUpdateExpiryUrl(id,expiryId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateSupplierExpiryDto,)
  }
);}


/**
 * Remove an expiry record from a supplier.
 * @summary Delete Expiry
 */
export type suppliersControllerDeleteExpiryResponse200 = {
  data: SupplierResponseDto
  status: 200
}
    
export type suppliersControllerDeleteExpiryResponseSuccess = (suppliersControllerDeleteExpiryResponse200) & {
  headers: Headers;
};
;

export type suppliersControllerDeleteExpiryResponse = (suppliersControllerDeleteExpiryResponseSuccess)

export const getSuppliersControllerDeleteExpiryUrl = (id: string,
    expiryId: string,) => {


  

  return `/suppliers/${id}/expiries/${expiryId}`
}

export const suppliersControllerDeleteExpiry = async (id: string,
    expiryId: string, options?: RequestInit): Promise<suppliersControllerDeleteExpiryResponse> => {
  
  return customFetch<suppliersControllerDeleteExpiryResponse>(getSuppliersControllerDeleteExpiryUrl(id,expiryId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}


/**
 * Retrieve a list of all supplier groups.
 * @summary List Supplier Groups
 */
export type supplierGroupsControllerFindAllResponse200 = {
  data: SupplierGroupResponseDto[]
  status: 200
}
    
export type supplierGroupsControllerFindAllResponseSuccess = (supplierGroupsControllerFindAllResponse200) & {
  headers: Headers;
};
;

export type supplierGroupsControllerFindAllResponse = (supplierGroupsControllerFindAllResponseSuccess)

export const getSupplierGroupsControllerFindAllUrl = (params?: SupplierGroupsControllerFindAllParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/supplier-groups?${stringifiedParams}` : `/supplier-groups`
}

export const supplierGroupsControllerFindAll = async (params?: SupplierGroupsControllerFindAllParams, options?: RequestInit): Promise<supplierGroupsControllerFindAllResponse> => {
  
  return customFetch<supplierGroupsControllerFindAllResponse>(getSupplierGroupsControllerFindAllUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * Create a new supplier group.
 * @summary Create Supplier Group
 */
export type supplierGroupsControllerCreateResponse201 = {
  data: SupplierGroupResponseDto
  status: 201
}
    
export type supplierGroupsControllerCreateResponseSuccess = (supplierGroupsControllerCreateResponse201) & {
  headers: Headers;
};
;

export type supplierGroupsControllerCreateResponse = (supplierGroupsControllerCreateResponseSuccess)

export const getSupplierGroupsControllerCreateUrl = () => {


  

  return `/supplier-groups`
}

export const supplierGroupsControllerCreate = async (createSupplierGroupDto: CreateSupplierGroupDto, options?: RequestInit): Promise<supplierGroupsControllerCreateResponse> => {
  
  return customFetch<supplierGroupsControllerCreateResponse>(getSupplierGroupsControllerCreateUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createSupplierGroupDto,)
  }
);}


/**
 * Retrieve detailed information for a specific supplier group.
 * @summary Get Supplier Group
 */
export type supplierGroupsControllerFindOneResponse200 = {
  data: SupplierGroupResponseDto
  status: 200
}
    
export type supplierGroupsControllerFindOneResponseSuccess = (supplierGroupsControllerFindOneResponse200) & {
  headers: Headers;
};
;

export type supplierGroupsControllerFindOneResponse = (supplierGroupsControllerFindOneResponseSuccess)

export const getSupplierGroupsControllerFindOneUrl = (id: string,
    params?: SupplierGroupsControllerFindOneParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/supplier-groups/${id}?${stringifiedParams}` : `/supplier-groups/${id}`
}

export const supplierGroupsControllerFindOne = async (id: string,
    params?: SupplierGroupsControllerFindOneParams, options?: RequestInit): Promise<supplierGroupsControllerFindOneResponse> => {
  
  return customFetch<supplierGroupsControllerFindOneResponse>(getSupplierGroupsControllerFindOneUrl(id,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * Modify the details of an existing supplier group.
 * @summary Update Supplier Group
 */
export type supplierGroupsControllerUpdateResponse200 = {
  data: SupplierGroupResponseDto
  status: 200
}
    
export type supplierGroupsControllerUpdateResponseSuccess = (supplierGroupsControllerUpdateResponse200) & {
  headers: Headers;
};
;

export type supplierGroupsControllerUpdateResponse = (supplierGroupsControllerUpdateResponseSuccess)

export const getSupplierGroupsControllerUpdateUrl = (id: string,) => {


  

  return `/supplier-groups/${id}`
}

export const supplierGroupsControllerUpdate = async (id: string,
    updateSupplierGroupDto: UpdateSupplierGroupDto, options?: RequestInit): Promise<supplierGroupsControllerUpdateResponse> => {
  
  return customFetch<supplierGroupsControllerUpdateResponse>(getSupplierGroupsControllerUpdateUrl(id),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateSupplierGroupDto,)
  }
);}


/**
 * Remove a supplier group from the system.
 * @summary Delete Supplier Group
 */
export type supplierGroupsControllerRemoveResponse200 = {
  data: SupplierGroupResponseDto
  status: 200
}
    
export type supplierGroupsControllerRemoveResponseSuccess = (supplierGroupsControllerRemoveResponse200) & {
  headers: Headers;
};
;

export type supplierGroupsControllerRemoveResponse = (supplierGroupsControllerRemoveResponseSuccess)

export const getSupplierGroupsControllerRemoveUrl = (id: string,) => {


  

  return `/supplier-groups/${id}`
}

export const supplierGroupsControllerRemove = async (id: string, options?: RequestInit): Promise<supplierGroupsControllerRemoveResponse> => {
  
  return customFetch<supplierGroupsControllerRemoveResponse>(getSupplierGroupsControllerRemoveUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}


