import { HeroBM } from '@herobm/sdk';

const SIM_URL = 'http://127.0.0.1:3005';
const API_URL = process.env.API_URL || 'http://localhost:3001';
const ADMIN_PASSWORD = process.env.ADMIN_PASSWORD;

const AGENT_ID = 'basic-agent';

async function log(message: string, level: 'info' | 'warn' | 'error' = 'info') {
  console.log(`[${AGENT_ID}] ${level.toUpperCase()}: ${message}`);
  try {
    await fetch(`${SIM_URL}/api/sim/logs`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ agentId: AGENT_ID, message, level })
    });
  } catch (err) {
    // Ignore log send errors
  }
}

async function getSdk(): Promise<HeroBM | null> {
  try {
    const loginRes = await fetch(`${API_URL}/api/auth/login`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ username: 'admin', password: ADMIN_PASSWORD })
    });
    if (!loginRes.ok) throw new Error('Login failed');
    const { access_token } = await loginRes.json();
    return new HeroBM({ BASE: API_URL, TOKEN: access_token });
  } catch (err: any) {
    await log(`Failed to init SDK: ${err.message}`, 'error');
    return null;
  }
}

async function run() {
  await log('Starting Basic Agent...');
  
  // Register with Sim Engine
  try {
    await fetch(`${SIM_URL}/api/sim/register`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ agentId: AGENT_ID })
    });
    await log('Registered with Simulation Engine.');
  } catch (err) {
    await log('Could not register with Simulation Engine. Is it running?', 'warn');
  }

  const sdk = await getSdk();
  if (!sdk) {
    await log('Could not get SDK. Will retry later.', 'error');
  }

  // Poll Loop
  setInterval(async () => {
    try {
      const res = await fetch(`${SIM_URL}/api/sim/inbox`);
      if (!res.ok) return;
      const { event } = await res.json();
      
      if (!event) return; // No event waiting for this agent

      await log(`Received event ${event.type} (${event.id})`);

      const currentSdk = sdk || await getSdk();
      if (!currentSdk) {
        await fetch(`${SIM_URL}/api/sim/turn-complete`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ agentId: AGENT_ID, outcomes: [{ eventId: event.id, status: 'failure', reason: 'SDK not initialized' }] })
        });
        return;
      }

      let outcome: any = { eventId: event.id, status: 'success' };

      try {
        if (event.type === 'CUSTOMER_ONBOARDING') {
          const cust = event.payload.customer;
          const apiCust = await currentSdk.customers.customersControllerCreate({
            name: cust.name,
            defaultCurrency: 'USD',
            email: cust.email,
            phone: cust.phone,
            notes: 'Generated by Simulation',
          });
          await log(`Created HeroBM Customer: ${apiCust.id}`);

        } else if (event.type === 'CUSTOMER_ORDER') {
          const { virtualOrderId, customer, lines } = event.payload;

          // If guest, create customer first
          let heroBmCustomerId = customer.heroBmId;
          if (!heroBmCustomerId) {
            try {
              const apiCust = await currentSdk.customers.customersControllerCreate({
                name: customer.name || 'Guest User',
                defaultCurrency: 'USD',
                email: customer.email,
                notes: 'Guest checkout from simulation',
              });
              heroBmCustomerId = apiCust.id;
              await log(`Created Guest Customer: ${heroBmCustomerId}`);
            } catch (err: any) {
              await log(`Failed to create guest customer: ${err.message}`, 'error');
              throw err;
            }
          }

          // Create Sales Order
          const apiOrder = await currentSdk.orders.ordersControllerCreate({
            customerId: heroBmCustomerId,
            customerReference: virtualOrderId,
            lines: lines.map((l: any) => ({
              productId: l.productId,
              quantity: l.quantity.toString(),
              pricePerUnit: "10.00", // Hardcoded price for sim
            }))
          });
          
          await log(`Created HeroBM Sales Order: ${apiOrder.orderNumber} for virtual ${virtualOrderId}`);
        } else {
          await log(`Ignored event type: ${event.type}`);
        }
      } catch (err: any) {
        await log(`Failed to process ${event.type}: ${err.message}`, 'error');
        // If it's a 400 Bad Request, it might be credit limit, out of stock, etc.
        // We capture the body if possible
        let reason = err.message;
        if (err.body && err.body.message) {
           reason = JSON.stringify(err.body.message);
           await log(`API Error Details: ${reason}`, 'error');
        }
        outcome = { eventId: event.id, status: 'failure', reason };
      }

      // Complete Turn
      await fetch(`${SIM_URL}/api/sim/turn-complete`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ agentId: AGENT_ID, outcomes: [outcome] })
      });
      await log(`Completed turn for event ${event.id}`);

    } catch (err) {
      // Polling error (engine down, etc)
    }
  }, 2000);
}

run();
