/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.1
 */
import type {
  CreateOrganizationContactDto,
  CreateOrganizationDto,
  CreateOrganizationLinkDto,
  CreateOrganizationNoteDto,
  EmptyBodyDto,
  OrganizationLinkResponseDto,
  OrganizationNoteResponseDto,
  OrganizationResponseDto,
  OrganizationsControllerFindAll200,
  OrganizationsControllerFindAllParams,
  SuccessResponseDto,
  UpdateOrganizationContactDto,
  UpdateOrganizationDto
} from '../../model';

import { customFetch } from '../../mutator';

/**
 * Create Organization
 * @summary Create Organization
 */
export type organizationsControllerCreateResponse201 = {
  data: OrganizationResponseDto
  status: 201
}
    
export type organizationsControllerCreateResponseSuccess = (organizationsControllerCreateResponse201) & {
  headers: Headers;
};
;

export type organizationsControllerCreateResponse = (organizationsControllerCreateResponseSuccess)

export const getOrganizationsControllerCreateUrl = () => {


  

  return `/organizations`
}

export const organizationsControllerCreate = async (createOrganizationDto: CreateOrganizationDto, options?: RequestInit): Promise<organizationsControllerCreateResponse> => {
  
  return customFetch<organizationsControllerCreateResponse>(getOrganizationsControllerCreateUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createOrganizationDto,)
  }
);}


/**
 * Get all Organizations (paginated)
 * @summary Get all Organizations (paginated)
 */
export type organizationsControllerFindAllResponse200 = {
  data: OrganizationsControllerFindAll200
  status: 200
}
    
export type organizationsControllerFindAllResponseSuccess = (organizationsControllerFindAllResponse200) & {
  headers: Headers;
};
;

export type organizationsControllerFindAllResponse = (organizationsControllerFindAllResponseSuccess)

export const getOrganizationsControllerFindAllUrl = (params?: OrganizationsControllerFindAllParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/organizations?${stringifiedParams}` : `/organizations`
}

export const organizationsControllerFindAll = async (params?: OrganizationsControllerFindAllParams, options?: RequestInit): Promise<organizationsControllerFindAllResponse> => {
  
  return customFetch<organizationsControllerFindAllResponse>(getOrganizationsControllerFindAllUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * Get Organization by ID
 * @summary Get Organization by ID
 */
export type organizationsControllerFindOneResponse200 = {
  data: OrganizationResponseDto
  status: 200
}
    
export type organizationsControllerFindOneResponseSuccess = (organizationsControllerFindOneResponse200) & {
  headers: Headers;
};
;

export type organizationsControllerFindOneResponse = (organizationsControllerFindOneResponseSuccess)

export const getOrganizationsControllerFindOneUrl = (id: string,) => {


  

  return `/organizations/${id}`
}

export const organizationsControllerFindOne = async (id: string, options?: RequestInit): Promise<organizationsControllerFindOneResponse> => {
  
  return customFetch<organizationsControllerFindOneResponse>(getOrganizationsControllerFindOneUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * Update Organization
 * @summary Update Organization
 */
export type organizationsControllerUpdateResponse200 = {
  data: OrganizationResponseDto
  status: 200
}
    
export type organizationsControllerUpdateResponseSuccess = (organizationsControllerUpdateResponse200) & {
  headers: Headers;
};
;

export type organizationsControllerUpdateResponse = (organizationsControllerUpdateResponseSuccess)

export const getOrganizationsControllerUpdateUrl = (id: string,) => {


  

  return `/organizations/${id}`
}

export const organizationsControllerUpdate = async (id: string,
    updateOrganizationDto: UpdateOrganizationDto, options?: RequestInit): Promise<organizationsControllerUpdateResponse> => {
  
  return customFetch<organizationsControllerUpdateResponse>(getOrganizationsControllerUpdateUrl(id),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateOrganizationDto,)
  }
);}


/**
 * Delete Organization
 * @summary Delete Organization
 */
export type organizationsControllerRemoveResponse200 = {
  data: SuccessResponseDto
  status: 200
}
    
export type organizationsControllerRemoveResponseSuccess = (organizationsControllerRemoveResponse200) & {
  headers: Headers;
};
;

export type organizationsControllerRemoveResponse = (organizationsControllerRemoveResponseSuccess)

export const getOrganizationsControllerRemoveUrl = (id: string,) => {


  

  return `/organizations/${id}`
}

export const organizationsControllerRemove = async (id: string, options?: RequestInit): Promise<organizationsControllerRemoveResponse> => {
  
  return customFetch<organizationsControllerRemoveResponse>(getOrganizationsControllerRemoveUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}


/**
 * Update Contact Link on Organization
 * @summary Update Contact Link on Organization
 */
export type organizationsControllerUpdateContactResponse200 = {
  data: SuccessResponseDto
  status: 200
}
    
export type organizationsControllerUpdateContactResponseSuccess = (organizationsControllerUpdateContactResponse200) & {
  headers: Headers;
};
;

export type organizationsControllerUpdateContactResponse = (organizationsControllerUpdateContactResponseSuccess)

export const getOrganizationsControllerUpdateContactUrl = (id: string,
    contactId: string,) => {


  

  return `/organizations/${id}/contacts/${contactId}`
}

export const organizationsControllerUpdateContact = async (id: string,
    contactId: string,
    updateOrganizationContactDto: UpdateOrganizationContactDto, options?: RequestInit): Promise<organizationsControllerUpdateContactResponse> => {
  
  return customFetch<organizationsControllerUpdateContactResponse>(getOrganizationsControllerUpdateContactUrl(id,contactId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateOrganizationContactDto,)
  }
);}


/**
 * Remove Contact Link from Organization
 * @summary Remove Contact Link from Organization
 */
export type organizationsControllerRemoveContactResponse200 = {
  data: SuccessResponseDto
  status: 200
}
    
export type organizationsControllerRemoveContactResponseSuccess = (organizationsControllerRemoveContactResponse200) & {
  headers: Headers;
};
;

export type organizationsControllerRemoveContactResponse = (organizationsControllerRemoveContactResponseSuccess)

export const getOrganizationsControllerRemoveContactUrl = (id: string,
    contactId: string,) => {


  

  return `/organizations/${id}/contacts/${contactId}`
}

export const organizationsControllerRemoveContact = async (id: string,
    contactId: string, options?: RequestInit): Promise<organizationsControllerRemoveContactResponse> => {
  
  return customFetch<organizationsControllerRemoveContactResponse>(getOrganizationsControllerRemoveContactUrl(id,contactId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}


/**
 * Link Contact to Organization
 * @summary Link Contact to Organization
 */
export type organizationsControllerAddContactResponse201 = {
  data: SuccessResponseDto
  status: 201
}
    
export type organizationsControllerAddContactResponseSuccess = (organizationsControllerAddContactResponse201) & {
  headers: Headers;
};
;

export type organizationsControllerAddContactResponse = (organizationsControllerAddContactResponseSuccess)

export const getOrganizationsControllerAddContactUrl = (id: string,) => {


  

  return `/organizations/${id}/contacts`
}

export const organizationsControllerAddContact = async (id: string,
    createOrganizationContactDto: CreateOrganizationContactDto, options?: RequestInit): Promise<organizationsControllerAddContactResponse> => {
  
  return customFetch<organizationsControllerAddContactResponse>(getOrganizationsControllerAddContactUrl(id),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createOrganizationContactDto,)
  }
);}


/**
 * Archives an organization
 * @summary Archive Organization
 */
export type organizationsControllerArchiveResponse200 = {
  data: OrganizationResponseDto
  status: 200
}

export type organizationsControllerArchiveResponse201 = {
  data: OrganizationResponseDto
  status: 201
}
    
export type organizationsControllerArchiveResponseSuccess = (organizationsControllerArchiveResponse200 | organizationsControllerArchiveResponse201) & {
  headers: Headers;
};
;

export type organizationsControllerArchiveResponse = (organizationsControllerArchiveResponseSuccess)

export const getOrganizationsControllerArchiveUrl = (id: string,) => {


  

  return `/organizations/${id}/archive`
}

export const organizationsControllerArchive = async (id: string,
    emptyBodyDto: EmptyBodyDto, options?: RequestInit): Promise<organizationsControllerArchiveResponse> => {
  
  return customFetch<organizationsControllerArchiveResponse>(getOrganizationsControllerArchiveUrl(id),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      emptyBodyDto,)
  }
);}


/**
 * Unarchives an organization
 * @summary Unarchive Organization
 */
export type organizationsControllerUnarchiveResponse200 = {
  data: OrganizationResponseDto
  status: 200
}

export type organizationsControllerUnarchiveResponse201 = {
  data: OrganizationResponseDto
  status: 201
}
    
export type organizationsControllerUnarchiveResponseSuccess = (organizationsControllerUnarchiveResponse200 | organizationsControllerUnarchiveResponse201) & {
  headers: Headers;
};
;

export type organizationsControllerUnarchiveResponse = (organizationsControllerUnarchiveResponseSuccess)

export const getOrganizationsControllerUnarchiveUrl = (id: string,) => {


  

  return `/organizations/${id}/unarchive`
}

export const organizationsControllerUnarchive = async (id: string,
    emptyBodyDto: EmptyBodyDto, options?: RequestInit): Promise<organizationsControllerUnarchiveResponse> => {
  
  return customFetch<organizationsControllerUnarchiveResponse>(getOrganizationsControllerUnarchiveUrl(id),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      emptyBodyDto,)
  }
);}


/**
 * Add Note to Organization
 * @summary Add Note to Organization
 */
export type organizationsControllerAddNoteResponse201 = {
  data: OrganizationNoteResponseDto
  status: 201
}
    
export type organizationsControllerAddNoteResponseSuccess = (organizationsControllerAddNoteResponse201) & {
  headers: Headers;
};
;

export type organizationsControllerAddNoteResponse = (organizationsControllerAddNoteResponseSuccess)

export const getOrganizationsControllerAddNoteUrl = (id: string,) => {


  

  return `/organizations/${id}/notes`
}

export const organizationsControllerAddNote = async (id: string,
    createOrganizationNoteDto: CreateOrganizationNoteDto, options?: RequestInit): Promise<organizationsControllerAddNoteResponse> => {
  
  return customFetch<organizationsControllerAddNoteResponse>(getOrganizationsControllerAddNoteUrl(id),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createOrganizationNoteDto,)
  }
);}


/**
 * Remove Note from Organization
 * @summary Remove Note from Organization
 */
export type organizationsControllerRemoveNoteResponse200 = {
  data: SuccessResponseDto
  status: 200
}
    
export type organizationsControllerRemoveNoteResponseSuccess = (organizationsControllerRemoveNoteResponse200) & {
  headers: Headers;
};
;

export type organizationsControllerRemoveNoteResponse = (organizationsControllerRemoveNoteResponseSuccess)

export const getOrganizationsControllerRemoveNoteUrl = (id: string,
    noteId: string,) => {


  

  return `/organizations/${id}/notes/${noteId}`
}

export const organizationsControllerRemoveNote = async (id: string,
    noteId: string, options?: RequestInit): Promise<organizationsControllerRemoveNoteResponse> => {
  
  return customFetch<organizationsControllerRemoveNoteResponse>(getOrganizationsControllerRemoveNoteUrl(id,noteId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}


/**
 * Get Organization Links
 * @summary Get Organization Links
 */
export type organizationsControllerGetLinksResponse200 = {
  data: OrganizationLinkResponseDto[]
  status: 200
}
    
export type organizationsControllerGetLinksResponseSuccess = (organizationsControllerGetLinksResponse200) & {
  headers: Headers;
};
;

export type organizationsControllerGetLinksResponse = (organizationsControllerGetLinksResponseSuccess)

export const getOrganizationsControllerGetLinksUrl = (id: string,) => {


  

  return `/organizations/${id}/links`
}

export const organizationsControllerGetLinks = async (id: string, options?: RequestInit): Promise<organizationsControllerGetLinksResponse> => {
  
  return customFetch<organizationsControllerGetLinksResponse>(getOrganizationsControllerGetLinksUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * Add Organization Link
 * @summary Add Organization Link
 */
export type organizationsControllerAddLinkResponse201 = {
  data: OrganizationLinkResponseDto
  status: 201
}
    
export type organizationsControllerAddLinkResponseSuccess = (organizationsControllerAddLinkResponse201) & {
  headers: Headers;
};
;

export type organizationsControllerAddLinkResponse = (organizationsControllerAddLinkResponseSuccess)

export const getOrganizationsControllerAddLinkUrl = (id: string,) => {


  

  return `/organizations/${id}/links`
}

export const organizationsControllerAddLink = async (id: string,
    createOrganizationLinkDto: CreateOrganizationLinkDto, options?: RequestInit): Promise<organizationsControllerAddLinkResponse> => {
  
  return customFetch<organizationsControllerAddLinkResponse>(getOrganizationsControllerAddLinkUrl(id),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createOrganizationLinkDto,)
  }
);}


/**
 * Remove Organization Link
 * @summary Remove Organization Link
 */
export type organizationsControllerRemoveLinkResponse200 = {
  data: SuccessResponseDto
  status: 200
}
    
export type organizationsControllerRemoveLinkResponseSuccess = (organizationsControllerRemoveLinkResponse200) & {
  headers: Headers;
};
;

export type organizationsControllerRemoveLinkResponse = (organizationsControllerRemoveLinkResponseSuccess)

export const getOrganizationsControllerRemoveLinkUrl = (id: string,
    linkId: string,) => {


  

  return `/organizations/${id}/links/${linkId}`
}

export const organizationsControllerRemoveLink = async (id: string,
    linkId: string, options?: RequestInit): Promise<organizationsControllerRemoveLinkResponse> => {
  
  return customFetch<organizationsControllerRemoveLinkResponse>(getOrganizationsControllerRemoveLinkUrl(id,linkId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}


