/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type {
  ActorResponseDto,
  ActorsControllerAddContact201,
  ActorsControllerAddNote201,
  ActorsControllerFindAll200,
  ActorsControllerFindAllParams,
  ActorsControllerRemove200,
  ActorsControllerRemoveContact200,
  ActorsControllerRemoveNote200,
  ActorsControllerUpdateContact200,
  CreateActorContactDto,
  CreateActorDto,
  CreateActorNoteDto,
  EmptyBodyDto,
  UpdateActorContactDto,
  UpdateActorDto
} from '../../model';

import { customFetch } from '../../mutator';

/**
 * Create Actor
 * @summary Create Actor
 */
export type actorsControllerCreateResponse201 = {
  data: ActorResponseDto
  status: 201
}
    
export type actorsControllerCreateResponseSuccess = (actorsControllerCreateResponse201) & {
  headers: Headers;
};
;

export type actorsControllerCreateResponse = (actorsControllerCreateResponseSuccess)

export const getActorsControllerCreateUrl = () => {


  

  return `/actors`
}

export const actorsControllerCreate = async (createActorDto: CreateActorDto, options?: RequestInit): Promise<actorsControllerCreateResponse> => {
  
  return customFetch<actorsControllerCreateResponse>(getActorsControllerCreateUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createActorDto,)
  }
);}


/**
 * Get all Actors (paginated)
 * @summary Get all Actors (paginated)
 */
export type actorsControllerFindAllResponse200 = {
  data: ActorsControllerFindAll200
  status: 200
}
    
export type actorsControllerFindAllResponseSuccess = (actorsControllerFindAllResponse200) & {
  headers: Headers;
};
;

export type actorsControllerFindAllResponse = (actorsControllerFindAllResponseSuccess)

export const getActorsControllerFindAllUrl = (params?: ActorsControllerFindAllParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/actors?${stringifiedParams}` : `/actors`
}

export const actorsControllerFindAll = async (params?: ActorsControllerFindAllParams, options?: RequestInit): Promise<actorsControllerFindAllResponse> => {
  
  return customFetch<actorsControllerFindAllResponse>(getActorsControllerFindAllUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * Get Actor by ID
 * @summary Get Actor by ID
 */
export type actorsControllerFindOneResponse200 = {
  data: ActorResponseDto
  status: 200
}
    
export type actorsControllerFindOneResponseSuccess = (actorsControllerFindOneResponse200) & {
  headers: Headers;
};
;

export type actorsControllerFindOneResponse = (actorsControllerFindOneResponseSuccess)

export const getActorsControllerFindOneUrl = (id: string,) => {


  

  return `/actors/${id}`
}

export const actorsControllerFindOne = async (id: string, options?: RequestInit): Promise<actorsControllerFindOneResponse> => {
  
  return customFetch<actorsControllerFindOneResponse>(getActorsControllerFindOneUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * Update Actor
 * @summary Update Actor
 */
export type actorsControllerUpdateResponse200 = {
  data: ActorResponseDto
  status: 200
}
    
export type actorsControllerUpdateResponseSuccess = (actorsControllerUpdateResponse200) & {
  headers: Headers;
};
;

export type actorsControllerUpdateResponse = (actorsControllerUpdateResponseSuccess)

export const getActorsControllerUpdateUrl = (id: string,) => {


  

  return `/actors/${id}`
}

export const actorsControllerUpdate = async (id: string,
    updateActorDto: UpdateActorDto, options?: RequestInit): Promise<actorsControllerUpdateResponse> => {
  
  return customFetch<actorsControllerUpdateResponse>(getActorsControllerUpdateUrl(id),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateActorDto,)
  }
);}


/**
 * Delete Actor
 * @summary Delete Actor
 */
export type actorsControllerRemoveResponse200 = {
  data: ActorsControllerRemove200
  status: 200
}
    
export type actorsControllerRemoveResponseSuccess = (actorsControllerRemoveResponse200) & {
  headers: Headers;
};
;

export type actorsControllerRemoveResponse = (actorsControllerRemoveResponseSuccess)

export const getActorsControllerRemoveUrl = (id: string,) => {


  

  return `/actors/${id}`
}

export const actorsControllerRemove = async (id: string, options?: RequestInit): Promise<actorsControllerRemoveResponse> => {
  
  return customFetch<actorsControllerRemoveResponse>(getActorsControllerRemoveUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}


/**
 * Update Contact Link on Actor
 * @summary Update Contact Link on Actor
 */
export type actorsControllerUpdateContactResponse200 = {
  data: ActorsControllerUpdateContact200
  status: 200
}
    
export type actorsControllerUpdateContactResponseSuccess = (actorsControllerUpdateContactResponse200) & {
  headers: Headers;
};
;

export type actorsControllerUpdateContactResponse = (actorsControllerUpdateContactResponseSuccess)

export const getActorsControllerUpdateContactUrl = (id: string,
    contactId: string,) => {


  

  return `/actors/${id}/contacts/${contactId}`
}

export const actorsControllerUpdateContact = async (id: string,
    contactId: string,
    updateActorContactDto: UpdateActorContactDto, options?: RequestInit): Promise<actorsControllerUpdateContactResponse> => {
  
  return customFetch<actorsControllerUpdateContactResponse>(getActorsControllerUpdateContactUrl(id,contactId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateActorContactDto,)
  }
);}


/**
 * Remove Contact Link from Actor
 * @summary Remove Contact Link from Actor
 */
export type actorsControllerRemoveContactResponse200 = {
  data: ActorsControllerRemoveContact200
  status: 200
}
    
export type actorsControllerRemoveContactResponseSuccess = (actorsControllerRemoveContactResponse200) & {
  headers: Headers;
};
;

export type actorsControllerRemoveContactResponse = (actorsControllerRemoveContactResponseSuccess)

export const getActorsControllerRemoveContactUrl = (id: string,
    contactId: string,) => {


  

  return `/actors/${id}/contacts/${contactId}`
}

export const actorsControllerRemoveContact = async (id: string,
    contactId: string, options?: RequestInit): Promise<actorsControllerRemoveContactResponse> => {
  
  return customFetch<actorsControllerRemoveContactResponse>(getActorsControllerRemoveContactUrl(id,contactId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}


/**
 * Link Contact to Actor
 * @summary Link Contact to Actor
 */
export type actorsControllerAddContactResponse201 = {
  data: ActorsControllerAddContact201
  status: 201
}
    
export type actorsControllerAddContactResponseSuccess = (actorsControllerAddContactResponse201) & {
  headers: Headers;
};
;

export type actorsControllerAddContactResponse = (actorsControllerAddContactResponseSuccess)

export const getActorsControllerAddContactUrl = (id: string,) => {


  

  return `/actors/${id}/contacts`
}

export const actorsControllerAddContact = async (id: string,
    createActorContactDto: CreateActorContactDto, options?: RequestInit): Promise<actorsControllerAddContactResponse> => {
  
  return customFetch<actorsControllerAddContactResponse>(getActorsControllerAddContactUrl(id),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createActorContactDto,)
  }
);}


/**
 * Archives an actor
 * @summary Archive Actor
 */
export type actorsControllerArchiveResponse200 = {
  data: ActorResponseDto
  status: 200
}

export type actorsControllerArchiveResponse201 = {
  data: ActorResponseDto
  status: 201
}
    
export type actorsControllerArchiveResponseSuccess = (actorsControllerArchiveResponse200 | actorsControllerArchiveResponse201) & {
  headers: Headers;
};
;

export type actorsControllerArchiveResponse = (actorsControllerArchiveResponseSuccess)

export const getActorsControllerArchiveUrl = (id: string,) => {


  

  return `/actors/${id}/archive`
}

export const actorsControllerArchive = async (id: string,
    emptyBodyDto: EmptyBodyDto, options?: RequestInit): Promise<actorsControllerArchiveResponse> => {
  
  return customFetch<actorsControllerArchiveResponse>(getActorsControllerArchiveUrl(id),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      emptyBodyDto,)
  }
);}


/**
 * Unarchives an actor
 * @summary Unarchive Actor
 */
export type actorsControllerUnarchiveResponse200 = {
  data: ActorResponseDto
  status: 200
}

export type actorsControllerUnarchiveResponse201 = {
  data: ActorResponseDto
  status: 201
}
    
export type actorsControllerUnarchiveResponseSuccess = (actorsControllerUnarchiveResponse200 | actorsControllerUnarchiveResponse201) & {
  headers: Headers;
};
;

export type actorsControllerUnarchiveResponse = (actorsControllerUnarchiveResponseSuccess)

export const getActorsControllerUnarchiveUrl = (id: string,) => {


  

  return `/actors/${id}/unarchive`
}

export const actorsControllerUnarchive = async (id: string,
    emptyBodyDto: EmptyBodyDto, options?: RequestInit): Promise<actorsControllerUnarchiveResponse> => {
  
  return customFetch<actorsControllerUnarchiveResponse>(getActorsControllerUnarchiveUrl(id),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      emptyBodyDto,)
  }
);}


/**
 * Add Note to Actor
 * @summary Add Note to Actor
 */
export type actorsControllerAddNoteResponse201 = {
  data: ActorsControllerAddNote201
  status: 201
}
    
export type actorsControllerAddNoteResponseSuccess = (actorsControllerAddNoteResponse201) & {
  headers: Headers;
};
;

export type actorsControllerAddNoteResponse = (actorsControllerAddNoteResponseSuccess)

export const getActorsControllerAddNoteUrl = (id: string,) => {


  

  return `/actors/${id}/notes`
}

export const actorsControllerAddNote = async (id: string,
    createActorNoteDto: CreateActorNoteDto, options?: RequestInit): Promise<actorsControllerAddNoteResponse> => {
  
  return customFetch<actorsControllerAddNoteResponse>(getActorsControllerAddNoteUrl(id),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createActorNoteDto,)
  }
);}


/**
 * Remove Note from Actor
 * @summary Remove Note from Actor
 */
export type actorsControllerRemoveNoteResponse200 = {
  data: ActorsControllerRemoveNote200
  status: 200
}
    
export type actorsControllerRemoveNoteResponseSuccess = (actorsControllerRemoveNoteResponse200) & {
  headers: Headers;
};
;

export type actorsControllerRemoveNoteResponse = (actorsControllerRemoveNoteResponseSuccess)

export const getActorsControllerRemoveNoteUrl = (id: string,
    noteId: string,) => {


  

  return `/actors/${id}/notes/${noteId}`
}

export const actorsControllerRemoveNote = async (id: string,
    noteId: string, options?: RequestInit): Promise<actorsControllerRemoveNoteResponse> => {
  
  return customFetch<actorsControllerRemoveNoteResponse>(getActorsControllerRemoveNoteUrl(id,noteId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}


