/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.1
 */
import type {
  CreateOpportunityContactDto,
  CreateOpportunityDto,
  CreateOpportunityNoteDto,
  CreateOpportunityOrganizationDto,
  EmptyBodyDto,
  OpportunitiesControllerFindAll200,
  OpportunitiesControllerFindAllParams,
  OpportunityNoteResponseDto,
  OpportunityResponseDto,
  SuccessResponseDto,
  UpdateOpportunityContactDto,
  UpdateOpportunityDto,
  UpdateOpportunityOrganizationDto
} from '../../model';

import { customFetch } from '../../mutator';

/**
 * Create Opportunity
 * @summary Create Opportunity
 */
export type opportunitiesControllerCreateResponse201 = {
  data: OpportunityResponseDto
  status: 201
}
    
export type opportunitiesControllerCreateResponseSuccess = (opportunitiesControllerCreateResponse201) & {
  headers: Headers;
};
;

export type opportunitiesControllerCreateResponse = (opportunitiesControllerCreateResponseSuccess)

export const getOpportunitiesControllerCreateUrl = () => {


  

  return `/opportunities`
}

export const opportunitiesControllerCreate = async (createOpportunityDto: CreateOpportunityDto, options?: RequestInit): Promise<opportunitiesControllerCreateResponse> => {
  
  return customFetch<opportunitiesControllerCreateResponse>(getOpportunitiesControllerCreateUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createOpportunityDto,)
  }
);}


/**
 * Get all Opportunities with filtering and pagination
 * @summary Get all Opportunities
 */
export type opportunitiesControllerFindAllResponse200 = {
  data: OpportunitiesControllerFindAll200
  status: 200
}
    
export type opportunitiesControllerFindAllResponseSuccess = (opportunitiesControllerFindAllResponse200) & {
  headers: Headers;
};
;

export type opportunitiesControllerFindAllResponse = (opportunitiesControllerFindAllResponseSuccess)

export const getOpportunitiesControllerFindAllUrl = (params?: OpportunitiesControllerFindAllParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/opportunities?${stringifiedParams}` : `/opportunities`
}

export const opportunitiesControllerFindAll = async (params?: OpportunitiesControllerFindAllParams, options?: RequestInit): Promise<opportunitiesControllerFindAllResponse> => {
  
  return customFetch<opportunitiesControllerFindAllResponse>(getOpportunitiesControllerFindAllUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * Get Opportunity by ID with linked organizations, contacts, and notes
 * @summary Get Opportunity by ID
 */
export type opportunitiesControllerFindOneResponse200 = {
  data: OpportunityResponseDto
  status: 200
}
    
export type opportunitiesControllerFindOneResponseSuccess = (opportunitiesControllerFindOneResponse200) & {
  headers: Headers;
};
;

export type opportunitiesControllerFindOneResponse = (opportunitiesControllerFindOneResponseSuccess)

export const getOpportunitiesControllerFindOneUrl = (id: string,) => {


  

  return `/opportunities/${id}`
}

export const opportunitiesControllerFindOne = async (id: string, options?: RequestInit): Promise<opportunitiesControllerFindOneResponse> => {
  
  return customFetch<opportunitiesControllerFindOneResponse>(getOpportunitiesControllerFindOneUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * Update Opportunity
 * @summary Update Opportunity
 */
export type opportunitiesControllerUpdateResponse200 = {
  data: OpportunityResponseDto
  status: 200
}
    
export type opportunitiesControllerUpdateResponseSuccess = (opportunitiesControllerUpdateResponse200) & {
  headers: Headers;
};
;

export type opportunitiesControllerUpdateResponse = (opportunitiesControllerUpdateResponseSuccess)

export const getOpportunitiesControllerUpdateUrl = (id: string,) => {


  

  return `/opportunities/${id}`
}

export const opportunitiesControllerUpdate = async (id: string,
    updateOpportunityDto: UpdateOpportunityDto, options?: RequestInit): Promise<opportunitiesControllerUpdateResponse> => {
  
  return customFetch<opportunitiesControllerUpdateResponse>(getOpportunitiesControllerUpdateUrl(id),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateOpportunityDto,)
  }
);}


/**
 * Deletes an opportunity permanently
 * @summary Delete Opportunity
 */
export type opportunitiesControllerRemoveResponse200 = {
  data: SuccessResponseDto
  status: 200
}
    
export type opportunitiesControllerRemoveResponseSuccess = (opportunitiesControllerRemoveResponse200) & {
  headers: Headers;
};
;

export type opportunitiesControllerRemoveResponse = (opportunitiesControllerRemoveResponseSuccess)

export const getOpportunitiesControllerRemoveUrl = (id: string,) => {


  

  return `/opportunities/${id}`
}

export const opportunitiesControllerRemove = async (id: string, options?: RequestInit): Promise<opportunitiesControllerRemoveResponse> => {
  
  return customFetch<opportunitiesControllerRemoveResponse>(getOpportunitiesControllerRemoveUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}


/**
 * Archives an opportunity
 * @summary Archive Opportunity
 */
export type opportunitiesControllerArchiveResponse200 = {
  data: OpportunityResponseDto
  status: 200
}

export type opportunitiesControllerArchiveResponse201 = {
  data: OpportunityResponseDto
  status: 201
}
    
export type opportunitiesControllerArchiveResponseSuccess = (opportunitiesControllerArchiveResponse200 | opportunitiesControllerArchiveResponse201) & {
  headers: Headers;
};
;

export type opportunitiesControllerArchiveResponse = (opportunitiesControllerArchiveResponseSuccess)

export const getOpportunitiesControllerArchiveUrl = (id: string,) => {


  

  return `/opportunities/${id}/archive`
}

export const opportunitiesControllerArchive = async (id: string,
    emptyBodyDto: EmptyBodyDto, options?: RequestInit): Promise<opportunitiesControllerArchiveResponse> => {
  
  return customFetch<opportunitiesControllerArchiveResponse>(getOpportunitiesControllerArchiveUrl(id),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      emptyBodyDto,)
  }
);}


/**
 * Unarchives an opportunity
 * @summary Unarchive Opportunity
 */
export type opportunitiesControllerUnarchiveResponse200 = {
  data: OpportunityResponseDto
  status: 200
}

export type opportunitiesControllerUnarchiveResponse201 = {
  data: OpportunityResponseDto
  status: 201
}
    
export type opportunitiesControllerUnarchiveResponseSuccess = (opportunitiesControllerUnarchiveResponse200 | opportunitiesControllerUnarchiveResponse201) & {
  headers: Headers;
};
;

export type opportunitiesControllerUnarchiveResponse = (opportunitiesControllerUnarchiveResponseSuccess)

export const getOpportunitiesControllerUnarchiveUrl = (id: string,) => {


  

  return `/opportunities/${id}/unarchive`
}

export const opportunitiesControllerUnarchive = async (id: string,
    emptyBodyDto: EmptyBodyDto, options?: RequestInit): Promise<opportunitiesControllerUnarchiveResponse> => {
  
  return customFetch<opportunitiesControllerUnarchiveResponse>(getOpportunitiesControllerUnarchiveUrl(id),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      emptyBodyDto,)
  }
);}


/**
 * Adds a note to an opportunity
 * @summary Add Opportunity Note
 */
export type opportunitiesControllerAddNoteResponse201 = {
  data: OpportunityNoteResponseDto
  status: 201
}
    
export type opportunitiesControllerAddNoteResponseSuccess = (opportunitiesControllerAddNoteResponse201) & {
  headers: Headers;
};
;

export type opportunitiesControllerAddNoteResponse = (opportunitiesControllerAddNoteResponseSuccess)

export const getOpportunitiesControllerAddNoteUrl = (id: string,) => {


  

  return `/opportunities/${id}/notes`
}

export const opportunitiesControllerAddNote = async (id: string,
    createOpportunityNoteDto: CreateOpportunityNoteDto, options?: RequestInit): Promise<opportunitiesControllerAddNoteResponse> => {
  
  return customFetch<opportunitiesControllerAddNoteResponse>(getOpportunitiesControllerAddNoteUrl(id),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createOpportunityNoteDto,)
  }
);}


/**
 * Gets all notes for an opportunity
 * @summary Get Opportunity Notes
 */
export type opportunitiesControllerGetNotesResponse200 = {
  data: OpportunityNoteResponseDto[]
  status: 200
}
    
export type opportunitiesControllerGetNotesResponseSuccess = (opportunitiesControllerGetNotesResponse200) & {
  headers: Headers;
};
;

export type opportunitiesControllerGetNotesResponse = (opportunitiesControllerGetNotesResponseSuccess)

export const getOpportunitiesControllerGetNotesUrl = (id: string,) => {


  

  return `/opportunities/${id}/notes`
}

export const opportunitiesControllerGetNotes = async (id: string, options?: RequestInit): Promise<opportunitiesControllerGetNotesResponse> => {
  
  return customFetch<opportunitiesControllerGetNotesResponse>(getOpportunitiesControllerGetNotesUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * Deletes a note from an opportunity
 * @summary Delete Opportunity Note
 */
export type opportunitiesControllerDeleteNoteResponse200 = {
  data: SuccessResponseDto
  status: 200
}
    
export type opportunitiesControllerDeleteNoteResponseSuccess = (opportunitiesControllerDeleteNoteResponse200) & {
  headers: Headers;
};
;

export type opportunitiesControllerDeleteNoteResponse = (opportunitiesControllerDeleteNoteResponseSuccess)

export const getOpportunitiesControllerDeleteNoteUrl = (id: string,
    noteId: string,) => {


  

  return `/opportunities/${id}/notes/${noteId}`
}

export const opportunitiesControllerDeleteNote = async (id: string,
    noteId: string, options?: RequestInit): Promise<opportunitiesControllerDeleteNoteResponse> => {
  
  return customFetch<opportunitiesControllerDeleteNoteResponse>(getOpportunitiesControllerDeleteNoteUrl(id,noteId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}


/**
 * Links a contact to an opportunity
 * @summary Add Opportunity Contact
 */
export type opportunitiesControllerAddContactResponse201 = {
  data: SuccessResponseDto
  status: 201
}
    
export type opportunitiesControllerAddContactResponseSuccess = (opportunitiesControllerAddContactResponse201) & {
  headers: Headers;
};
;

export type opportunitiesControllerAddContactResponse = (opportunitiesControllerAddContactResponseSuccess)

export const getOpportunitiesControllerAddContactUrl = (id: string,) => {


  

  return `/opportunities/${id}/contacts`
}

export const opportunitiesControllerAddContact = async (id: string,
    createOpportunityContactDto: CreateOpportunityContactDto, options?: RequestInit): Promise<opportunitiesControllerAddContactResponse> => {
  
  return customFetch<opportunitiesControllerAddContactResponse>(getOpportunitiesControllerAddContactUrl(id),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createOpportunityContactDto,)
  }
);}


/**
 * Updates roles for a linked contact
 * @summary Update Opportunity Contact Roles
 */
export type opportunitiesControllerUpdateContactResponse200 = {
  data: SuccessResponseDto
  status: 200
}
    
export type opportunitiesControllerUpdateContactResponseSuccess = (opportunitiesControllerUpdateContactResponse200) & {
  headers: Headers;
};
;

export type opportunitiesControllerUpdateContactResponse = (opportunitiesControllerUpdateContactResponseSuccess)

export const getOpportunitiesControllerUpdateContactUrl = (id: string,
    contactId: string,) => {


  

  return `/opportunities/${id}/contacts/${contactId}`
}

export const opportunitiesControllerUpdateContact = async (id: string,
    contactId: string,
    updateOpportunityContactDto: UpdateOpportunityContactDto, options?: RequestInit): Promise<opportunitiesControllerUpdateContactResponse> => {
  
  return customFetch<opportunitiesControllerUpdateContactResponse>(getOpportunitiesControllerUpdateContactUrl(id,contactId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateOpportunityContactDto,)
  }
);}


/**
 * Unlinks a contact from an opportunity
 * @summary Remove Opportunity Contact
 */
export type opportunitiesControllerDeleteContactResponse200 = {
  data: SuccessResponseDto
  status: 200
}
    
export type opportunitiesControllerDeleteContactResponseSuccess = (opportunitiesControllerDeleteContactResponse200) & {
  headers: Headers;
};
;

export type opportunitiesControllerDeleteContactResponse = (opportunitiesControllerDeleteContactResponseSuccess)

export const getOpportunitiesControllerDeleteContactUrl = (id: string,
    contactId: string,) => {


  

  return `/opportunities/${id}/contacts/${contactId}`
}

export const opportunitiesControllerDeleteContact = async (id: string,
    contactId: string, options?: RequestInit): Promise<opportunitiesControllerDeleteContactResponse> => {
  
  return customFetch<opportunitiesControllerDeleteContactResponse>(getOpportunitiesControllerDeleteContactUrl(id,contactId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}


/**
 * Links an organization to an opportunity
 * @summary Add Opportunity Organization
 */
export type opportunitiesControllerAddOrganizationResponse201 = {
  data: SuccessResponseDto
  status: 201
}
    
export type opportunitiesControllerAddOrganizationResponseSuccess = (opportunitiesControllerAddOrganizationResponse201) & {
  headers: Headers;
};
;

export type opportunitiesControllerAddOrganizationResponse = (opportunitiesControllerAddOrganizationResponseSuccess)

export const getOpportunitiesControllerAddOrganizationUrl = (id: string,) => {


  

  return `/opportunities/${id}/organizations`
}

export const opportunitiesControllerAddOrganization = async (id: string,
    createOpportunityOrganizationDto: CreateOpportunityOrganizationDto, options?: RequestInit): Promise<opportunitiesControllerAddOrganizationResponse> => {
  
  return customFetch<opportunitiesControllerAddOrganizationResponse>(getOpportunitiesControllerAddOrganizationUrl(id),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createOpportunityOrganizationDto,)
  }
);}


/**
 * Updates roles for a linked organization
 * @summary Update Opportunity Organization Roles
 */
export type opportunitiesControllerUpdateOrganizationResponse200 = {
  data: SuccessResponseDto
  status: 200
}
    
export type opportunitiesControllerUpdateOrganizationResponseSuccess = (opportunitiesControllerUpdateOrganizationResponse200) & {
  headers: Headers;
};
;

export type opportunitiesControllerUpdateOrganizationResponse = (opportunitiesControllerUpdateOrganizationResponseSuccess)

export const getOpportunitiesControllerUpdateOrganizationUrl = (id: string,
    organizationId: string,) => {


  

  return `/opportunities/${id}/organizations/${organizationId}`
}

export const opportunitiesControllerUpdateOrganization = async (id: string,
    organizationId: string,
    updateOpportunityOrganizationDto: UpdateOpportunityOrganizationDto, options?: RequestInit): Promise<opportunitiesControllerUpdateOrganizationResponse> => {
  
  return customFetch<opportunitiesControllerUpdateOrganizationResponse>(getOpportunitiesControllerUpdateOrganizationUrl(id,organizationId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateOpportunityOrganizationDto,)
  }
);}


/**
 * Unlinks an organization from an opportunity
 * @summary Remove Opportunity Organization
 */
export type opportunitiesControllerDeleteOrganizationResponse200 = {
  data: SuccessResponseDto
  status: 200
}
    
export type opportunitiesControllerDeleteOrganizationResponseSuccess = (opportunitiesControllerDeleteOrganizationResponse200) & {
  headers: Headers;
};
;

export type opportunitiesControllerDeleteOrganizationResponse = (opportunitiesControllerDeleteOrganizationResponseSuccess)

export const getOpportunitiesControllerDeleteOrganizationUrl = (id: string,
    organizationId: string,) => {


  

  return `/opportunities/${id}/organizations/${organizationId}`
}

export const opportunitiesControllerDeleteOrganization = async (id: string,
    organizationId: string, options?: RequestInit): Promise<opportunitiesControllerDeleteOrganizationResponse> => {
  
  return customFetch<opportunitiesControllerDeleteOrganizationResponse>(getOpportunitiesControllerDeleteOrganizationUrl(id,organizationId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}


