'use client';

import React from 'react';
import { useTranslations } from 'next-intl';
import { InlineSettingsTable } from '@/components/shared/InlineSettingsTable';
import { Webhook } from '../hooks/useDevelopers';

interface WebhooksSectionProps {
  webhooks: Webhook[];
  availableEvents: string[];
  createWebhook: (targetUrl: string, eventTypesString: string) => Promise<void>;
  deleteWebhook: (webhookId: string) => Promise<void>;
}

export function WebhooksSection({
  webhooks,
  availableEvents,
  createWebhook,
  deleteWebhook,
}: WebhooksSectionProps) {
  const tDev = useTranslations('admin.developers');

  return (
    <div id="webhooks" className="card">
      <h3 className="section-heading mb-4">
        {/* eslint-disable-next-line i18next/no-literal-string -- Material UI Icon */}
        <span className="material-symbols-outlined">webhook</span>
        {tDev('webhooks')}
      </h3>
      <InlineSettingsTable
        data={webhooks || []}
        // eslint-disable-next-line @typescript-eslint/no-explicit-any -- InlineSettingsTable uses generic any rows to support mixed entity types
        rowKey={(r: any) => r.webhookId}
        // eslint-disable-next-line @typescript-eslint/no-explicit-any -- InlineSettingsTable uses generic any rows to support mixed entity types
        onSave={async (row: any, isNew: boolean) => {
          if (isNew) {
            await createWebhook(row.targetUrl, row.eventTypes);
          }
        }}
        // eslint-disable-next-line @typescript-eslint/no-explicit-any -- InlineSettingsTable uses generic any rows to support mixed entity types
        onDelete={async (row: any) => {
          await deleteWebhook(row.webhookId);
        }}
        // eslint-disable-next-line @typescript-eslint/no-explicit-any -- InlineSettingsTable uses generic any rows to support mixed entity types
        onAdd={() => ({ targetUrl: '', eventTypes: '', secretKey: tDev('autoGenerated') } as any)}
        canEdit={() => false}
        canDelete={() => true}
        addLabel={tDev('addWebhook')}
        emptyLabel={tDev('noWebhooksFound')}
        columns={[
          {
            key: 'targetUrl',
            title: tDev('targetUrl'),
            type: 'text',
            validate: (v) => (v ? null : 'Required'),
          },
          {
            key: 'eventTypes',
            title: tDev('events'),
            type: 'text',
            // eslint-disable-next-line @typescript-eslint/no-explicit-any -- InlineSettingsTable uses generic any rows to support mixed entity types
            render: (row: any, isEditing: boolean, onChange?: (val: any) => void) => {
              const currentEvents = Array.isArray(row.eventTypes)
                ? row.eventTypes
                : (row.eventTypes || '').split(',').map((e: string) => e.trim()).filter(Boolean);
              if (isEditing) {
                return (
                  <div className="flex flex-col gap-1 max-h-32 overflow-y-auto border border-[var(--border)] p-2 rounded text-xs bg-black/5">
                    <label className="flex items-center gap-2 cursor-pointer hover:text-[var(--text-primary)]">
                      <input
                        type="checkbox"
                        checked={currentEvents.includes('*')}
                        onChange={(e) => {
                          if (e.target.checked) onChange?.('*');
                          else onChange?.('');
                        }}
                      />
                      {tDev('allEvents')}
                    </label>
                    {availableEvents.map((e) => (
                      <label key={e} className="flex items-center gap-2 cursor-pointer hover:text-[var(--text-primary)]">
                        <input
                          type="checkbox"
                          checked={currentEvents.includes(e)}
                          onChange={(ev) => {
                            const newEvents = ev.target.checked
                              ? [...currentEvents.filter((c: string) => c !== '*'), e]
                              : currentEvents.filter((c: string) => c !== e && c !== '*');
                            onChange?.(newEvents.join(', '));
                          }}
                        />
                        {e}
                      </label>
                    ))}
                  </div>
                );
              }
              return (
                <div className="flex flex-wrap gap-1">
                  {currentEvents.map((e: string) => (
                    <span key={e} className="inline-block px-2 py-0.5 text-xs">
                      {e.trim()}
                    </span>
                  ))}
                </div>
              );
            },
          },
          {
            key: 'secretKey',
            title: tDev('secretKey'),
            type: 'text',
            disabled: true,
            // eslint-disable-next-line @typescript-eslint/no-explicit-any -- InlineSettingsTable uses generic any rows to support mixed entity types
            render: (row: any) => <span className="font-mono text-xs">{row.secretKey}</span>,
          },
        ]}
      />
    </div>
  );
}
