/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type {
  CreateTransferFromDemandsDto,
  CreateTransferOrderDto,
  CreateTransferOrderLineDto,
  EmptyBodyDto,
  PickLineDto,
  ReceiveTransferDto,
  ShipmentResponseDto,
  TransferEventResponseDto,
  TransferPickingSummaryResponseDto,
  TransferResponseDto,
  TransfersControllerFindAll200,
  TransfersControllerFindAllParams,
  TransfersControllerFindOneParams,
  UpdateTransferOrderDto,
  UpdateTransferOrderLineDto
} from '../../model';

import { customFetch } from '../../mutator';

/**
 * Create a new transfer order from open backorder demands.
 * @summary Create From Demands
 */
export type transfersControllerCreateTransferFromDemandsResponse201 = {
  data: TransferResponseDto
  status: 201
}
    
export type transfersControllerCreateTransferFromDemandsResponseSuccess = (transfersControllerCreateTransferFromDemandsResponse201) & {
  headers: Headers;
};
;

export type transfersControllerCreateTransferFromDemandsResponse = (transfersControllerCreateTransferFromDemandsResponseSuccess)

export const getTransfersControllerCreateTransferFromDemandsUrl = () => {


  

  return `/transfers/from-demands`
}

export const transfersControllerCreateTransferFromDemands = async (createTransferFromDemandsDto: CreateTransferFromDemandsDto, options?: RequestInit): Promise<transfersControllerCreateTransferFromDemandsResponse> => {
  
  return customFetch<transfersControllerCreateTransferFromDemandsResponse>(getTransfersControllerCreateTransferFromDemandsUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createTransferFromDemandsDto,)
  }
);}


/**
 * Retrieve the event history for a specific transfer order.
 * @summary Find Events
 */
export type transfersControllerFindEventsResponse200 = {
  data: TransferEventResponseDto[]
  status: 200
}
    
export type transfersControllerFindEventsResponseSuccess = (transfersControllerFindEventsResponse200) & {
  headers: Headers;
};
;

export type transfersControllerFindEventsResponse = (transfersControllerFindEventsResponseSuccess)

export const getTransfersControllerFindEventsUrl = (id: string,) => {


  

  return `/transfers/${id}/events`
}

export const transfersControllerFindEvents = async (id: string, options?: RequestInit): Promise<transfersControllerFindEventsResponse> => {
  
  return customFetch<transfersControllerFindEventsResponse>(getTransfersControllerFindEventsUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * Retrieve the picking summary for a transfer order.
 * @summary Get Picking Summary
 */
export type transfersControllerGetPickingSummaryResponse200 = {
  data: TransferPickingSummaryResponseDto[]
  status: 200
}
    
export type transfersControllerGetPickingSummaryResponseSuccess = (transfersControllerGetPickingSummaryResponse200) & {
  headers: Headers;
};
;

export type transfersControllerGetPickingSummaryResponse = (transfersControllerGetPickingSummaryResponseSuccess)

export const getTransfersControllerGetPickingSummaryUrl = (id: string,) => {


  

  return `/transfers/${id}/picking`
}

export const transfersControllerGetPickingSummary = async (id: string, options?: RequestInit): Promise<transfersControllerGetPickingSummaryResponse> => {
  
  return customFetch<transfersControllerGetPickingSummaryResponse>(getTransfersControllerGetPickingSummaryUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * Record a picked quantity for a transfer order line item.
 * @summary Pick Transfer Line
 */
export type transfersControllerPickLineResponse201 = {
  data: TransferResponseDto
  status: 201
}
    
export type transfersControllerPickLineResponseSuccess = (transfersControllerPickLineResponse201) & {
  headers: Headers;
};
;

export type transfersControllerPickLineResponse = (transfersControllerPickLineResponseSuccess)

export const getTransfersControllerPickLineUrl = (id: string,
    lineId: string,) => {


  

  return `/transfers/${id}/picking/lines/${lineId}`
}

export const transfersControllerPickLine = async (id: string,
    lineId: string,
    pickLineDto: PickLineDto, options?: RequestInit): Promise<transfersControllerPickLineResponse> => {
  
  return customFetch<transfersControllerPickLineResponse>(getTransfersControllerPickLineUrl(id,lineId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      pickLineDto,)
  }
);}


/**
 * Cancel and revert a recorded pick for a transfer order.
 * @summary Cancel Transfer Pick
 */
export type transfersControllerCancelPickResponse200 = {
  data: TransferResponseDto
  status: 200
}
    
export type transfersControllerCancelPickResponseSuccess = (transfersControllerCancelPickResponse200) & {
  headers: Headers;
};
;

export type transfersControllerCancelPickResponse = (transfersControllerCancelPickResponseSuccess)

export const getTransfersControllerCancelPickUrl = (id: string,
    pickId: string,) => {


  

  return `/transfers/${id}/picking/picks/${pickId}`
}

export const transfersControllerCancelPick = async (id: string,
    pickId: string, options?: RequestInit): Promise<transfersControllerCancelPickResponse> => {
  
  return customFetch<transfersControllerCancelPickResponse>(getTransfersControllerCancelPickUrl(id,pickId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}


/**
 * Mark a transfer order as shipped and dispatch inventory.
 * @summary Ship Transfer Order
 */
export type transfersControllerShipTransferOrderResponse201 = {
  data: TransferResponseDto
  status: 201
}
    
export type transfersControllerShipTransferOrderResponseSuccess = (transfersControllerShipTransferOrderResponse201) & {
  headers: Headers;
};
;

export type transfersControllerShipTransferOrderResponse = (transfersControllerShipTransferOrderResponseSuccess)

export const getTransfersControllerShipTransferOrderUrl = (id: string,) => {


  

  return `/transfers/${id}/ship`
}

export const transfersControllerShipTransferOrder = async (id: string,
    emptyBodyDto: EmptyBodyDto, options?: RequestInit): Promise<transfersControllerShipTransferOrderResponse> => {
  
  return customFetch<transfersControllerShipTransferOrderResponse>(getTransfersControllerShipTransferOrderUrl(id),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      emptyBodyDto,)
  }
);}


/**
 * Process the receipt of a transferred inventory.
 * @summary Receive Transfer Order
 */
export type transfersControllerReceiveTransferOrderResponse201 = {
  data: TransferResponseDto
  status: 201
}
    
export type transfersControllerReceiveTransferOrderResponseSuccess = (transfersControllerReceiveTransferOrderResponse201) & {
  headers: Headers;
};
;

export type transfersControllerReceiveTransferOrderResponse = (transfersControllerReceiveTransferOrderResponseSuccess)

export const getTransfersControllerReceiveTransferOrderUrl = (id: string,) => {


  

  return `/transfers/${id}/receive`
}

export const transfersControllerReceiveTransferOrder = async (id: string,
    receiveTransferDto: ReceiveTransferDto, options?: RequestInit): Promise<transfersControllerReceiveTransferOrderResponse> => {
  
  return customFetch<transfersControllerReceiveTransferOrderResponse>(getTransfersControllerReceiveTransferOrderUrl(id),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      receiveTransferDto,)
  }
);}


/**
 * Cancel an open transfer order and revert any picks.
 * @summary Cancel Transfer Order
 */
export type transfersControllerCancelTransferOrderResponse201 = {
  data: TransferResponseDto
  status: 201
}
    
export type transfersControllerCancelTransferOrderResponseSuccess = (transfersControllerCancelTransferOrderResponse201) & {
  headers: Headers;
};
;

export type transfersControllerCancelTransferOrderResponse = (transfersControllerCancelTransferOrderResponseSuccess)

export const getTransfersControllerCancelTransferOrderUrl = (id: string,) => {


  

  return `/transfers/${id}/cancel`
}

export const transfersControllerCancelTransferOrder = async (id: string,
    emptyBodyDto: EmptyBodyDto, options?: RequestInit): Promise<transfersControllerCancelTransferOrderResponse> => {
  
  return customFetch<transfersControllerCancelTransferOrderResponse>(getTransfersControllerCancelTransferOrderUrl(id),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      emptyBodyDto,)
  }
);}


/**
 * Cancel the active dispatched shipment of a transfer order.
 * @summary Cancel Transfer Order Shipment
 */
export type transfersControllerCancelTransferOrderShipmentResponse201 = {
  data: TransferResponseDto
  status: 201
}
    
export type transfersControllerCancelTransferOrderShipmentResponseSuccess = (transfersControllerCancelTransferOrderShipmentResponse201) & {
  headers: Headers;
};
;

export type transfersControllerCancelTransferOrderShipmentResponse = (transfersControllerCancelTransferOrderShipmentResponseSuccess)

export const getTransfersControllerCancelTransferOrderShipmentUrl = (id: string,) => {


  

  return `/transfers/${id}/cancel-shipment`
}

export const transfersControllerCancelTransferOrderShipment = async (id: string,
    emptyBodyDto: EmptyBodyDto, options?: RequestInit): Promise<transfersControllerCancelTransferOrderShipmentResponse> => {
  
  return customFetch<transfersControllerCancelTransferOrderShipmentResponse>(getTransfersControllerCancelTransferOrderShipmentUrl(id),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      emptyBodyDto,)
  }
);}


/**
 * Retrieve a paginated list of transfer orders.
 * @summary Find All Transfers
 */
export type transfersControllerFindAllResponse200 = {
  data: TransfersControllerFindAll200
  status: 200
}
    
export type transfersControllerFindAllResponseSuccess = (transfersControllerFindAllResponse200) & {
  headers: Headers;
};
;

export type transfersControllerFindAllResponse = (transfersControllerFindAllResponseSuccess)

export const getTransfersControllerFindAllUrl = (params?: TransfersControllerFindAllParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/transfers?${stringifiedParams}` : `/transfers`
}

export const transfersControllerFindAll = async (params?: TransfersControllerFindAllParams, options?: RequestInit): Promise<transfersControllerFindAllResponse> => {
  
  return customFetch<transfersControllerFindAllResponse>(getTransfersControllerFindAllUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * Create a new transfer order.
 * @summary Create Transfer Order
 */
export type transfersControllerCreateResponse201 = {
  data: TransferResponseDto
  status: 201
}
    
export type transfersControllerCreateResponseSuccess = (transfersControllerCreateResponse201) & {
  headers: Headers;
};
;

export type transfersControllerCreateResponse = (transfersControllerCreateResponseSuccess)

export const getTransfersControllerCreateUrl = () => {


  

  return `/transfers`
}

export const transfersControllerCreate = async (createTransferOrderDto: CreateTransferOrderDto, options?: RequestInit): Promise<transfersControllerCreateResponse> => {
  
  return customFetch<transfersControllerCreateResponse>(getTransfersControllerCreateUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createTransferOrderDto,)
  }
);}


/**
 * Retrieve detailed information for a specific transfer order.
 * @summary Find Transfer
 */
export type transfersControllerFindOneResponse200 = {
  data: TransferResponseDto
  status: 200
}
    
export type transfersControllerFindOneResponseSuccess = (transfersControllerFindOneResponse200) & {
  headers: Headers;
};
;

export type transfersControllerFindOneResponse = (transfersControllerFindOneResponseSuccess)

export const getTransfersControllerFindOneUrl = (id: string,
    params?: TransfersControllerFindOneParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/transfers/${id}?${stringifiedParams}` : `/transfers/${id}`
}

export const transfersControllerFindOne = async (id: string,
    params?: TransfersControllerFindOneParams, options?: RequestInit): Promise<transfersControllerFindOneResponse> => {
  
  return customFetch<transfersControllerFindOneResponse>(getTransfersControllerFindOneUrl(id,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * Modify the details of a draft transfer order.
 * @summary Update Transfer Order
 */
export type transfersControllerUpdateResponse200 = {
  data: TransferResponseDto
  status: 200
}
    
export type transfersControllerUpdateResponseSuccess = (transfersControllerUpdateResponse200) & {
  headers: Headers;
};
;

export type transfersControllerUpdateResponse = (transfersControllerUpdateResponseSuccess)

export const getTransfersControllerUpdateUrl = (id: string,) => {


  

  return `/transfers/${id}`
}

export const transfersControllerUpdate = async (id: string,
    updateTransferOrderDto: UpdateTransferOrderDto, options?: RequestInit): Promise<transfersControllerUpdateResponse> => {
  
  return customFetch<transfersControllerUpdateResponse>(getTransfersControllerUpdateUrl(id),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateTransferOrderDto,)
  }
);}


/**
 * Retrieve all shipments for a specific transfer order.
 * @summary Find Shipments
 */
export type transfersControllerFindShipmentsResponse200 = {
  data: ShipmentResponseDto[]
  status: 200
}
    
export type transfersControllerFindShipmentsResponseSuccess = (transfersControllerFindShipmentsResponse200) & {
  headers: Headers;
};
;

export type transfersControllerFindShipmentsResponse = (transfersControllerFindShipmentsResponseSuccess)

export const getTransfersControllerFindShipmentsUrl = (id: string,) => {


  

  return `/transfers/${id}/shipments`
}

export const transfersControllerFindShipments = async (id: string, options?: RequestInit): Promise<transfersControllerFindShipmentsResponse> => {
  
  return customFetch<transfersControllerFindShipmentsResponse>(getTransfersControllerFindShipmentsUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * Add a new line item to a transfer order.
 * @summary Add Transfer Line
 */
export type transfersControllerAddLineResponse201 = {
  data: TransferResponseDto
  status: 201
}
    
export type transfersControllerAddLineResponseSuccess = (transfersControllerAddLineResponse201) & {
  headers: Headers;
};
;

export type transfersControllerAddLineResponse = (transfersControllerAddLineResponseSuccess)

export const getTransfersControllerAddLineUrl = (id: string,) => {


  

  return `/transfers/${id}/lines`
}

export const transfersControllerAddLine = async (id: string,
    createTransferOrderLineDto: CreateTransferOrderLineDto, options?: RequestInit): Promise<transfersControllerAddLineResponse> => {
  
  return customFetch<transfersControllerAddLineResponse>(getTransfersControllerAddLineUrl(id),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createTransferOrderLineDto,)
  }
);}


/**
 * Modify an existing line item on a transfer order.
 * @summary Update Transfer Line
 */
export type transfersControllerUpdateLineResponse200 = {
  data: TransferResponseDto
  status: 200
}
    
export type transfersControllerUpdateLineResponseSuccess = (transfersControllerUpdateLineResponse200) & {
  headers: Headers;
};
;

export type transfersControllerUpdateLineResponse = (transfersControllerUpdateLineResponseSuccess)

export const getTransfersControllerUpdateLineUrl = (id: string,
    lineId: string,) => {


  

  return `/transfers/${id}/lines/${lineId}`
}

export const transfersControllerUpdateLine = async (id: string,
    lineId: string,
    updateTransferOrderLineDto: UpdateTransferOrderLineDto, options?: RequestInit): Promise<transfersControllerUpdateLineResponse> => {
  
  return customFetch<transfersControllerUpdateLineResponse>(getTransfersControllerUpdateLineUrl(id,lineId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateTransferOrderLineDto,)
  }
);}


/**
 * Delete a line item from a transfer order.
 * @summary Remove Transfer Line
 */
export type transfersControllerRemoveLineResponse200 = {
  data: TransferResponseDto
  status: 200
}
    
export type transfersControllerRemoveLineResponseSuccess = (transfersControllerRemoveLineResponse200) & {
  headers: Headers;
};
;

export type transfersControllerRemoveLineResponse = (transfersControllerRemoveLineResponseSuccess)

export const getTransfersControllerRemoveLineUrl = (id: string,
    lineId: string,) => {


  

  return `/transfers/${id}/lines/${lineId}`
}

export const transfersControllerRemoveLine = async (id: string,
    lineId: string, options?: RequestInit): Promise<transfersControllerRemoveLineResponse> => {
  
  return customFetch<transfersControllerRemoveLineResponse>(getTransfersControllerRemoveLineUrl(id,lineId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}


