/**
 * @module @herobm/shared/state-machines
 *
 * Single source of truth for every entity state machine in the platform.
 * Both the API (NestJS) and the portal UI (Next.js) import from here.
 *
 * Rules:
 *   1. Never duplicate these maps in consumer code.
 *   2. Every `changeState` endpoint MUST validate against its transition map.
 *   3. If a new entity needs states, add its map here first.
 */

// ============================================================================
// Transition maps  (from → allowed next states)
// ============================================================================


export const SALES_ORDER_STATE = {
  ARCHIVED: 'archived',
  CANCELLED: 'cancelled',
  CONFIRMED: 'confirmed',
  DRAFT: 'draft',
  INVOICED: 'invoiced',
  PICKING: 'picking',
  QUOTED: 'quoted',
  SHIPPED: 'shipped',
} as const;

export const SALES_ORDER_TRANSITIONS: Record<string, string[]> = {
  [SALES_ORDER_STATE.DRAFT]: [SALES_ORDER_STATE.QUOTED, SALES_ORDER_STATE.CANCELLED],
  [SALES_ORDER_STATE.QUOTED]: [SALES_ORDER_STATE.CONFIRMED, SALES_ORDER_STATE.DRAFT, SALES_ORDER_STATE.CANCELLED],
  [SALES_ORDER_STATE.CONFIRMED]: [SALES_ORDER_STATE.PICKING, SALES_ORDER_STATE.CANCELLED, SALES_ORDER_STATE.QUOTED],
  [SALES_ORDER_STATE.PICKING]: [SALES_ORDER_STATE.SHIPPED, SALES_ORDER_STATE.QUOTED],
  [SALES_ORDER_STATE.SHIPPED]: [SALES_ORDER_STATE.INVOICED],
  [SALES_ORDER_STATE.INVOICED]: [],
  [SALES_ORDER_STATE.CANCELLED]: [SALES_ORDER_STATE.DRAFT, SALES_ORDER_STATE.ARCHIVED],
  [SALES_ORDER_STATE.ARCHIVED]: [SALES_ORDER_STATE.CANCELLED],
};

export const PURCHASE_ORDER_STATE = {
  ARCHIVED: 'archived',
  CANCELLED: 'cancelled',
  CLOSED_SHORT: 'closed_short',
  DRAFT: 'draft',
  INVOICED: 'invoiced',
  ORDERED: 'ordered',
  PARTIALLY_RECEIVED: 'partially_received',
  RECEIVED: 'received',
} as const;

export const PURCHASE_ORDER_TRANSITIONS: Record<string, string[]> = {
  [PURCHASE_ORDER_STATE.DRAFT]: [PURCHASE_ORDER_STATE.ORDERED, PURCHASE_ORDER_STATE.CANCELLED],
  [PURCHASE_ORDER_STATE.ORDERED]: [PURCHASE_ORDER_STATE.PARTIALLY_RECEIVED, PURCHASE_ORDER_STATE.RECEIVED, PURCHASE_ORDER_STATE.CANCELLED, PURCHASE_ORDER_STATE.CLOSED_SHORT],
  [PURCHASE_ORDER_STATE.PARTIALLY_RECEIVED]: [PURCHASE_ORDER_STATE.RECEIVED, PURCHASE_ORDER_STATE.CLOSED_SHORT, PURCHASE_ORDER_STATE.ORDERED],
  [PURCHASE_ORDER_STATE.RECEIVED]: [PURCHASE_ORDER_STATE.INVOICED, PURCHASE_ORDER_STATE.PARTIALLY_RECEIVED, PURCHASE_ORDER_STATE.ORDERED],
  [PURCHASE_ORDER_STATE.INVOICED]: [],
  [PURCHASE_ORDER_STATE.CANCELLED]: [PURCHASE_ORDER_STATE.DRAFT, PURCHASE_ORDER_STATE.ARCHIVED],
  [PURCHASE_ORDER_STATE.CLOSED_SHORT]: [PURCHASE_ORDER_STATE.ARCHIVED],
  [PURCHASE_ORDER_STATE.ARCHIVED]: [PURCHASE_ORDER_STATE.CANCELLED],
};

export const PURCHASE_INVOICE_STATE = {
  ARCHIVED: 'archived',
  CANCELLED: 'cancelled',
  DRAFT: 'draft',
  INVOICED: 'invoiced',
  PAID: 'paid',
  PARTIALLY_PAID: 'partially_paid',
} as const;

export const PURCHASE_INVOICE_TRANSITIONS: Record<string, string[]> = {
  [PURCHASE_INVOICE_STATE.DRAFT]: [PURCHASE_INVOICE_STATE.INVOICED, PURCHASE_INVOICE_STATE.CANCELLED],
  [PURCHASE_INVOICE_STATE.INVOICED]: [PURCHASE_INVOICE_STATE.PARTIALLY_PAID, PURCHASE_INVOICE_STATE.PAID, PURCHASE_INVOICE_STATE.CANCELLED],
  [PURCHASE_INVOICE_STATE.PARTIALLY_PAID]: [PURCHASE_INVOICE_STATE.INVOICED, PURCHASE_INVOICE_STATE.PAID],
  [PURCHASE_INVOICE_STATE.PAID]: [PURCHASE_INVOICE_STATE.PARTIALLY_PAID, PURCHASE_INVOICE_STATE.INVOICED],
  [PURCHASE_INVOICE_STATE.CANCELLED]: [PURCHASE_INVOICE_STATE.DRAFT],
  [PURCHASE_INVOICE_STATE.ARCHIVED]: [],
};

export const SALES_INVOICE_STATE = {
  ARCHIVED: 'archived',
  CANCELLED: 'cancelled',
  DRAFT: 'draft',
  INVOICED: 'invoiced',
  PAID: 'paid',
  PARTIALLY_PAID: 'partially_paid',
} as const;

export const SALES_INVOICE_TRANSITIONS: Record<string, string[]> = {
  [SALES_INVOICE_STATE.DRAFT]: [SALES_INVOICE_STATE.INVOICED, SALES_INVOICE_STATE.CANCELLED],
  [SALES_INVOICE_STATE.INVOICED]: [SALES_INVOICE_STATE.PARTIALLY_PAID, SALES_INVOICE_STATE.PAID, SALES_INVOICE_STATE.CANCELLED],
  [SALES_INVOICE_STATE.PARTIALLY_PAID]: [SALES_INVOICE_STATE.INVOICED, SALES_INVOICE_STATE.PAID],
  [SALES_INVOICE_STATE.PAID]: [SALES_INVOICE_STATE.PARTIALLY_PAID, SALES_INVOICE_STATE.INVOICED],
  [SALES_INVOICE_STATE.CANCELLED]: [SALES_INVOICE_STATE.DRAFT],
  [SALES_INVOICE_STATE.ARCHIVED]: [],
};

export const SHIPMENT_STATE = {
  CANCELLED: 'cancelled',
  DISPATCHED: 'dispatched',
  DRAFT: 'draft',
} as const;

export const RECONCILIATION_STATE = {
  DRAFT: 'draft',
  POSTED: 'posted',
} as const;

export const RECONCILIATION_TRANSITIONS: Record<string, string[]> = {
  [RECONCILIATION_STATE.DRAFT]: [RECONCILIATION_STATE.POSTED],
  [RECONCILIATION_STATE.POSTED]: [],
};

export const SHIPMENT_TRANSITIONS: Record<string, string[]> = {
  [SHIPMENT_STATE.DRAFT]: [SHIPMENT_STATE.DISPATCHED, SHIPMENT_STATE.CANCELLED],
  [SHIPMENT_STATE.DISPATCHED]: [SHIPMENT_STATE.CANCELLED],
  [SHIPMENT_STATE.CANCELLED]: [],
};

export const GOODS_RECEIVED_STATE = {
  CANCELLED: 'cancelled',
  RECEIVED: 'received',
} as const;



export const GOODS_RECEIVED_TRANSITIONS: Record<string, string[]> = {
  [GOODS_RECEIVED_STATE.RECEIVED]: [GOODS_RECEIVED_STATE.CANCELLED],
  [GOODS_RECEIVED_STATE.CANCELLED]: [],
};



export const SALES_ORDER_PICK_STATE = {
  CANCELLED: 'cancelled',
  PICKED: 'picked',
  SHIPPED: 'shipped',
} as const;

export const SALES_ORDER_PICK_TRANSITIONS: Record<string, string[]> = {
  [SALES_ORDER_PICK_STATE.PICKED]: [SALES_ORDER_PICK_STATE.SHIPPED, SALES_ORDER_PICK_STATE.CANCELLED],
  [SALES_ORDER_PICK_STATE.SHIPPED]: [SALES_ORDER_PICK_STATE.PICKED, SALES_ORDER_PICK_STATE.CANCELLED],
  [SALES_ORDER_PICK_STATE.CANCELLED]: [],
};

export const PUTAWAY_STATUS = {
  AWAITING_MATCHING: 'awaiting_matching',
  PENDING_PUTAWAY: 'pending_putaway',
  QUARANTINED: 'quarantined',
  COMPLETED: 'completed',
} as const;

export const MATCH_STATUS = {
  MATCHED: 'matched',
  UNMATCHED: 'unmatched',
  AMBIGUOUS: 'ambiguous',
} as const;

export const TRANSFER_ORDER_PICK_STATE = {
  CANCELLED: 'cancelled',
  PICKED: 'picked',
  SHIPPED: 'shipped',
} as const;

export const TRANSFER_ORDER_PICK_TRANSITIONS: Record<string, string[]> = {
  [TRANSFER_ORDER_PICK_STATE.PICKED]: [TRANSFER_ORDER_PICK_STATE.SHIPPED, TRANSFER_ORDER_PICK_STATE.CANCELLED],
  [TRANSFER_ORDER_PICK_STATE.SHIPPED]: [TRANSFER_ORDER_PICK_STATE.PICKED],
  [TRANSFER_ORDER_PICK_STATE.CANCELLED]: [],
};


export const PURCHASE_RETURN_STATE = {
  CANCELLED: 'cancelled',
  DRAFT: 'draft',
  STAGED: 'staged',
  SHIPPED: 'shipped',
} as const;

export const PURCHASE_RETURN_TRANSITIONS: Record<string, string[]> = {
  [PURCHASE_RETURN_STATE.DRAFT]: [PURCHASE_RETURN_STATE.STAGED, PURCHASE_RETURN_STATE.CANCELLED],
  [PURCHASE_RETURN_STATE.STAGED]: [PURCHASE_RETURN_STATE.SHIPPED, PURCHASE_RETURN_STATE.CANCELLED],
  [PURCHASE_RETURN_STATE.SHIPPED]: [PURCHASE_RETURN_STATE.CANCELLED],
  [PURCHASE_RETURN_STATE.CANCELLED]: [],
};

export const PURCHASE_RETURN_SHIPMENT_STATE = {
  CANCELLED: 'cancelled',
  DISPATCHED: 'dispatched',
  DRAFT: 'draft',
  SHIPPED: 'shipped',
} as const;

export const PURCHASE_RETURN_SHIPMENT_TRANSITIONS: Record<string, string[]> = {
  [PURCHASE_RETURN_SHIPMENT_STATE.DRAFT]: [PURCHASE_RETURN_SHIPMENT_STATE.DISPATCHED, PURCHASE_RETURN_SHIPMENT_STATE.CANCELLED],
  [PURCHASE_RETURN_SHIPMENT_STATE.DISPATCHED]: [PURCHASE_RETURN_SHIPMENT_STATE.CANCELLED],
  [PURCHASE_RETURN_SHIPMENT_STATE.CANCELLED]: [],
};

export const PURCHASE_DEBIT_NOTE_STATE = {
  CANCELLED: 'cancelled',
  DRAFT: 'draft',
  POSTED: 'posted',
} as const;

export const PURCHASE_DEBIT_NOTE_TRANSITIONS: Record<string, string[]> = {
  [PURCHASE_DEBIT_NOTE_STATE.DRAFT]: [PURCHASE_DEBIT_NOTE_STATE.POSTED, PURCHASE_DEBIT_NOTE_STATE.CANCELLED],
  [PURCHASE_DEBIT_NOTE_STATE.POSTED]: [PURCHASE_DEBIT_NOTE_STATE.CANCELLED],
  [PURCHASE_DEBIT_NOTE_STATE.CANCELLED]: [],
};


export const RETURN_STATE = {
  CANCELLED: 'cancelled',
  CONFIRMED: 'confirmed',
  DRAFT: 'draft',
  PARTIALLY_RECEIVED: 'partially_received',
  RECEIVED: 'received',
  PROCESSED: 'processed',
} as const;

export const RETURN_RESOLUTION = {
  REFUND: 'refund',
  REPLACE: 'replace',
} as const;

export const RETURN_TRANSITIONS: Record<string, string[]> = {
  [RETURN_STATE.DRAFT]: [RETURN_STATE.CONFIRMED, RETURN_STATE.CANCELLED],
  [RETURN_STATE.CONFIRMED]: [RETURN_STATE.PARTIALLY_RECEIVED, RETURN_STATE.RECEIVED, RETURN_STATE.CANCELLED],
  [RETURN_STATE.PARTIALLY_RECEIVED]: [RETURN_STATE.RECEIVED],
  [RETURN_STATE.RECEIVED]: [RETURN_STATE.PROCESSED],
  [RETURN_STATE.PROCESSED]: [RETURN_STATE.CANCELLED],
  [RETURN_STATE.CANCELLED]: [],
};

export const SALES_CREDIT_NOTE_STATE = {
  CANCELLED: 'cancelled',
  DRAFT: 'draft',
  POSTED: 'posted',
} as const;

export const SALES_CREDIT_NOTE_TRANSITIONS: Record<string, string[]> = {
  [SALES_CREDIT_NOTE_STATE.DRAFT]: [SALES_CREDIT_NOTE_STATE.POSTED, SALES_CREDIT_NOTE_STATE.CANCELLED],
  [SALES_CREDIT_NOTE_STATE.POSTED]: [SALES_CREDIT_NOTE_STATE.CANCELLED],
  [SALES_CREDIT_NOTE_STATE.CANCELLED]: [],
};


export const BACKORDER_STATE = {
  PENDING_SUPPLY: 'pending_supply',
  AWAITING_RECEIPT: 'awaiting_receipt',
  RECEIVED_RESERVED: 'received_reserved',
  FULFILLED: 'fulfilled',
  CANCELLED: 'cancelled',
} as const;

export const BACKORDER_TRANSITIONS: Record<string, string[]> = {
  [BACKORDER_STATE.PENDING_SUPPLY]: [BACKORDER_STATE.AWAITING_RECEIPT, BACKORDER_STATE.CANCELLED],
  [BACKORDER_STATE.AWAITING_RECEIPT]: [BACKORDER_STATE.PENDING_SUPPLY, BACKORDER_STATE.RECEIVED_RESERVED, BACKORDER_STATE.CANCELLED],
  [BACKORDER_STATE.RECEIVED_RESERVED]: [BACKORDER_STATE.AWAITING_RECEIPT, BACKORDER_STATE.FULFILLED, BACKORDER_STATE.CANCELLED],
  [BACKORDER_STATE.FULFILLED]: [],
  [BACKORDER_STATE.CANCELLED]: [BACKORDER_STATE.PENDING_SUPPLY],
};

export const TRANSFER_ORDER_STATE = {
  CONFIRMED: 'confirmed',
  PICKING: 'picking',
  SHIPPED: 'shipped',
  PARTIALLY_RECEIVED: 'partially_received',
  RECEIVED: 'received',
  CANCELLED: 'cancelled',
} as const;

export const TRANSFER_ORDER_TRANSITIONS: Record<string, string[]> = {
  [TRANSFER_ORDER_STATE.CONFIRMED]: [TRANSFER_ORDER_STATE.PICKING, TRANSFER_ORDER_STATE.CANCELLED],
  [TRANSFER_ORDER_STATE.PICKING]: [TRANSFER_ORDER_STATE.SHIPPED, TRANSFER_ORDER_STATE.CANCELLED],
  [TRANSFER_ORDER_STATE.SHIPPED]: [TRANSFER_ORDER_STATE.PARTIALLY_RECEIVED, TRANSFER_ORDER_STATE.RECEIVED, TRANSFER_ORDER_STATE.PICKING],
  [TRANSFER_ORDER_STATE.PARTIALLY_RECEIVED]: [TRANSFER_ORDER_STATE.RECEIVED],
  [TRANSFER_ORDER_STATE.RECEIVED]: [],
  [TRANSFER_ORDER_STATE.CANCELLED]: [],
};

export const PAYMENT_TYPE = {
  CUSTOMER_RECEIPT: 'customer_receipt',
  SUPPLIER_PAYMENT: 'supplier_payment',
  CUSTOMER_REFUND: 'customer_refund',
  SUPPLIER_REFUND: 'supplier_refund',
  DIRECT_RECEIPT: 'direct_receipt',
  DIRECT_PAYMENT: 'direct_payment',
} as const;

export type PaymentType = typeof PAYMENT_TYPE[keyof typeof PAYMENT_TYPE];

export const PAYMENT_STATE = {
  DRAFT: 'draft',
  EXPORTED: 'exported',
  SUBMITTED: 'submitted',
  CANCELLED: 'cancelled',
} as const;

export const PAYMENT_TRANSITIONS: Record<string, string[]> = {
  [PAYMENT_STATE.DRAFT]: [PAYMENT_STATE.EXPORTED, PAYMENT_STATE.SUBMITTED, PAYMENT_STATE.CANCELLED],
  [PAYMENT_STATE.EXPORTED]: [PAYMENT_STATE.SUBMITTED, PAYMENT_STATE.DRAFT, PAYMENT_STATE.CANCELLED],
  [PAYMENT_STATE.SUBMITTED]: [PAYMENT_STATE.CANCELLED],
  [PAYMENT_STATE.CANCELLED]: [],
};

export const CUSTOMER_STATE = {
  DRAFT: 'draft',
  ACTIVE: 'active',
  INACTIVE: 'inactive',
  ARCHIVED: 'archived',
} as const;

export const CUSTOMER_TRANSITIONS: Record<string, string[]> = {
  [CUSTOMER_STATE.DRAFT]: [CUSTOMER_STATE.ACTIVE, CUSTOMER_STATE.ARCHIVED],
  [CUSTOMER_STATE.ACTIVE]: [CUSTOMER_STATE.INACTIVE, CUSTOMER_STATE.ARCHIVED],
  [CUSTOMER_STATE.INACTIVE]: [CUSTOMER_STATE.ACTIVE, CUSTOMER_STATE.ARCHIVED],
  [CUSTOMER_STATE.ARCHIVED]: [CUSTOMER_STATE.ACTIVE],
};

export const SUPPLIER_STATE = {
  ACTIVE: 'active',
  INACTIVE: 'inactive',
  ARCHIVED: 'archived',
} as const;

export const SUPPLIER_TRANSITIONS: Record<string, string[]> = {
  [SUPPLIER_STATE.ACTIVE]: [SUPPLIER_STATE.INACTIVE, SUPPLIER_STATE.ARCHIVED],
  [SUPPLIER_STATE.INACTIVE]: [SUPPLIER_STATE.ACTIVE, SUPPLIER_STATE.ARCHIVED],
  [SUPPLIER_STATE.ARCHIVED]: [SUPPLIER_STATE.ACTIVE],
};

export const PRODUCT_STATE = {
  ACTIVE: 'active',
  INACTIVE: 'inactive',
  DISCONTINUED: 'discontinued',
  ARCHIVED: 'archived',
  DRAFT: 'draft',
} as const;

export const ACTOR_STATE = {
  ACTIVE: 'active',
  INACTIVE: 'inactive',
  ARCHIVED: 'archived',
} as const;

export const CONTACT_STATE = {
  ACTIVE: 'active',
  INACTIVE: 'inactive',
  ARCHIVED: 'archived',
} as const;

export const PROJECT_STATE = {
  ACTIVE: 'active',
  INACTIVE: 'inactive',
  ARCHIVED: 'archived',
} as const;

export const PRODUCT_TRANSITIONS: Record<string, string[]> = {
  [PRODUCT_STATE.DRAFT]: [PRODUCT_STATE.ACTIVE, PRODUCT_STATE.ARCHIVED],
  [PRODUCT_STATE.ACTIVE]: [
    PRODUCT_STATE.INACTIVE,
    PRODUCT_STATE.DISCONTINUED,
    PRODUCT_STATE.ARCHIVED,
    PRODUCT_STATE.DRAFT,
  ],
  [PRODUCT_STATE.INACTIVE]: [
    PRODUCT_STATE.ACTIVE,
    PRODUCT_STATE.DISCONTINUED,
    PRODUCT_STATE.ARCHIVED,
  ],
  [PRODUCT_STATE.DISCONTINUED]: [
    PRODUCT_STATE.ACTIVE,
    PRODUCT_STATE.INACTIVE,
    PRODUCT_STATE.ARCHIVED,
  ],
  [PRODUCT_STATE.ARCHIVED]: [
    PRODUCT_STATE.ACTIVE,
    PRODUCT_STATE.DRAFT,
    PRODUCT_STATE.INACTIVE,
    PRODUCT_STATE.DISCONTINUED,
  ],
};

export type SalesOrderState = typeof SALES_ORDER_STATE[keyof typeof SALES_ORDER_STATE];
export type PurchaseOrderState = typeof PURCHASE_ORDER_STATE[keyof typeof PURCHASE_ORDER_STATE];
export type PurchaseInvoiceState = typeof PURCHASE_INVOICE_STATE[keyof typeof PURCHASE_INVOICE_STATE];
export type SalesInvoiceState = typeof SALES_INVOICE_STATE[keyof typeof SALES_INVOICE_STATE];
export type ShipmentState = typeof SHIPMENT_STATE[keyof typeof SHIPMENT_STATE];
export type GoodsReceivedState = typeof GOODS_RECEIVED_STATE[keyof typeof GOODS_RECEIVED_STATE];
export type PurchaseReturnState = typeof PURCHASE_RETURN_STATE[keyof typeof PURCHASE_RETURN_STATE];
export type ReturnState = typeof RETURN_STATE[keyof typeof RETURN_STATE];
export type ReturnResolution = typeof RETURN_RESOLUTION[keyof typeof RETURN_RESOLUTION];
export type SalesCreditNoteState = typeof SALES_CREDIT_NOTE_STATE[keyof typeof SALES_CREDIT_NOTE_STATE];
export type SalesOrderPickState = typeof SALES_ORDER_PICK_STATE[keyof typeof SALES_ORDER_PICK_STATE];
export type BackorderState = typeof BACKORDER_STATE[keyof typeof BACKORDER_STATE];
export type TransferOrderState = typeof TRANSFER_ORDER_STATE[keyof typeof TRANSFER_ORDER_STATE];
export type TransferOrderPickState = typeof TRANSFER_ORDER_PICK_STATE[keyof typeof TRANSFER_ORDER_PICK_STATE];
export type PaymentState = typeof PAYMENT_STATE[keyof typeof PAYMENT_STATE];
export type CustomerState = typeof CUSTOMER_STATE[keyof typeof CUSTOMER_STATE];
export type SupplierState = typeof SUPPLIER_STATE[keyof typeof SUPPLIER_STATE];
export type ProductState = typeof PRODUCT_STATE[keyof typeof PRODUCT_STATE];
export type ActorState = typeof ACTOR_STATE[keyof typeof ACTOR_STATE];
export type ContactState = typeof CONTACT_STATE[keyof typeof CONTACT_STATE];
export type ProjectState = typeof PROJECT_STATE[keyof typeof PROJECT_STATE];
export type ReconciliationState = typeof RECONCILIATION_STATE[keyof typeof RECONCILIATION_STATE];
export type PurchaseReturnShipmentState = typeof PURCHASE_RETURN_SHIPMENT_STATE[keyof typeof PURCHASE_RETURN_SHIPMENT_STATE];
export type PurchaseDebitNoteState = typeof PURCHASE_DEBIT_NOTE_STATE[keyof typeof PURCHASE_DEBIT_NOTE_STATE];

// ============================================================================
// Lifecycle ordinals  (higher = further along the happy path)
//
// Used by the UI to decide whether a transition button is "forward" (primary)
// or "backward" (secondary).  `cancelled` is always ordinal 0.
// ============================================================================

export const SALES_ORDER_LIFECYCLE: Record<string, number> = {
  [SALES_ORDER_STATE.CANCELLED]: 0,
  [SALES_ORDER_STATE.DRAFT]: 1,
  [SALES_ORDER_STATE.QUOTED]: 2,
  [SALES_ORDER_STATE.CONFIRMED]: 3,
  [SALES_ORDER_STATE.PICKING]: 4,
  [SALES_ORDER_STATE.SHIPPED]: 5,
  [SALES_ORDER_STATE.INVOICED]: 6,
  [SALES_ORDER_STATE.ARCHIVED]: 8,
};

export const PURCHASE_ORDER_LIFECYCLE: Record<string, number> = {
  [PURCHASE_ORDER_STATE.CANCELLED]: 0,
  [PURCHASE_ORDER_STATE.CLOSED_SHORT]: 0,
  [PURCHASE_ORDER_STATE.DRAFT]: 1,
  [PURCHASE_ORDER_STATE.ORDERED]: 2,
  [PURCHASE_ORDER_STATE.PARTIALLY_RECEIVED]: 3,
  [PURCHASE_ORDER_STATE.RECEIVED]: 4,
  [PURCHASE_ORDER_STATE.INVOICED]: 5,
  [PURCHASE_ORDER_STATE.ARCHIVED]: 7,
};

export const OPEN_PURCHASE_ORDER_STATES: PurchaseOrderState[] = [
  PURCHASE_ORDER_STATE.DRAFT,
  PURCHASE_ORDER_STATE.ORDERED,
  PURCHASE_ORDER_STATE.PARTIALLY_RECEIVED,
];


export const PURCHASE_INVOICE_LIFECYCLE: Record<string, number> = {
  [PURCHASE_INVOICE_STATE.CANCELLED]: 0,
  [PURCHASE_INVOICE_STATE.DRAFT]: 1,
  [PURCHASE_INVOICE_STATE.INVOICED]: 2,
  [PURCHASE_INVOICE_STATE.PARTIALLY_PAID]: 3,
  [PURCHASE_INVOICE_STATE.PAID]: 4,
  [PURCHASE_INVOICE_STATE.ARCHIVED]: 6,
};

export const SALES_INVOICE_LIFECYCLE: Record<string, number> = {
  [SALES_INVOICE_STATE.CANCELLED]: 0,
  [SALES_INVOICE_STATE.DRAFT]: 1,
  [SALES_INVOICE_STATE.INVOICED]: 2,
  [SALES_INVOICE_STATE.PARTIALLY_PAID]: 3,
  [SALES_INVOICE_STATE.PAID]: 4,
  [SALES_INVOICE_STATE.ARCHIVED]: 6,
};

export const SHIPMENT_LIFECYCLE: Record<string, number> = {
  [SHIPMENT_STATE.CANCELLED]: 0,
  [SHIPMENT_STATE.DISPATCHED]: 1,
};

export const RECONCILIATION_LIFECYCLE: Record<string, number> = {
  [RECONCILIATION_STATE.DRAFT]: 1,
  [RECONCILIATION_STATE.POSTED]: 2,
};

export const GOODS_RECEIVED_LIFECYCLE: Record<string, number> = {
  [GOODS_RECEIVED_STATE.CANCELLED]: 0,
  [GOODS_RECEIVED_STATE.RECEIVED]: 1,
};



export const PURCHASE_RETURN_LIFECYCLE: Record<string, number> = {
  [PURCHASE_RETURN_STATE.CANCELLED]: 0,
  [PURCHASE_RETURN_STATE.DRAFT]: 1,
  [PURCHASE_RETURN_STATE.STAGED]: 2,
  [PURCHASE_RETURN_STATE.SHIPPED]: 3,
};

export const PURCHASE_RETURN_SHIPMENT_LIFECYCLE: Record<string, number> = {
  [PURCHASE_RETURN_SHIPMENT_STATE.CANCELLED]: 0,
  [PURCHASE_RETURN_SHIPMENT_STATE.DRAFT]: 1,
  [PURCHASE_RETURN_SHIPMENT_STATE.DISPATCHED]: 2,
  [PURCHASE_RETURN_SHIPMENT_STATE.SHIPPED]: 3,
};

export const PURCHASE_DEBIT_NOTE_LIFECYCLE: Record<string, number> = {
  [PURCHASE_DEBIT_NOTE_STATE.CANCELLED]: 0,
  [PURCHASE_DEBIT_NOTE_STATE.DRAFT]: 1,
  [PURCHASE_DEBIT_NOTE_STATE.POSTED]: 2,
};

export const RETURN_LIFECYCLE: Record<string, number> = {
  [RETURN_STATE.CANCELLED]: 0,
  [RETURN_STATE.DRAFT]: 1,
  [RETURN_STATE.CONFIRMED]: 2,
  [RETURN_STATE.RECEIVED]: 3,
  [RETURN_STATE.PROCESSED]: 4,
};

export const SALES_CREDIT_NOTE_LIFECYCLE: Record<string, number> = {
  [SALES_CREDIT_NOTE_STATE.CANCELLED]: 0,
  [SALES_CREDIT_NOTE_STATE.DRAFT]: 1,
  [SALES_CREDIT_NOTE_STATE.POSTED]: 2,
};

export const SALES_ORDER_PICK_LIFECYCLE: Record<string, number> = {
  [SALES_ORDER_PICK_STATE.CANCELLED]: 0,
  [SALES_ORDER_PICK_STATE.PICKED]: 1,
  [SALES_ORDER_PICK_STATE.SHIPPED]: 2,
};

export const TRANSFER_ORDER_PICK_LIFECYCLE: Record<string, number> = {
  [TRANSFER_ORDER_PICK_STATE.CANCELLED]: 0,
  [TRANSFER_ORDER_PICK_STATE.PICKED]: 1,
  [TRANSFER_ORDER_PICK_STATE.SHIPPED]: 2,
};


export const BACKORDER_LIFECYCLE: Record<string, number> = {
  [BACKORDER_STATE.CANCELLED]: 0,
  [BACKORDER_STATE.PENDING_SUPPLY]: 1,
  [BACKORDER_STATE.AWAITING_RECEIPT]: 2,
  [BACKORDER_STATE.RECEIVED_RESERVED]: 3,
  [BACKORDER_STATE.FULFILLED]: 4,
};

// ============================================================================
// Helpers
// ============================================================================

/** Get the allowed next states for a given current state. */
export function getAllowedTransitions(
  map: Record<string, string[]>,
  currentState: string,
): string[] {
  return map[currentState] ?? [];
}

/** Get all valid state names from a transition map. */
export function getValidStates(map: Record<string, string[]>): string[] {
  return Object.keys(map);
}

/**
 * Is the transition a "backward" move on the lifecycle?
 * Used by UI to render ← buttons for demotions and → for promotions.
 * `cancelled` is never treated as a backward transition (it gets its own styling).
 */
export function isBackTransition(
  lifecycle: Record<string, number>,
  from: string,
  to: string,
): boolean {
  return (lifecycle[to] ?? 99) < (lifecycle[from] ?? 99) && to !== SALES_ORDER_STATE.CANCELLED;
}

/** Capitalise the first letter of a string. */
export function cap(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}
