/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type {
  AddReturnLineDto,
  ChangeReturnStateDto,
  CreateReturnDto,
  CreateSalesCreditNoteDto,
  EmptyBodyDto,
  GlobalReturnListResponseDto,
  GlobalReturnsControllerFindGlobalReturnsParams,
  ReceiveReturnDto,
  ReturnResponseDto,
  SalesCreditNoteResponseDto,
  SalesCreditNotesControllerFindAllParams,
  UpdateReturnDto,
  UpdateReturnLineDto
} from '../../model';

import { customFetch } from '../../mutator';

/**
 * Create a new customer return (RMA) against a sales order.
 * @summary Create Return
 */
export type orderReturnsControllerCreateReturnResponse201 = {
  data: ReturnResponseDto
  status: 201
}
    
export type orderReturnsControllerCreateReturnResponseSuccess = (orderReturnsControllerCreateReturnResponse201) & {
  headers: Headers;
};
;

export type orderReturnsControllerCreateReturnResponse = (orderReturnsControllerCreateReturnResponseSuccess)

export const getOrderReturnsControllerCreateReturnUrl = (id: string,) => {


  

  return `/sales-orders/${id}/returns`
}

export const orderReturnsControllerCreateReturn = async (id: string,
    createReturnDto: CreateReturnDto, options?: RequestInit): Promise<orderReturnsControllerCreateReturnResponse> => {
  
  return customFetch<orderReturnsControllerCreateReturnResponse>(getOrderReturnsControllerCreateReturnUrl(id),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createReturnDto,)
  }
);}


/**
 * Retrieve all returns associated with a specific sales order.
 * @summary Find Order Returns
 */
export type orderReturnsControllerFindReturnsResponse200 = {
  data: ReturnResponseDto
  status: 200
}
    
export type orderReturnsControllerFindReturnsResponseSuccess = (orderReturnsControllerFindReturnsResponse200) & {
  headers: Headers;
};
;

export type orderReturnsControllerFindReturnsResponse = (orderReturnsControllerFindReturnsResponseSuccess)

export const getOrderReturnsControllerFindReturnsUrl = (id: string,) => {


  

  return `/sales-orders/${id}/returns`
}

export const orderReturnsControllerFindReturns = async (id: string, options?: RequestInit): Promise<orderReturnsControllerFindReturnsResponse> => {
  
  return customFetch<orderReturnsControllerFindReturnsResponse>(getOrderReturnsControllerFindReturnsUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * Retrieve detailed information for a specific return.
 * @summary Find Return
 */
export type orderReturnsControllerFindReturnResponse200 = {
  data: ReturnResponseDto
  status: 200
}
    
export type orderReturnsControllerFindReturnResponseSuccess = (orderReturnsControllerFindReturnResponse200) & {
  headers: Headers;
};
;

export type orderReturnsControllerFindReturnResponse = (orderReturnsControllerFindReturnResponseSuccess)

export const getOrderReturnsControllerFindReturnUrl = (id: string,
    returnId: string,) => {


  

  return `/sales-orders/${id}/returns/${returnId}`
}

export const orderReturnsControllerFindReturn = async (id: string,
    returnId: string, options?: RequestInit): Promise<orderReturnsControllerFindReturnResponse> => {
  
  return customFetch<orderReturnsControllerFindReturnResponse>(getOrderReturnsControllerFindReturnUrl(id,returnId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * Modify the details or metadata of an existing return.
 * @summary Update Return
 */
export type orderReturnsControllerUpdateReturnResponse200 = {
  data: ReturnResponseDto
  status: 200
}
    
export type orderReturnsControllerUpdateReturnResponseSuccess = (orderReturnsControllerUpdateReturnResponse200) & {
  headers: Headers;
};
;

export type orderReturnsControllerUpdateReturnResponse = (orderReturnsControllerUpdateReturnResponseSuccess)

export const getOrderReturnsControllerUpdateReturnUrl = (id: string,
    returnId: string,) => {


  

  return `/sales-orders/${id}/returns/${returnId}`
}

export const orderReturnsControllerUpdateReturn = async (id: string,
    returnId: string,
    updateReturnDto: UpdateReturnDto, options?: RequestInit): Promise<orderReturnsControllerUpdateReturnResponse> => {
  
  return customFetch<orderReturnsControllerUpdateReturnResponse>(getOrderReturnsControllerUpdateReturnUrl(id,returnId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateReturnDto,)
  }
);}


/**
 * Update the processing state of a sales return.
 * @summary Change Return State
 */
export type orderReturnsControllerChangeReturnStateResponse200 = {
  data: ReturnResponseDto
  status: 200
}
    
export type orderReturnsControllerChangeReturnStateResponseSuccess = (orderReturnsControllerChangeReturnStateResponse200) & {
  headers: Headers;
};
;

export type orderReturnsControllerChangeReturnStateResponse = (orderReturnsControllerChangeReturnStateResponseSuccess)

export const getOrderReturnsControllerChangeReturnStateUrl = (id: string,
    returnId: string,) => {


  

  return `/sales-orders/${id}/returns/${returnId}/state`
}

export const orderReturnsControllerChangeReturnState = async (id: string,
    returnId: string,
    changeReturnStateDto: ChangeReturnStateDto, options?: RequestInit): Promise<orderReturnsControllerChangeReturnStateResponse> => {
  
  return customFetch<orderReturnsControllerChangeReturnStateResponse>(getOrderReturnsControllerChangeReturnStateUrl(id,returnId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      changeReturnStateDto,)
  }
);}


/**
 * Add a new line item to a sales return.
 * @summary Add Return Line
 */
export type orderReturnsControllerAddReturnLineResponse201 = {
  data: ReturnResponseDto
  status: 201
}
    
export type orderReturnsControllerAddReturnLineResponseSuccess = (orderReturnsControllerAddReturnLineResponse201) & {
  headers: Headers;
};
;

export type orderReturnsControllerAddReturnLineResponse = (orderReturnsControllerAddReturnLineResponseSuccess)

export const getOrderReturnsControllerAddReturnLineUrl = (id: string,
    returnId: string,) => {


  

  return `/sales-orders/${id}/returns/${returnId}/lines`
}

export const orderReturnsControllerAddReturnLine = async (id: string,
    returnId: string,
    addReturnLineDto: AddReturnLineDto, options?: RequestInit): Promise<orderReturnsControllerAddReturnLineResponse> => {
  
  return customFetch<orderReturnsControllerAddReturnLineResponse>(getOrderReturnsControllerAddReturnLineUrl(id,returnId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      addReturnLineDto,)
  }
);}


/**
 * Modify an existing line item on a sales return.
 * @summary Update Return Line
 */
export type orderReturnsControllerUpdateReturnLineResponse200 = {
  data: ReturnResponseDto
  status: 200
}
    
export type orderReturnsControllerUpdateReturnLineResponseSuccess = (orderReturnsControllerUpdateReturnLineResponse200) & {
  headers: Headers;
};
;

export type orderReturnsControllerUpdateReturnLineResponse = (orderReturnsControllerUpdateReturnLineResponseSuccess)

export const getOrderReturnsControllerUpdateReturnLineUrl = (id: string,
    returnId: string,
    lineId: string,) => {


  

  return `/sales-orders/${id}/returns/${returnId}/lines/${lineId}`
}

export const orderReturnsControllerUpdateReturnLine = async (id: string,
    returnId: string,
    lineId: string,
    updateReturnLineDto: UpdateReturnLineDto, options?: RequestInit): Promise<orderReturnsControllerUpdateReturnLineResponse> => {
  
  return customFetch<orderReturnsControllerUpdateReturnLineResponse>(getOrderReturnsControllerUpdateReturnLineUrl(id,returnId,lineId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateReturnLineDto,)
  }
);}


/**
 * Delete a line item from a sales return.
 * @summary Remove Return Line
 */
export type orderReturnsControllerRemoveReturnLineResponse200 = {
  data: ReturnResponseDto
  status: 200
}
    
export type orderReturnsControllerRemoveReturnLineResponseSuccess = (orderReturnsControllerRemoveReturnLineResponse200) & {
  headers: Headers;
};
;

export type orderReturnsControllerRemoveReturnLineResponse = (orderReturnsControllerRemoveReturnLineResponseSuccess)

export const getOrderReturnsControllerRemoveReturnLineUrl = (id: string,
    returnId: string,
    lineId: string,) => {


  

  return `/sales-orders/${id}/returns/${returnId}/lines/${lineId}`
}

export const orderReturnsControllerRemoveReturnLine = async (id: string,
    returnId: string,
    lineId: string, options?: RequestInit): Promise<orderReturnsControllerRemoveReturnLineResponse> => {
  
  return customFetch<orderReturnsControllerRemoveReturnLineResponse>(getOrderReturnsControllerRemoveReturnLineUrl(id,returnId,lineId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}


/**
 * Process the receipt of returned goods into inventory.
 * @summary Receive Return
 */
export type orderReturnsControllerReceiveReturnResponse201 = {
  data: ReturnResponseDto
  status: 201
}
    
export type orderReturnsControllerReceiveReturnResponseSuccess = (orderReturnsControllerReceiveReturnResponse201) & {
  headers: Headers;
};
;

export type orderReturnsControllerReceiveReturnResponse = (orderReturnsControllerReceiveReturnResponseSuccess)

export const getOrderReturnsControllerReceiveReturnUrl = (id: string,
    returnId: string,) => {


  

  return `/sales-orders/${id}/returns/${returnId}/receive`
}

export const orderReturnsControllerReceiveReturn = async (id: string,
    returnId: string,
    receiveReturnDto: ReceiveReturnDto, options?: RequestInit): Promise<orderReturnsControllerReceiveReturnResponse> => {
  
  return customFetch<orderReturnsControllerReceiveReturnResponse>(getOrderReturnsControllerReceiveReturnUrl(id,returnId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      receiveReturnDto,)
  }
);}


/**
 * Retrieve all sales returns across all orders, optionally filtered by state.
 * @summary Find Global Returns
 */
export type globalReturnsControllerFindGlobalReturnsResponse200 = {
  data: GlobalReturnListResponseDto
  status: 200
}
    
export type globalReturnsControllerFindGlobalReturnsResponseSuccess = (globalReturnsControllerFindGlobalReturnsResponse200) & {
  headers: Headers;
};
;

export type globalReturnsControllerFindGlobalReturnsResponse = (globalReturnsControllerFindGlobalReturnsResponseSuccess)

export const getGlobalReturnsControllerFindGlobalReturnsUrl = (params?: GlobalReturnsControllerFindGlobalReturnsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/sales-returns?${stringifiedParams}` : `/sales-returns`
}

export const globalReturnsControllerFindGlobalReturns = async (params?: GlobalReturnsControllerFindGlobalReturnsParams, options?: RequestInit): Promise<globalReturnsControllerFindGlobalReturnsResponse> => {
  
  return customFetch<globalReturnsControllerFindGlobalReturnsResponse>(getGlobalReturnsControllerFindGlobalReturnsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * Retrieve a specific sales return by its ID.
 * @summary Find Return by ID
 */
export type globalReturnsControllerFindOneResponse200 = {
  data: ReturnResponseDto
  status: 200
}
    
export type globalReturnsControllerFindOneResponseSuccess = (globalReturnsControllerFindOneResponse200) & {
  headers: Headers;
};
;

export type globalReturnsControllerFindOneResponse = (globalReturnsControllerFindOneResponseSuccess)

export const getGlobalReturnsControllerFindOneUrl = (id: string,) => {


  

  return `/sales-returns/${id}`
}

export const globalReturnsControllerFindOne = async (id: string, options?: RequestInit): Promise<globalReturnsControllerFindOneResponse> => {
  
  return customFetch<globalReturnsControllerFindOneResponse>(getGlobalReturnsControllerFindOneUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * Retrieve a list of sales credit notes.
 * @summary Find Credit Notes
 */
export type salesCreditNotesControllerFindAllResponse200 = {
  data: SalesCreditNoteResponseDto[]
  status: 200
}
    
export type salesCreditNotesControllerFindAllResponseSuccess = (salesCreditNotesControllerFindAllResponse200) & {
  headers: Headers;
};
;

export type salesCreditNotesControllerFindAllResponse = (salesCreditNotesControllerFindAllResponseSuccess)

export const getSalesCreditNotesControllerFindAllUrl = (params?: SalesCreditNotesControllerFindAllParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/sales-credit-notes?${stringifiedParams}` : `/sales-credit-notes`
}

export const salesCreditNotesControllerFindAll = async (params?: SalesCreditNotesControllerFindAllParams, options?: RequestInit): Promise<salesCreditNotesControllerFindAllResponse> => {
  
  return customFetch<salesCreditNotesControllerFindAllResponse>(getSalesCreditNotesControllerFindAllUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * Create a credit note from a return.
 * @summary Create Credit Note
 */
export type salesCreditNotesControllerCreateCreditNoteResponse201 = {
  data: SalesCreditNoteResponseDto
  status: 201
}
    
export type salesCreditNotesControllerCreateCreditNoteResponseSuccess = (salesCreditNotesControllerCreateCreditNoteResponse201) & {
  headers: Headers;
};
;

export type salesCreditNotesControllerCreateCreditNoteResponse = (salesCreditNotesControllerCreateCreditNoteResponseSuccess)

export const getSalesCreditNotesControllerCreateCreditNoteUrl = () => {


  

  return `/sales-credit-notes`
}

export const salesCreditNotesControllerCreateCreditNote = async (createSalesCreditNoteDto: CreateSalesCreditNoteDto, options?: RequestInit): Promise<salesCreditNotesControllerCreateCreditNoteResponse> => {
  
  return customFetch<salesCreditNotesControllerCreateCreditNoteResponse>(getSalesCreditNotesControllerCreateCreditNoteUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createSalesCreditNoteDto,)
  }
);}


/**
 * Retrieve a sales credit note by ID.
 * @summary Get Credit Note
 */
export type salesCreditNotesControllerFindOneResponse200 = {
  data: SalesCreditNoteResponseDto
  status: 200
}
    
export type salesCreditNotesControllerFindOneResponseSuccess = (salesCreditNotesControllerFindOneResponse200) & {
  headers: Headers;
};
;

export type salesCreditNotesControllerFindOneResponse = (salesCreditNotesControllerFindOneResponseSuccess)

export const getSalesCreditNotesControllerFindOneUrl = (id: string,) => {


  

  return `/sales-credit-notes/${id}`
}

export const salesCreditNotesControllerFindOne = async (id: string, options?: RequestInit): Promise<salesCreditNotesControllerFindOneResponse> => {
  
  return customFetch<salesCreditNotesControllerFindOneResponse>(getSalesCreditNotesControllerFindOneUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * Post an existing credit note.
 * @summary Post Credit Note
 */
export type salesCreditNotesControllerPostCreditNoteResponse200 = {
  data: SalesCreditNoteResponseDto
  status: 200
}
    
export type salesCreditNotesControllerPostCreditNoteResponseSuccess = (salesCreditNotesControllerPostCreditNoteResponse200) & {
  headers: Headers;
};
;

export type salesCreditNotesControllerPostCreditNoteResponse = (salesCreditNotesControllerPostCreditNoteResponseSuccess)

export const getSalesCreditNotesControllerPostCreditNoteUrl = (id: string,) => {


  

  return `/sales-credit-notes/${id}/post`
}

export const salesCreditNotesControllerPostCreditNote = async (id: string,
    emptyBodyDto: EmptyBodyDto, options?: RequestInit): Promise<salesCreditNotesControllerPostCreditNoteResponse> => {
  
  return customFetch<salesCreditNotesControllerPostCreditNoteResponse>(getSalesCreditNotesControllerPostCreditNoteUrl(id),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      emptyBodyDto,)
  }
);}


