/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type {
  ContactResponseDto,
  ContactsControllerFindAll200,
  ContactsControllerFindAllParams,
  ContactsControllerRemove200,
  CreateContactDto,
  EmptyBodyDto,
  UpdateContactDto
} from '../../model';

import { customFetch } from '../../mutator';

/**
 * Retrieve a paginated list of contacts.
 * @summary List Contacts
 */
export type contactsControllerFindAllResponse200 = {
  data: ContactsControllerFindAll200
  status: 200
}
    
export type contactsControllerFindAllResponseSuccess = (contactsControllerFindAllResponse200) & {
  headers: Headers;
};
;

export type contactsControllerFindAllResponse = (contactsControllerFindAllResponseSuccess)

export const getContactsControllerFindAllUrl = (params?: ContactsControllerFindAllParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/contacts?${stringifiedParams}` : `/contacts`
}

export const contactsControllerFindAll = async (params?: ContactsControllerFindAllParams, options?: RequestInit): Promise<contactsControllerFindAllResponse> => {
  
  return customFetch<contactsControllerFindAllResponse>(getContactsControllerFindAllUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * Create a new contact for a given entity.
 * @summary Create Contact
 */
export type contactsControllerCreateResponse201 = {
  data: ContactResponseDto
  status: 201
}
    
export type contactsControllerCreateResponseSuccess = (contactsControllerCreateResponse201) & {
  headers: Headers;
};
;

export type contactsControllerCreateResponse = (contactsControllerCreateResponseSuccess)

export const getContactsControllerCreateUrl = () => {


  

  return `/contacts`
}

export const contactsControllerCreate = async (createContactDto: CreateContactDto, options?: RequestInit): Promise<contactsControllerCreateResponse> => {
  
  return customFetch<contactsControllerCreateResponse>(getContactsControllerCreateUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createContactDto,)
  }
);}


/**
 * Retrieve a single contact by ID.
 * @summary Get Contact
 */
export type contactsControllerFindOneResponse200 = {
  data: ContactResponseDto
  status: 200
}
    
export type contactsControllerFindOneResponseSuccess = (contactsControllerFindOneResponse200) & {
  headers: Headers;
};
;

export type contactsControllerFindOneResponse = (contactsControllerFindOneResponseSuccess)

export const getContactsControllerFindOneUrl = (id: string,) => {


  

  return `/contacts/${id}`
}

export const contactsControllerFindOne = async (id: string, options?: RequestInit): Promise<contactsControllerFindOneResponse> => {
  
  return customFetch<contactsControllerFindOneResponse>(getContactsControllerFindOneUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * Update an existing contact.
 * @summary Update Contact
 */
export type contactsControllerUpdateResponse200 = {
  data: ContactResponseDto
  status: 200
}
    
export type contactsControllerUpdateResponseSuccess = (contactsControllerUpdateResponse200) & {
  headers: Headers;
};
;

export type contactsControllerUpdateResponse = (contactsControllerUpdateResponseSuccess)

export const getContactsControllerUpdateUrl = (id: string,) => {


  

  return `/contacts/${id}`
}

export const contactsControllerUpdate = async (id: string,
    updateContactDto: UpdateContactDto, options?: RequestInit): Promise<contactsControllerUpdateResponse> => {
  
  return customFetch<contactsControllerUpdateResponse>(getContactsControllerUpdateUrl(id),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateContactDto,)
  }
);}


/**
 * Hard delete an existing contact.
 * @summary Delete Contact
 */
export type contactsControllerRemoveResponse200 = {
  data: ContactsControllerRemove200
  status: 200
}
    
export type contactsControllerRemoveResponseSuccess = (contactsControllerRemoveResponse200) & {
  headers: Headers;
};
;

export type contactsControllerRemoveResponse = (contactsControllerRemoveResponseSuccess)

export const getContactsControllerRemoveUrl = (id: string,) => {


  

  return `/contacts/${id}`
}

export const contactsControllerRemove = async (id: string, options?: RequestInit): Promise<contactsControllerRemoveResponse> => {
  
  return customFetch<contactsControllerRemoveResponse>(getContactsControllerRemoveUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}


/**
 * Archives a contact
 * @summary Archive Contact
 */
export type contactsControllerArchiveResponse200 = {
  data: ContactResponseDto
  status: 200
}

export type contactsControllerArchiveResponse201 = {
  data: ContactResponseDto
  status: 201
}
    
export type contactsControllerArchiveResponseSuccess = (contactsControllerArchiveResponse200 | contactsControllerArchiveResponse201) & {
  headers: Headers;
};
;

export type contactsControllerArchiveResponse = (contactsControllerArchiveResponseSuccess)

export const getContactsControllerArchiveUrl = (id: string,) => {


  

  return `/contacts/${id}/archive`
}

export const contactsControllerArchive = async (id: string,
    emptyBodyDto: EmptyBodyDto, options?: RequestInit): Promise<contactsControllerArchiveResponse> => {
  
  return customFetch<contactsControllerArchiveResponse>(getContactsControllerArchiveUrl(id),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      emptyBodyDto,)
  }
);}


/**
 * Unarchives a contact
 * @summary Unarchive Contact
 */
export type contactsControllerUnarchiveResponse200 = {
  data: ContactResponseDto
  status: 200
}

export type contactsControllerUnarchiveResponse201 = {
  data: ContactResponseDto
  status: 201
}
    
export type contactsControllerUnarchiveResponseSuccess = (contactsControllerUnarchiveResponse200 | contactsControllerUnarchiveResponse201) & {
  headers: Headers;
};
;

export type contactsControllerUnarchiveResponse = (contactsControllerUnarchiveResponseSuccess)

export const getContactsControllerUnarchiveUrl = (id: string,) => {


  

  return `/contacts/${id}/unarchive`
}

export const contactsControllerUnarchive = async (id: string,
    emptyBodyDto: EmptyBodyDto, options?: RequestInit): Promise<contactsControllerUnarchiveResponse> => {
  
  return customFetch<contactsControllerUnarchiveResponse>(getContactsControllerUnarchiveUrl(id),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      emptyBodyDto,)
  }
);}


