/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type {
  HelpContextResponseDto,
  HelpControllerGetContextParams,
  HelpControllerSearchParams,
  HelpSearchResultDto,
  HelpTopicDto,
  HelpTopicSummaryDto
} from '../../model';

import { customFetch } from '../../mutator';

/**
 * Resolves the most relevant help topic and field guide for a route.
 * @summary Get contextual help for the active screen route
 */
export type helpControllerGetContextResponse200 = {
  data: HelpContextResponseDto
  status: 200
}
    
export type helpControllerGetContextResponseSuccess = (helpControllerGetContextResponse200) & {
  headers: Headers;
};
;

export type helpControllerGetContextResponse = (helpControllerGetContextResponseSuccess)

export const getHelpControllerGetContextUrl = (params: HelpControllerGetContextParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/help/context?${stringifiedParams}` : `/help/context`
}

export const helpControllerGetContext = async (params: HelpControllerGetContextParams, options?: RequestInit): Promise<helpControllerGetContextResponse> => {
  
  return customFetch<helpControllerGetContextResponse>(getHelpControllerGetContextUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * Returns the categorized table of contents for user manuals.
 * @summary Get all accessible documentation topics
 */
export type helpControllerGetTopicsResponse200 = {
  data: HelpTopicSummaryDto[]
  status: 200
}
    
export type helpControllerGetTopicsResponseSuccess = (helpControllerGetTopicsResponse200) & {
  headers: Headers;
};
;

export type helpControllerGetTopicsResponse = (helpControllerGetTopicsResponseSuccess)

export const getHelpControllerGetTopicsUrl = () => {


  

  return `/help/topics`
}

export const helpControllerGetTopics = async ( options?: RequestInit): Promise<helpControllerGetTopicsResponse> => {
  
  return customFetch<helpControllerGetTopicsResponse>(getHelpControllerGetTopicsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * Returns the full markdown content and metadata for a specific topic.
 * @summary Get full topic content by ID
 */
export type helpControllerGetTopicByIdResponse200 = {
  data: HelpTopicDto
  status: 200
}
    
export type helpControllerGetTopicByIdResponseSuccess = (helpControllerGetTopicByIdResponse200) & {
  headers: Headers;
};
;

export type helpControllerGetTopicByIdResponse = (helpControllerGetTopicByIdResponseSuccess)

export const getHelpControllerGetTopicByIdUrl = (id: string,) => {


  

  return `/help/topics/${id}`
}

export const helpControllerGetTopicById = async (id: string, options?: RequestInit): Promise<helpControllerGetTopicByIdResponse> => {
  
  return customFetch<helpControllerGetTopicByIdResponse>(getHelpControllerGetTopicByIdUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * Searches titles, tags, field definitions, and markdown content.
 * @summary Search documentation topics
 */
export type helpControllerSearchResponse200 = {
  data: HelpSearchResultDto[]
  status: 200
}
    
export type helpControllerSearchResponseSuccess = (helpControllerSearchResponse200) & {
  headers: Headers;
};
;

export type helpControllerSearchResponse = (helpControllerSearchResponseSuccess)

export const getHelpControllerSearchUrl = (params: HelpControllerSearchParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/help/search?${stringifiedParams}` : `/help/search`
}

export const helpControllerSearch = async (params: HelpControllerSearchParams, options?: RequestInit): Promise<helpControllerSearchResponse> => {
  
  return customFetch<helpControllerSearchResponse>(getHelpControllerSearchUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


