/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * HeroBM API
 * Core API System endpoints
 * OpenAPI spec version: 1.0
 */
import type {
  AddShipmentLineDto,
  AdjustStockDto,
  AllocationResolveResponseDto,
  AllocationSuccessResponseDto,
  AllocationsControllerGetAvailablePoLinesParams,
  AvailablePoLineDto,
  BinResponseDto,
  CancelReceptionResponseDto,
  ChangeShipmentStateDto,
  CreateBinBulkDto,
  CreateBinDto,
  CreateGoodsReceivedDto,
  CreateLocationDto,
  CreateShipmentDto,
  CreateZoneDto,
  EmptyBodyDto,
  FindByProductIdsBulkDto,
  GeneratePOsDto,
  GenerateTransfersDto,
  GlobalShipmentsControllerFindAllParams,
  GlobalShipmentsControllerFindOneParams,
  GoodsReceivedControllerCancelReception200,
  GoodsReceivedControllerFindAllLinesParams,
  GoodsReceivedControllerFindAllParams,
  GoodsReceivedControllerFindOneParams,
  GoodsReceivedLineResponseDto,
  GoodsReceivedResponseDto,
  InventoryBinResponseDto,
  InventoryControllerFindAll200,
  InventoryControllerFindAllLocationsParams,
  InventoryControllerFindAllParams,
  InventoryControllerFindBins200,
  InventoryControllerFindBinsByLocationParams,
  InventoryControllerFindBinsParams,
  InventoryControllerFindByProductIdsParams,
  InventoryControllerGetLedgerParams,
  InventoryControllerGetPendingPutawayParams,
  InventoryControllerGetPutawayContextParams,
  InventoryEntryDetailsResponseDto,
  InventoryLedgerResponseDto,
  InventoryLocationResponseDto,
  InventoryResponseDto,
  InventorySuccessResponseDto,
  LinkDemandToPoDto,
  LocationResponseDto,
  MoveStockDto,
  OpenDemandDto,
  OrderPickingControllerGetPickingQueueParams,
  OrderPickingControllerGetShippingQueueParams,
  PaginatedGoodsReceivedDto,
  PaginatedGoodsReceivedLineDto,
  PendingPutawayResponseDto,
  PickOrderLineDto,
  PickingQueueResponseDto,
  PickingSummaryDto,
  PickingSummaryPickDto,
  PoAllocationDto,
  PutawayBulkDto,
  PutawayContextResponseDto,
  QuarantineMoveDto,
  ReallocateDemandDto,
  ResolveAllocationDto,
  ResolveAllocationResponseDto,
  ShipmentResponseDto,
  ShippingContextDto,
  ShippingQueueOrderDto,
  TopographyLocationResponseDto,
  UpdateBinDto,
  UpdateGoodsReceivedDto,
  UpdateLocationDto,
  UpdateShipmentDto,
  UpdateShipmentLineDto,
  UpdateZoneDto,
  ZoneResponseDto
} from '../../model';

import { customFetch } from '../../mutator';

/**
 * Retrieve a paginated list of inventory levels.
 * @summary List Inventory
 */
export type inventoryControllerFindAllResponse200 = {
  data: InventoryControllerFindAll200
  status: 200
}
    
export type inventoryControllerFindAllResponseSuccess = (inventoryControllerFindAllResponse200) & {
  headers: Headers;
};
;

export type inventoryControllerFindAllResponse = (inventoryControllerFindAllResponseSuccess)

export const getInventoryControllerFindAllUrl = (params?: InventoryControllerFindAllParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/inventory?${stringifiedParams}` : `/inventory`
}

export const inventoryControllerFindAll = async (params?: InventoryControllerFindAllParams, options?: RequestInit): Promise<inventoryControllerFindAllResponse> => {
  
  return customFetch<inventoryControllerFindAllResponse>(getInventoryControllerFindAllUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * Retrieve inventory items for specific product IDs.
 * @summary Get By Products
 */
export type inventoryControllerFindByProductIdsResponse200 = {
  data: InventoryResponseDto[]
  status: 200
}
    
export type inventoryControllerFindByProductIdsResponseSuccess = (inventoryControllerFindByProductIdsResponse200) & {
  headers: Headers;
};
;

export type inventoryControllerFindByProductIdsResponse = (inventoryControllerFindByProductIdsResponseSuccess)

export const getInventoryControllerFindByProductIdsUrl = (params?: InventoryControllerFindByProductIdsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/inventory/by-products?${stringifiedParams}` : `/inventory/by-products`
}

export const inventoryControllerFindByProductIds = async (params?: InventoryControllerFindByProductIdsParams, options?: RequestInit): Promise<inventoryControllerFindByProductIdsResponse> => {
  
  return customFetch<inventoryControllerFindByProductIdsResponse>(getInventoryControllerFindByProductIdsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * Retrieve inventory items for multiple product IDs in bulk.
 * @summary Bulk Get By Products
 */
export type inventoryControllerFindByProductIdsBulkResponse201 = {
  data: InventoryResponseDto[]
  status: 201
}
    
export type inventoryControllerFindByProductIdsBulkResponseSuccess = (inventoryControllerFindByProductIdsBulkResponse201) & {
  headers: Headers;
};
;

export type inventoryControllerFindByProductIdsBulkResponse = (inventoryControllerFindByProductIdsBulkResponseSuccess)

export const getInventoryControllerFindByProductIdsBulkUrl = () => {


  

  return `/inventory/by-products-bulk`
}

export const inventoryControllerFindByProductIdsBulk = async (findByProductIdsBulkDto: FindByProductIdsBulkDto, options?: RequestInit): Promise<inventoryControllerFindByProductIdsBulkResponse> => {
  
  return customFetch<inventoryControllerFindByProductIdsBulkResponse>(getInventoryControllerFindByProductIdsBulkUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      findByProductIdsBulkDto,)
  }
);}


/**
 * Retrieve a paginated list of inventory bins.
 * @summary List Inventory Bins
 */
export type inventoryControllerFindBinsResponse200 = {
  data: InventoryControllerFindBins200
  status: 200
}
    
export type inventoryControllerFindBinsResponseSuccess = (inventoryControllerFindBinsResponse200) & {
  headers: Headers;
};
;

export type inventoryControllerFindBinsResponse = (inventoryControllerFindBinsResponseSuccess)

export const getInventoryControllerFindBinsUrl = (params?: InventoryControllerFindBinsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/inventory/bins?${stringifiedParams}` : `/inventory/bins`
}

export const inventoryControllerFindBins = async (params?: InventoryControllerFindBinsParams, options?: RequestInit): Promise<inventoryControllerFindBinsResponse> => {
  
  return customFetch<inventoryControllerFindBinsResponse>(getInventoryControllerFindBinsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * Create a new storage bin.
 * @summary Create Bin
 */
export type locationsControllerCreateBinResponse201 = {
  data: BinResponseDto
  status: 201
}
    
export type locationsControllerCreateBinResponseSuccess = (locationsControllerCreateBinResponse201) & {
  headers: Headers;
};
;

export type locationsControllerCreateBinResponse = (locationsControllerCreateBinResponseSuccess)

export const getLocationsControllerCreateBinUrl = () => {


  

  return `/inventory/bins`
}

export const locationsControllerCreateBin = async (createBinDto: CreateBinDto, options?: RequestInit): Promise<locationsControllerCreateBinResponse> => {
  
  return customFetch<locationsControllerCreateBinResponse>(getLocationsControllerCreateBinUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createBinDto,)
  }
);}


/**
 * Retrieve context for putting away inventory.
 * @summary Get Putaway Context
 */
export type inventoryControllerGetPutawayContextResponse200 = {
  data: PutawayContextResponseDto
  status: 200
}
    
export type inventoryControllerGetPutawayContextResponseSuccess = (inventoryControllerGetPutawayContextResponse200) & {
  headers: Headers;
};
;

export type inventoryControllerGetPutawayContextResponse = (inventoryControllerGetPutawayContextResponseSuccess)

export const getInventoryControllerGetPutawayContextUrl = (params: InventoryControllerGetPutawayContextParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/inventory/putaway-context?${stringifiedParams}` : `/inventory/putaway-context`
}

export const inventoryControllerGetPutawayContext = async (params: InventoryControllerGetPutawayContextParams, options?: RequestInit): Promise<inventoryControllerGetPutawayContextResponse> => {
  
  return customFetch<inventoryControllerGetPutawayContextResponse>(getInventoryControllerGetPutawayContextUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * Retrieve all inventory locations.
 * @summary List Locations
 */
export type inventoryControllerFindAllLocationsResponse200 = {
  data: InventoryLocationResponseDto[]
  status: 200
}
    
export type inventoryControllerFindAllLocationsResponseSuccess = (inventoryControllerFindAllLocationsResponse200) & {
  headers: Headers;
};
;

export type inventoryControllerFindAllLocationsResponse = (inventoryControllerFindAllLocationsResponseSuccess)

export const getInventoryControllerFindAllLocationsUrl = (params?: InventoryControllerFindAllLocationsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/inventory/locations?${stringifiedParams}` : `/inventory/locations`
}

export const inventoryControllerFindAllLocations = async (params?: InventoryControllerFindAllLocationsParams, options?: RequestInit): Promise<inventoryControllerFindAllLocationsResponse> => {
  
  return customFetch<inventoryControllerFindAllLocationsResponse>(getInventoryControllerFindAllLocationsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * Create a new warehouse location.
 * @summary Create Location
 */
export type locationsControllerCreateLocationResponse201 = {
  data: LocationResponseDto
  status: 201
}
    
export type locationsControllerCreateLocationResponseSuccess = (locationsControllerCreateLocationResponse201) & {
  headers: Headers;
};
;

export type locationsControllerCreateLocationResponse = (locationsControllerCreateLocationResponseSuccess)

export const getLocationsControllerCreateLocationUrl = () => {


  

  return `/inventory/locations`
}

export const locationsControllerCreateLocation = async (createLocationDto: CreateLocationDto, options?: RequestInit): Promise<locationsControllerCreateLocationResponse> => {
  
  return customFetch<locationsControllerCreateLocationResponse>(getLocationsControllerCreateLocationUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createLocationDto,)
  }
);}


/**
 * Retrieve all bins for a specific location.
 * @summary Get Location Bins
 */
export type inventoryControllerFindBinsByLocationResponse200 = {
  data: InventoryBinResponseDto[]
  status: 200
}
    
export type inventoryControllerFindBinsByLocationResponseSuccess = (inventoryControllerFindBinsByLocationResponse200) & {
  headers: Headers;
};
;

export type inventoryControllerFindBinsByLocationResponse = (inventoryControllerFindBinsByLocationResponseSuccess)

export const getInventoryControllerFindBinsByLocationUrl = (id: string,
    params?: InventoryControllerFindBinsByLocationParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/inventory/locations/${id}/bins?${stringifiedParams}` : `/inventory/locations/${id}/bins`
}

export const inventoryControllerFindBinsByLocation = async (id: string,
    params?: InventoryControllerFindBinsByLocationParams, options?: RequestInit): Promise<inventoryControllerFindBinsByLocationResponse> => {
  
  return customFetch<inventoryControllerFindBinsByLocationResponse>(getInventoryControllerFindBinsByLocationUrl(id,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * Retrieve full warehouse topography hierarchy.
 * @summary Get Warehouse Topography
 */
export type inventoryControllerGetTopographyResponse200 = {
  data: TopographyLocationResponseDto[]
  status: 200
}
    
export type inventoryControllerGetTopographyResponseSuccess = (inventoryControllerGetTopographyResponse200) & {
  headers: Headers;
};
;

export type inventoryControllerGetTopographyResponse = (inventoryControllerGetTopographyResponseSuccess)

export const getInventoryControllerGetTopographyUrl = () => {


  

  return `/inventory/topography`
}

export const inventoryControllerGetTopography = async ( options?: RequestInit): Promise<inventoryControllerGetTopographyResponse> => {
  
  return customFetch<inventoryControllerGetTopographyResponse>(getInventoryControllerGetTopographyUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * Retrieve inventory ledger entries.
 * @summary List Ledger Entries
 */
export type inventoryControllerGetLedgerResponse200 = {
  data: InventoryLedgerResponseDto[]
  status: 200
}
    
export type inventoryControllerGetLedgerResponseSuccess = (inventoryControllerGetLedgerResponse200) & {
  headers: Headers;
};
;

export type inventoryControllerGetLedgerResponse = (inventoryControllerGetLedgerResponseSuccess)

export const getInventoryControllerGetLedgerUrl = (params?: InventoryControllerGetLedgerParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/inventory/ledger?${stringifiedParams}` : `/inventory/ledger`
}

export const inventoryControllerGetLedger = async (params?: InventoryControllerGetLedgerParams, options?: RequestInit): Promise<inventoryControllerGetLedgerResponse> => {
  
  return customFetch<inventoryControllerGetLedgerResponse>(getInventoryControllerGetLedgerUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * Retrieve details for a specific inventory entry.
 * @summary Get Entry Details
 */
export type inventoryControllerGetEntryDetailsResponse200 = {
  data: InventoryEntryDetailsResponseDto
  status: 200
}
    
export type inventoryControllerGetEntryDetailsResponseSuccess = (inventoryControllerGetEntryDetailsResponse200) & {
  headers: Headers;
};
;

export type inventoryControllerGetEntryDetailsResponse = (inventoryControllerGetEntryDetailsResponseSuccess)

export const getInventoryControllerGetEntryDetailsUrl = (id: string,) => {


  

  return `/inventory/entries/${id}`
}

export const inventoryControllerGetEntryDetails = async (id: string, options?: RequestInit): Promise<inventoryControllerGetEntryDetailsResponse> => {
  
  return customFetch<inventoryControllerGetEntryDetailsResponse>(getInventoryControllerGetEntryDetailsUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * Retrieve pending putaway lines.
 * @summary List Pending Putaways
 */
export type inventoryControllerGetPendingPutawayResponse200 = {
  data: PendingPutawayResponseDto[]
  status: 200
}
    
export type inventoryControllerGetPendingPutawayResponseSuccess = (inventoryControllerGetPendingPutawayResponse200) & {
  headers: Headers;
};
;

export type inventoryControllerGetPendingPutawayResponse = (inventoryControllerGetPendingPutawayResponseSuccess)

export const getInventoryControllerGetPendingPutawayUrl = (params?: InventoryControllerGetPendingPutawayParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/inventory/pending-putaway?${stringifiedParams}` : `/inventory/pending-putaway`
}

export const inventoryControllerGetPendingPutaway = async (params?: InventoryControllerGetPendingPutawayParams, options?: RequestInit): Promise<inventoryControllerGetPendingPutawayResponse> => {
  
  return customFetch<inventoryControllerGetPendingPutawayResponse>(getInventoryControllerGetPendingPutawayUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * Process inventory putaway.
 * @summary Process Putaways
 */
export type inventoryControllerPutawayResponse201 = {
  data: InventorySuccessResponseDto
  status: 201
}
    
export type inventoryControllerPutawayResponseSuccess = (inventoryControllerPutawayResponse201) & {
  headers: Headers;
};
;

export type inventoryControllerPutawayResponse = (inventoryControllerPutawayResponseSuccess)

export const getInventoryControllerPutawayUrl = () => {


  

  return `/inventory/putaway`
}

export const inventoryControllerPutaway = async (putawayBulkDto: PutawayBulkDto, options?: RequestInit): Promise<inventoryControllerPutawayResponse> => {
  
  return customFetch<inventoryControllerPutawayResponse>(getInventoryControllerPutawayUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      putawayBulkDto,)
  }
);}


/**
 * Move stock between quarantine and regular storage.
 * @summary Move to/from Quarantine
 */
export type inventoryControllerQuarantineMoveResponse201 = {
  data: InventorySuccessResponseDto
  status: 201
}
    
export type inventoryControllerQuarantineMoveResponseSuccess = (inventoryControllerQuarantineMoveResponse201) & {
  headers: Headers;
};
;

export type inventoryControllerQuarantineMoveResponse = (inventoryControllerQuarantineMoveResponseSuccess)

export const getInventoryControllerQuarantineMoveUrl = () => {


  

  return `/inventory/quarantine/move`
}

export const inventoryControllerQuarantineMove = async (quarantineMoveDto: QuarantineMoveDto, options?: RequestInit): Promise<inventoryControllerQuarantineMoveResponse> => {
  
  return customFetch<inventoryControllerQuarantineMoveResponse>(getInventoryControllerQuarantineMoveUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      quarantineMoveDto,)
  }
);}


/**
 * Manually move stock between bins in the same location.
 * @summary Move Stock manually
 */
export type inventoryControllerMoveStockResponse201 = {
  data: InventorySuccessResponseDto
  status: 201
}
    
export type inventoryControllerMoveStockResponseSuccess = (inventoryControllerMoveStockResponse201) & {
  headers: Headers;
};
;

export type inventoryControllerMoveStockResponse = (inventoryControllerMoveStockResponseSuccess)

export const getInventoryControllerMoveStockUrl = () => {


  

  return `/inventory/move`
}

export const inventoryControllerMoveStock = async (moveStockDto: MoveStockDto, options?: RequestInit): Promise<inventoryControllerMoveStockResponse> => {
  
  return customFetch<inventoryControllerMoveStockResponse>(getInventoryControllerMoveStockUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      moveStockDto,)
  }
);}


/**
 * Manually adjust stock levels to match a physical count.
 * @summary Adjust Stock manually
 */
export type inventoryControllerAdjustStockResponse201 = {
  data: InventorySuccessResponseDto
  status: 201
}
    
export type inventoryControllerAdjustStockResponseSuccess = (inventoryControllerAdjustStockResponse201) & {
  headers: Headers;
};
;

export type inventoryControllerAdjustStockResponse = (inventoryControllerAdjustStockResponseSuccess)

export const getInventoryControllerAdjustStockUrl = () => {


  

  return `/inventory/adjust`
}

export const inventoryControllerAdjustStock = async (adjustStockDto: AdjustStockDto, options?: RequestInit): Promise<inventoryControllerAdjustStockResponse> => {
  
  return customFetch<inventoryControllerAdjustStockResponse>(getInventoryControllerAdjustStockUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      adjustStockDto,)
  }
);}


/**
 * Retrieve the paginated queue of orders ready to be picked at a specific location.
 * @summary Get Picking Queue
 */
export type orderPickingControllerGetPickingQueueResponse200 = {
  data: PickingQueueResponseDto
  status: 200
}
    
export type orderPickingControllerGetPickingQueueResponseSuccess = (orderPickingControllerGetPickingQueueResponse200) & {
  headers: Headers;
};
;

export type orderPickingControllerGetPickingQueueResponse = (orderPickingControllerGetPickingQueueResponseSuccess)

export const getOrderPickingControllerGetPickingQueueUrl = (params?: OrderPickingControllerGetPickingQueueParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/sales-orders/picking-queue?${stringifiedParams}` : `/sales-orders/picking-queue`
}

export const orderPickingControllerGetPickingQueue = async (params?: OrderPickingControllerGetPickingQueueParams, options?: RequestInit): Promise<orderPickingControllerGetPickingQueueResponse> => {
  
  return customFetch<orderPickingControllerGetPickingQueueResponse>(getOrderPickingControllerGetPickingQueueUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * Retrieve the picking summary for a specific sales order.
 * @summary Get Picking Summary
 */
export type orderPickingControllerGetPickingSummaryResponse200 = {
  data: PickingSummaryDto
  status: 200
}
    
export type orderPickingControllerGetPickingSummaryResponseSuccess = (orderPickingControllerGetPickingSummaryResponse200) & {
  headers: Headers;
};
;

export type orderPickingControllerGetPickingSummaryResponse = (orderPickingControllerGetPickingSummaryResponseSuccess)

export const getOrderPickingControllerGetPickingSummaryUrl = (id: string,) => {


  

  return `/sales-orders/${id}/picking`
}

export const orderPickingControllerGetPickingSummary = async (id: string, options?: RequestInit): Promise<orderPickingControllerGetPickingSummaryResponse> => {
  
  return customFetch<orderPickingControllerGetPickingSummaryResponse>(getOrderPickingControllerGetPickingSummaryUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * Record a picked quantity for a specific sales order line item.
 * @summary Pick Order Line
 */
export type orderPickingControllerPickLineResponse201 = {
  data: PickingSummaryPickDto
  status: 201
}
    
export type orderPickingControllerPickLineResponseSuccess = (orderPickingControllerPickLineResponse201) & {
  headers: Headers;
};
;

export type orderPickingControllerPickLineResponse = (orderPickingControllerPickLineResponseSuccess)

export const getOrderPickingControllerPickLineUrl = (id: string,
    lineId: string,) => {


  

  return `/sales-orders/${id}/picking/lines/${lineId}`
}

export const orderPickingControllerPickLine = async (id: string,
    lineId: string,
    pickOrderLineDto: PickOrderLineDto, options?: RequestInit): Promise<orderPickingControllerPickLineResponse> => {
  
  return customFetch<orderPickingControllerPickLineResponse>(getOrderPickingControllerPickLineUrl(id,lineId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      pickOrderLineDto,)
  }
);}


/**
 * Cancel and revert a recorded pick for a sales order.
 * @summary Cancel Pick
 */
export type orderPickingControllerCancelPickResponse200 = {
  data: PickingSummaryPickDto
  status: 200
}
    
export type orderPickingControllerCancelPickResponseSuccess = (orderPickingControllerCancelPickResponse200) & {
  headers: Headers;
};
;

export type orderPickingControllerCancelPickResponse = (orderPickingControllerCancelPickResponseSuccess)

export const getOrderPickingControllerCancelPickUrl = (id: string,
    pickId: string,) => {


  

  return `/sales-orders/${id}/picking/picks/${pickId}`
}

export const orderPickingControllerCancelPick = async (id: string,
    pickId: string, options?: RequestInit): Promise<orderPickingControllerCancelPickResponse> => {
  
  return customFetch<orderPickingControllerCancelPickResponse>(getOrderPickingControllerCancelPickUrl(id,pickId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}


/**
 * Retrieve the queue of orders ready to be shipped from a location.
 * @summary Get Shipping Queue
 */
export type orderPickingControllerGetShippingQueueResponse200 = {
  data: ShippingQueueOrderDto[]
  status: 200
}
    
export type orderPickingControllerGetShippingQueueResponseSuccess = (orderPickingControllerGetShippingQueueResponse200) & {
  headers: Headers;
};
;

export type orderPickingControllerGetShippingQueueResponse = (orderPickingControllerGetShippingQueueResponseSuccess)

export const getOrderPickingControllerGetShippingQueueUrl = (params?: OrderPickingControllerGetShippingQueueParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/sales-orders/shipping-queue?${stringifiedParams}` : `/sales-orders/shipping-queue`
}

export const orderPickingControllerGetShippingQueue = async (params?: OrderPickingControllerGetShippingQueueParams, options?: RequestInit): Promise<orderPickingControllerGetShippingQueueResponse> => {
  
  return customFetch<orderPickingControllerGetShippingQueueResponse>(getOrderPickingControllerGetShippingQueueUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * Retrieve shipment details and context for a sales order.
 * @summary Get Shipping Context
 */
export type orderPickingControllerGetShippingContextResponse200 = {
  data: ShippingContextDto
  status: 200
}
    
export type orderPickingControllerGetShippingContextResponseSuccess = (orderPickingControllerGetShippingContextResponse200) & {
  headers: Headers;
};
;

export type orderPickingControllerGetShippingContextResponse = (orderPickingControllerGetShippingContextResponseSuccess)

export const getOrderPickingControllerGetShippingContextUrl = (id: string,) => {


  

  return `/sales-orders/${id}/shipping-context`
}

export const orderPickingControllerGetShippingContext = async (id: string, options?: RequestInit): Promise<orderPickingControllerGetShippingContextResponse> => {
  
  return customFetch<orderPickingControllerGetShippingContextResponse>(getOrderPickingControllerGetShippingContextUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * Create a new shipment for a sales order or transfer order.
 * @summary Create Shipment
 */
export type orderShipmentsControllerCreateShipmentResponse201 = {
  data: ShipmentResponseDto
  status: 201
}
    
export type orderShipmentsControllerCreateShipmentResponseSuccess = (orderShipmentsControllerCreateShipmentResponse201) & {
  headers: Headers;
};
;

export type orderShipmentsControllerCreateShipmentResponse = (orderShipmentsControllerCreateShipmentResponseSuccess)

export const getOrderShipmentsControllerCreateShipmentUrl = (id: string,) => {


  

  return `/sales-orders/${id}/shipments`
}

export const orderShipmentsControllerCreateShipment = async (id: string,
    createShipmentDto: CreateShipmentDto, options?: RequestInit): Promise<orderShipmentsControllerCreateShipmentResponse> => {
  
  return customFetch<orderShipmentsControllerCreateShipmentResponse>(getOrderShipmentsControllerCreateShipmentUrl(id),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createShipmentDto,)
  }
);}


/**
 * Retrieve all shipments associated with a specific sales order.
 * @summary Find Order Shipments
 */
export type orderShipmentsControllerFindShipmentsResponse200 = {
  data: ShipmentResponseDto[]
  status: 200
}
    
export type orderShipmentsControllerFindShipmentsResponseSuccess = (orderShipmentsControllerFindShipmentsResponse200) & {
  headers: Headers;
};
;

export type orderShipmentsControllerFindShipmentsResponse = (orderShipmentsControllerFindShipmentsResponseSuccess)

export const getOrderShipmentsControllerFindShipmentsUrl = (id: string,) => {


  

  return `/sales-orders/${id}/shipments`
}

export const orderShipmentsControllerFindShipments = async (id: string, options?: RequestInit): Promise<orderShipmentsControllerFindShipmentsResponse> => {
  
  return customFetch<orderShipmentsControllerFindShipmentsResponse>(getOrderShipmentsControllerFindShipmentsUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * Retrieve detailed information for a specific shipment.
 * @summary Find Shipment
 */
export type orderShipmentsControllerFindShipmentResponse200 = {
  data: ShipmentResponseDto
  status: 200
}
    
export type orderShipmentsControllerFindShipmentResponseSuccess = (orderShipmentsControllerFindShipmentResponse200) & {
  headers: Headers;
};
;

export type orderShipmentsControllerFindShipmentResponse = (orderShipmentsControllerFindShipmentResponseSuccess)

export const getOrderShipmentsControllerFindShipmentUrl = (id: string,
    shipmentId: string,) => {


  

  return `/sales-orders/${id}/shipments/${shipmentId}`
}

export const orderShipmentsControllerFindShipment = async (id: string,
    shipmentId: string, options?: RequestInit): Promise<orderShipmentsControllerFindShipmentResponse> => {
  
  return customFetch<orderShipmentsControllerFindShipmentResponse>(getOrderShipmentsControllerFindShipmentUrl(id,shipmentId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * Modify the details of an existing shipment.
 * @summary Update Shipment
 */
export type orderShipmentsControllerUpdateShipmentResponse200 = {
  data: ShipmentResponseDto
  status: 200
}
    
export type orderShipmentsControllerUpdateShipmentResponseSuccess = (orderShipmentsControllerUpdateShipmentResponse200) & {
  headers: Headers;
};
;

export type orderShipmentsControllerUpdateShipmentResponse = (orderShipmentsControllerUpdateShipmentResponseSuccess)

export const getOrderShipmentsControllerUpdateShipmentUrl = (id: string,
    shipmentId: string,) => {


  

  return `/sales-orders/${id}/shipments/${shipmentId}`
}

export const orderShipmentsControllerUpdateShipment = async (id: string,
    shipmentId: string,
    updateShipmentDto: UpdateShipmentDto, options?: RequestInit): Promise<orderShipmentsControllerUpdateShipmentResponse> => {
  
  return customFetch<orderShipmentsControllerUpdateShipmentResponse>(getOrderShipmentsControllerUpdateShipmentUrl(id,shipmentId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateShipmentDto,)
  }
);}


/**
 * Update the processing state of a shipment.
 * @summary Change Shipment State
 */
export type orderShipmentsControllerChangeShipmentStateResponse200 = {
  data: ShipmentResponseDto
  status: 200
}
    
export type orderShipmentsControllerChangeShipmentStateResponseSuccess = (orderShipmentsControllerChangeShipmentStateResponse200) & {
  headers: Headers;
};
;

export type orderShipmentsControllerChangeShipmentStateResponse = (orderShipmentsControllerChangeShipmentStateResponseSuccess)

export const getOrderShipmentsControllerChangeShipmentStateUrl = (id: string,
    shipmentId: string,) => {


  

  return `/sales-orders/${id}/shipments/${shipmentId}/state`
}

export const orderShipmentsControllerChangeShipmentState = async (id: string,
    shipmentId: string,
    changeShipmentStateDto: ChangeShipmentStateDto, options?: RequestInit): Promise<orderShipmentsControllerChangeShipmentStateResponse> => {
  
  return customFetch<orderShipmentsControllerChangeShipmentStateResponse>(getOrderShipmentsControllerChangeShipmentStateUrl(id,shipmentId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      changeShipmentStateDto,)
  }
);}


/**
 * Cancel an open shipment and revert picked inventory.
 * @summary Cancel Shipment
 */
export type orderShipmentsControllerCancelShipmentResponse201 = {
  data: ShipmentResponseDto
  status: 201
}
    
export type orderShipmentsControllerCancelShipmentResponseSuccess = (orderShipmentsControllerCancelShipmentResponse201) & {
  headers: Headers;
};
;

export type orderShipmentsControllerCancelShipmentResponse = (orderShipmentsControllerCancelShipmentResponseSuccess)

export const getOrderShipmentsControllerCancelShipmentUrl = (id: string,
    shipmentId: string,) => {


  

  return `/sales-orders/${id}/shipments/${shipmentId}/cancel`
}

export const orderShipmentsControllerCancelShipment = async (id: string,
    shipmentId: string,
    emptyBodyDto: EmptyBodyDto, options?: RequestInit): Promise<orderShipmentsControllerCancelShipmentResponse> => {
  
  return customFetch<orderShipmentsControllerCancelShipmentResponse>(getOrderShipmentsControllerCancelShipmentUrl(id,shipmentId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      emptyBodyDto,)
  }
);}


/**
 * Add a new line item to a shipment.
 * @summary Add Shipment Line
 */
export type orderShipmentsControllerAddShipmentLineResponse201 = {
  data: ShipmentResponseDto
  status: 201
}
    
export type orderShipmentsControllerAddShipmentLineResponseSuccess = (orderShipmentsControllerAddShipmentLineResponse201) & {
  headers: Headers;
};
;

export type orderShipmentsControllerAddShipmentLineResponse = (orderShipmentsControllerAddShipmentLineResponseSuccess)

export const getOrderShipmentsControllerAddShipmentLineUrl = (id: string,
    shipmentId: string,) => {


  

  return `/sales-orders/${id}/shipments/${shipmentId}/lines`
}

export const orderShipmentsControllerAddShipmentLine = async (id: string,
    shipmentId: string,
    addShipmentLineDto: AddShipmentLineDto, options?: RequestInit): Promise<orderShipmentsControllerAddShipmentLineResponse> => {
  
  return customFetch<orderShipmentsControllerAddShipmentLineResponse>(getOrderShipmentsControllerAddShipmentLineUrl(id,shipmentId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      addShipmentLineDto,)
  }
);}


/**
 * Modify an existing line item on a shipment.
 * @summary Update Shipment Line
 */
export type orderShipmentsControllerUpdateShipmentLineResponse200 = {
  data: ShipmentResponseDto
  status: 200
}
    
export type orderShipmentsControllerUpdateShipmentLineResponseSuccess = (orderShipmentsControllerUpdateShipmentLineResponse200) & {
  headers: Headers;
};
;

export type orderShipmentsControllerUpdateShipmentLineResponse = (orderShipmentsControllerUpdateShipmentLineResponseSuccess)

export const getOrderShipmentsControllerUpdateShipmentLineUrl = (id: string,
    shipmentId: string,
    lineId: string,) => {


  

  return `/sales-orders/${id}/shipments/${shipmentId}/lines/${lineId}`
}

export const orderShipmentsControllerUpdateShipmentLine = async (id: string,
    shipmentId: string,
    lineId: string,
    updateShipmentLineDto: UpdateShipmentLineDto, options?: RequestInit): Promise<orderShipmentsControllerUpdateShipmentLineResponse> => {
  
  return customFetch<orderShipmentsControllerUpdateShipmentLineResponse>(getOrderShipmentsControllerUpdateShipmentLineUrl(id,shipmentId,lineId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateShipmentLineDto,)
  }
);}


/**
 * Delete a line item from a shipment.
 * @summary Remove Shipment Line
 */
export type orderShipmentsControllerRemoveShipmentLineResponse200 = {
  data: ShipmentResponseDto
  status: 200
}
    
export type orderShipmentsControllerRemoveShipmentLineResponseSuccess = (orderShipmentsControllerRemoveShipmentLineResponse200) & {
  headers: Headers;
};
;

export type orderShipmentsControllerRemoveShipmentLineResponse = (orderShipmentsControllerRemoveShipmentLineResponseSuccess)

export const getOrderShipmentsControllerRemoveShipmentLineUrl = (id: string,
    shipmentId: string,
    lineId: string,) => {


  

  return `/sales-orders/${id}/shipments/${shipmentId}/lines/${lineId}`
}

export const orderShipmentsControllerRemoveShipmentLine = async (id: string,
    shipmentId: string,
    lineId: string, options?: RequestInit): Promise<orderShipmentsControllerRemoveShipmentLineResponse> => {
  
  return customFetch<orderShipmentsControllerRemoveShipmentLineResponse>(getOrderShipmentsControllerRemoveShipmentLineUrl(id,shipmentId,lineId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}


/**
 * Retrieve a list of shipments globally.
 * @summary Find All Shipments
 */
export type globalShipmentsControllerFindAllResponse200 = {
  data: ShipmentResponseDto[]
  status: 200
}
    
export type globalShipmentsControllerFindAllResponseSuccess = (globalShipmentsControllerFindAllResponse200) & {
  headers: Headers;
};
;

export type globalShipmentsControllerFindAllResponse = (globalShipmentsControllerFindAllResponseSuccess)

export const getGlobalShipmentsControllerFindAllUrl = (params?: GlobalShipmentsControllerFindAllParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/shipments?${stringifiedParams}` : `/shipments`
}

export const globalShipmentsControllerFindAll = async (params?: GlobalShipmentsControllerFindAllParams, options?: RequestInit): Promise<globalShipmentsControllerFindAllResponse> => {
  
  return customFetch<globalShipmentsControllerFindAllResponse>(getGlobalShipmentsControllerFindAllUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * Retrieve detailed information for a specific shipment.
 * @summary Find Shipment
 */
export type globalShipmentsControllerFindOneResponse200 = {
  data: ShipmentResponseDto
  status: 200
}
    
export type globalShipmentsControllerFindOneResponseSuccess = (globalShipmentsControllerFindOneResponse200) & {
  headers: Headers;
};
;

export type globalShipmentsControllerFindOneResponse = (globalShipmentsControllerFindOneResponseSuccess)

export const getGlobalShipmentsControllerFindOneUrl = (id: string,
    params?: GlobalShipmentsControllerFindOneParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/shipments/${id}?${stringifiedParams}` : `/shipments/${id}`
}

export const globalShipmentsControllerFindOne = async (id: string,
    params?: GlobalShipmentsControllerFindOneParams, options?: RequestInit): Promise<globalShipmentsControllerFindOneResponse> => {
  
  return customFetch<globalShipmentsControllerFindOneResponse>(getGlobalShipmentsControllerFindOneUrl(id,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * Retrieve pending or awaiting-receipt backorders across all sales orders and work orders.
 * @summary Get Open Demands
 */
export type allocationsControllerGetOpenDemandsResponse200 = {
  data: OpenDemandDto[]
  status: 200
}
    
export type allocationsControllerGetOpenDemandsResponseSuccess = (allocationsControllerGetOpenDemandsResponse200) & {
  headers: Headers;
};
;

export type allocationsControllerGetOpenDemandsResponse = (allocationsControllerGetOpenDemandsResponseSuccess)

export const getAllocationsControllerGetOpenDemandsUrl = () => {


  

  return `/allocations/open`
}

export const allocationsControllerGetOpenDemands = async ( options?: RequestInit): Promise<allocationsControllerGetOpenDemandsResponse> => {
  
  return customFetch<allocationsControllerGetOpenDemandsResponse>(getAllocationsControllerGetOpenDemandsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * Retrieve all backorder allocations linked to a specific purchase order.
 * @summary Get PO Allocations
 */
export type allocationsControllerGetAllocationsByPoResponse200 = {
  data: PoAllocationDto[]
  status: 200
}
    
export type allocationsControllerGetAllocationsByPoResponseSuccess = (allocationsControllerGetAllocationsByPoResponse200) & {
  headers: Headers;
};
;

export type allocationsControllerGetAllocationsByPoResponse = (allocationsControllerGetAllocationsByPoResponseSuccess)

export const getAllocationsControllerGetAllocationsByPoUrl = (poId: string,) => {


  

  return `/allocations/by-po/${poId}`
}

export const allocationsControllerGetAllocationsByPo = async (poId: string, options?: RequestInit): Promise<allocationsControllerGetAllocationsByPoResponse> => {
  
  return customFetch<allocationsControllerGetAllocationsByPoResponse>(getAllocationsControllerGetAllocationsByPoUrl(poId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * Find open purchase order lines for a specific product to allocate against.
 * @summary Get Available PO Lines
 */
export type allocationsControllerGetAvailablePoLinesResponse200 = {
  data: AvailablePoLineDto[]
  status: 200
}
    
export type allocationsControllerGetAvailablePoLinesResponseSuccess = (allocationsControllerGetAvailablePoLinesResponse200) & {
  headers: Headers;
};
;

export type allocationsControllerGetAvailablePoLinesResponse = (allocationsControllerGetAvailablePoLinesResponseSuccess)

export const getAllocationsControllerGetAvailablePoLinesUrl = (params: AllocationsControllerGetAvailablePoLinesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/allocations/available-po-lines?${stringifiedParams}` : `/allocations/available-po-lines`
}

export const allocationsControllerGetAvailablePoLines = async (params: AllocationsControllerGetAvailablePoLinesParams, options?: RequestInit): Promise<allocationsControllerGetAvailablePoLinesResponse> => {
  
  return customFetch<allocationsControllerGetAvailablePoLinesResponse>(getAllocationsControllerGetAvailablePoLinesUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * Manually allocate a backorder demand to an open purchase order line.
 * @summary Link Demand To PO
 */
export type allocationsControllerLinkDemandToPoResponse201 = {
  data: AllocationSuccessResponseDto
  status: 201
}
    
export type allocationsControllerLinkDemandToPoResponseSuccess = (allocationsControllerLinkDemandToPoResponse201) & {
  headers: Headers;
};
;

export type allocationsControllerLinkDemandToPoResponse = (allocationsControllerLinkDemandToPoResponseSuccess)

export const getAllocationsControllerLinkDemandToPoUrl = () => {


  

  return `/allocations/link-po`
}

export const allocationsControllerLinkDemandToPo = async (linkDemandToPoDto: LinkDemandToPoDto, options?: RequestInit): Promise<allocationsControllerLinkDemandToPoResponse> => {
  
  return customFetch<allocationsControllerLinkDemandToPoResponse>(getAllocationsControllerLinkDemandToPoUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      linkDemandToPoDto,)
  }
);}


/**
 * Run the MRP engine to automatically resolve backorder demands.
 * @summary Resolve Open Demands
 */
export type allocationsControllerResolveOpenDemandsResponse201 = {
  data: AllocationResolveResponseDto
  status: 201
}
    
export type allocationsControllerResolveOpenDemandsResponseSuccess = (allocationsControllerResolveOpenDemandsResponse201) & {
  headers: Headers;
};
;

export type allocationsControllerResolveOpenDemandsResponse = (allocationsControllerResolveOpenDemandsResponseSuccess)

export const getAllocationsControllerResolveOpenDemandsUrl = () => {


  

  return `/allocations/resolve`
}

export const allocationsControllerResolveOpenDemands = async (emptyBodyDto: EmptyBodyDto, options?: RequestInit): Promise<allocationsControllerResolveOpenDemandsResponse> => {
  
  return customFetch<allocationsControllerResolveOpenDemandsResponse>(getAllocationsControllerResolveOpenDemandsUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      emptyBodyDto,)
  }
);}


/**
 * Remove the link between a backorder demand and its allocated purchase order.
 * @summary Unlink Demand
 */
export type allocationsControllerUnlinkDemandResponse201 = {
  data: AllocationSuccessResponseDto
  status: 201
}
    
export type allocationsControllerUnlinkDemandResponseSuccess = (allocationsControllerUnlinkDemandResponse201) & {
  headers: Headers;
};
;

export type allocationsControllerUnlinkDemandResponse = (allocationsControllerUnlinkDemandResponseSuccess)

export const getAllocationsControllerUnlinkDemandUrl = (id: string,) => {


  

  return `/allocations/${id}/unlink`
}

export const allocationsControllerUnlinkDemand = async (id: string,
    emptyBodyDto: EmptyBodyDto, options?: RequestInit): Promise<allocationsControllerUnlinkDemandResponse> => {
  
  return customFetch<allocationsControllerUnlinkDemandResponse>(getAllocationsControllerUnlinkDemandUrl(id),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      emptyBodyDto,)
  }
);}


/**
 * Change the fulfillment location for an open backorder demand.
 * @summary Reallocate Demand
 */
export type allocationsControllerReallocateDemandResponse201 = {
  data: AllocationSuccessResponseDto
  status: 201
}
    
export type allocationsControllerReallocateDemandResponseSuccess = (allocationsControllerReallocateDemandResponse201) & {
  headers: Headers;
};
;

export type allocationsControllerReallocateDemandResponse = (allocationsControllerReallocateDemandResponseSuccess)

export const getAllocationsControllerReallocateDemandUrl = (id: string,) => {


  

  return `/allocations/${id}/reallocate`
}

export const allocationsControllerReallocateDemand = async (id: string,
    reallocateDemandDto: ReallocateDemandDto, options?: RequestInit): Promise<allocationsControllerReallocateDemandResponse> => {
  
  return customFetch<allocationsControllerReallocateDemandResponse>(getAllocationsControllerReallocateDemandUrl(id),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      reallocateDemandDto,)
  }
);}


/**
 * Bulk create purchase orders from open backorder demands.
 * @summary Generate POs
 */
export type allocationsControllerGeneratePOsResponse201 = {
  data: AllocationSuccessResponseDto
  status: 201
}
    
export type allocationsControllerGeneratePOsResponseSuccess = (allocationsControllerGeneratePOsResponse201) & {
  headers: Headers;
};
;

export type allocationsControllerGeneratePOsResponse = (allocationsControllerGeneratePOsResponseSuccess)

export const getAllocationsControllerGeneratePOsUrl = () => {


  

  return `/allocations/generate-pos`
}

export const allocationsControllerGeneratePOs = async (generatePOsDto: GeneratePOsDto, options?: RequestInit): Promise<allocationsControllerGeneratePOsResponse> => {
  
  return customFetch<allocationsControllerGeneratePOsResponse>(getAllocationsControllerGeneratePOsUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      generatePOsDto,)
  }
);}


/**
 * Bulk create inventory transfers from open backorder demands.
 * @summary Generate Transfers
 */
export type allocationsControllerGenerateTransfersResponse201 = {
  data: AllocationSuccessResponseDto
  status: 201
}
    
export type allocationsControllerGenerateTransfersResponseSuccess = (allocationsControllerGenerateTransfersResponse201) & {
  headers: Headers;
};
;

export type allocationsControllerGenerateTransfersResponse = (allocationsControllerGenerateTransfersResponseSuccess)

export const getAllocationsControllerGenerateTransfersUrl = () => {


  

  return `/allocations/generate-transfers`
}

export const allocationsControllerGenerateTransfers = async (generateTransfersDto: GenerateTransfersDto, options?: RequestInit): Promise<allocationsControllerGenerateTransfersResponse> => {
  
  return customFetch<allocationsControllerGenerateTransfersResponse>(getAllocationsControllerGenerateTransfersUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      generateTransfersDto,)
  }
);}


/**
 * Retrieve a specific warehouse location by ID, including its address details.
 * @summary Get Location
 */
export type locationsControllerGetLocationResponse200 = {
  data: LocationResponseDto
  status: 200
}
    
export type locationsControllerGetLocationResponseSuccess = (locationsControllerGetLocationResponse200) & {
  headers: Headers;
};
;

export type locationsControllerGetLocationResponse = (locationsControllerGetLocationResponseSuccess)

export const getLocationsControllerGetLocationUrl = (id: string,) => {


  

  return `/inventory/locations/${id}`
}

export const locationsControllerGetLocation = async (id: string, options?: RequestInit): Promise<locationsControllerGetLocationResponse> => {
  
  return customFetch<locationsControllerGetLocationResponse>(getLocationsControllerGetLocationUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * Modify the details of an existing warehouse location.
 * @summary Update Location
 */
export type locationsControllerUpdateLocationResponse200 = {
  data: LocationResponseDto
  status: 200
}
    
export type locationsControllerUpdateLocationResponseSuccess = (locationsControllerUpdateLocationResponse200) & {
  headers: Headers;
};
;

export type locationsControllerUpdateLocationResponse = (locationsControllerUpdateLocationResponseSuccess)

export const getLocationsControllerUpdateLocationUrl = (id: string,) => {


  

  return `/inventory/locations/${id}`
}

export const locationsControllerUpdateLocation = async (id: string,
    updateLocationDto: UpdateLocationDto, options?: RequestInit): Promise<locationsControllerUpdateLocationResponse> => {
  
  return customFetch<locationsControllerUpdateLocationResponse>(getLocationsControllerUpdateLocationUrl(id),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateLocationDto,)
  }
);}


/**
 * Remove a warehouse location.
 * @summary Delete Location
 */
export type locationsControllerDeleteLocationResponse200 = {
  data: LocationResponseDto
  status: 200
}
    
export type locationsControllerDeleteLocationResponseSuccess = (locationsControllerDeleteLocationResponse200) & {
  headers: Headers;
};
;

export type locationsControllerDeleteLocationResponse = (locationsControllerDeleteLocationResponseSuccess)

export const getLocationsControllerDeleteLocationUrl = (id: string,) => {


  

  return `/inventory/locations/${id}`
}

export const locationsControllerDeleteLocation = async (id: string, options?: RequestInit): Promise<locationsControllerDeleteLocationResponse> => {
  
  return customFetch<locationsControllerDeleteLocationResponse>(getLocationsControllerDeleteLocationUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}


/**
 * Create a new storage zone.
 * @summary Create Zone
 */
export type locationsControllerCreateZoneResponse201 = {
  data: ZoneResponseDto
  status: 201
}
    
export type locationsControllerCreateZoneResponseSuccess = (locationsControllerCreateZoneResponse201) & {
  headers: Headers;
};
;

export type locationsControllerCreateZoneResponse = (locationsControllerCreateZoneResponseSuccess)

export const getLocationsControllerCreateZoneUrl = () => {


  

  return `/inventory/zones`
}

export const locationsControllerCreateZone = async (createZoneDto: CreateZoneDto, options?: RequestInit): Promise<locationsControllerCreateZoneResponse> => {
  
  return customFetch<locationsControllerCreateZoneResponse>(getLocationsControllerCreateZoneUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createZoneDto,)
  }
);}


/**
 * Modify the details of an existing storage zone.
 * @summary Update Zone
 */
export type locationsControllerUpdateZoneResponse200 = {
  data: ZoneResponseDto
  status: 200
}
    
export type locationsControllerUpdateZoneResponseSuccess = (locationsControllerUpdateZoneResponse200) & {
  headers: Headers;
};
;

export type locationsControllerUpdateZoneResponse = (locationsControllerUpdateZoneResponseSuccess)

export const getLocationsControllerUpdateZoneUrl = (id: string,) => {


  

  return `/inventory/zones/${id}`
}

export const locationsControllerUpdateZone = async (id: string,
    updateZoneDto: UpdateZoneDto, options?: RequestInit): Promise<locationsControllerUpdateZoneResponse> => {
  
  return customFetch<locationsControllerUpdateZoneResponse>(getLocationsControllerUpdateZoneUrl(id),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateZoneDto,)
  }
);}


/**
 * Remove a storage zone.
 * @summary Delete Zone
 */
export type locationsControllerDeleteZoneResponse200 = {
  data: ZoneResponseDto
  status: 200
}
    
export type locationsControllerDeleteZoneResponseSuccess = (locationsControllerDeleteZoneResponse200) & {
  headers: Headers;
};
;

export type locationsControllerDeleteZoneResponse = (locationsControllerDeleteZoneResponseSuccess)

export const getLocationsControllerDeleteZoneUrl = (id: string,) => {


  

  return `/inventory/zones/${id}`
}

export const locationsControllerDeleteZone = async (id: string, options?: RequestInit): Promise<locationsControllerDeleteZoneResponse> => {
  
  return customFetch<locationsControllerDeleteZoneResponse>(getLocationsControllerDeleteZoneUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}


/**
 * Create multiple storage bins at once.
 * @summary Create Bins in Bulk
 */
export type locationsControllerCreateBinsBulkResponse201 = {
  data: BinResponseDto[]
  status: 201
}
    
export type locationsControllerCreateBinsBulkResponseSuccess = (locationsControllerCreateBinsBulkResponse201) & {
  headers: Headers;
};
;

export type locationsControllerCreateBinsBulkResponse = (locationsControllerCreateBinsBulkResponseSuccess)

export const getLocationsControllerCreateBinsBulkUrl = () => {


  

  return `/inventory/bins/bulk`
}

export const locationsControllerCreateBinsBulk = async (createBinBulkDto: CreateBinBulkDto, options?: RequestInit): Promise<locationsControllerCreateBinsBulkResponse> => {
  
  return customFetch<locationsControllerCreateBinsBulkResponse>(getLocationsControllerCreateBinsBulkUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createBinBulkDto,)
  }
);}


/**
 * Modify the details of an existing storage bin.
 * @summary Update Bin
 */
export type locationsControllerUpdateBinResponse200 = {
  data: BinResponseDto
  status: 200
}
    
export type locationsControllerUpdateBinResponseSuccess = (locationsControllerUpdateBinResponse200) & {
  headers: Headers;
};
;

export type locationsControllerUpdateBinResponse = (locationsControllerUpdateBinResponseSuccess)

export const getLocationsControllerUpdateBinUrl = (id: string,) => {


  

  return `/inventory/bins/${id}`
}

export const locationsControllerUpdateBin = async (id: string,
    updateBinDto: UpdateBinDto, options?: RequestInit): Promise<locationsControllerUpdateBinResponse> => {
  
  return customFetch<locationsControllerUpdateBinResponse>(getLocationsControllerUpdateBinUrl(id),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateBinDto,)
  }
);}


/**
 * Remove a storage bin.
 * @summary Delete Bin
 */
export type locationsControllerDeleteBinResponse200 = {
  data: BinResponseDto
  status: 200
}
    
export type locationsControllerDeleteBinResponseSuccess = (locationsControllerDeleteBinResponse200) & {
  headers: Headers;
};
;

export type locationsControllerDeleteBinResponse = (locationsControllerDeleteBinResponseSuccess)

export const getLocationsControllerDeleteBinUrl = (id: string,) => {


  

  return `/inventory/bins/${id}`
}

export const locationsControllerDeleteBin = async (id: string, options?: RequestInit): Promise<locationsControllerDeleteBinResponse> => {
  
  return customFetch<locationsControllerDeleteBinResponse>(getLocationsControllerDeleteBinUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}


/**
 * Create a new goods receipt note.
 * @summary Create Goods Receipt
 */
export type goodsReceivedControllerCreateResponse201 = {
  data: GoodsReceivedResponseDto
  status: 201
}
    
export type goodsReceivedControllerCreateResponseSuccess = (goodsReceivedControllerCreateResponse201) & {
  headers: Headers;
};
;

export type goodsReceivedControllerCreateResponse = (goodsReceivedControllerCreateResponseSuccess)

export const getGoodsReceivedControllerCreateUrl = () => {


  

  return `/goods-received`
}

export const goodsReceivedControllerCreate = async (createGoodsReceivedDto: CreateGoodsReceivedDto, options?: RequestInit): Promise<goodsReceivedControllerCreateResponse> => {
  
  return customFetch<goodsReceivedControllerCreateResponse>(getGoodsReceivedControllerCreateUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createGoodsReceivedDto,)
  }
);}


/**
 * Retrieve a paginated list of goods receipts.
 * @summary List Goods Receipts
 */
export type goodsReceivedControllerFindAllResponse200 = {
  data: PaginatedGoodsReceivedDto
  status: 200
}
    
export type goodsReceivedControllerFindAllResponseSuccess = (goodsReceivedControllerFindAllResponse200) & {
  headers: Headers;
};
;

export type goodsReceivedControllerFindAllResponse = (goodsReceivedControllerFindAllResponseSuccess)

export const getGoodsReceivedControllerFindAllUrl = (params?: GoodsReceivedControllerFindAllParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/goods-received?${stringifiedParams}` : `/goods-received`
}

export const goodsReceivedControllerFindAll = async (params?: GoodsReceivedControllerFindAllParams, options?: RequestInit): Promise<goodsReceivedControllerFindAllResponse> => {
  
  return customFetch<goodsReceivedControllerFindAllResponse>(getGoodsReceivedControllerFindAllUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * Retrieve a paginated list of received goods lines.
 * @summary List Received Lines
 */
export type goodsReceivedControllerFindAllLinesResponse200 = {
  data: PaginatedGoodsReceivedLineDto
  status: 200
}
    
export type goodsReceivedControllerFindAllLinesResponseSuccess = (goodsReceivedControllerFindAllLinesResponse200) & {
  headers: Headers;
};
;

export type goodsReceivedControllerFindAllLinesResponse = (goodsReceivedControllerFindAllLinesResponseSuccess)

export const getGoodsReceivedControllerFindAllLinesUrl = (params?: GoodsReceivedControllerFindAllLinesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/goods-received/lines?${stringifiedParams}` : `/goods-received/lines`
}

export const goodsReceivedControllerFindAllLines = async (params?: GoodsReceivedControllerFindAllLinesParams, options?: RequestInit): Promise<goodsReceivedControllerFindAllLinesResponse> => {
  
  return customFetch<goodsReceivedControllerFindAllLinesResponse>(getGoodsReceivedControllerFindAllLinesUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * Retrieve details for a specific goods receipt note.
 * @summary Get Goods Receipt
 */
export type goodsReceivedControllerFindOneResponse200 = {
  data: GoodsReceivedResponseDto
  status: 200
}
    
export type goodsReceivedControllerFindOneResponseSuccess = (goodsReceivedControllerFindOneResponse200) & {
  headers: Headers;
};
;

export type goodsReceivedControllerFindOneResponse = (goodsReceivedControllerFindOneResponseSuccess)

export const getGoodsReceivedControllerFindOneUrl = (id: string,
    params?: GoodsReceivedControllerFindOneParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/goods-received/${id}?${stringifiedParams}` : `/goods-received/${id}`
}

export const goodsReceivedControllerFindOne = async (id: string,
    params?: GoodsReceivedControllerFindOneParams, options?: RequestInit): Promise<goodsReceivedControllerFindOneResponse> => {
  
  return customFetch<goodsReceivedControllerFindOneResponse>(getGoodsReceivedControllerFindOneUrl(id,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * Update header fields for an existing goods receipt note.
 * @summary Update Goods Receipt
 */
export type goodsReceivedControllerUpdateResponse200 = {
  data: GoodsReceivedResponseDto
  status: 200
}
    
export type goodsReceivedControllerUpdateResponseSuccess = (goodsReceivedControllerUpdateResponse200) & {
  headers: Headers;
};
;

export type goodsReceivedControllerUpdateResponse = (goodsReceivedControllerUpdateResponseSuccess)

export const getGoodsReceivedControllerUpdateUrl = (id: string,) => {


  

  return `/goods-received/${id}`
}

export const goodsReceivedControllerUpdate = async (id: string,
    updateGoodsReceivedDto: UpdateGoodsReceivedDto, options?: RequestInit): Promise<goodsReceivedControllerUpdateResponse> => {
  
  return customFetch<goodsReceivedControllerUpdateResponse>(getGoodsReceivedControllerUpdateUrl(id),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateGoodsReceivedDto,)
  }
);}


/**
 * Cancel an existing goods receipt note.
 * @summary Cancel Goods Receipt
 */
export type goodsReceivedControllerCancelReceptionResponse200 = {
  data: GoodsReceivedControllerCancelReception200
  status: 200
}

export type goodsReceivedControllerCancelReceptionResponse201 = {
  data: CancelReceptionResponseDto
  status: 201
}
    
export type goodsReceivedControllerCancelReceptionResponseSuccess = (goodsReceivedControllerCancelReceptionResponse200 | goodsReceivedControllerCancelReceptionResponse201) & {
  headers: Headers;
};
;

export type goodsReceivedControllerCancelReceptionResponse = (goodsReceivedControllerCancelReceptionResponseSuccess)

export const getGoodsReceivedControllerCancelReceptionUrl = (id: string,) => {


  

  return `/goods-received/${id}/cancel`
}

export const goodsReceivedControllerCancelReception = async (id: string,
    emptyBodyDto: EmptyBodyDto, options?: RequestInit): Promise<goodsReceivedControllerCancelReceptionResponse> => {
  
  return customFetch<goodsReceivedControllerCancelReceptionResponse>(getGoodsReceivedControllerCancelReceptionUrl(id),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      emptyBodyDto,)
  }
);}


/**
 * Resolve allocation for a received goods line.
 * @summary Resolve Allocation
 */
export type goodsReceivedControllerResolveAllocationResponse200 = {
  data: ResolveAllocationResponseDto
  status: 200
}

export type goodsReceivedControllerResolveAllocationResponse201 = {
  data: ResolveAllocationResponseDto
  status: 201
}
    
export type goodsReceivedControllerResolveAllocationResponseSuccess = (goodsReceivedControllerResolveAllocationResponse200 | goodsReceivedControllerResolveAllocationResponse201) & {
  headers: Headers;
};
;

export type goodsReceivedControllerResolveAllocationResponse = (goodsReceivedControllerResolveAllocationResponseSuccess)

export const getGoodsReceivedControllerResolveAllocationUrl = (lineId: string,) => {


  

  return `/goods-received/lines/${lineId}/resolve`
}

export const goodsReceivedControllerResolveAllocation = async (lineId: string,
    resolveAllocationDto: ResolveAllocationDto, options?: RequestInit): Promise<goodsReceivedControllerResolveAllocationResponse> => {
  
  return customFetch<goodsReceivedControllerResolveAllocationResponse>(getGoodsReceivedControllerResolveAllocationUrl(lineId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      resolveAllocationDto,)
  }
);}


/**
 * Unresolve allocation for a received goods line.
 * @summary Unresolve Allocation
 */
export type goodsReceivedControllerUnresolveAllocationResponse200 = {
  data: GoodsReceivedLineResponseDto
  status: 200
}

export type goodsReceivedControllerUnresolveAllocationResponse201 = {
  data: GoodsReceivedLineResponseDto
  status: 201
}
    
export type goodsReceivedControllerUnresolveAllocationResponseSuccess = (goodsReceivedControllerUnresolveAllocationResponse200 | goodsReceivedControllerUnresolveAllocationResponse201) & {
  headers: Headers;
};
;

export type goodsReceivedControllerUnresolveAllocationResponse = (goodsReceivedControllerUnresolveAllocationResponseSuccess)

export const getGoodsReceivedControllerUnresolveAllocationUrl = (lineId: string,) => {


  

  return `/goods-received/lines/${lineId}/unresolve`
}

export const goodsReceivedControllerUnresolveAllocation = async (lineId: string,
    emptyBodyDto: EmptyBodyDto, options?: RequestInit): Promise<goodsReceivedControllerUnresolveAllocationResponse> => {
  
  return customFetch<goodsReceivedControllerUnresolveAllocationResponse>(getGoodsReceivedControllerUnresolveAllocationUrl(lineId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      emptyBodyDto,)
  }
);}


