export type ValidState = 
  | 'active'
  | 'inactive'
  | 'discontinued'
  | 'archived'
  | 'confirmed'
  | 'picking'
  | 'shipped'
  | 'invoiced'
  | 'cancelled'
  | 'draft'
  | 'quoted'
  | 'ordered'
  | 'partially_received'
  | 'received'
  | 'dispatched'
  | 'processed'
  | 'legacy'
  | 'released'
  | 'in_progress'
  | 'completed';

