const fs = require('fs');
let content = fs.readFileSync('PaymentManagerSlideOver.tsx', 'utf8');

const replacements = [
  ['title={isAllocated ? "Click to remove allocation" : "Click to auto-allocate max"}', 'title={isAllocated ? t("manager.messages.clickToRemoveAllocation") : t("manager.messages.clickToAutoAllocateMax")}'],
  [/headerName: 'Date'/g, "headerName: t('manager.columns.date')"],
  [/headerName: 'Invoice No.'/g, "headerName: t('manager.columns.invoiceNo')"],
  [/headerName: 'Outstanding'/g, "headerName: t('manager.columns.outstanding')"],
  [/headerName: 'Allocated'/g, "headerName: t('manager.columns.allocated')"],
  [/headerName: 'Allocate\?'/g, "headerName: t('manager.columns.allocate')"],
  [/toast\.success\('Payment created and posted successfully'\)/g, "toast.success(t('manager.messages.paymentCreated'))"],
  [/toast\.error\(err\.message \|\| 'Failed to create payment'\)/g, "toast.error(err.message || t('manager.messages.failedToCreate'))"],
  [/toast\.success\('Payment submitted and posted to GL'\)/g, "toast.success(t('manager.messages.paymentSubmitted'))"],
  [/\? 'Are you sure you want to delete this draft payment\?'/g, "? t('manager.messages.deleteDraftConfirm')"],
  [/: 'Are you sure you want to reverse this payment\? This will create a reversing GL entry\.'/g, ": t('manager.messages.reversePaymentConfirm')"],
  [/toast\.success\('Payment cancelled'\)/g, "toast.success(t('manager.messages.paymentCancelled'))"],
  [/toast\.error\('Total allocation exceeds unallocated amount'\)/g, "toast.error(t('manager.messages.allocationExceedsUnallocated'))"],
  [/toast\.success\('Allocations saved'\)/g, "toast.success(t('manager.messages.allocationsSaved'))"],
  [/Reverse\s*<\/button>/g, "{t('manager.buttons.reverse')}</button>"],
  [/title="Previous Payment"/g, "title={t('manager.buttons.previousPayment')}"],
  [/<span className="material-symbols-outlined text-\[18px\]">chevron_left<\/span>/g, "{/* eslint-disable-next-line i18next/no-literal-string -- Hardcoded string exceptions for standard system IDs, technical constants, or non-translatable symbols (e.g., -- Material UI Icon). */}\n              <span className=\"material-symbols-outlined text-[18px]\">chevron_left</span>"],
  [/title="Next Payment"/g, "title={t('manager.buttons.nextPayment')}"],
  [/<span className="material-symbols-outlined text-\[18px\]">chevron_right<\/span>/g, "{/* eslint-disable-next-line i18next/no-literal-string -- Hardcoded string exceptions for standard system IDs, technical constants, or non-translatable symbols (e.g., -- Material UI Icon). */}\n              <span className=\"material-symbols-outlined text-[18px]\">chevron_right</span>"],
  [/'New Payment Entry'/g, "t('manager.newEntry')"],
  [/\? 'Customer Receipt' : 'Supplier Payment'/g, "? t('manager.options.customerReceipt') : t('manager.options.supplierPayment')"],
  [/<span className="material-symbols-outlined animate-spin text-3xl mb-2">sync<\/span>/g, "{/* eslint-disable-next-line i18next/no-literal-string -- Hardcoded string exceptions for standard system IDs, technical constants, or non-translatable symbols (e.g., -- Material UI Icon). */}\n            <span className=\"material-symbols-outlined animate-spin text-3xl mb-2\">sync</span>"],
  [/Type<\/label>/g, "{t('manager.labels.type')}</label>"],
  [/<option value="receive">Customer Receipt<\/option>/g, "<option value=\"receive\">{t('manager.options.customerReceipt')}</option>"],
  [/<option value="pay">Supplier Payment<\/option>/g, "<option value=\"pay\">{t('manager.options.supplierPayment')}</option>"],
  [/Mode<\/label>/g, "{t('manager.labels.mode')}</label>"],
  [/<option value="Cash">Cash<\/option>/g, "<option value=\"Cash\">{t('manager.options.cash')}</option>"],
  [/<option value="EFT">EFT \/ Wire<\/option>/g, "<option value=\"EFT\">{t('manager.options.eft')}</option>"],
  [/<option value="Credit Card">Credit Card<\/option>/g, "<option value=\"Credit Card\">{t('manager.options.creditCard')}</option>"],
  [/<option value="Cheque">Cheque<\/option>/g, "<option value=\"Cheque\">{t('manager.options.cheque')}</option>"],
  [/GL Bank Customer<\/label>/g, "{t('manager.labels.glBank')}</label>"],
  [/<span className="material-symbols-outlined text-\[14px\] text-\[var\(--text-muted\)\]">payments<\/span>/g, "{/* eslint-disable-next-line i18next/no-literal-string */}\n                      <span className=\"material-symbols-outlined text-[14px] text-[var(--text-muted)]\">payments</span>"],
  [/Settlement Currency:/g, "{t('manager.labels.settlementCurrency')}:"],
  [/Amount<\/label>/g, "{t('manager.labels.amount')}</label>"],
  [/placeholder="0\.00"/g, "placeholder={t('manager.placeholders.amount')}"],
  [/Date<\/label>/g, "{t('manager.labels.date')}</label>"],
  [/Reference \/ Memo<\/label>/g, "{t('manager.labels.reference')}</label>"],
  [/placeholder="e\.g\. Check #, Wire Ref"/g, "placeholder={t('manager.placeholders.reference')}"],
  [/>Party<\/span>/g, ">{t('manager.labels.party')}</span>"],
  [/>Status<\/span>/g, ">{t('manager.labels.status')}</span>"],
  [/>Mode of Payment<\/span>/g, ">{t('manager.labels.mode')}</span>"],
  [/>Reference \/ Memo<\/span>/g, ">{t('manager.labels.reference')}</span>"],
  [/>Unallocated Amount<\/span>/g, ">{t('manager.labels.unallocatedAmount')}</span>"],
  [/>Customer<\/th>/g, ">{t('manager.columns.customer')}</th>"],
  [/>Debit<\/th>/g, ">{t('manager.columns.debit')}</th>"],
  [/>Credit<\/th>/g, ">{t('manager.columns.credit')}</th>"],
  [/>Memo<\/th>/g, ">{t('manager.columns.memo')}</th>"],
  [/>Total<\/td>/g, ">{t('manager.messages.total')}</td>"],
  [/No ledger lines found for this entry\./g, "{t('manager.messages.noLedgerLines')}"],
  [/<span className="material-symbols-outlined">history<\/span>/g, "{/* eslint-disable-next-line i18next/no-literal-string -- Hardcoded string exceptions for standard system IDs, technical constants, or non-translatable symbols (e.g., -- Material UI Icon). */}\n                          <span className=\"material-symbols-outlined\">history</span>"],
  [/Allocation History<\/h3>/g, "{t('manager.messages.allocationHistory')}</h3>"],
  [/>Invoice<\/th>/g, ">{t('manager.columns.invoice')}</th>"],
  [/>Type<\/th>/g, ">{t('manager.columns.type')}</th>"],
  [/>Allocated Amount<\/th>/g, ">{t('manager.columns.allocatedAmount')}</th>"],
  [/<span className="material-symbols-outlined animate-spin text-3xl mb-4">sync<\/span>/g, "{/* eslint-disable-next-line i18next/no-literal-string -- Hardcoded string exceptions for standard system IDs, technical constants, or non-translatable symbols (e.g., -- Material UI Icon). */}\n                        <span className=\"material-symbols-outlined animate-spin text-3xl mb-4\">sync</span>"],
  [/Loading outstanding invoices\.\.\./g, "{t('manager.messages.loadingInvoices')}"],
  [/>Payment Unallocated<\/div>/g, ">{t('manager.labels.paymentUnallocated')}</div>"],
  [/>Total Outstanding<\/div>/g, ">{t('manager.labels.totalOutstanding')}</div>"],
  [/>Allocated Now<\/div>/g, ">{t('manager.labels.allocatedNow')}</div>"],
  [/>Remaining to Allocate<\/div>/g, ">{t('manager.labels.remainingToAllocate')}</div>"],
  [/title=\{!selectedInvoice \? "Select a row to allocate partially" : ""\}/g, "title={!selectedInvoice ? t('manager.messages.selectRowForPartial') : \"\"}"],
  [/>Partial<\/button>/g, ">{t('manager.messages.partial')}</button>"],
  [/No outstanding invoices to allocate/g, "{t('manager.messages.noOutstandingInvoices')}"],
  [/<span className="material-symbols-outlined text-4xl mb-4 text-gray-400">receipt_long<\/span>/g, "{/* eslint-disable-next-line i18next/no-literal-string -- Hardcoded string exceptions for standard system IDs, technical constants, or non-translatable symbols (e.g., -- Material UI Icon). */}\n                          <span className=\"material-symbols-outlined text-4xl mb-4 text-gray-400\">receipt_long</span>"]
];

replacements.forEach(([search, replace]) => {
  content = content.replace(search, replace);
});

fs.writeFileSync('PaymentManagerSlideOver.tsx', content, 'utf8');
